Update deploy-wdac-policies-with-script.md
MicrosoftDocs/windows-itpro-docs pull request #10079
Opened 2021-11-06 05:21 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9988
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9895
Dear @jsuther1974, please have a look

2021-11-06 05:21 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

2021-11-07 12:22 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/deployment/deploy-wdac-policies-with-script.md
> +3. Reboot the system.
```suggestion
3. Restart the system.
```

2021-11-07 12:25 UTC, JohanFreelancer9 requested changes
Copy review - minor suggestion.

2021-11-10 08:06 UTC, JohanFreelancer9 approved these changes

2021-11-10 16:41 UTC, merged