update info
MicrosoftDocs/windows-itpro-docs pull request #10086
Opened 2021-11-08 09:43 UTC by VLG17

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9837

2021-11-09 09:17 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md
> +    > For access issues in the context of VPN make sure to check the resolution and workaround described in  [this article](https://docs.microsoft.com/en-us/troubleshoot/windows-client/group-policy/g
```suggestion
> [!NOTE]
> For access issues in the context of VPN, make sure to check the resolution and workaround described in  [this article](https://docs.microsoft.com/en-us/troubleshoot/windows-client/group-policy/group-membership-changes-not-updating-over-some-vpn-connections#workarounds).
```

2021-11-09 09:23 UTC, JohanFreelancer9 requested changes
Copy review - @VLG17, kindly commit the suggested change if you agree with it. Many thanks.

2021-11-09 12:05 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md
> +> For access issues in the context of VPN, make sure to check the resolution and workaround described in  [this article](https://docs.microsoft.com/en-us/troubleshoot/windows-client/group-policy/grou
```suggestion
> For access issues in the context of VPN, make sure to check the resolution and workaround described in [Workaround for user security context and access control](/troubleshoot/windows-client/group-policy/group-membership-changes-not-updating-over-some-vpn-connections#workarounds).
```

2021-11-09 12:07 UTC, JohanFreelancer9 requested changes
@VLG17 - you were a bit too quick for me and committed my changes before I completed the edit. Could you please also commit this suggested change (note that we have to use relative links)? Many thanks.

2021-11-09 14:31 UTC, JohanFreelancer9 approved these changes

2021-11-10 17:29 UTC, mapalko approved these changes

2021-11-27 23:38 UTC, e0i commented
@tiburd This PR has been approved by the document author and can be merged. Thanks.

2021-11-29 16:48 UTC, merged