Update policy-csp-experience.md in regards to Chat icon policy
MicrosoftDocs/windows-itpro-docs pull request #10108
Opened 2021-11-15 00:33 UTC by harshparakh

2021-11-16 08:02 UTC, JohanFreelancer9 commented on windows/client-management/mdm/policy-csp-experience.md
> +Note: Options 1 and 2 (Show, Hide) only work on first boot whereas option 3 - Disabled will work on all attempts.
```suggestion
> [!NOTE]
> Options 1 and 2 (Show, Hide) only work on the first sign-in attempt whereas Option 3 (Disabled) works on all attempts.
```

2021-11-16 08:08 UTC, JohanFreelancer9 requested changes
Copy review - @harshparakh, kindly commit the suggested changes if you agree with them. Many thanks.

2021-11-18 00:00 UTC, harshparakh commented on windows/client-management/mdm/policy-csp-experience.md
> +> Options 1 and 2 (Show, Hide) only work on the first sign-in attempt whereas Option 3 (Disabled) works on all attempts.
```suggestion
> Option 1 (Show) and Option 2 (Hide) only work on the first sign-in attempt. Option 3 (Disabled) works on all attempts.
```

2021-11-18 00:03 UTC, merged

2021-11-18 00:28 UTC, garycentric commented
@harshparakh 
Microsoft-credentialed contributors are strongly encouraged to work in the private repos, not the public. The private repos provide checks for build integrity, checks for spelling & grammar, and provide preview links for added and modified articles. The private repos also have a shorter path to publication, and they're a secure place to add content prior to official release. 

For more information about working in the private repos, please see [Where do I start?](https://review.docs.microsoft.com/en-us/office-authoring-guide/office-docs-authoring-overview?branch=master#where-do-i-start) in the MARVEL authoring guide. If you have questions or need help, please contact [Ask an Admin](https://aka.ms/askanadmin) in Teams.

2021-11-18 02:24 UTC, harshparakh commented
> @harshparakh Microsoft-credentialed contributors are strongly encouraged to work in the private repos, not the public. The private repos provide checks for build integrity, checks for spelling & grammar, and provide preview links for added and modified articles. The private repos also have a shorter path to publication, and they're a secure place to add content prior to official release.
> 
> For more information about working in the private repos, please see [Where do I start?](https://review.docs.microsoft.com/en-us/office-authoring-guide/office-docs-authoring-overview?branch=master#where-do-i-start) in the MARVEL authoring guide. If you have questions or need help, please contact [Ask an Admin](https://aka.ms/askanadmin) in Teams.

Thanks @garycentric, that makes sense. @Dansimp is helping me out with access to the private repository.