Restriction Peer Selection Update
MicrosoftDocs/windows-itpro-docs pull request #10129
Opened 2021-11-17 08:35 UTC by maurice-daly

In the documentation it currently states that peer selection can be configured to "local peer discovery". This setting can only be set via MDM based policies in Windows 11 builds, and therefore clarification is required, as although technically the docs state 20H2 and docs here - https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization-reference, state 1803, setting the value via MDM policies in these builds will result in a policy failure.

2021-11-18 05:16 UTC, JohanFreelancer9 commented on windows/deployment/update/waas-delivery-optimization.md
> +**Please Note:** that the "Local peer discovery (DNS-SD)" option can only be set via MDM delivered policies on Windows 11 builds. This feature can be enabled in supported Windows 10 builds by setting
```suggestion
> [!NOTE]
> The Local Peer Discovery (DNS-SD) option can only be set via MDM delivered policies on Windows 11 builds. This feature can be enabled in supported Windows 10 builds by setting the `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DeliveryOptimization\DORestrictPeerSelectionBy` value to **2**. For more information, see [Delivery Optimization reference](/windows/deployment/update/waas-delivery-optimization-reference).
```

2021-11-18 05:18 UTC, JohanFreelancer9 requested changes
Copy review - @maurice-daly, kindly commit the suggested changes. Many thanks.

2021-11-19 04:40 UTC, JohanFreelancer9 approved these changes

2021-12-01 00:10 UTC, maurice-daly commented
Just checking in to see if this pull request is going to be published?

2021-12-14 22:41 UTC, cmknox commented
#sign-off

2021-12-16 16:16 UTC, cmknox commented
@JohanFreelancer9 can you help with merging this one. It is related to the other PR I have related to the same information for the Delivery Optimization reference page.

2021-12-17 02:06 UTC, JohanFreelancer9 commented
@e0i, can you assist to get this merged, please?

2022-01-11 22:06 UTC, merged