Update audit-registry.md
MicrosoftDocs/windows-itpro-docs pull request #10188
Opened 2021-12-06 21:35 UTC by sravanigannavarapu

Add a note about expected events on Create Subkey.

2021-12-13 04:52 UTC, JohanFreelancer9 commented on windows/security/threat-protection/auditing/audit-registry.md
> +> On creating a subkey for a parent (RegCreateKey), the expectation is to see an event for opening a handle for the newly created object (Event 4656) issued by the object manager. We see this event o
```suggestion
> On creating a subkey for a parent (RegCreateKey), the expectation is to see an event for opening a handle for the newly created object (event 4656) issued by the object manager. You would see this event only when "Audit Object Access" is enabled under **Local Policies** > **Audit Policy** in Local Security Policy. This event is not generated while using precisely-defined settings for seeing only registry-related events under **Advanced Audit Policy Configurations** > **Object Access** > **Audit Registry** in Local Security Policy. For example, you would not see this event with the setting to just see the registry-related auditing events using "auditpol.exe /set /subcategory:{0CCE921E-69AE-11D9-BED3-505054503030} /success:enable". 
```

2021-12-13 04:54 UTC, JohanFreelancer9 commented on windows/security/threat-protection/auditing/audit-registry.md
> +Calls to Registry API's to access an open key object to perform an operation like RegSetValue, RegEnumValue, RegRenameKey etc. would trigger an event to access the object (Event 4663). So for example
```suggestion
Calls to Registry APIs to access an open key object to perform an operation such as RegSetValue, RegEnumValue, and RegRenameKey, would trigger an event to access the object (event 4663). For example, creating a subkey using regedit.exe would not trigger a 4663 event, but renaming it would.
```

2021-12-13 04:57 UTC, JohanFreelancer9 requested changes
Copy review.

2021-12-16 19:21 UTC, denisebmsft approved these changes

2021-12-16 19:21 UTC, merged