i corrected sentences
MicrosoftDocs/windows-itpro-docs pull request #10195
Opened 2021-12-09 13:21 UTC by RAJU2529

as per user feedback #10193 , so i corrected it after verifying with GPO  explanation under Windows 11.

![Screenshot 2021-12-09 185101](https://user-images.githubusercontent.com/3296790/145403975-88fee395-5348-4eef-af4d-b56933625014.jpg)

2021-12-09 18:04 UTC, mapalko approved these changes

2021-12-10 05:21 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-manage-in-organization.md
> +|Require special characters|Computer|<p><b>Not configured</b>: Windows allows, but does not require, special characters in the PIN<p><b>Enabled</b>: Windows requires the user to include at least one
```suggestion
|Require special characters|Computer|<p><b>Not configured</b>: Windows allows, but does not require, special characters in the PIN.<p><b>Enabled</b>: Windows requires the user to include at least one special character in their PIN.<p><b>Disabled</b>: Windows does not allow the user to include special characters in their PIN.|
```

2021-12-10 05:22 UTC, JohanFreelancer9 requested changes
Copt review.

2021-12-10 06:15 UTC, JohanFreelancer9 approved these changes

2021-12-10 19:22 UTC, merged