Update policy-csp-networklistmanager.md
MicrosoftDocs/windows-itpro-docs pull request #10196
Opened 2021-12-09 15:40 UTC by msarcletti

Additional information on how to use and configure AllowedTlsAuthenticationEndpoints and ConfiguredTLSAuthenticationNetworkName

2021-12-10 04:54 UTC, JohanFreelancer9 commented on windows/client-management/mdm/policy-csp-networklistmanager.md
> +When entering a list of TLS Endpoints in MEM (Microsoft Endpoint Management), you must follow this format even in the UI:
```suggestion

When entering a list of TLS endpoints in Microsoft Endpoint Manager, you should follow this format, even in the UI:  
```

2021-12-10 05:08 UTC, JohanFreelancer9 commented on windows/client-management/mdm/policy-csp-networklistmanager.md
> +- The HTTPS endpoint must not have any additional authentication checks such as login or multi-factor authentication.
```suggestion
- The HTTPS endpoint must not have any additional authentication checks, such as login or multifactor authentication.
```

2021-12-10 05:10 UTC, JohanFreelancer9 commented on windows/client-management/mdm/policy-csp-networklistmanager.md
> +- The client must trust the server certificate, so the CA cert the HTTPS server cert chains to must be present in the client machines root certificate store.
```suggestion
- The client must trust the server certificate, so the CA certificate that the HTTPS server certificate chains to must be present in the client machine's root certificate store.
```

2021-12-10 05:11 UTC, JohanFreelancer9 commented on windows/client-management/mdm/policy-csp-networklistmanager.md
> +
```suggestion
```

2021-12-10 05:13 UTC, JohanFreelancer9 requested changes
Copy review - @msarcletti, kindly commit the suggested changes. Many thanks.

2021-12-10 06:24 UTC, JohanFreelancer9 approved these changes

2021-12-10 07:58 UTC, msarcletti commented on windows/client-management/mdm/policy-csp-networklistmanager.md
> +When entering a list of TLS endpoints in Microsoft Endpoint Manager, you should follow this format, even in the UI:
```suggestion
When entering a list of TLS endpoints in Microsoft Endpoint Manager, you must follow this format, even in the UI:  
```

2021-12-10 12:59 UTC, JohanFreelancer9 approved these changes

2021-12-16 19:16 UTC, denisebmsft commented
Thank you @msarcletti @JohanFreelancer9

2021-12-16 19:16 UTC, merged