removed outdated step
MicrosoftDocs/windows-itpro-docs pull request #10218
Opened 2021-12-18 04:12 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10032

2021-12-18 04:13 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

2021-12-18 04:47 UTC, JohanFreelancer9 commented on windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md
> +Select **Remove everything**, then, on the **How would you like to reinstall Windows**, select Local reinstall. Finally, select **Reset**.
```suggestion
Select **Remove everything**, then, on **How would you like to reinstall Windows**, select **Local reinstall**. Finally, select **Reset**.
```

2021-12-18 04:50 UTC, JohanFreelancer9 requested changes
Copy review - @MaratMussabekov, kindly commit the minor suggested changes. Many thanks.

2021-12-18 16:44 UTC, Lovygoogle commented on windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md
> +Select **Remove everything**, then, on the **How would you like to reinstall Windows**, select Local reinstall. Finally, select **Reset**.
![reel-officially.jpg](https://user-images.githubusercontent.com/94048360/146648799-a86ba273-2243-4dff-8b82-39d32b5787cd.jpg)
<!-- Error while uploading نسختي من one_piece_40.flv -->

2021-12-18 16:49 UTC, Lovygoogle commented on windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md
> +Select **Remove everything**, then, on the **How would you like to reinstall Windows**, select Local reinstall. Finally, select **Reset**.
</b>
  </font>
    </span>
       <br />
         <span style="font-family: arial">
           <font size="5">
<b>وذكر المؤلفون نماذج من كتمان الأسرار وهى :</b>
           </font>
         </span>
       <br />
     <span style="font-family: arial">
  <font size="5">
<b>&quot;نماذج من كتمان السر</b>
  </font>
    </span>
      <br />
        <span style="font-family: arial">
          <font size="5">
            <b>1

2021-12-18 16:50 UTC, Lovygoogle commented on windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md
> +Select **Remove everything**, then, on the **How would you like to reinstall Windows**, select Local reinstall. Finally, select **Reset**.
- [ ]> </b>
>   </font>
>     </span>
>        <br />
>          <span style="font-family: arial">
>            <font size="5">
> <b>وذكر المؤلفون نماذج من كتمان الأسرار وهى :</b>
>            </font>
>          </span>
>        <br />
>      <span style="font-family: arial">
>   <font size="5">
> <b>&quot;نماذج من كتمان السر</b>
>   </font>
>     </span>
>       <br />
>         <span style="font-family: arial">
>           <font size="5">
>             <b>1

2021-12-18 16:51 UTC, Lovygoogle commented on windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md
> +Select **Remove everything**, then, on the **How would you like to reinstall Windows**, select Local reinstall. Finally, select **Reset**.
<iframe src="https://www.google.com/maps/d/embed?mid=1QzkPZ1ne4kuvPFjmbI57w1E3wCU&hl=ar&ehbc=2E312F" width="640" height="480"></iframe>
> > </b>
> >   </font>
> >     </span>
> >        <br />
> >          <span style="font-family: arial">
> >            <font size="5">
> > <b>
</b>
> >            </font>
> >          </span>
> >        <br />
> >      <span style="font-family: arial">
> >   <font size="5">
> > <b>&quot;
</b>
> >   </font>
> >     </span>
> >       <br />
> >         <span style="font-family: arial">
> >           <font size="5">
> >             <b>1
> 
>

2021-12-18 16:53 UTC, Lovygoogle commented
<!-- Error while uploading نسخة من one_piece_40.flv -->

2021-12-18 16:57 UTC, Lovygoogle commented on windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md
> +Select **Remove everything**, then, on the **How would you like to reinstall Windows**, select Local reinstall. Finally, select **Reset**.
Select **Remove everything**, then, on the **How would you like to reinstall Windows**, select Local reinstall. Finally, select **Reset**.
Select **Remove everything**, then, on **How would you like to reinstall Windows**, select **Local reinstall**. Finally, select **Reset**.

2021-12-23 08:05 UTC, JohanFreelancer9 approved these changes

2022-01-13 22:24 UTC, merged