Update security-identifiers.md
MicrosoftDocs/windows-itpro-docs pull request #10217
Opened 2021-12-18 03:57 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10111
added two rows to Identifier Authority table, removed S-1-16 entries from the list of well-known SIDs
source:
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/81d92bba-d22b-4a8c-908a-554ab29148ab
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/c6ce4275-3d90-4890-ab3a-514745e4637e

2021-12-18 03:58 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

2021-12-18 04:54 UTC, JohanFreelancer9 commented on windows/security/identity-protection/access-control/security-identifiers.md
> +The following table lists the predefined identifier authority constants. The first four values are used with universal well-known SIDs, and the rest values are used with well-known SIDs in Windows op
```suggestion
The following table lists the predefined identifier authority constants. The first four values are used with universal well-known SIDs, and the rest of the values are used with well-known SIDs in Windows operating systems designated in the **Applies To** list.
```

2021-12-18 04:55 UTC, JohanFreelancer9 requested changes
Copy review - @MaratMussabekov, kindly commit the minor suggested change. Many thanks.

2021-12-21 20:11 UTC, denisebmsft approved these changes
Thank you @MaratMussabekov @JohanFreelancer9

2021-12-21 20:11 UTC, merged