Replaced old Azure AD Graph-based examples
MicrosoftDocs/windows-itpro-docs pull request #10223
Opened 2021-12-19 22:57 UTC by timpeteren

Updated section "Verify the onPremisesDistinguishedName attribute is synchronized" as suggested in user feedback for issue #10216
Replaced Azure AD Graph examples with Microsoft Graph.
#ATCP

2021-12-20 08:58 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md
> +1. Open a web browser and navigate to https://developer.microsoft.com/en-us/graph/graph-explorer
```suggestion
1. Open a web browser and navigate to https://developer.microsoft.com/graph/graph-explorer
```

2021-12-20 09:02 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md
> +2. Click **Sign in to Graph Explorer** and provide Azure credentials
```suggestion
2. Select **Sign in to Graph Explorer** and provide Azure credentials.
```

2021-12-20 09:03 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md
> +3. Select **Modify permissions (Preview)**. Scroll down and locate **User.Read.All** (or any other required permission) and click **Consent**. You will now be prompted for delegated permissions conse
```suggestion
3. Select **Modify permissions (Preview)**. Scroll down and locate **User.Read.All** (or any other required permission) and select **Consent**. You will now be prompted for delegated permissions consent.
```

2021-12-20 09:06 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md
> +4. In the Graph Explorer URL, type https://graph.microsoft.com/v1.0/users/[userid]?$select=displayName,userPrincipalName,onPremisesDistinguishedName, where **[userid]** is the user principal name of
```suggestion
4. In the Graph Explorer URL, enter https://graph.microsoft.com/v1.0/users/[userid]?$select=displayName,userPrincipalName,onPremisesDistinguishedName, where **[userid]** is the user principal name of a user in Azure Active Directory.  Select **Run query**.
```

2021-12-20 09:08 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md
> +> Because the v1.0 endpoint of the Graph API only provides a limited set of parameters we will use the $select [Optional OData query parameter](/graph/api/user-get?view=graph-rest-1.0&tabs=http#optio
```suggestion
> Because the v1.0 endpoint of the Graph API only provides a limited set of parameters, we will use the $select [Optional OData query parameter](/graph/api/user-get?view=graph-rest-1.0&tabs=http#optional-query-parameters). For convenience, it is possible to switch the API version selector from **v1.0** to **beta** before performing the query. This will provide all available user information, but remember, **beta** endpoint queries should not be used in production scenarios.
```

2021-12-20 09:11 UTC, JohanFreelancer9 requested changes
Copy review - a few minor suggested changes, please.

2021-12-20 14:20 UTC, timpeteren commented
Five commits added based on excellent suggestions by @JohanFreelancer9 👍

2021-12-21 04:07 UTC, JohanFreelancer9 approved these changes
Thank you @timpeteren.

2022-01-04 16:51 UTC, mapalko approved these changes

2022-01-19 23:12 UTC, mapalko commented
@e0i can you help get this merged?

2022-01-31 16:55 UTC, andyruth commented
Should I try to find someone to merge this?

2022-01-31 17:17 UTC, BarbaraSelden commented
@omondiatieno - Can you please take a look at this one, and help us get it published?

2022-02-04 17:38 UTC, merged