added missed identities
MicrosoftDocs/windows-itpro-docs pull request #10225
Opened 2021-12-20 06:27 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10026

2021-12-20 06:27 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

2021-12-20 08:37 UTC, JohanFreelancer9 commented on windows/security/identity-protection/access-control/special-identities.md
> +
```suggestion
```

2021-12-20 08:37 UTC, JohanFreelancer9 commented on windows/security/identity-protection/access-control/special-identities.md
> +
```suggestion
```

2021-12-20 08:49 UTC, JohanFreelancer9 commented on windows/security/identity-protection/access-control/special-identities.md
> +## Fresh public key identity
```suggestion
## Fresh Public Key Identity
```

2021-12-20 08:53 UTC, JohanFreelancer9 commented on windows/security/identity-protection/access-control/special-identities.md
> +Internet Information Services (IIS) use this account by default whenever anonymous authentication is enabled.
```suggestion
Internet Information Services (IIS) uses this account by default whenever anonymous authentication is enabled.
```

2021-12-20 08:56 UTC, JohanFreelancer9 requested changes
Copy review - @MaratMussabekov, kindly commit the few minor suggested changes. Many thanks.

2021-12-21 20:08 UTC, denisebmsft approved these changes
Thank you @MaratMussabekov @JohanFreelancer9

2021-12-21 20:08 UTC, merged