Update guidance as policy is enabled by default from Windows 10 1607
MicrosoftDocs/windows-itpro-docs pull request #10245
Opened 2021-12-29 20:10 UTC by takondo

…omputer-to-use-online-identities.md

1. Fix typo in "Notes" section under "Possible values" and add wording to make condition clearer.

2. This setting is enabled by default on Windows 10 1607 and newer. Make changes accordingly.

3. Currently, the [best practices] state that the policy should be disabled. However, this is the best practice from Server 2008 R2 era and is old suggestion. The [Security considerations] section addresses this and specifies that the policy should be enabled for hybrid environments, but the [Best practices] section has not been updated.

2021-12-30 04:57 UTC, JohanFreelancer9 commented on windows/security/threat-protection/security-policy-settings/network-security-allow-pku2u-authentication-requests-to-this-computer-to-use-online-identities.md
> +This policy isn't configured by default on domain-joined devices. This would disallow the online identities to authenticate to domain-joined computers in Windows 7 up to Windows 10 1607. This policy
```suggestion
This policy isn't configured by default on domain-joined devices. This would disallow the online identities to authenticate to domain-joined computers from Windows 7 up to Windows 10, version 1607. This policy is enabled by default in Windows 10, version 1607, and later.
```

2021-12-30 05:01 UTC, JohanFreelancer9 commented on windows/security/threat-protection/security-policy-settings/network-security-allow-pku2u-authentication-requests-to-this-computer-to-use-online-identities.md
> +Within a domain, domain accounts should be used for authentication. Set this policy to **Disabled** or don't configure this policy to exclude online identities from being used to authenticate for on-
```suggestion
Within a domain, domain accounts should be used for authentication. Set this policy to **Disabled** or don't configure this policy to exclude online identities from being used to authenticate for on-premises only environments. Set this policy to **Enabled** for hybrid and Azure AD-joined environments.
```

2021-12-30 05:02 UTC, JohanFreelancer9 commented on windows/security/threat-protection/security-policy-settings/network-security-allow-pku2u-authentication-requests-to-this-computer-to-use-online-identities.md
> +| Effective GPO default settings on client computers prior to Windows 10 1607 | Disabled|
```suggestion
| Effective GPO default settings on client computers prior to Windows 10, Version 1607 | Disabled| 
```

2021-12-30 05:03 UTC, JohanFreelancer9 commented on windows/security/threat-protection/security-policy-settings/network-security-allow-pku2u-authentication-requests-to-this-computer-to-use-online-identities.md
> +| Effective GPO default settings on client computers Windows 10 1607 and newer | Enabled|
```suggestion
| Effective GPO default settings on client computers Windows 10, Version 1607 and later| Enabled| 
```

2021-12-30 05:04 UTC, JohanFreelancer9 requested changes
Copy review.

2022-01-03 19:24 UTC, denisebmsft approved these changes
Thank you @takondo @JohanFreelancer9

2022-01-03 19:25 UTC, merged