Update activate-using-active-directory-based-activation-client.md
MicrosoftDocs/windows-itpro-docs pull request #10247
Opened 2021-12-30 11:24 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10213

2021-12-30 11:24 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

2021-12-30 14:38 UTC, JohanFreelancer9 commented on windows/deployment/volume-activation/activate-using-active-directory-based-activation-client.md
> +
```suggestion
```

2021-12-30 14:39 UTC, JohanFreelancer9 commented on windows/deployment/volume-activation/activate-using-active-directory-based-activation-client.md
> +    > To activate a KMS Host Key (CSVLK) for Microsoft Office, you need to install the version-specific Office Volume License Pack on the server where the Volume Activation Server Role is installed.
```suggestion
    > To activate a KMS Host Key (CSVLK) for Microsoft Office, you need to install the version-specific Office Volume License Pack on the server where the Volume Activation Server Role is installed. For more details, see [Activate volume licensed versions of Office by using Active Directory](/deployoffice/vlactivation/activate-office-by-using-active-directory).

```

2021-12-30 14:40 UTC, JohanFreelancer9 commented on windows/deployment/volume-activation/activate-using-active-directory-based-activation-client.md
> +    > - [Office LTSC 2021 VL pack](https://www.microsoft.com/en-us/download/details.aspx?id=103446)
```suggestion
    > - [Office LTSC 2021 VL pack](https://www.microsoft.com/download/details.aspx?id=103446)

```

2021-12-30 14:41 UTC, JohanFreelancer9 requested changes
Copy review.

2022-01-01 04:58 UTC, JohanFreelancer9 approved these changes

2022-01-13 22:31 UTC, merged