Add info about next version
MicrosoftDocs/windows-itpro-docs pull request #10261
Opened 2022-01-05 11:02 UTC by VLG17

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10051

2022-01-06 08:34 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/use-device-guard-signing-portal-in-microsoft-store-for-business.md
> +> The existing web-based mechanism for the Device Guard Signing service v1 will be retired on June 9, 2021. Please transition to the PowerShell based version of the service [(DGSS v2)](https://docs.m
```suggestion
> The existing web-based mechanism for the Device Guard Signing Service v1 will be retired on June 9, 2021. Please transition to the PowerShell based version of the service [(DGSS v2)](/microsoft-store/device-guard-signing-portal). For more details, see [Sign an MSIX package with Device Guard signing](/windows/msix/package/signing-package-device-guard-signing) and [Device Guard signing](/microsoft-store/device-guard-signing-portal).
```

2022-01-06 08:35 UTC, JohanFreelancer9 requested changes
Copy review.

2022-01-06 10:15 UTC, JohanFreelancer9 approved these changes

2022-01-26 18:53 UTC, tiburd commented on windows/security/threat-protection/windows-defender-application-control/use-device-guard-signing-portal-in-microsoft-store-for-business.md
> +> The existing web-based mechanism for the Device Guard Signing Service v1 will be retired on June 9, 2021. Please transition to the PowerShell based version of the service [(DGSS v2)](/microsoft-sto
```suggestion
> The web-based Device Guard Signing Service is retired. Please transition to the PowerShell based version of the service [(DGSS v2)](/microsoft-store/device-guard-signing-portal). For more details, see [Sign an MSIX package with Device Guard signing](/windows/msix/package/signing-package-device-guard-signing) and [Device Guard signing](/microsoft-store/device-guard-signing-portal).
```

2022-01-26 19:02 UTC, merged