add detail this also logs event 4625
MicrosoftDocs/windows-itpro-docs pull request #10300
Opened 2022-01-20 08:47 UTC by HerbertMauerer

We may have customers seeing event 4625 as additional hint the task failed.

2022-01-20 09:00 UTC, HerbertMauerer commented
oh, two typos, sorry about it. Better:
failure event 4625 with error 0xC0000064

2022-01-21 07:20 UTC, JohanFreelancer9 commented on windows/security/identity-protection/credential-guard/credential-guard-known-issues.md
> +-  When enabling NTLM audit on the domain controller, an Event ID 8004 with an indecipherable username format is logged. You get a similar user name in a user logon failure event 4525 wiith error 0xC
```suggestion
-  When enabling NTLM audit on the domain controller, an Event ID 8004 with an indecipherable username format is logged. You also get a similar user name in a user logon failure event 4525 with error 0xC0000064 on the machine itself. For example:
```

2022-01-21 07:21 UTC, JohanFreelancer9 requested changes
Copy review - @HerbertMauerer, kindly commit the suggested changes. Many thanks.

2022-01-24 17:31 UTC, denisebmsft approved these changes
Thank you @HerbertMauerer @JohanFreelancer9

2022-01-24 17:31 UTC, merged