Update wip-learning.md
MicrosoftDocs/windows-itpro-docs pull request #10430
Opened 2022-03-16 16:51 UTC by loadedleke

The path the App protection status has changed. The image on the page also needs to be changed. See below.
![image](https://user-images.githubusercontent.com/10186278/158644163-87f223ff-ee81-4b15-81ef-b40c9e948253.png)

2022-03-16 21:27 UTC, cabailey commented
I have no knowledge of this product - looking for correct writer ownership

2022-03-16 22:35 UTC, cabailey commented
Reassigning to dougeby as agreed - please update the writer/manager fields for this article (I don't work in this repo)

2022-03-19 08:05 UTC, JohanFreelancer9 commented on windows/security/information-protection/windows-information-protection/wip-learning.md
> +1. Click **Apps** > **Monitor** > **App protection status** > **Reports**.
```suggestion
1. Select **Apps** > **Monitor** > **App protection status** > **Reports**.
```

2022-03-19 08:06 UTC, JohanFreelancer9 requested changes
Copy review - @loadedleke, kindly commit the minor suggested change. Many thanks.

2022-03-22 06:22 UTC, JohanFreelancer9 approved these changes

2022-03-22 20:54 UTC, aczechowski approved these changes
Thanks @loadedleke for making this change. I also updated the article metadata - I'm the best assignee for right now.

2022-03-22 20:55 UTC, merged

2022-03-22 21:38 UTC, CryptoGodfatherVA2 reviewed
confirmed