fix redundant acronym
MicrosoftDocs/windows-itpro-docs pull request #10454
Opened 2022-03-30 17:41 UTC by nonotnoah

ATM machine is a redundant acronym. This fix is in line with other uses of ATM in this document such as here: https://docs.microsoft.com/en-us/windows/deployment/update/get-started-updates-channels-tools#long-term-servicing-channel

2022-04-01 08:45 UTC, JohanFreelancer9 commented on windows/deployment/update/waas-quick-start.md
> +  - The **Long-Term Servicing Channel**, which meant only for specialized devices (which typically don't run Office) such as those that control medical equipment or ATMs, receives new feature release
```suggestion
  - The **Long-Term Servicing Channel**, which is meant only for specialized devices (which typically don't run Office) such as those that control medical equipment or ATMs, receives new feature releases every two to three years.
```

2022-04-01 08:46 UTC, JohanFreelancer9 requested changes
Copy review - @nonotnoah, kindly commit the additional suggested change to correct the typo. Many thanks.

2022-04-01 16:25 UTC, nonotnoah commented
Good catch @JohanFreelancer9!

2022-04-02 03:29 UTC, JohanFreelancer9 approved these changes

2022-04-11 18:18 UTC, aczechowski approved these changes

2022-04-11 18:18 UTC, merged