Update manage connections for new search binary
MicrosoftDocs/windows-itpro-docs pull request #10476
Opened 2022-04-12 21:58 UTC by Ansemler

In Windows 11 the search binary is now searchhost.exe so I have updated the documentation for creating a firewall rule for search

2022-04-13 03:19 UTC, JohanFreelancer9 commented on windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md
> +   - On Windows 11 instead type **"%windir%\\SystemApps\\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\\SearchHost.exe"**
```suggestion

   - On Windows 11, type **"%windir%\\SystemApps\\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\\SearchHost.exe"** instead.
```

2022-04-13 03:20 UTC, JohanFreelancer9 commented on windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md
> +- On Windows 11 instead follow the previous section and use the Group Policy editor
```suggestion
- On Windows 11, follow the previous section instead and use the Group Policy editor.
```

2022-04-13 03:21 UTC, JohanFreelancer9 requested changes
Copy review - @Ansemler, kindly commit the suggested changes. Many thanks.

2022-04-14 04:05 UTC, JohanFreelancer9 approved these changes

2022-04-14 18:30 UTC, TomLayson approved these changes

2022-04-14 18:35 UTC, merged