Update how-windows-update-works.md
MicrosoftDocs/windows-itpro-docs pull request #10482
Opened 2022-04-15 07:17 UTC by itsrlyAria

Adding Proxy behavior information as these changes were added last year to all versions of Windows 10+.

2022-04-16 06:21 UTC, JohanFreelancer9 commented on windows/deployment/update/how-windows-update-works.md
> +For Windows Update (WU) scans URLs which are used for update detection ([MS-WUSP]: SimpleAuth Web Service | Microsoft Docs, [MS-WUSP]: Client Web Service | Microsoft Docs):
```suggestion
For Windows Update (WU) scans URLs that are used for update detection ([MS-WUSP]: SimpleAuth Web Service | Microsoft Docs, [MS-WUSP]: Client Web Service | Microsoft Docs:
```

2022-04-16 06:22 UTC, JohanFreelancer9 commented on windows/deployment/update/how-windows-update-works.md
> +- System proxy is attempted (set using the netsh command).
```suggestion
- System proxy is attempted (set using the Netsh command).
```

2022-04-16 06:23 UTC, JohanFreelancer9 commented on windows/deployment/update/how-windows-update-works.md
> +- If WUA fails to reach the service due to a certain proxy, service, or authentication error code, then user proxy is attempted (generally it is the logged-in user) Note: For intranet WSUS update ser
```suggestion
- If WUA fails to reach the service due to a certain proxy, service, or authentication error code, then user proxy is attempted (generally it is the logged-in user). **Note**: For intranet WSUS update service URLs, we provide an option via Windows Update policy to select the proxy behavior.
```

2022-04-16 06:24 UTC, JohanFreelancer9 commented on windows/deployment/update/how-windows-update-works.md
> +For WU URLs which are NOT used for update detection (download, reporting etc):
```suggestion
For WU URLs that are *not* used for update detection (such as download and reporting):
```

2022-04-16 06:25 UTC, JohanFreelancer9 commented on windows/deployment/update/how-windows-update-works.md
> +- If WUA fails to reach the service due to certain proxy, service, or authentication error code, then the system proxy is attempted.
```suggestion
- If WUA fails to reach the service due to a certain proxy, service, or authentication error code, then the system proxy is attempted.
```

2022-04-16 06:26 UTC, JohanFreelancer9 requested changes
Copy review - @itsrlyAria, kindly commit the suggested changes. Many thanks.

2022-05-04 00:21 UTC, aczechowski commented on windows/deployment/update/how-windows-update-works.md
> +For Windows Update (WU) scans URLs which are used for update detection ([MS-WUSP]: SimpleAuth Web Service | Microsoft Docs, [MS-WUSP]: Client Web Service | Microsoft Docs):
I fixed this term, but kept the end parentheses which is needed

2022-05-04 00:22 UTC, aczechowski commented on windows/deployment/update/how-windows-update-works.md
> +- System proxy is attempted (set using the netsh command).
Arguably, the command is `netsh` from the command prompt. The usage shows all lowercase. So I wrapped it in \` 😄

2022-05-04 00:24 UTC, aczechowski commented on windows/deployment/update/how-windows-update-works.md
> +- If WUA fails to reach the service due to a certain proxy, service, or authentication error code, then user proxy is attempted (generally it is the logged-in user) Note: For intranet WSUS update ser
I fixed this to be a proper `> [!NOTE]`

2022-05-04 00:25 UTC, aczechowski commented on windows/deployment/update/how-windows-update-works.md
> +For WU URLs which are NOT used for update detection (download, reporting etc):
I fixed this, mostly by using contraction "_aren't_" and with emphasis

2022-05-04 00:31 UTC, aczechowski approved these changes
Thanks @itsrlyAria for the contribution, and thank you for what appears to be your first to the Windows repository! 🎉 I made some tweaks based on feedback from @JohanFreelancer9, but otherwise looks good. The changes will publish live around 11 AM Pacific on 4 May 2022.

2022-05-04 00:32 UTC, merged