Refresh Repository Contribution Guide
MicrosoftDocs/windows-itpro-docs pull request #10539
Opened 2022-05-13 04:49 UTC by aisgbnok

## Description

The `windows-itpro-docs` repository contains a specific contributing guide that was a little outdated and misleading. It also doesn't include helpful information from the [main contributing guide.](https://docs.microsoft.com/contribute/)

### Changes: 
- Added links to the main Microsoft hosted contributing guide, custom Microsoft docs markdown, etc.
- Also updated this repo specific contributing guide
   - Screenshots match the current GitHub and Docs design
   - Improved clarity and accuracy in regards to current contribution flow
- Closes #10468

2022-05-14 07:24 UTC, JohanFreelancer9 commented on CONTRIBUTING.md
> +    - **If you're external to Microsoft:** [Microsoft Docs Markdown reference](https://docs.microsoft.com/contribute/markdown-reference), [Mastering Markdown](https://guides.github.com/features/maste
```suggestion
    - **If you're external to Microsoft:** [Microsoft Docs Markdown reference](/contribute/markdown-reference), [Mastering Markdown](https://guides.github.com/features/mastering-markdown/)
```

2022-05-14 07:34 UTC, JohanFreelancer9 commented on CONTRIBUTING.md
> +At the top of a topic page you'll see an **Issues** tab. Click the tab and then click the **New issue** button.
```suggestion
At the top of a topic page, you'll see an **Issues** tab. Select the tab and then select the **New issue** button.
```

2022-05-16 04:31 UTC, JohanFreelancer9 commented on CONTRIBUTING.md
>  >At this time, only the English (en-us) content is available for editing.
```suggestion
> [!NOTE]
> At this time, only the English (en-us) content is available for editing.
```

2022-05-16 04:33 UTC, JohanFreelancer9 commented on CONTRIBUTING.md
> +    If the pencil icon isn't present, it may mean the content isn't open to public contributions. Some pages are generated (for example, from inline documentation in code) and must be edited in the p
```suggestion
    If the pencil icon isn't present, it might mean the content isn't open to public contributions. Some pages are generated (for example, from inline documentation in code) and must be edited in the project they belong to.
```

2022-05-16 04:34 UTC, JohanFreelancer9 commented on CONTRIBUTING.md
> +2. On GitHub, select the **Pencil** icon to edit the article. If the pencil icon is grayed out, you need to either log in to your GitHub account or create a new account.
```suggestion
2. In GitHub, select the **Pencil** icon to edit the article. If the pencil icon is grayed out, you need to either log in to your GitHub account or create a new account.
```

2022-05-16 04:38 UTC, JohanFreelancer9 commented on CONTRIBUTING.md
> +7. Click **Create pull request** again to actually submit the pull request.
```suggestion
7. Select **Create pull request** again to actually submit the pull request.
```

2022-05-16 04:39 UTC, JohanFreelancer9 commented on CONTRIBUTING.md
> +    The pull request is sent to the writer of the topic and your edits are reviewed. If your request is accepted, updates are published to their respective article. This repository contains articles
```suggestion
    The pull request is sent to the writer of the topic and your edits are reviewed. If your request is accepted, updates are published to their respective article. This repository contains articles on some of the following topics:
```

2022-05-16 04:51 UTC, JohanFreelancer9 requested changes
Copy review - @aisgbnok, kindly commit the minor suggested changes if you agree with them. Many thanks.

2022-05-16 12:29 UTC, aisgbnok commented on CONTRIBUTING.md
>  >At this time, only the English (en-us) content is available for editing.
I don't believe this `CONTRIBUTING.md` page gets published to docs.microsoft.com, it's repo specific. So using the traditional markdown `**Note**` will render better here.

2022-05-16 12:32 UTC, aisgbnok commented
@JohanFreelancer9 As far as I know this page doesn't get converted into a Microsoft docs page, so I'm not committing the Note change. It wouldn't render correctly in traditional markdown.

I have committed the other changes! As always, thank you for these reviews they are super helpful. 👍

2022-05-16 12:37 UTC, JohanFreelancer9 approved these changes

2022-05-16 12:38 UTC, JohanFreelancer9 commented
Thank you @aisgbnok!

2022-05-20 00:15 UTC, aczechowski requested changes
Thanks @aisgbnok for the updates! I have some inline comments for you to change.

2022-05-20 00:15 UTC, aczechowski commented on CONTRIBUTING.md
> +    - **If you're linked to the Microsoft organization in GitHub:** [Windows authoring guide](https://aka.ms/WindowsAuthoring)
Let's remove this line (and then adjust the others on either side accordingly). I wasn't even aware of that aka.ms link, but it's focused on the Windows _developer_ experience docs. Whereas this repo (and thus contributing.md) is focused on the Windows _IT Pro_ experience.

2022-05-20 00:15 UTC, aczechowski commented on CONTRIBUTING.md
>      - [Surface](https://docs.microsoft.com/surface)
Nope, Surface isn't in this repo, it's in devices-docs, so just remove this line

2022-05-20 00:15 UTC, aczechowski commented on CONTRIBUTING.md
>      - [Surface Hub](https://docs.microsoft.com/surface-hub)
Same, in devices-docs, remove this line

2022-05-20 00:15 UTC, aczechowski commented on CONTRIBUTING.md
>      - [HoloLens](https://docs.microsoft.com/hololens)
In the hololens repo, remove this line

2022-05-20 00:15 UTC, aczechowski commented on CONTRIBUTING.md
> +    - [Windows client documentation for IT Pros](https://docs.microsoft.com/windows/)
Change this to the more specific, `https://docs.microsoft.com/windows/resources/`, which is the Windows client for IT pros audience. Other Windows audiences fall into other repositories.

2022-05-20 00:15 UTC, aczechowski commented on CONTRIBUTING.md
>      - [Microsoft Desktop Optimization Pack](https://docs.microsoft.com/microsoft-desktop-optimization-pack)
Remove MDOP, it's in mdop-docs repo

2022-05-20 00:50 UTC, aisgbnok commented
@aczechowski Thanks for those suggestions I wasn't sure what articles were still maintained in this repo. I committed your suggestions and made a few other improvements as well.

I attempted to add you as co-author but GitHub didn't take it. I kind of guessed on the email.

2022-05-20 00:58 UTC, aisgbnok commented
There I got it to work. Was missing a space. Sorry for the force pushes, but they should be fine in this instance. Done unless you have any other recommendations. Thanks again!

2022-05-24 22:53 UTC, aczechowski reviewed
Thanks @aisgbnok for the revisions. I'm going to do a preemptive check with our repo admins on this edit. (I should have done it earlier.) I don't think it will be an issue, but want to make sure before going further with it.

2022-05-25 00:13 UTC, aczechowski approved these changes
I just went ahead and made some direct edits based on feedback from repo admins. (They may adopt this for other repos our team owns 😉 ) Merging now

2022-05-25 00:13 UTC, merged

2022-05-25 00:58 UTC, aisgbnok commented on CONTRIBUTING.md
> +    > View the page source in your browser, and look for the following metadata: `original_content_git_url`. This path always points to the source markdown file for the article.
Huh, what a cool tip! In certain instances that may come in handy. Good to know.