Replace credential guard group policy image
MicrosoftDocs/windows-itpro-docs pull request #10577
Opened 2022-06-02 18:38 UTC by aisgbnok

> **Warning**
> This is a draft. Not complete.

Closes #9761

2022-06-02 23:38 UTC, aisgbnok reviewed
Here are some hopefully helpful inline comments describing what I did and why. 👍

**It might make the most sense if you view these comments directly in the file.**

2022-06-02 23:38 UTC, aisgbnok commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> +1. From the Group Policy Management Console, go to **Computer Configuration** > **Administrative Templates** > **System** > **Device Guard**.
I changed all the different arrows like `->` to `>` as I see that used more widely in the Docs. I did this throughout the article.

2022-06-02 23:38 UTC, aisgbnok commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> +1. Select **Turn On Virtualization Based Security**, and then select the **Enabled** option.
[Word choice **Select** instead of **Click**.](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/c/click)

2022-06-02 23:38 UTC, aisgbnok commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> +1. In the **Secure Launch Configuration** box, choose **Not Configured**, **Enabled** or **Disabled**. See [System Guard Secure Launch and SMM protection](../../threat-protection/windows-defender-sys
Replaced **this article** with the actual article title.

2022-06-02 23:38 UTC, aisgbnok commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> +1. In the **Credential Guard Configuration** box, select **Enabled with UEFI lock**. If you want to be able to turn off Windows Defender Credential Guard remotely, choose **Enabled without lock**.
Removed **click OK** because the user isn't done making selections yet.

2022-06-02 23:38 UTC, aisgbnok commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> +1. Select **OK**, and then close the Group Policy Management Console.
The user is now done. Can now select **OK**.

2022-06-02 23:38 UTC, aisgbnok commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> +##### Add the virtualization-based security features by using Programs and Features
Made this a heading instead of just bolded.

2022-06-02 23:38 UTC, aisgbnok commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> +##### Add the virtualization-based security features to an offline image by using DISM
Made this a heading instead of just bolded.

2022-06-02 23:38 UTC, aisgbnok commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> +   :::image type="content" source="images/credguard-gp.png" alt-text="Windows Defender Credential Guard Group Policy setting.":::
The crux of this PR. The updated `credguard-gp.png`.

2022-06-02 23:38 UTC, aisgbnok commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> +   1. Go to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\DeviceGuard`.
I formatted all of the registry entries as code. I also removed their weird escaped `HKEY\_LOCAL\_MACHINE\\` formatting with just single slashes. Did not change or verify their paths. I assume they are correct. I'm just formatting not changing content.

2022-06-02 23:38 UTC, aisgbnok commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> -<span id="hardware-readiness-tool"/>
I removed these HTML span tags. On the production page, they seem to stop the headings from getting their own anchor [even though one is present.](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#enable-windows-defender-credential-guard-by-using-the-hvci-and-windows-defender-credential-guard-hardware-readiness-tool) If you go to that page and hover over the "Enable Windows Defender Credential Guard by using the HVCI and Windows Defender Credential Guard hardware readiness tool" heading no link button will show up.

I did not find any usages of `#hardware-readiness-tool` in this entire repo.

2022-06-02 23:38 UTC, aisgbnok commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> +#### Is Windows Defender Credential Guard running?
This seemed like a heading.

2022-06-02 23:38 UTC, aisgbnok commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> +   :::image type="content" source="images/credguard-msinfo32.png" alt-text="The 'Virtualization-based security Services Running' entry lists Credential Guard in System Information (msinfo32.exe).":::
Removed the "Here's an example:", didn't think it was needed.

Replaced the weird image format with the `:::` image format and also updated the alt text.

2022-06-02 23:38 UTC, aisgbnok commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> -<span id="turn-off-with-hardware-readiness-tool"/>
Removed this span tag as described above. I replaced all references to `#turn-off-with-hardware-readiness-tool` with `#disable-windows-defender-credential-guard-by-using-the-hvci-and-windows-defender-credential-guard-hardware-readiness-tool`.

I know longer, but not sure if span tag is standard practice anymore.

2022-06-02 23:38 UTC, aisgbnok commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> +### Disable Windows Defender Credential Guard for a virtual machine
This and the previous heading had the wrong increment. Should be heading level 3 not 4, as the parent is level 2.

2022-06-02 23:38 UTC, aisgbnok commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> +To disable Windows Defender Credential Guard, you can use the following set of procedures or the [HVCI and Windows Defender Credential Guard hardware readiness tool](#disable-windows-defender-credent
Updated this link as the span tag was removed. Also, use **HVCI and Windows Defender Credential Guard hardware readiness tool** as that specific wording is used elsewhere in this article.

2022-06-02 23:45 UTC, aisgbnok commented
@aczechowski, this is ready to review now. Whoever reviews this, please let me know how I could better write PR descriptions to be understandable for you. I try my best to provide just enough detail on what and why but not too much. Also, let me know if the inline comments are helpful or just make it more confusing.

2022-06-03 01:50 UTC, aczechowski requested changes
Hi @aisgbnok thank you this contribution and for the detailed comments! I'm sure it took some time, but it was very helpful in understanding the reasoning behind your edits.

I have two minor suggestions, but otherwise awesome! Thanks!

2022-06-03 01:50 UTC, aczechowski commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> +1. In the **Secure Launch Configuration** box, choose **Not Configured**, **Enabled** or **Disabled**. See [System Guard Secure Launch and SMM protection](../../threat-protection/windows-defender-sys
Can you revise this to the standard format, "For more information, see [title](link)."

```suggestion
1. In the **Secure Launch Configuration** box, choose **Not Configured**, **Enabled** or **Disabled**. For more information, see [System Guard Secure Launch and SMM protection](../../threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection.md).
```

2022-06-03 01:50 UTC, aczechowski commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> +   1. Go to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\DeviceGuard`.
Changes you made are generally awesome. While you're there... 😉 could you also change the devlang on the code blocks from "console" to "cmd"? For example:

```markdown
   ```cmd
   runme.exe...
```

2022-06-03 16:38 UTC, aisgbnok commented
@aczechowski, should be good now. 

Is `cmd` a replacement for `console`, or is `cmd` just preferred because it's more specific towards the content?

2022-06-03 17:52 UTC, aczechowski approved these changes

2022-06-03 17:52 UTC, merged