Set Policy Driven Update path's are wrong
MicrosoftDocs/windows-itpro-docs pull request #10626
Opened 2022-06-15 16:40 UTC by GrischaE1

All Updates SetPolicyDrivenUpdateSource path's are wrong - there needs an "Updates" added to the settings name.
Verified under 21H2 -> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\default\Update

2022-06-15 21:26 UTC, denisebmsft commented
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10617

2022-06-17 05:50 UTC, JohanFreelancer9 commented on windows/client-management/mdm/policy-csp-update.md
>  >If you have not properly configured Update/UpdateServiceUrl correctly to point  your WSUS server, this policy will have no effect.
```suggestion
>If you have not properly configured Update/UpdateServiceUrl correctly to point to your WSUS server, this policy will have no effect. 
```

2022-06-17 05:50 UTC, JohanFreelancer9 commented on windows/client-management/mdm/policy-csp-update.md
>  >If you have not properly configured Update/UpdateServiceUrl correctly to point  your WSUS server, this policy will have no effect.
```suggestion
>If you have not properly configured Update/UpdateServiceUrl correctly to point to your WSUS server, this policy will have no effect. 
```

2022-06-17 05:51 UTC, JohanFreelancer9 commented on windows/client-management/mdm/policy-csp-update.md
>  >If you have not properly configured Update/UpdateServiceUrl correctly to point your WSUS server, this policy will have no effect.
```suggestion
>If you have not properly configured Update/UpdateServiceUrl correctly to point to your WSUS server, this policy will have no effect. 
```

2022-06-17 05:51 UTC, JohanFreelancer9 commented on windows/client-management/mdm/policy-csp-update.md
>  >If you have not properly configured Update/UpdateServiceUrl correctly to point your WSUS server, this policy will have no effect.
```suggestion
>If you have not properly configured Update/UpdateServiceUrl correctly to point to your WSUS server, this policy will have no effect. 
```

2022-06-17 05:58 UTC, JohanFreelancer9 requested changes
Copy review - @GrischaE1,  not related, but could you kindly also commit the suggested changes to correct the typos? Many thanks.

2022-06-20 09:09 UTC, JohanFreelancer9 approved these changes

2022-07-12 23:52 UTC, aczechowski approved these changes

2022-07-12 23:52 UTC, merged