updated the note
MicrosoftDocs/windows-itpro-docs pull request #10632
Opened 2022-06-17 10:00 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10508

2022-06-17 13:08 UTC, JohanFreelancer9 commented on windows/security/information-protection/kernel-dma-protection-for-thunderbolt.md
> +   > If the **Hyper-V** Windows feature is enabled, all the Hyper-V-related features will be hidden, and **A hypervisor has been detected. Features required for Hyper-V will not be displayed** entity
```suggestion
   > If the **Hyper-V** Windows feature is enabled, all the Hyper-V-related features will be hidden, and **A hypervisor has been detected. Features required for Hyper-V will not be displayed** entity will be shown at the bottom of the list. It means that **Hyper-V - Virtualization Enabled in Firmware** is set to YES.
```

2022-06-17 13:08 UTC, JohanFreelancer9 commented on windows/security/information-protection/kernel-dma-protection-for-thunderbolt.md
> +   >[!NOTE]
```suggestion
   > [!NOTE]
```

2022-06-17 13:08 UTC, JohanFreelancer9 requested changes
Copy review.

2022-06-17 16:06 UTC, SillyKeith commented
Are there 3 Notes now?   I think this is more confusing. 

Also, perhaps the feature team can get you a better MSINFO32 screenshot?  One that zooms into just the area of interest and without all the MS internal Build#s and codenames (Palindrome in System Mfgr).  I've attached an example (Don't use mine though since my system is missing a security feature). A Surface PC might be a better one to take it from... 

![MSINFO32](https://user-images.githubusercontent.com/28606059/174334830-61d42174-6d0b-4870-991c-ea1471d3c84e.png)

2022-06-17 16:53 UTC, JohanFreelancer9 commented on windows/security/information-protection/kernel-dma-protection-for-thunderbolt.md
>     >[!NOTE]
```suggestion
   > [!NOTE]
```

2022-06-18 05:35 UTC, MaratMussabekov commented
Hello,
Are there 3 Notes now? I think this is more confusing. - no, only two. I separated the part where it said that IOMMU is required.

2022-06-18 05:48 UTC, JohanFreelancer9 approved these changes

2022-07-13 00:06 UTC, aczechowski approved these changes

2022-07-13 00:08 UTC, aczechowski commented
Thanks @MaratMussabekov for the contribution.
@SillyKeith if things still aren't clear based on your original feedback #10508, please file additional feedback. Also, regarding the screenshot, probably best to file a separate issue specific to that request.

2022-07-13 00:08 UTC, merged