Replaced the instruction with the link
MicrosoftDocs/windows-itpro-docs pull request #10649
Opened 2022-06-22 05:42 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10520
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10308

replaced the outdated instruction with the link to the document with up-to-date instruction

2022-06-22 05:42 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

2022-06-22 06:40 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md
> +To learn how to download, install and configure Intune Certificate Connector, please see [Install the Certificate Connector for Microsoft Intune](/mem/intune/protect/certificate-connector-install)
```suggestion
To learn how to download, install, and configure Intune Certificate Connector, see [Install the Certificate Connector for Microsoft Intune](/mem/intune/protect/certificate-connector-install).
```

2022-06-22 06:44 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md
> +Optionally (not required), you can configure the Intune connector for certificate revocation when a device is wiped, unenrolled, or when the certificate profile falls out of scope for the targeted us
```suggestion
Optionally (not required), you can configure the Intune connector for certificate revocation when a device is wiped, unenrolled, or when the certificate profile falls out of scope for the targeted user (users are removed, deleted, or the profile is deleted). You need to select the **Certificate revocation** option during the connector configuration to enable automatic certificate revocation for certificates issued from a Microsoft Active Directory Certification Authority. Additionally, you need to enable the NDES Service account for revocation.
```

2022-06-22 06:45 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md
> +1. Sign-in the certificate authority used by the NDES Connector with access equivalent to _domain administrator_.
```suggestion
1. Sign in the certificate authority used by the NDES Connector with access equivalent to _domain administrator_.
```

2022-06-22 06:49 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md
> +4. Click the **Security** tab.  Click **Add**. In **Enter the object names to select** box, type **NDESSvc** (or the name you gave the NDES Service account).  Click *Check Names*. Click **OK**.  Sele
```suggestion
4. Select the **Security** tab, then select **Add**. In the **Enter the object names to select** box, enter **NDESSvc** (or the name you gave the NDES Service account).  Select *Check Names*, then select **OK**.  Select the NDES Service account from the **Group or user names** list. Select **Allow** for the **Issue and Manage Certificates** permission.  Select **OK**.
```

2022-06-22 06:53 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md
> +4. Select the **Security** tab, then select **Add**. In the **Enter the object names to select** box, enter **NDESSvc** (or the name you gave the NDES Service account).  Select *Check Names*, then se
```suggestion
4. Select the **Security** tab, then select **Add**. In the **Enter the object names to select** box, enter **NDESSvc** (or the name you gave the NDES Service account). Select *Check Names*, then select **OK**. Select the NDES Service account from the **Group or user names** list. Select **Allow** for the **Issue and Manage Certificates** permission. Select **OK**.
```

2022-06-22 06:55 UTC, JohanFreelancer9 requested changes
Copy review.

2022-06-22 10:58 UTC, JohanFreelancer9 approved these changes

2022-07-13 00:50 UTC, aczechowski approved these changes

2022-07-13 00:52 UTC, merged