schedulequickscantime does not rely on scanparameter
MicrosoftDocs/windows-itpro-docs pull request #10661
Opened 2022-06-27 12:47 UTC by peterhuerlimann

Edited to reflect that schedulequickscantime does not rely on scanparameter, as it's about setting the time for a daily quick scan. I added a remark to reiterate the fact that this enables a daily quick scan on the specified time.

2022-06-28 07:17 UTC, JohanFreelancer9 commented on windows/client-management/mdm/policy-csp-defender.md
> +Selects the time of day that the Windows Defender quick scan should run. The Windows Defender quick scan runs daily, if a time is specified.
```suggestion
Selects the time of day that the Windows Defender quick scan should run. The Windows Defender quick scan runs daily if a time is specified.
```

2022-06-28 07:18 UTC, JohanFreelancer9 requested changes
Copy review - @peterhuerlimann, kindly commit the minor suggested change. Many thanks.

2022-07-01 14:02 UTC, JohanFreelancer9 approved these changes

2022-07-13 00:59 UTC, aczechowski approved these changes

2022-07-13 00:59 UTC, merged