add more info
MicrosoftDocs/windows-itpro-docs pull request #10660
Opened 2022-06-27 10:19 UTC by VLG17

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9759

2022-06-28 07:10 UTC, JohanFreelancer9 commented on windows/security/threat-protection/security-policy-settings/log-on-as-a-batch-job.md
> +The **Log on as a batch job** user right presents a low-risk vulnerability, that allows non-administrators to perform administrator-like functions.  If not assessed, understood, and restricted accord
```suggestion
The **Log on as a batch job** user right presents a low-risk vulnerability that allows non-administrators to perform administrator-like functions.  If not assessed, understood, and restricted accordingly, attackers can easily exploit this potential attack vector to compromise systems, credentials, and data. For most organizations, the default settings are sufficient. Members of the local Administrators group have this right by default.
```

2022-06-28 07:11 UTC, JohanFreelancer9 requested changes
Copy review - @VLG17, kindly commit the minor suggested change. Many thanks.

2022-06-28 08:47 UTC, JohanFreelancer9 approved these changes

2022-07-13 00:57 UTC, aczechowski approved these changes

2022-07-13 00:57 UTC, merged