10678-UpdateCredentialGuardIntuneDocu
MicrosoftDocs/windows-itpro-docs pull request #10679
Opened 2022-07-01 12:19 UTC by Speed1

Changed the manual to settings catalog options for Microsoft Endpoint Manager

2022-07-02 09:08 UTC, JohanFreelancer9 commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> +   1. Configuration settings: In the settings picker select **Device Guard** as category and add the needed settings
```suggestion
   1. Configuration settings: In the settings picker select **Device Guard** as category and add the needed settings.
```

2022-07-02 09:10 UTC, JohanFreelancer9 requested changes
Copy review - @Speed1, kindly commit the minor suggested change. Many thanks.

2022-07-04 07:47 UTC, JohanFreelancer9 approved these changes

2022-07-12 21:56 UTC, aczechowski approved these changes
Thanks @Speed1 for submitting this edit, and thank you for your first contribution to windows-itpro-docs! 🎉

2022-07-12 21:56 UTC, merged