Update deploy-multiple-windows-defender-application-control-policies.md
MicrosoftDocs/windows-itpro-docs pull request #10698
Opened 2022-07-06 20:29 UTC by timbrigham-onecall

Add some details surrounding issues and what happens on exceeding the 32 policy limit.

2022-07-07 07:23 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/deploy-multiple-windows-defender-application-control-policies.md
> +### Known Issues in Multiple Policy Format
```suggestion
### Known issues in multiple policy format
```

2022-07-07 07:27 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/deploy-multiple-windows-defender-application-control-policies.md
> +* If policies are loaded without requiring a reboot such as `PS_UpdateAndCompareCIPolicy` will still count towards this limit.
```suggestion
* If policies are loaded without requiring a reboot such as `PS_UpdateAndCompareCIPolicy`, they will still count towards this limit. 
```

2022-07-07 07:27 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/deploy-multiple-windows-defender-application-control-policies.md
> +* This may pose an especially large challenge if the value of `{PolicyGUID}.cip` changes between releases. This may result in a long window between a change and the resultant reboot.
```suggestion
* This may pose an especially large challenge if the value of `{PolicyGUID}.cip` changes between releases. It may result in a long window between a change and the resultant reboot.
```

2022-07-07 07:28 UTC, JohanFreelancer9 requested changes
Copy review - @timbrigham-onecall, kindly commit the suggested changes. Many thanks.

2022-07-08 09:11 UTC, JohanFreelancer9 approved these changes

2022-07-13 02:29 UTC, aczechowski approved these changes

2022-07-13 02:30 UTC, aczechowski commented
Thanks @timbrigham-onecall for the edit, and thank you for your first contribution to windows-itpro-docs! 🎉

2022-07-13 02:31 UTC, merged