Add new CSP node IcmpTypesAndCodes
MicrosoftDocs/windows-itpro-docs pull request #10693
Opened 2022-07-05 22:57 UTC by jess-krynitsky

We have added support for a new firewall rule setting and corresponding CSP node allowing users to specify ICMP types and codes. I have updated the tree and description on this page to reflect the new settings.

2022-07-05 23:07 UTC, jess-krynitsky commented
Adding author @Dansimp to review. Thanks!

2022-07-06 09:44 UTC, JohanFreelancer9 commented on windows/client-management/mdm/firewall-csp.md
> +ICMP types and codes applicable to the firewall rule. To specify all ICMP types and codes, use the “*” character. For specific ICMP types and codes, use the “:” character to separate the type and cod
```suggestion
ICMP types and codes applicable to the firewall rule. To specify all ICMP types and codes, use the “/*” character. For specific ICMP types and codes, use the “:” character to separate the type and code, for example, 3:4, 1:/*. The “/*” character can be used to represent any code. The “/*” character cannot be used to specify any type; examples such as “/*:4” or “/*:/*” are invalid.
```

2022-07-06 09:44 UTC, JohanFreelancer9 commented on windows/client-management/mdm/firewall-csp.md
> +
```suggestion
```

2022-07-06 09:51 UTC, JohanFreelancer9 requested changes
Copy review - @jess-krynitsky, kindly commit the suggested changes. The "\" is needed for the text to render correctly (please see the preview). Many thanks.

2022-07-11 23:31 UTC, jess-krynitsky reviewed
Committing suggested changes for proper rendering. However, the "*" character is not showing up in the preview now so I will need to check in an additional change.

2022-07-12 10:45 UTC, JohanFreelancer9 approved these changes

2022-07-12 15:49 UTC, jess-krynitsky commented
@JohanFreelancer9 thanks for the PR approval. What need to be done to merge this change with the base branch?

2022-07-13 01:38 UTC, aczechowski approved these changes

2022-07-13 01:38 UTC, merged