Update waas-wu-settings.md
MicrosoftDocs/windows-itpro-docs pull request #10730
Opened 2022-07-27 09:19 UTC by itsrlyAria

Added Microsoft Store for Business to the list of things that stop working if you prevent all connection to Windows Updates.

2022-07-27 15:09 UTC, alvinchardon approved these changes

2022-07-28 06:09 UTC, JohanFreelancer9 commented on windows/deployment/update/waas-wu-settings.md
> +Use **Computer Configuration\Administrative Templates\Windows Components\Windows update\Do not connect to any Windows Update Internet locations** to enable this policy. When enabled, this policy will
```suggestion
Use **Computer Configuration\Administrative Templates\Windows Components\Windows update\Do not connect to any Windows Update Internet locations** to enable this policy. When enabled, this policy will disable the functionality described above, and may cause connection to public services such as the Microsoft Store, Microsoft Store for Business, Windows Update for Business, and Delivery Optimization to stop working.
```

2022-07-28 06:09 UTC, JohanFreelancer9 requested changes
Copy review - @itsrlyAria, kindly commit the minor suggested change. Many thanks.

2022-07-28 14:48 UTC, aczechowski approved these changes

2022-07-28 14:49 UTC, merged