Update bitlocker-recovery-guide-plan.md
MicrosoftDocs/windows-itpro-docs pull request #10873
Opened 2022-09-19 23:52 UTC by rafals2

added info about accessibility tools

## Why

- Closes #[Issue Number]

## Changes

2022-09-21 05:57 UTC, JohanFreelancer9 commented on windows/security/information-protection/bitlocker/bitlocker-recovery-guide-plan.md
> +The BitLocker recovery screen that is shown by Windows RE has the accessibility tools like narrator and on-screen keyboard to help people enter their BitLocker recovery key. Those tools may not be av
```suggestion
The BitLocker recovery screen that is shown by Windows RE has the accessibility tools like narrator and on-screen keyboard to help you enter your BitLocker recovery key. Those tools might not be available if the BitLocker recovery key is requested by the Windows boot manager.
```

2022-09-21 05:57 UTC, JohanFreelancer9 commented on windows/security/information-protection/bitlocker/bitlocker-recovery-guide-plan.md
> +To activate narrator during BitLocker Recovery in WinRE press Win + CTRL + ENTER
```suggestion
To activate narrator during BitLocker Recovery in WinRE, press Win + CTRL + ENTER
```

2022-09-21 05:58 UTC, JohanFreelancer9 requested changes
Copy review - @rafals2, ki ndly commit the minor suggested changes. Many thanks.

2022-09-22 18:20 UTC, aczechowski approved these changes
Thanks @rafals2 for the contribution! 😄

2022-09-22 18:20 UTC, merged