Added missing explanation of the "container" term to hello-faq.yml on…
MicrosoftDocs/windows-itpro-docs pull request #10979
Opened 2022-11-07 18:15 UTC by vazome

… the base of retired hello-how-it-works.md.

## Why

**What’s a container?** – elaborately explained the concept of WH4B container, but now is lost because of retirement.
Let's bring it back in a shorter form.

- Closes #[Issue Number]

## Changes

windows/security/identity-protection/hello-for-business/hello-faq.yml

2022-11-08 05:13 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-faq.yml
> +          In the context of Windows Hello for Business it is shorthand for a logical grouping of key material or data. Windows 10 or Windows 11 Hello uses a single container that holds user key mater
```suggestion
          In the context of Windows Hello for Business, it is shorthand for a logical grouping of key material or data. Windows 10 or Windows 11 Hello uses a single container that holds user key material for personal accounts, including key material associated with the user's Microsoft account or with other consumer identity providers, and credentials associated with a workplace or school account.
```

2022-11-08 05:14 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-faq.yml
> +          It's important to keep in mind that there are no physical containers on disk, in the registry, or elsewhere. Containers are logical units used to group related items. The keys, certificates
```suggestion
          It's important to keep in mind that there are no physical containers on disk, in the registry, or elsewhere. Containers are logical units used to group related items. The keys, certificates, and credentials of Windows Hello stores are protected without the creation of actual containers or folders.
```

2022-11-08 05:14 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-faq.yml
> +      - question: How to delete Windows Hello for Business container on a device?
```suggestion
      - question: How do I delete a Windows Hello for Business container on a device?
```

2022-11-08 05:14 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-faq.yml
> +          You can effectively disable Windows Hello for Business by launching `certutil.exe -deleteHelloContainer` on the end device under a user account. Reboot is required.
```suggestion
          You can effectively disable Windows Hello for Business by launching `certutil.exe -deleteHelloContainer` on the end device under a user account, and then restarting the device.
```

2022-11-08 05:19 UTC, JohanFreelancer9 requested changes
Copy review - @vazome, kindly commit the suggested changes. Many thanks.

2022-11-08 08:51 UTC, opbld32 commented
Learn Build status updates of commit _[4e5db7c](https://github.com/vazome/windows-itpro-docs/commits/4e5db7c46371774ddd85ee909e840f6391eeacab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/security/identity-protection/hello-for-business/hello-faq.yml](https://github.com/vazome/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-faq.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211080844589456-10979/BuildReport?accessString=8a8566d30a234e7a4799c2e6c2808a785174a5f19588a784d57606b3ee5e0d07).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-08 09:11 UTC, vazome commented
@JohanFreelancer9 sure

2022-11-08 11:26 UTC, JohanFreelancer9 approved these changes

2022-11-09 20:31 UTC, paolomatarazzo commented on windows/security/identity-protection/hello-for-business/hello-faq.yml
> +
can you please update with the following (taken from the retired article):

      - question: What's a container?
        answer: |  
          In the context of Windows Hello for Business, it's shorthand for a logical grouping of key material or data. Windows Hello uses a single container that holds user key material for personal accounts, including key material associated with the user's Microsoft account or with other consumer identity providers, and credentials associated with a workplace or school account.
          The container holds enterprise credentials only on devices that have been registered with an organization; it contains key material for the enterprise IDP, such as on-premises Active Directory or Azure AD.
          Note that there are no physical containers on disk, in the registry, or elsewhere. Containers are logical units used to group related items. The keys, certificates, and credentials of Windows Hello stores, are protected without the creation of actual containers or folders.
          The container contains a set of keys, some of which are used to protect other keys. The following image shows an example: the protector key is used to encrypt the authentication key, and the authentication key is used to encrypt the individual keys stored in the container. [Each logical container holds one or more sets of keys.](./images/passport-fig3-logicalcontainer.png)

2022-11-09 20:31 UTC, paolomatarazzo commented
hello @vazome and thank you for the contribution. Can you please update looking at the proposed change?

2022-11-09 21:13 UTC, vazome commented on windows/security/identity-protection/hello-for-business/hello-faq.yml
> +
Done

2022-11-09 21:17 UTC, opbld31 commented
Learn Build status updates of commit _[311f28c](https://github.com/vazome/windows-itpro-docs/commits/311f28c3985a967adbc9eed85fc1bcc3a1223c5f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/security/identity-protection/hello-for-business/hello-faq.yml](https://github.com/vazome/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-faq.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211092111435681-10979/BuildReport?accessString=f3b6eaf4e4355b6c7300174d35f806c6e253c08cff7d2dffa485a2355282eb15).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 21:38 UTC, merged