typo correction
MicrosoftDocs/windows-itpro-docs pull request #10977
Opened 2022-11-06 05:45 UTC by RAJU2529

as per user report #10963, so I added the correct path

![Screenshot 2022-11-06 111445](https://user-images.githubusercontent.com/3296790/200156184-5aa0d40c-a99f-4031-ab26-bb9e15c70f82.jpg)

2022-11-06 05:52 UTC, opbld33 commented
Learn Build status updates of commit _[68f6a4f](https://github.com/RAJU2529/windows-itpro-docs/commits/68f6a4f08ab57323f1b2800defa0f408818edd33)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/deployment/windows-10-missing-fonts.md](https://github.com/RAJU2529/windows-itpro-docs/blob/patch-265/windows/deployment/windows-10-missing-fonts.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211060545387807-10977/BuildReport?accessString=c82ba1397f129f635c1219dc8e9064181ae5c213b59943e7ca1bcaf29abd68af).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-07 06:21 UTC, JohanFreelancer9 commented on windows/deployment/windows-10-missing-fonts.md
> +   For Windows 11, In **Settings**, select **Time & language**, and then select **Langauge & Region**.
```suggestion
2. For Windows 10, in **Settings**, select **Time & language**, and then select **Region & language**.

   For Windows 11, in **Settings**, select **Time & language**, and then select **Langauge & Region**.
```

2022-11-07 06:22 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-07 06:37 UTC, opbld30 commented
Learn Build status updates of commit _[a14a4fe](https://github.com/RAJU2529/windows-itpro-docs/commits/a14a4fe184ddcbdfe0070ca1ea4057b0a78a1fcd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/deployment/windows-10-missing-fonts.md](https://github.com/RAJU2529/windows-itpro-docs/blob/patch-265/windows/deployment/windows-10-missing-fonts.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211070630258057-10977/BuildReport?accessString=0cb79033fbaa4abf40eff5fe3a6e5584c3fefec020b735cbb10924d7f411a5a1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-07 07:54 UTC, JohanFreelancer9 approved these changes

2022-11-07 13:02 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-11-07 15:04 UTC, merged