Update servicing-stack-updates.md
MicrosoftDocs/windows-itpro-docs pull request #10985
Opened 2022-11-08 14:02 UTC by msbemba

Made changes to the document as we can now deploy Windows SSUs and LCUs together with one cumulative update

reference https://techcommunity.microsoft.com/t5/windows-it-pro-blog/deploy-windows-ssus-and-lcus-together-with-one-cumulative-update/ba-p/1967887

per issue#https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10582

## Why

- Closes #[Issue Number]

## Changes

2022-11-08 14:02 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-11-08 14:09 UTC, opbld30 commented
Learn Build status updates of commit _[360a60f](https://github.com/msbemba/windows-itpro-docs/commits/360a60f5e407a360b769f66bb1d62a32712ae7e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/deployment/update/servicing-stack-updates.md](https://github.com/msbemba/windows-itpro-docs/blob/patch-5/windows/deployment/update/servicing-stack-updates.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211081402194507-10985/BuildReport?accessString=619374ade5d8ee162a63e6a940878fb4bb51f471d1ede4824013235901f75f1c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-08 15:06 UTC, JohanFreelancer9 commented on windows/deployment/update/servicing-stack-updates.md
> +Beginning with the February 2021 LCU, microsoft will publish all future cumulative updates and SSUs for Windows 10, version 2004 and above together as one cumulative monthly update to the normal rele
```suggestion
Beginning with the February 2021 LCU, Microsoft will publish all future cumulative updates and SSUs for Windows 10, version 2004 and later together as one cumulative monthly update to the normal release category in WSUS.
```

2022-11-08 15:07 UTC, JohanFreelancer9 commented on windows/deployment/update/servicing-stack-updates.md
> +
```suggestion
```

2022-11-08 15:07 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-08 17:15 UTC, opbld32 commented
Learn Build status updates of commit _[92dd269](https://github.com/msbemba/windows-itpro-docs/commits/92dd269296098e288c35837e66dc9c577a388c70)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/deployment/update/servicing-stack-updates.md](https://github.com/msbemba/windows-itpro-docs/blob/patch-5/windows/deployment/update/servicing-stack-updates.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211081706019306-10985/BuildReport?accessString=0a08bfde0a82e4f2c0a20ce0e46d1d9d681d253a72278b3ef37d3e10f4a23653).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 05:14 UTC, JohanFreelancer9 requested changes
@msbemba, you seem to have missed one suggested change. Could you also commit that, please?

2022-11-09 05:54 UTC, opbld30 commented
Learn Build status updates of commit _[b6afa82](https://github.com/msbemba/windows-itpro-docs/commits/b6afa82e9427d0ffa7559754c1035dd8d9925944)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/deployment/update/servicing-stack-updates.md](https://github.com/msbemba/windows-itpro-docs/blob/patch-5/windows/deployment/update/servicing-stack-updates.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211090548584550-10985/BuildReport?accessString=fed9b5497c4957b212dff3f32b380304026084f8c2a3b7db5de17982c36dae30).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 07:20 UTC, JohanFreelancer9 approved these changes

2022-11-14 15:06 UTC, yogkumgit commented
@aczechowski Please merge this PR. Thanks

2022-11-17 18:05 UTC, aczechowski approved these changes

2022-11-17 18:06 UTC, merged