Update wds-boot-support.md
MicrosoftDocs/windows-itpro-docs pull request #10992
Opened 2022-11-08 16:59 UTC by msbemba

Updated the document to represent  OS deployed vs boot image version as per the table

Per issue#https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10973

2022-11-08 16:59 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-11-08 17:05 UTC, opbld33 commented
Learn Build status updates of commit _[25da8c4](https://github.com/msbemba/windows-itpro-docs/commits/25da8c447f81b6a397eff89b336c46435744d480)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/deployment/wds-boot-support.md](https://github.com/msbemba/windows-itpro-docs/blob/patch-10/windows/deployment/wds-boot-support.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211081659350652-10992/BuildReport?accessString=ff7ee9a903192b97381a56346ead74d511ed4d043cc6f91df872d4bf269f2363).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 04:59 UTC, JohanFreelancer9 commented on windows/deployment/wds-boot-support.md
> +The table below provides support details for specific deployment scenarios (The table represents OS Deployed (vertical) and Boot Image Version(Horizontal) ).
```suggestion
The table below provides support details for specific deployment scenarios. (The table represents OS Deployed (vertical) and Boot Image Version (horizontal).)
```

2022-11-09 05:02 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-09 05:56 UTC, opbld32 commented
Learn Build status updates of commit _[89be3fd](https://github.com/msbemba/windows-itpro-docs/commits/89be3fd385c05e2662114425f7450d618bd2c771)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/deployment/wds-boot-support.md](https://github.com/msbemba/windows-itpro-docs/blob/patch-10/windows/deployment/wds-boot-support.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211090549472303-10992/BuildReport?accessString=7c5076df1f79001328ffe68cdc766f686ecdd5e71461739ff33a83b698e83e87).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 07:42 UTC, JohanFreelancer9 approved these changes

2022-11-09 10:07 UTC, yogkumgit commented
@aczechowski Please merge this PR. Thanks

2022-12-02 01:52 UTC, frankroj commented
I am going to take an alternate approach to updating the documentation besides the one proposed. I am going to label the top row as "Boot.wim for" and then label the columns as "OS Being Deployed". This should clarify what the table means.

2022-12-02 02:08 UTC, frankroj commented
Fixes https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10973

2022-12-02 02:09 UTC, frankroj commented
Fixes #10973

2022-12-02 02:10 UTC, frankroj commented
Made suggested changes. Merging and closing PR.

2022-12-02 02:10 UTC, merged