Update windows-10-subscription-activation.md
MicrosoftDocs/windows-itpro-docs pull request #10991
Opened 2022-11-08 16:40 UTC by msbemba

added a note about  excluding the Universal Store Service APIs and Web Application in the device compliance policy reference - https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-policy-compliant-device

Per issue#https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10972

2022-11-09 04:42 UTC, JohanFreelancer9 commented on windows/deployment/windows-10-subscription-activation.md
> +> Organizations that use the [Subscription Activation](/windows/deployment/windows-10-subscription-activation) feature to enable users to “step-up” from one version of Windows to another, may want to
```suggestion
> Organizations that use the [Subscription Activation](/windows/deployment/windows-10-subscription-activation) feature to enable users to upgrade from one version of Windows to another might want to exclude the Universal Store Service APIs and Web Application, AppID 45a330b1-b1ec-4cc1-9161-9f03992aa49f, from their device compliance policy.
```

2022-11-09 04:43 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-09 05:56 UTC, opbld32 commented
Learn Build status updates of commit _[b64fa61](https://github.com/msbemba/windows-itpro-docs/commits/b64fa615d60109386c36adaf8f33215a3b37af8c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/deployment/windows-10-subscription-activation.md](https://github.com/msbemba/windows-itpro-docs/blob/patch-9/windows/deployment/windows-10-subscription-activation.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211090550075336-10991/BuildReport?accessString=a9727f002ec0395449c19cbcae6d12967bd23eeba37d5f95c2a9ea5af30ef7c4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 07:44 UTC, JohanFreelancer9 approved these changes

2022-11-09 10:04 UTC, yogkumgit commented
@frankroj Please merge this PR. Thanks

2022-12-06 18:20 UTC, frankroj commented
This note previously existed in the docs and then was removed. Verifying with PMs if we should add back in.

2022-12-15 03:06 UTC, lee-halford commented
Noting that this has been mentioned in the Conditional Access Documentation which has a reference to this page. But there is no reference on this page about the problem. Would be good to also link back to the CA policy doc as well.

https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/active-directory/conditional-access/howto-conditional-access-policy-all-users-mfa.md#subscription-activation

2022-12-15 22:57 UTC, ngangulyms approved these changes

2022-12-16 15:06 UTC, merged