Update servicing-stack-updates.md
MicrosoftDocs/windows-itpro-docs pull request #10990
Opened 2022-11-08 14:57 UTC by msbemba

Added a related article - Windows server OS SSU catalog

per issue#https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10905

2022-11-08 14:57 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-11-08 15:05 UTC, opbld32 commented
Learn Build status updates of commit _[a8f9f99](https://github.com/msbemba/windows-itpro-docs/commits/a8f9f997dd095e1a436188f23f824ef5230ab896)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/deployment/update/servicing-stack-updates.md](https://github.com/msbemba/windows-itpro-docs/blob/patch-8/windows/deployment/update/servicing-stack-updates.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211081457102331-10990/BuildReport?accessString=801597cb128d52d0513c59fa555956b946a4992c87e4ffc40d5cf1535e19711d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-08 15:55 UTC, JohanFreelancer9 commented on windows/deployment/update/servicing-stack-updates.md
> +[Microsoft Servicing Stack Updates catalog for windows server operating system](https://www.catalog.update.microsoft.com/Search.aspx?q=Servicing%20Stack%20Update)
```suggestion
[Microsoft Servicing Stack Updates Catalog for Windows Server](https://www.catalog.update.microsoft.com/Search.aspx?q=Servicing%20Stack%20Update)
```

2022-11-08 15:55 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-08 16:24 UTC, JohanFreelancer9 approved these changes

2022-11-09 09:45 UTC, yogkumgit commented
@aczechowski Please merge this PR. Thanks

2022-11-17 16:54 UTC, aczechowski requested changes
Thanks @msbemba for the edit... 
🤔 That link might be useful, but it does return almost 800 results. I suppose there's no harm in keeping it.
But I think the simpler way to address the issue is to just add "Windows Server" to the bullets under "Applies to" at the top of the article. (FYI, we are working on a standard way to note the applicability of an article, so that might change in the future, but for now that will suffice.)

2022-12-07 14:56 UTC, msbemba commented
> Thanks @msbemba for the edit... 🤔 That link might be useful, but it does return almost 800 results. I suppose there's no harm in keeping it. But I think the simpler way to address the issue is to just add "Windows Server" to the bullets under "Applies to" at the top of the article. (FYI, we are working on a standard way to note the applicability of an article, so that might change in the future, but for now that will suffice.)

@aczechowski That's a good idea. I have made the changes as per your recommendation.

Thanks
Sri

2022-12-07 15:01 UTC, opbld32 commented
Learn Build status updates of commit _[5500255](https://github.com/msbemba/windows-itpro-docs/commits/5500255fa6a39c9a75df72295137aac826ff3230)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/deployment/update/servicing-stack-updates.md](https://github.com/msbemba/windows-itpro-docs/blob/patch-8/windows/deployment/update/servicing-stack-updates.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202212071455238775-10990/BuildReport?accessString=a4c448d3db765991153400a4045e3f8208309149175e353eabcb317930841d87).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-23 02:23 UTC, aczechowski approved these changes

2022-12-23 02:23 UTC, merged