Update microsoft-network-server-amount-of-idle-time-required-before-s…
MicrosoftDocs/windows-itpro-docs pull request #10993
Opened 2022-11-08 17:04 UTC by msbemba

…uspending-session.md

Added more information on what 99999 Minutes represent as it is 8 business hours per day *208 days

Per issue#https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10974

2022-11-08 17:04 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-11-09 05:04 UTC, JohanFreelancer9 commented on windows/security/threat-protection/security-policy-settings/microsoft-network-server-amount-of-idle-time-required-before-suspending-session.md
> +    For this policy setting, a value of 0 means to disconnect an idle session as quickly as is reasonably possible. The maximum value is 99999(8 business hours per day), which is 208 days . In effect
```suggestion
    For this policy setting, a value of 0 means to disconnect an idle session as quickly as is reasonably possible. The maximum value is 99999 (8 business hours per day), which is 208 days. In effect, this value disables the policy.
```

2022-11-09 05:04 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-09 05:55 UTC, opbld32 commented
Learn Build status updates of commit _[d8d0237](https://github.com/msbemba/windows-itpro-docs/commits/d8d02378e830ff741d8f8f52cfe513597e32a615)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/security/threat-protection/security-policy-settings/microsoft-network-server-amount-of-idle-time-required-before-suspending-session.md](https://github.com/msbemba/windows-itpro-docs/blob/patch-11/windows/security/threat-protection/security-policy-settings/microsoft-network-server-amount-of-idle-time-required-before-suspending-session.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211090549271183-10993/BuildReport?accessString=68d8cedaa973679b88dc150d4de8f8288a61345408f5a39c444790e6369fe8a0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 07:34 UTC, JohanFreelancer9 approved these changes

2022-11-09 10:09 UTC, yogkumgit commented
@vinaypamnani-msft Please merge this PR. Thanks

2022-11-21 18:40 UTC, merged