Update DORestrictPeerSelectionBy
MicrosoftDocs/windows-itpro-docs pull request #11003
Opened 2022-11-10 17:23 UTC by GrischaE1

We need to update the Policy to reflect the new options – 0 for NAT and 2 for Local Peer Discovery. See the DO reference article:
https://learn.microsoft.com/en-us/windows/deployment/do/waas-delivery-optimization-reference#select-a-method-to-restrict-peer-selection

## Why

- Closes #[Issue Number]

## Changes

2022-11-10 17:29 UTC, opbld31 commented
Learn Build status updates of commit _[0623d4a](https://github.com/GrischaE1/windows-itpro-docs/commits/0623d4a1db0e336a46d99a58f9eb8182eb2e04be)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/client-management/mdm/policy-csp-deliveryoptimization.md](https://github.com/GrischaE1/windows-itpro-docs/blob/patch-2/windows/client-management/mdm/policy-csp-deliveryoptimization.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211101723561832-11003/BuildReport?accessString=5dbff6e62394ea91fe8bed2019c4593edb9dc116a62ae4bec48269c3ab87a5e3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-10 19:50 UTC, cmknox commented
#SignOff

2022-11-11 09:57 UTC, JohanFreelancer9 commented on windows/client-management/mdm/policy-csp-deliveryoptimization.md
> +In Windows 11 the 'Local Peer Discovery' option was introduced to restrict peer discovery to the local network. Currently the available options include: 0 = NAT, 1 = Subnet mask, and 2 = Local Peer D
```suggestion
In Windows 11 the 'Local Peer Discovery' option was introduced to restrict peer discovery to the local network. Currently, the available options include: 0 = NAT, 1 = Subnet mask, and 2 = Local Peer Discovery. These options apply to both Download Modes LAN (1) and Group (2) and therefore it means that there is no peering between subnets. The default value in Windows 11 is set to "Local Peer Discovery".
```

2022-11-11 09:58 UTC, JohanFreelancer9 requested changes
Copy review - @GrischaE1, kindly commit the minor suggested changes. Many thanks.

2022-11-11 16:26 UTC, opbld32 commented
Learn Build status updates of commit _[b3cfed5](https://github.com/GrischaE1/windows-itpro-docs/commits/b3cfed50e4e3a17719b4a15e34438246414f3d74)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/client-management/mdm/policy-csp-deliveryoptimization.md](https://github.com/GrischaE1/windows-itpro-docs/blob/patch-2/windows/client-management/mdm/policy-csp-deliveryoptimization.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211111620380913-11003/BuildReport?accessString=11885b8ad61388a166e2ac3c6af4ef3cddc47826444155c7a5756789f1b60700).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-12 06:23 UTC, JohanFreelancer9 approved these changes

2022-11-21 19:31 UTC, merged