Update install-md-app-guard.md
MicrosoftDocs/windows-itpro-docs pull request #11017
Opened 2022-11-15 14:23 UTC by msbemba

Made changes to the navigation in the steps to install by using Intune

fixes #https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10770

2022-11-15 14:23 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-11-15 14:29 UTC, opbld30 commented
Learn Build status updates of commit _[c353652](https://github.com/msbemba/windows-itpro-docs/commits/c353652b97e343590665d0af65b811437858d39e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/security/threat-protection/microsoft-defender-application-guard/install-md-app-guard.md](https://github.com/msbemba/windows-itpro-docs/blob/patch-19/windows/security/threat-protection/microsoft-defender-application-guard/install-md-app-guard.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211151423373020-11017/BuildReport?accessString=2bca237a479dfbf4596bb54e0c505fea0577f3a3038e852e820152dee51407d2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-16 04:43 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-application-guard/install-md-app-guard.md
> +   1. In the **Profile** Type, Choose **Templates** and select **Endpoint protection** .
```suggestion
   1. In the **Profile** type, choose **Templates** and select **Endpoint protection**. 
```

2022-11-16 04:43 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-16 04:49 UTC, opbld30 commented
Learn Build status updates of commit _[13fdf16](https://github.com/msbemba/windows-itpro-docs/commits/13fdf16793f4547c1b74e968631d54f5b8ee952d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/security/threat-protection/microsoft-defender-application-guard/install-md-app-guard.md](https://github.com/msbemba/windows-itpro-docs/blob/patch-19/windows/security/threat-protection/microsoft-defender-application-guard/install-md-app-guard.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211160443516292-11017/BuildReport?accessString=ecfd789ba0ac6c93fe2e20f3e5644e020cce56b2ce7ac468606ac3d1a0fc37c3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-16 05:06 UTC, JohanFreelancer9 approved these changes

2022-11-17 15:13 UTC, yogkumgit commented
@denisebmsft Please merge this PR. Thanks

2022-11-30 20:53 UTC, opbld32 commented
Learn Build status updates of commit _[059c0d6](https://github.com/msbemba/windows-itpro-docs/commits/059c0d6e2c46512dd49e7973297c5db8515f8f3c)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/security/threat-protection/microsoft-defender-application-guard/install-md-app-guard.md](https://github.com/msbemba/windows-itpro-docs/blob/patch-19/windows/security/threat-protection/microsoft-defender-application-guard/install-md-app-guard.md) | :bulb:Suggestion | | [Details](#user-content-d6a214c9622096e9ded75e1ff7bd2ffe-1b9f31ce)

<a id="d6a214c9622096e9ded75e1ff7bd2ffe-1b9f31ce"></a>
### [windows/security/threat-protection/microsoft-defender-application-guard/install-md-app-guard.md](https://github.com/msbemba/windows-itpro-docs/blob/patch-19/windows/security/threat-protection/microsoft-defender-application-guard/install-md-app-guard.md)
 - **Line 2, Column 1**: **[Suggestion: ms-topic-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-topic-missing?branch=main)]** `````Missing required attribute: 'ms.topic'. Add a valid value to indicate the article type.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211302047453905-11017/BuildReport?accessString=011e71a969ad597ebc11aafe7ed75aa72adc338b95488070112df6dcd5cb33c0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-30 20:59 UTC, opbld32 commented
Learn Build status updates of commit _[d23d717](https://github.com/msbemba/windows-itpro-docs/commits/d23d717dcbfc8d789a8d20451afed341b2155046)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/security/threat-protection/microsoft-defender-application-guard/install-md-app-guard.md](https://github.com/msbemba/windows-itpro-docs/blob/patch-19/windows/security/threat-protection/microsoft-defender-application-guard/install-md-app-guard.md) | :bulb:Suggestion | | [Details](#user-content-d6a214c9622096e9ded75e1ff7bd2ffe-25cdfc5d)

<a id="d6a214c9622096e9ded75e1ff7bd2ffe-25cdfc5d"></a>
### [windows/security/threat-protection/microsoft-defender-application-guard/install-md-app-guard.md](https://github.com/msbemba/windows-itpro-docs/blob/patch-19/windows/security/threat-protection/microsoft-defender-application-guard/install-md-app-guard.md)
 - **Line 2, Column 1**: **[Suggestion: ms-topic-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-topic-missing?branch=main)]** `````Missing required attribute: 'ms.topic'. Add a valid value to indicate the article type.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211302050509334-11017/BuildReport?accessString=2f85a503a5fc1b9ec78ba4aaf8e7acf289002e8cf7fbe6ccda0ce30d5d033978).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-03 17:22 UTC, opbld30 commented
Learn Build status updates of commit _[7149698](https://github.com/msbemba/windows-itpro-docs/commits/71496988589b2ed0952461098b405db0ae8d381b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/security/threat-protection/microsoft-defender-application-guard/install-md-app-guard.md](https://github.com/msbemba/windows-itpro-docs/blob/patch-19/windows/security/threat-protection/microsoft-defender-application-guard/install-md-app-guard.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202301031716117173-11017/BuildReport?accessString=747513988f9b6c150e2aac14b2ff3b1d0adba3e2e5a5f6d1175480b072833ca5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-03 17:45 UTC, merged