added windows server 2022
MicrosoftDocs/windows-itpro-docs pull request #11044
Opened 2022-11-18 13:53 UTC by RAJU2529

as per user report #11029 so i added **Windows Server 2022** after verifying below  official article

**https://learn.microsoft.com/windows-server/get-started/whats-new-in-windows-server-2022**

2022-11-18 13:59 UTC, opbld32 commented
Learn Build status updates of commit _[b9a7912](https://github.com/RAJU2529/windows-itpro-docs/commits/b9a7912833a512f695f3fdb4edf1aa4995646b8a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/security/information-protection/tpm/trusted-platform-module-overview.md](https://github.com/RAJU2529/windows-itpro-docs/blob/patch-285/windows/security/information-protection/tpm/trusted-platform-module-overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211181353471273-11044/BuildReport?accessString=e703252c1096784037dad95e07c81775f13dbda5903ef72e1003905923899a2b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-21 03:24 UTC, JohanFreelancer9 commented on windows/security/information-protection/tpm/trusted-platform-module-overview.md
> +| TPM **2.0** |   **Yes**   |  **Yes**    |    **Yes**          |    **Yes**          |    **Yes**          |
```suggestion
| TPM 2.0 |   **Yes**   |  **Yes**    |    **Yes**          |    **Yes**          |    **Yes**          |
```

2022-11-21 03:24 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-21 03:49 UTC, opbld32 commented
Learn Build status updates of commit _[427ddae](https://github.com/RAJU2529/windows-itpro-docs/commits/427ddaea334fc09703f0faa657186fb88ea4795d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/security/information-protection/tpm/trusted-platform-module-overview.md](https://github.com/RAJU2529/windows-itpro-docs/blob/patch-285/windows/security/information-protection/tpm/trusted-platform-module-overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211210342028119-11044/BuildReport?accessString=830f8fd9fbb0559ee965c9b1e1c37bf554db94a43c84af2b63d1b4b65dfc2cc6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-21 04:19 UTC, JohanFreelancer9 approved these changes

2022-11-24 11:53 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2022-12-22 21:45 UTC, aczechowski approved these changes

2022-12-22 21:52 UTC, aczechowski commented
Thanks @RAJU2529 for the edit! I made a minor tweak to add back "yes" for Server 2019 and TPM 1.2, which was previously listed.

2022-12-22 21:58 UTC, opbld30 commented
Learn Build status updates of commit _[99992ca](https://github.com/RAJU2529/windows-itpro-docs/commits/99992caaa905bdcc3b4beffe02706a578601bd29)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/security/information-protection/tpm/trusted-platform-module-overview.md](https://github.com/RAJU2529/windows-itpro-docs/blob/patch-285/windows/security/information-protection/tpm/trusted-platform-module-overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202212222151396833-11044/BuildReport?accessString=00a68076a1710810387f9be71e6f1dd0daa7dba8f784abaccc00f60518f64294).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-22 21:59 UTC, merged