Clarification changing .cip to .bin
MicrosoftDocs/windows-itpro-docs pull request #11048
Opened 2022-11-22 07:14 UTC by Zephyrusg

## Why

Just a little clarification what to do with the .cip file. 
You first need to change it to .bin.
This is not stated on the page.

2022-11-22 07:21 UTC, opbld31 commented
Learn Build status updates of commit _[2b46bfd](https://github.com/Zephyrusg/windows-itpro-docs/commits/2b46bfd25189e965fc5e4019b8232acc107ba85a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/security/threat-protection/windows-defender-application-control/deployment/deploy-windows-defender-application-control-policies-using-intune.md](https://github.com/Zephyrusg/windows-itpro-docs/blob/patch-1/windows/security/threat-protection/windows-defender-application-control/deployment/deploy-windows-defender-application-control-policies-using-intune.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211220714377545-11048/BuildReport?accessString=a66d70a1756170f2fd1c29715e9d9c98cc7b66505525e7bab361a246116f0a06).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-23 04:32 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/deployment/deploy-windows-defender-application-control-policies-using-intune.md
> +    - **Certificate file**: upload your binary format policy file. Todo this change your {GUID}.cip file to {GUID}.bin. You don't need to upload a Base64 file, as Intune will convert the uploaded .bi
```suggestion
    - **Certificate file**: Upload your binary format policy file. To do this, change your {GUID}.cip file to {GUID}.bin. You don't need to upload a Base64 file, as Intune will convert the uploaded .bin file to Base64 on your behalf. 
```

2022-11-23 04:33 UTC, JohanFreelancer9 requested changes
Copy review - @Zephyrusg, kindly commit the suggested changes. Many thanks.

2022-11-23 07:58 UTC, Zephyrusg commented
@JohanFreelancer9  Done :).

2022-11-23 08:04 UTC, opbld30 commented
Learn Build status updates of commit _[a20e6c7](https://github.com/Zephyrusg/windows-itpro-docs/commits/a20e6c7196c6234a1286a0084dd061ca4527eabf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/security/threat-protection/windows-defender-application-control/deployment/deploy-windows-defender-application-control-policies-using-intune.md](https://github.com/Zephyrusg/windows-itpro-docs/blob/patch-1/windows/security/threat-protection/windows-defender-application-control/deployment/deploy-windows-defender-application-control-policies-using-intune.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211230758342281-11048/BuildReport?accessString=37d0e6995ba360b63d1c5287d16089223954d6c56df9c29e01704693614079ad).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-23 09:48 UTC, JohanFreelancer9 approved these changes

2022-11-23 18:52 UTC, jgeurten approved these changes

2022-11-30 17:31 UTC, merged