Update mcc-isp-faq.yml
MicrosoftDocs/windows-itpro-docs pull request #11067
Opened 2022-11-30 02:37 UTC by andyrivMSFT

Adding clarification around OS requirements.

## Description

Adding clarification around OS requirements.

## Why

Documentation needs to be clear for customers.

## Changes

Added Ubuntu OS version information

2022-11-30 02:43 UTC, opbld31 commented
Learn Build status updates of commit _[d4f3e92](https://github.com/andyrivMSFT/windows-itpro-docs/commits/d4f3e9203bcf4379c246a47098feddad23e0d29d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/deployment/do/mcc-isp-faq.yml](https://github.com/andyrivMSFT/windows-itpro-docs/blob/patch-3/windows/deployment/do/mcc-isp-faq.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202211300237444236-11067/BuildReport?accessString=a8adfa01ca343c3a9dd6842e21439b3f0f375a9a507f9a180c86606f2f6b4c6f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-30 05:06 UTC, JohanFreelancer9 commented on windows/deployment/do/mcc-isp-faq.yml
>           - Azure subscription
```suggestion
         - Azure subscription.
```

2022-11-30 05:06 UTC, JohanFreelancer9 commented on windows/deployment/do/mcc-isp-faq.yml
> +         - Hardware to host Microsoft Connected Cache
```suggestion
         - Hardware to host Microsoft Connected Cache.
```

2022-11-30 05:06 UTC, JohanFreelancer9 commented on windows/deployment/do/mcc-isp-faq.yml
> +         > The Microsoft Connected Cache is deployed and managed using Azure IoT Edge and Ubuntu 20.04 is an [Azure IoT Edge Tier 1 operating system](https://learn.microsoft.com/en-us/azure/iot-edge/
```suggestion
         > The Microsoft Connected Cache is deployed and managed using Azure IoT Edge and Ubuntu 20.04 is an [Azure IoT Edge Tier 1 operating system](https://learn.microsoft.com/azure/iot-edge/support?view=iotedge-2020-11#tier-1). Additionally, the Microsoft Connected Cache module is optimized for Ubuntu 20.04 LTS. 
```

2022-11-30 05:06 UTC, JohanFreelancer9 commented on windows/deployment/do/mcc-isp-faq.yml
> +         We have one customer who is able to achieve mid-30s Gbps egress rate using the following hardware specification:
```suggestion
         We have one customer who is able to achieve a mid-30s Gbps egress rate using the following hardware specification:  
```

2022-11-30 05:07 UTC, JohanFreelancer9 requested changes
Copy review - @andyrivMSFT, kindly commit the suggested changes. Many thanks.

2022-12-01 06:41 UTC, JohanFreelancer9 commented on windows/deployment/do/mcc-isp-faq.yml
> +         > The Microsoft Connected Cache is deployed and managed using Azure IoT Edge and Ubuntu 20.04 is an [Azure IoT Edge Tier 1 operating system](https://learn.microsoft.com/en-us/azure/iot-edge/
```suggestion
         > The Microsoft Connected Cache is deployed and managed using Azure IoT Edge and Ubuntu 20.04 is an [Azure IoT Edge Tier 1 operating system](/azure/iot-edge/support?view=iotedge-2020-11#tier-1). Additionally, the Microsoft Connected Cache module is optimized for Ubuntu 20.04 LTS. 
```

2022-12-01 06:42 UTC, JohanFreelancer9 requested changes
@andyrivMSFT, one more, please, to change the link to a relative link. Many thanks.

2022-12-22 22:01 UTC, aczechowski approved these changes

2022-12-22 22:06 UTC, opbld30 commented
Learn Build status updates of commit _[3e18ff6](https://github.com/andyrivMSFT/windows-itpro-docs/commits/3e18ff60e706f7fa98e6205a156a06f2b3ec60d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/deployment/do/mcc-isp-faq.yml](https://github.com/andyrivMSFT/windows-itpro-docs/blob/patch-3/windows/deployment/do/mcc-isp-faq.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202212222200469446-11067/BuildReport?accessString=f9bdf4122e1e353b2a7cbbb84f4b8aef88a569ac647c8acf9ba3a1f6d657c477).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-22 22:17 UTC, merged