Update bitlocker-management-for-enterprises.md
MicrosoftDocs/windows-itpro-docs pull request #11075
Opened 2022-12-02 23:09 UTC by rafals2

## Why

- Closes #[Issue Number]

## Changes

2022-12-02 23:15 UTC, opbld31 commented
Learn Build status updates of commit _[e149c62](https://github.com/rafals2/windows-itpro-docs/commits/e149c6257ea466a8fafc79a9015d90f1331ff88c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises.md](https://github.com/rafals2/windows-itpro-docs/blob/patch-13/windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202212022309470918-11075/BuildReport?accessString=503030a6530ee5a06a10535d1f553e95410d71dae39a82e7344048aa78cec715).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-05 03:48 UTC, JohanFreelancer9 commented on windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises.md
> +
```suggestion
> [!NOTE]
> To manage Bitlocker, except to enable and disable it, one of the following licenses must be assigned to your users:
> - Windows 10/11 Enterprise E3 or E5 (included in Microsoft 365 F3, E3, and E5).
> - Windows 10/11 Education A3 or A5 (included in Microsoft 365 A3 and A5).
```

2022-12-05 03:50 UTC, JohanFreelancer9 requested changes
Copy review - @rafals2, kindly commit the suggested changes. Many thanks.

2022-12-23 02:01 UTC, aczechowski approved these changes

2022-12-23 02:07 UTC, opbld31 commented
Learn Build status updates of commit _[dfa3662](https://github.com/rafals2/windows-itpro-docs/commits/dfa3662f265e9d40fc6df0c0b395e2d917d9f150)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises.md](https://github.com/rafals2/windows-itpro-docs/blob/patch-13/windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202212230200528325-11075/BuildReport?accessString=292152f179e78df741197cc4b16c234805bdbc3eb42be91b2b28938af46005e6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-23 02:13 UTC, merged