Explanation of convenience PIN
MicrosoftDocs/windows-itpro-docs pull request #11101
Opened 2022-12-20 19:06 UTC by rui0122

None of public documents defines what convenience PIN is.

## Why

- Closes #[Issue Number]

## Changes

2022-12-20 19:12 UTC, opbld31 commented
Learn Build status updates of commit _[5d957bf](https://github.com/rui0122/windows-itpro-docs/commits/5d957bf8fb2bc8548735b97cad39bc8f01483c14)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/security/identity-protection/hello-for-business/hello-faq.yml](https://github.com/rui0122/windows-itpro-docs/blob/patch-2/windows/security/identity-protection/hello-for-business/hello-faq.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202212201906025396-11101/BuildReport?accessString=dfde19483367d087074727f79f00f9c2cd491e6e0f59d2a61dfd4834d35faa29).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-21 08:44 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-faq.yml
> +          A Convenience Pin is used for sign-in (Windows Hello gesture only) which includes PIN, and Biometrics sign-in to the PC is not compatible with WHFB or with Hybrid AAD Join. Microsoft is com
```suggestion
          A convenience PIN is used for sign-in (Windows Hello gesture only) which includes a PIN, and biometrics sign-in to the device is not compatible with Windows Hellow for Business or with Hybrid Azure AD join. Microsoft is committed to its vision of a <u>world without passwords.</u> We recognize the *convenience* provided by convenience PIN, but it still uses a password for authentication. We recommend that customers using Windows 10 and convenience PINs move to Windows Hello for Business. New Windows 10 deployments should deploy Windows Hello for Business, not convenience PINs. Microsoft will be deprecating convenience PINs in the future and will publish the date early to ensure customers have adequate lead time to deploy Windows Hello for Business. 
```

2022-12-21 08:47 UTC, JohanFreelancer9 requested changes
Copy review - @rui0122, kindly commit the suggested changes. Many thanks.

2022-12-21 20:55 UTC, rui0122 reviewed
Submit

2022-12-21 20:59 UTC, opbld32 commented
Learn Build status updates of commit _[573cee1](https://github.com/rui0122/windows-itpro-docs/commits/573cee1dbfc3e613161f580bc3963a1730fe5c2f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/security/identity-protection/hello-for-business/hello-faq.yml](https://github.com/rui0122/windows-itpro-docs/blob/patch-2/windows/security/identity-protection/hello-for-business/hello-faq.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202212212053099199-11101/BuildReport?accessString=f90e3ccd837460e1f04a992b813a7f39acb5a5d02ba0d526d6b2f8b7cb8967d2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-22 05:08 UTC, JohanFreelancer9 approved these changes

2022-12-28 12:36 UTC, paolomatarazzo commented
@rui0122 thank you for the contribution. However, the suggested sentence doesn't provide an explanation of what *convenience PIN* is. To me, it actually adds more confusion. Can you please reword the sentence so that I can understand better what you're trying to communicate? "A convenience PIN is used for sign-in (Windows Hello gesture only) which includes a PIN, and biometrics sign-in to the device is not compatible with Windows Hellow for Business or with Hybrid Azure AD join."

2022-12-28 12:57 UTC, paolomatarazzo commented
I updated the description. Note that this Q/A refers about deprecation of convenience PIN, not about its description. (similar to the Q/A above). I'll close this PR and update the answer on a separate, existing PR.

2022-12-28 12:57 UTC, closed without merging