added windows 11
MicrosoftDocs/windows-itpro-docs pull request #11137
Opened 2022-12-23 12:50 UTC by RAJU2529

after reading this article, i confirmed windows 11 is supported

2022-12-26 09:40 UTC, JohanFreelancer9 commented on windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit.md
> +-
```suggestion
```

2022-12-26 09:40 UTC, JohanFreelancer9 requested changes
Copy review.

2022-12-28 07:00 UTC, JohanFreelancer9 commented
@msbemba

2022-12-28 07:14 UTC, opbld33 commented
Learn Build status updates of commit _[619d31d](https://github.com/RAJU2529/windows-itpro-docs/commits/619d31ded542c66472d88db1680703e1a28d68d8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit.md](https://github.com/RAJU2529/windows-itpro-docs/blob/patch-316/windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202212280709021915-11137/BuildReport?accessString=f98447732b9d57e27a68cf3be0df9504751213d316f69e00ee0f8252a1ca6282).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-28 08:58 UTC, JohanFreelancer9 approved these changes

2023-01-07 00:20 UTC, aczechowski approved these changes

2023-01-07 00:21 UTC, merged