added windows 11, adjusted format
MicrosoftDocs/windows-itpro-docs pull request #11163
Opened 2022-12-23 14:08 UTC by RAJU2529

after reading this article, i confirmed windows 11 is supported

2022-12-23 14:13 UTC, opbld33 commented
Learn Build status updates of commit _[7f70170](https://github.com/RAJU2529/windows-itpro-docs/commits/7f7017065a8e63fe772a089f64396750f2ea7c99)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/security/threat-protection/security-policy-settings/network-security-configure-encryption-types-allowed-for-kerberos.md](https://github.com/RAJU2529/windows-itpro-docs/blob/patch-344/windows/security/threat-protection/security-policy-settings/network-security-configure-encryption-types-allowed-for-kerberos.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202212231408030512-11163/BuildReport?accessString=ffca1b91e87c5e1166078c68743296ea92a2e1341702eeec2073fd1e8946f060).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-26 11:07 UTC, JohanFreelancer9 commented on windows/security/threat-protection/security-policy-settings/network-security-configure-encryption-types-allowed-for-kerberos.md
> +-   Windows Vista-
```suggestion
-   Windows Vista
```

2022-12-26 11:07 UTC, JohanFreelancer9 requested changes
Copy review.

2022-12-28 06:24 UTC, JohanFreelancer9 commented
@RAJU2529

2022-12-28 07:14 UTC, opbld33 commented
Learn Build status updates of commit _[8f7b8c1](https://github.com/RAJU2529/windows-itpro-docs/commits/8f7b8c1db654c6307f5f446a9431de775d265b72)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/security/threat-protection/security-policy-settings/network-security-configure-encryption-types-allowed-for-kerberos.md](https://github.com/RAJU2529/windows-itpro-docs/blob/patch-344/windows/security/threat-protection/security-policy-settings/network-security-configure-encryption-types-allowed-for-kerberos.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202212280708366905-11163/BuildReport?accessString=b7c2778a1b756197bd27e9b52c46eef98593e11b666b3ec247538eab45b21df5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-28 08:58 UTC, JohanFreelancer9 approved these changes

2023-01-13 21:49 UTC, aczechowski approved these changes

2023-01-13 21:57 UTC, merged