added windows 11 and arranaged in order
MicrosoftDocs/windows-itpro-docs pull request #11200
Opened 2022-12-27 14:31 UTC by RAJU2529

after reading this article, i confirmed windows 11 is supported

2022-12-27 14:37 UTC, opbld32 commented
Learn Build status updates of commit _[ed1c5e9](https://github.com/RAJU2529/windows-itpro-docs/commits/ed1c5e91bbaac397dc269da96bd75b451f35fee2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/security/threat-protection/security-policy-settings/access-this-computer-from-the-network.md](https://github.com/RAJU2529/windows-itpro-docs/blob/patch-379/windows/security/threat-protection/security-policy-settings/access-this-computer-from-the-network.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202212271431348679-11200/BuildReport?accessString=aaaf1be0b88243d53d80579f35e3b0a412ee0996ffbffbe890ca3861117f900a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-28 07:17 UTC, JohanFreelancer9 commented on windows/security/threat-protection/security-policy-settings/access-this-computer-from-the-network.md
> +-   Windows 10-
```suggestion
-   Windows 10
```

2022-12-28 07:17 UTC, JohanFreelancer9 requested changes
Copy review.

2022-12-28 07:24 UTC, opbld33 commented
Learn Build status updates of commit _[edc0d2d](https://github.com/RAJU2529/windows-itpro-docs/commits/edc0d2dbf9ba40049c418f48153faca9e28ca3fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows/security/threat-protection/security-policy-settings/access-this-computer-from-the-network.md](https://github.com/RAJU2529/windows-itpro-docs/blob/patch-379/windows/security/threat-protection/security-policy-settings/access-this-computer-from-the-network.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0b99eb70-7e0d-8338-27c0-5d77041105bb/202212280719223334-11200/BuildReport?accessString=04423ab9d8387d1eca958332899782b4cad210aef7990ff13571e638780fd767).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0b99eb70-7e0d-8338-27c0-5d77041105bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-28 08:57 UTC, JohanFreelancer9 approved these changes

2023-01-13 23:39 UTC, aczechowski approved these changes

2023-01-13 23:39 UTC, merged