Windows 11 ADK USMT
MicrosoftDocs/windows-itpro-docs pull request #11286
Opened 2023-01-23 20:20 UTC by robgrame

Just make some changes to the page but my main reason is asking whether to have a specular page covering Windows 11 USMT migration supported scenarios. Unfortunately I cannot find anything specific to Windows 11 even though I am pretty sure Windows 11 ADK USMT is supposed to cover migration scenarios from Windows 10. Thanks

/roberto

## Why

- Closes #[Issue Number]

## Changes

2023-01-24 04:53 UTC, JohanFreelancer9 commented on windows/deployment/usmt/usmt-requirements.md
> +- USMT for Windows 10/11 shouldn't be used for migrating between previous versions of Windows. USMT for Windows 10 is only meant to migrate to Windows 10 or between Windows 10 versions. For more info
```suggestion
- USMT for Windows 10 and Windows 11 shouldn't be used for migrating between previous versions of Windows. USMT for Windows 10 is only meant to migrate to Windows 10 or between Windows 10 versions. For more information about previous releases of the USMT tools, see [User State Migration Tool (USMT) overview](/previous-versions/windows/hh825227(v=win.10)).
```

2023-01-24 04:54 UTC, JohanFreelancer9 requested changes
Copy review - @robgrame, kindly commit the suggested change. Many thanks.

2023-01-30 23:31 UTC, frankroj commented
Need to confirm that USMT is supported to migrate from Windows 10 to Windows 11, and then reword article accordingly.

2023-01-30 23:32 UTC, frankroj commented
@robgrame in general all supported scenarios for Windows 10 USMT is also supported for Windows 11 USMT. Updating these articles are on our to do list but it may be some time before we get to it. The one scenario I need to confirm is migrating from Windows 10 to Windows 11, which I am pretty sure is supported.

2023-02-05 21:05 UTC, robgrame commented on windows/deployment/usmt/usmt-requirements.md
> +- USMT for Windows 10/11 shouldn't be used for migrating between previous versions of Windows. USMT for Windows 10 is only meant to migrate to Windows 10 or between Windows 10 versions. For more info
Hi @JohanFreelancer9 . 
From my point of view we are not clarifying yet the supportability to use USMT to migrate profiles from Windows 10 to Windows 11.
We should clearly state if Windows 11 ADK USMT is supposed (read supported) to migrate Windows 10 profiles to Windows 11 or it's not supported.
Thanks

2023-02-06 06:01 UTC, JohanFreelancer9 approved these changes

2023-03-20 17:33 UTC, frankroj commented
Confirming with PMs what exactly is supported with Windows 11.

2023-03-20 19:17 UTC, frankroj commented
Thank you @robgrame for the contribution. Although the contribution is good and valid, in the next month or two, I am going to be working on a greater project to update the USMT documentation with regards to Windows 11 support. I will make the changes as part of that project.

2023-03-20 19:17 UTC, closed without merging