Typo fixes, style fixes
MicrosoftDocs/windows-itpro-docs pull request #11304
Opened 2023-01-28 14:12 UTC by skycommand

- Fixed a paragraph that had mistakenly been merged into a warning box.
- Fixed a typo. "File system object" (FSO) and "Group Policy Object" (GPO) are both written without a hyphen.

2023-01-29 05:37 UTC, JohanFreelancer9 commented on windows/security/threat-protection/security-policy-settings/create-symbolic-links.md
>  >**Warning:**   This privilege should only be given to trusted users. Symbolic links can expose security vulnerabilities in applications that aren't designed to handle them.
```suggestion
> [!WARNING]
> This privilege should only be given to trusted users. Symbolic links can expose security vulnerabilities in applications that aren't designed to handle them.
```

2023-01-29 05:39 UTC, JohanFreelancer9 requested changes
Copy review - @skycommand, many thanks for your submission. Could you kindly also submit the additional suggested change to format the warning correctly? Thank you so much.

2023-01-29 11:51 UTC, skycommand commented
Done.

2023-01-30 04:57 UTC, JohanFreelancer9 approved these changes

2023-01-30 16:51 UTC, merged

2023-01-30 16:51 UTC, vinaypamnani-msft commented
Thanks for the contribution @skycommand