SHA256 PCR is a singled bank
MicrosoftDocs/windows-itpro-docs pull request #11330
Opened 2023-02-09 00:19 UTC by baloo

This fixes a confusion between platform configuration register and banks

2023-02-09 06:14 UTC, JohanFreelancer9 commented on windows/security/information-protection/tpm/switch-pcr-banks-on-tpm-2-0-devices.md
> +It is important to note that this binding to PCR values also includes the hashing algorithm used for the PCR. For instance, a key can be bound to a specific value of the SHA-1 PCR\[12\], if using SHA
```suggestion
It is important to note that this binding to PCR values also includes the hashing algorithm used for the PCR. For instance, a key can be bound to a specific value of the SHA-1 PCR\[12\], if using the SHA-256 PCR bank, even with the same system configuration. Otherwise, the PCR values will not match.
```

2023-02-09 06:15 UTC, JohanFreelancer9 requested changes
Copy review - @baloo, kindly commit the suggested change. Many thanks.

2023-02-10 02:43 UTC, aczechowski approved these changes
Thanks @baloo for the edit, and thank you for your first contribution to Windows docs! 🎉

2023-02-10 02:51 UTC, aczechowski commented
close/reopen to retry build

2023-02-10 06:24 UTC, JohanFreelancer9 approved these changes

2023-02-10 16:28 UTC, merged