Update hello-hybrid-cloud-kerberos-trust-provision.md
MicrosoftDocs/windows-itpro-docs pull request #11400
Opened 2023-03-13 18:20 UTC by bartbilliet

Added clarification concerning HAADJ vs AADJ with regards to cloud Kerberos trust.

## Why
Line-of-sight to domain controller requirement for Hybrid Azure AD joined devices was clearly described, however the difference with regards to Azure AD Join & line-of-sight to DC could be more clear. I wrote a proposal to make this difference more clearly articulated. Feel free to propose changes if my statement would be incorrect.

2023-03-14 05:48 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust-provision.md
> +> For hybrid Azure AD joined devices, users must perform the first sign in with new credentials while having line of sight to a DC. Without line of sight to a DC, even when the client is configured t
```suggestion
> For hybrid Azure AD joined devices, users must sign in the first time with new credentials while having a line of sight to a DC. Without line of sight to a DC, even when the client is configured to use cloud Kerberos trust, the system will fall back to key trust if signing in to cloud Kerberos trust fails.
```

2023-03-14 05:49 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust-provision.md
> +> For Azure AD joined devices, a line of sight to a DC is not required during the first sign in with new credentials, and is only required in order to access on-premises resources.
```suggestion
> For Azure AD joined devices, a line of sight to a DC is not required when first signing in with new credentials, and is only required in order to access on-premises resources. 
```

2023-03-14 05:51 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cloud-kerberos-trust-provision.md
> +> For Azure AD joined devices, a line of sight to a DC is not required during the first sign in with new credentials, and is only required in order to access on-premises resources.
```suggestion
> For hybrid Azure AD joined devices, users must sign in the first time with new credentials while having line of sight to a DC.
> 
> For Azure AD joined devices, a line of sight to a DC is not required when first signing in with new credentials, and is only required in order to access on-premises resources.  
```

2023-03-14 05:53 UTC, JohanFreelancer9 requested changes
Copy review - @bartbilliet, kindly commit the minor suggested changes. Many thanks.

2023-03-14 12:28 UTC, JohanFreelancer9 approved these changes

2023-03-14 17:30 UTC, paolomatarazzo commented
Hello @bartbilliet and thank you for the contribution. I feel that the proposed change adds confusion. You can't sign in to an Azure AD join devices using AD auth. The authentication can only be done by Azure AD (or a federated IdP). Therefore, adding the proposed statement is misleading.
The current statement is simple and technically correct, referencing only HAADJ devices.

2023-03-15 21:10 UTC, closed without merging

2023-03-15 21:12 UTC, bartbilliet commented
My mind went in this direction, since you can do SSO to on-prem resources from AADJ devices. That's why I started doubting if for AADJ devices you would need line-of-sight to an on-prem DC as well during WHfB enrollment.

2023-03-15 21:15 UTC, paolomatarazzo commented
I'll revise the document to improve clarity, thank you for the feedback!