Update manage-connections-from-windows-operating-system-components-to-microsoft-services.md
MicrosoftDocs/windows-itpro-docs pull request #11490
Opened 2023-04-29 09:01 UTC by starchturrets

## Why
Add instruction to disable Widgets using Group Policy, instead of only the registry.

- Closes #[Issue Number]

## Changes

2023-04-30 05:36 UTC, JohanFreelancer9 commented on windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md
> +You can turn off Widgets by:
```suggestion
To turn off Widgets:
```

2023-04-30 05:37 UTC, JohanFreelancer9 requested changes
Copy review - @starchturrets, kindly commit the minor suggested change. Many thanks.

2023-04-30 21:37 UTC, starchturrets commented
Sorry, this is the first time I've used git in a while to collaborate with others, how do I do that?

2023-05-01 04:25 UTC, JohanFreelancer9 commented
> Sorry, this is the first time I've used git in a while to collaborate with others, how do I do that?

You should see a button that says "Commit suggestion". Just select it and you are done.

2023-05-01 08:36 UTC, JohanFreelancer9 approved these changes

2023-05-02 16:03 UTC, DHB-MSFT commented
@JohanFreelancer9 Please don't review, edit, or approve any pull requests for content in the Windows "privacy" folder. We have a separate internal process for reviewing & approving updates to privacy content. Thank you.

2023-05-03 04:53 UTC, JohanFreelancer9 commented
> @JohanFreelancer9 Please don't review, edit, or approve any pull requests for content in the Windows "privacy" folder. We have a separate internal process for reviewing & approving updates to privacy content. Thank you.

@DHB-MSFT My apologies. Thank you for pointing it out to me. I will not do so in future.

2023-06-23 23:00 UTC, DHB-MSFT commented
@starchturrets Thanks for your suggestion to update/improve this content. We've published some changes to the article based on your suggestion.

2023-06-23 23:00 UTC, closed without merging