Update waas-restart.md
MicrosoftDocs/windows-itpro-docs pull request #11503
Opened 2023-05-10 16:05 UTC by msbemba

Added more registry details to the document

Fixes https://github.com/MicrosoftDocs/windows-itpro-docs/issues/11472

2023-05-10 16:05 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-05-11 05:39 UTC, JohanFreelancer9 commented on windows/deployment/update/waas-restart.md
> +| ScheduledInstallDay |  | 0: Every day</br>1 through 7: The days of the week from Sunday (1) to Saturday (7).
```suggestion
| ScheduledInstallDay |  | 0: every day</br>1 through 7: the days of the week from Sunday (1) to Saturday (7)
```

2023-05-11 05:39 UTC, JohanFreelancer9 requested changes
Copy review.

2023-05-11 08:40 UTC, JohanFreelancer9 approved these changes

2023-06-26 15:26 UTC, yogkumgit commented
@mestew Please merge this PR. Thanks

2023-07-22 05:44 UTC, yogkumgit commented
@mestew Gentle reminder. Thanks

2024-02-06 22:30 UTC, mestew commented
declining change since specific article is tightly scoped to restart settings and while an argument can be made for some of the suggested reg values, they are slightly outside the scope

2024-02-06 22:30 UTC, closed without merging