Update supported windows versions
MicrosoftDocs/windows-itpro-docs pull request #11584
Opened 2023-06-27 19:26 UTC by chiyao-ms

The old supported information is really confused for customer. Also, should we delete those un-supported windows version information?

## Why

- Closes #[Issue Number]

## Changes

2023-06-28 11:38 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md
> +> All Editions of Windows 11
```suggestion
> The Microsoft PIN Reset service works with the following versions of Windows:
>
> - Windows 10 Enterprise Edition, versions 1709 to 1809.
> - Windows 10 Enterprise Edition and Pro edition, version 1903 and later.
> - All Editions of Windows 11.
```

2023-06-28 11:39 UTC, JohanFreelancer9 requested changes
Copy review - @chiyao-ms, kindly commit the suggested changes. Many thanks.

2023-06-28 21:48 UTC, aczechowski commented
Assigning to Paolo for final review. I'd suggest just removing the specific versions, which are all now end of service. So it could just be all supported versions of Windows 10 and Windows 11.

Also I noticed the line about Azure Government was removed - purposeful or accidental?

2023-07-03 08:55 UTC, paolomatarazzo commented
Hello @chiyao-ms and thank you for the contribution. I updated the article as part of a different PR therefore I'm closing this one.

2023-07-03 08:55 UTC, closed without merging