Add a clarification about IP Address for Microsoft content
MicrosoftDocs/windows-itpro-docs pull request #11595
Opened 2023-07-04 01:32 UTC by narkissit

## Why

- Closes #[Issue Number]

## Changes

2023-07-05 03:17 UTC, JohanFreelancer9 commented on windows/deployment/do/waas-delivery-optimization-faq.yml
> +          The network of CDNs and MCCs allows Microsoft to reach the scale required to meet the demand of the Windows user base. Given this delivery infrastructure changes dynamically, providing an e
```suggestion
     - question: My firewall requires an IP Address and cannot process FQDNs, how do I configure it to download content with Delivery Optimization?
        answer: | 
          Microsoft content such as Windows Updates are hosted and delivered globally via Content Delivery Networks (CDNs) as well as Microsoft's Connected Cache (MCC) servers which are hosted within Internet Service Provider (ISP) networks. 
          The network of CDNs and MCCs allows Microsoft to reach the scale required to meet the demand of the Windows user base. Given this delivery infrastructure changes dynamically, providing an exhaustive list of IPs and keeping it up to date is not feasible. 
```

2023-07-05 03:19 UTC, JohanFreelancer9 commented on windows/deployment/do/waas-delivery-optimization-faq.yml
> +     - question: My firewall requires IP Address and cannot process FQDN's, how do I configure it to download content with Delivery Optimization?
```suggestion
     - question: My firewall requires an IP Address and cannot process FQDNs, how do I configure it to download content with Delivery Optimization?
```

2023-07-05 03:20 UTC, JohanFreelancer9 requested changes
Copy review - @narkissit, kindly commit the minor suggested changes. Many thanks.

2023-07-10 20:39 UTC, cmknox commented
@JohanFreelancer9 can you take a look again, I made the change you requested. Thanks!

2023-07-11 07:38 UTC, JohanFreelancer9 approved these changes

2023-07-11 23:31 UTC, mestew commented
I pulled Narkis's branch into the private to work on it. Closing this PR.

2023-07-11 23:31 UTC, closed without merging