Windows Drivers update setting to block drivers
MicrosoftDocs/windows-itpro-docs pull request #11599
Opened 2023-07-04 16:32 UTC by silvermarkg

In the 'Locations of policies that exclude drivers' list, the Windows Drivers update setting indicates being set to Allow blocks drivers. I believe this should be **Block** and not **Allow**.

2023-07-05 03:26 UTC, JohanFreelancer9 approved these changes

2024-01-29 14:50 UTC, Ahmedgama12345 requested changes
ارجو اغلاق جميع الاوامر والحزم وحزرهم من الوصول إلى حسابي من تاني

2024-02-06 22:22 UTC, merged

2024-02-06 22:22 UTC, mestew commented
verified update ring setting, merging this

2024-02-06 22:30 UTC, Lo236816 commented
Revert

On Tue, Feb 6, 2024 at 2:23 PM Meghan Stewart ***@***.***>
wrote:

> verified update ring setting, merging this
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MicrosoftDocs/windows-itpro-docs/pull/11599#issuecomment-1930866242>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BE6SG5GBNUHS45ZHLKIAHRTYSKUNDAVCNFSM6AAAAAAZ56KMAKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMZQHA3DMMRUGI>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>