Update how-it-works.md
MicrosoftDocs/windows-itpro-docs pull request #11607
Opened 2023-07-17 08:47 UTC by HerbertMauerer

Reflect Pasting is disabled for almost six years...customer who notice today were on WS16 so far.

## Why

- Closes CSS SR 2305240040009948

## Changes

2023-07-18 02:29 UTC, JohanFreelancer9 commented on windows/security/application-security/application-control/user-account-control/how-it-works.md
> +On the secure desktop it is not possible to paste a password you may have in the clipboard. This ability was removed in Windows 10 1709 and is present in all subsequent releases.
```suggestion
On the secure desktop, it is not possible to paste a password you may have in the clipboard. This ability was removed in Windows 10, version 1709, and is present in all subsequent releases.
```

2023-07-18 02:30 UTC, JohanFreelancer9 requested changes
Copy review - @HerbertMauerer, kindly commit the suggested change. Many thanks.

2023-07-18 05:54 UTC, HerbertMauerer commented
Johan writes:
kindly commit the suggested change. Many thanks.

I can close it, not commit. Not sure what to do.

2023-07-18 11:30 UTC, JohanFreelancer9 approved these changes
Thank you, @HerbertMauerer.

2023-07-24 07:49 UTC, paolomatarazzo requested changes

2023-07-24 07:49 UTC, paolomatarazzo commented on windows/security/application-security/application-control/user-account-control/how-it-works.md
> +
Hello, please consider update with the following.
```suggestion
> [!NOTE]
> It's not possible to paste the content of the clipboard on the secure desktop.
```

2023-07-24 08:18 UTC, paolomatarazzo commented on windows/security/application-security/application-control/user-account-control/how-it-works.md
> +
That's good! We don't want to reference unsupported OS like "Windows 10, version 1709".
I believe all currently supported client OS behave the same (?). If we limit the statement to Windows Server we're good.

2023-07-24 09:52 UTC, merged