Update feature-multifactor-unlock.md
MicrosoftDocs/windows-itpro-docs pull request #11706
Opened 2023-09-13 20:59 UTC by HEVARY

Added the client OS version in the missing section.

## Why

- Closes #[Issue Number]

## Changes

2023-09-14 03:14 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/feature-multifactor-unlock.md
> +> On Windows 10 and Windows 11, when the [DontDisplayLastUserName](/windows/security/threat-protection/security-policy-settings/interactive-logon-do-not-display-last-user-name) security policy is ena
```suggestion
> On Windows 10 and Windows 11, when the [DontDisplayLastUserName](/windows/security/threat-protection/security-policy-settings/interactive-logon-do-not-display-last-user-name) security policy is enabled, it is known to interfere with the ability to use multifactor unlock.
```

2023-09-14 03:15 UTC, JohanFreelancer9 requested changes
Copy review - @HEVARY, kindly also commit the minor additional change. Many thanks.

2023-09-17 12:46 UTC, paolomatarazzo requested changes
Thank you for the feedback, please review my comment with the changes.

2023-09-17 12:46 UTC, paolomatarazzo commented on windows/security/identity-protection/hello-for-business/feature-multifactor-unlock.md
> +> On Windows 10 and Windows 11, when the [DontDisplayLastUserName](/windows/security/threat-protection/security-policy-settings/interactive-logon-do-not-display-last-user-name) security policy is ena
The article applies to Win10/11 so we can remove the OS version here
```suggestion
> When the [DontDisplayLastUserName](/windows/security/threat-protection/security-policy-settings/interactive-logon-do-not-display-last-user-name) security policy is enabled, it is known to interfere with the ability to use multi factor unlock.
```

2023-09-25 21:38 UTC, merged