Update windows-11-plan.md
MicrosoftDocs/windows-itpro-docs pull request #11782
Opened 2023-10-28 06:51 UTC by RAJU2529

1. added Windows 11 update history page link  **https://support.microsoft.com/topic/windows-11-version-21h2-update-history-a19cd327-b57f-44b9-84e0-26ced7109ba9**

2. made few words to bold
2. Corrected grammatical errors.

article link
**https://learn.microsoft.com/en-us/windows/whats-new/windows-11-plan?toc=%2Fwindows%2Fdeployment%2Ftoc.json&bc=%2Fwindows%2Fdeployment%2Fbreadcrumb%2Ftoc.json**

2023-10-30 07:25 UTC, JohanFreelancer9 commented on windows/whats-new/windows-11-plan.md
> +When Windows 11 reaches general availability, a consolidated [Windows 11 update history](https://support.microsoft.com/en-us/topic/windows-11-version-21h2-update-history-a19cd327-b57f-44b9-84e0-26ced
```suggestion
When Windows 11 reaches general availability, a consolidated [Windows 11 update history](https://support.microsoft.com/topic/windows-11-version-21h2-update-history-a19cd327-b57f-44b9-84e0-26ced7109ba9) is available, similar to what is [available today for Windows 10](https://support.microsoft.com/topic/windows-10-update-history-1b6aac92-bf01-42b5-b158-f80c6d93eb11). Similarly, the [Windows release health](/windows/release-health/) hub will offer quick access to Windows 11 servicing announcements, known issues, and safeguard holds. 
```

2023-10-30 07:25 UTC, JohanFreelancer9 commented on windows/whats-new/windows-11-plan.md
> +- **Test Base for Microsoft 365**: [Test Base](https://portal.azure.com/?feature.Win11=true%2F#view/Microsoft_Azure_Marketplace/GalleryItemDetailsBladeNopdl/id/Microsoft.TestBase) is a cloud testing
```suggestion
- **Test Base for Microsoft 365**: [Test Base](https://portal.azure.com/?feature.Win11=true%2F#view/Microsoft_Azure_Marketplace/GalleryItemDetailsBladeNopdl/id/Microsoft.TestBase) is a cloud testing platform that can help you evaluate applications readiness for Windows 11 upgrade or migration. IT administrators, software publishers, and system integrators can find desired test cases throughout the entire Windows validation lifecycle. Tests include, but aren't limited to, in-place upgrade validation, monthly quality updates, and tests against Windows preview features.
```

2023-10-30 07:26 UTC, JohanFreelancer9 requested changes
Copy review.

2023-10-30 08:51 UTC, JohanFreelancer9 approved these changes

2024-02-06 22:36 UTC, mestew commented on windows/whats-new/windows-11-plan.md
> +When Windows 11 reaches general availability, a consolidated [Windows 11 update history](https://support.microsoft.com/topic/windows-11-version-21h2-update-history-a19cd327-b57f-44b9-84e0-26ced7109ba
```suggestion
When Windows 11 reaches general availability, a consolidated [Windows 11 update history](https://support.microsoft.com/topic/59875222-b990-4bd9-932f-91a5954de434) is available, similar to what is [available today for Windows 10](https://support.microsoft.com/topic/windows-10-update-history-1b6aac92-bf01-42b5-b158-f80c6d93eb11). Similarly, the [Windows release health](/windows/release-health/) hub will offer quick access to Windows 11 servicing announcements, known issues, and safeguard holds. 
```

2024-02-06 22:36 UTC, mestew commented on windows/whats-new/windows-11-plan.md
> +Microsoft is currently developing analysis tools to help you evaluate your devices against the Windows 11 hardware requirements. When Windows 11 reaches general availability, users running **Windows
```suggestion
Microsoft is currently developing analysis tools to help you evaluate your devices against the Windows 11 hardware requirements. When Windows 11 reaches general availability, users running Windows 10 Home, Pro, and Pro for Workstations will be able to use the [PC Health Check](https://www.microsoft.com/windows/windows-11#pchealthcheck) app to determine their eligibility for Windows 11. Users running Windows 10 Enterprise and Education editions should rely on their IT administrators to let them know when they're eligible for the upgrade.  
```

2024-02-06 22:38 UTC, mestew commented on windows/whats-new/windows-11-plan.md
> +**Enterprise organizations** looking to evaluate device readiness in their environments can expect this capability to be integrated into existing Microsoft tools, such as Endpoint analytics and Updat
```suggestion
Enterprise organizations looking to evaluate device readiness in their environments can expect this capability to be integrated into existing Microsoft tools, such as Endpoint analytics and Update Compliance. This capability will be available when Windows 11 is generally available. Microsoft is also working with software publishing partners to facilitate adding Windows 11 device support into their solutions. 
```

2024-02-06 22:38 UTC, mestew commented on windows/whats-new/windows-11-plan.md
> +The availability of **Windows 11** will vary according to a device's hardware and whether the device receives updates directly, or from a management solution that is maintained by an IT administrator
```suggestion
The availability of Windows 11 will vary according to a device's hardware and whether the device receives updates directly, or from a management solution that is maintained by an IT administrator. 
```

2024-02-06 22:54 UTC, merged

2024-02-06 22:55 UTC, mestew commented
Did some style and URL edits.