Update mcc-enterprise-appendix.md
MicrosoftDocs/windows-itpro-docs pull request #11804
Opened 2023-11-07 23:35 UTC by narkissit

clarification on installation on vmware

## Why

- Closes #[Issue Number]

## Changes

2023-11-08 08:57 UTC, JohanFreelancer9 commented on windows/deployment/do/mcc-enterprise-appendix.md
> +1. Microsoft Connected Cache for Enterprise and Education can be successfully installed on VMware. To do so, there are a couple of additional configurations to be made. Please ensure the VM is turned
```suggestion
1. Microsoft Connected Cache for Enterprise and Education can be successfully installed on VMware. To do so, there are a couple of additional configurations to be made. Ensure the VM is turned off before making the configuration changes:
```

2023-11-08 08:58 UTC, JohanFreelancer9 requested changes
Copy review - @narkissit, kindly commit the minor suggested change. For reference, we do not use the word "please" except in certain cases that do not apply here. Many thanks.

2023-11-09 05:29 UTC, JohanFreelancer9 approved these changes

2023-12-28 20:59 UTC, aczechowski approved these changes
Thanks @narkissit for the edit, and sorry for the delay!

2023-12-28 21:03 UTC, merged