Updating troubleshooting docs
MicrosoftDocs/windows-itpro-docs pull request #5892
Opened 2020-01-22 18:56 UTC by yannisle

## Hologram image color or brightness does not look right
## Holograms look unstable
### Lights to indicate problems

2020-01-22 18:59 UTC, yannisle commented
Edits to troubleshooting docs

2020-01-22 21:01 UTC, scooley commented on devices/hololens/hololens-troubleshooting.md
> +- **Run eye calibration:** The display uses your IPD and eye gaze to optimize images on the display. If you don't run eye calibration, the image quality may be made worse.
There are a number of environmental factors that may also change how your holograms look including light level.  Read more about environmental considerations [here](https://docs.microsoft.com/hololens/hololens-environment-considerations) if the steps above don't work.

`[here](hololens-environment-considerations.md)`

2020-01-22 21:04 UTC, scooley commented on devices/hololens/hololens-troubleshooting.md
> +
Here is the light guide for [HoloLens (1st gen)](https://docs.microsoft.com/hololens/hololens1-setup#hololens-indicator-lights) and [HoloLens 2](https://docs.microsoft.com/hololens/hololens2-setup#hololens-behavior-reference).

`[HoloLens (1st gen)](hololens1-setup.md#hololens-indicator-lights)`
`[HoloLens 2](hololens2-setup.md#hololens-behavior-reference)`

2020-02-15 18:53 UTC, e0i commented
@yannisle Please let us know when you are able to follow up with revision suggestions.Thanks.

2020-02-17 05:30 UTC, yannisle commented
Reviewed revisions.

2020-02-17 21:12 UTC, illfated commented on devices/hololens/hololens-troubleshooting.md
> +- **Run eye calibration:** The display uses your IPD and eye gaze to optimize images on the display. If you don't run eye calibration, the image quality may be made worse.
This link has not been added. Sorry, I forgot to check the previous reviews.

2020-02-17 21:15 UTC, illfated commented
> Reviewed revisions.

Maybe you would like specific suggestions within the source text, to be merged by using the button **[Commit suggestion]** ?

2020-10-21 17:14 UTC, e0i commented
@yannisle Good to go once the merge conflicts have been resolved. Thank you.

2021-02-10 07:42 UTC, JohanFreelancer9 commented on devices/hololens/hololens-troubleshooting.md
> +| You press the Power button. | The 1st, 3rd, and 5th lights flash together continually. |  HoloLens may have a hardware failure. To be sure, [reinstall the OS](hololens-recovery.md#hololens-2), and
```suggestion
| You press the Power button. | The first, third, and fifth lights flash together continually. |  HoloLens may have a hardware failure. To be sure, [reinstall the OS](hololens-recovery.md#hololens-2), and try again. After reinstalling the OS, if the light-flash pattern persists, contact [support](https://support.microsoft.com/supportforbusiness/productselection?sapid=3ec35c62-022f-466b-3a1e-dbbb7b9a55fb). |
```

2021-02-10 07:43 UTC, JohanFreelancer9 commented on devices/hololens/hololens-troubleshooting.md
> +| You press the Power button. | The 1st, 3rd, and 5th lights flash together continually. |  HoloLens may have a hardware failure. To be sure, [reinstall the OS](hololens-recovery.md#hololens-2), and
```suggestion
| You press the Power button. | The first, third, and fifth lights flash together continually. |  HoloLens may have a hardware failure. To be sure, [reinstall the OS](hololens-recovery.md#hololens-2), and try again. After reinstalling the OS, if the light-flash pattern persists, contact [support](https://support.microsoft.com/supportforbusiness/productselection?sapid=3ec35c62-022f-466b-3a1e-dbbb7b9a55fb). |
```

2021-02-10 07:45 UTC, JohanFreelancer9 requested changes
Copy review - minor edits to align with Microsoft Style Guide.

2021-03-11 15:05 UTC, e0i commented
@yannisle Please feel free to re-open this PR by resolving the merge conflicts and applying the copy editing suggestions. The content is ready to merge once that’s been done. Thank you for the feedback and for your patience with the process.

2021-03-11 15:05 UTC, closed without merging