added licensing requirements
MicrosoftDocs/windows-itpro-docs pull request #8135
Opened 2020-08-25 11:57 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8061

2020-08-25 11:57 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

2020-08-25 14:50 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-mac.md
> +> Eligible Licensed Users may use Microsoft Defender Advanced Threat Protection on up to five concurrent devices.
```suggestion
> Eligible licensed users may use Microsoft Defender Advanced Threat Protection on up to five concurrent devices.
```

2020-08-25 14:52 UTC, JohanFreelancer9 requested changes
Copy review.

2020-08-26 07:48 UTC, JohanFreelancer9 approved these changes

2020-10-06 19:27 UTC, merged