updated the steps for WHfB
MicrosoftDocs/windows-itpro-docs pull request #8180
Opened 2020-08-29 13:18 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8098

2020-08-29 13:26 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

2020-08-29 15:07 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md
>  4. Click **Windows enrollment**
```suggestion
4. Click **Windows enrollment**.
```

2020-08-29 15:11 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md
> +7. Select **Required** next to **Use a Trusted Platform Module (TPM)**.  By default, Windows Hello for Business prefers TPM 2.0 or falls backs to software. Choosing **Required** forces Windows Hello
```suggestion
7. Select **Required** next to **Use a Trusted Platform Module (TPM)**.  By default, Windows Hello for Business prefers TPM 2.0 or falls backs to software. Choosing **Required** forces Windows Hello for Business to only use TPM 2.0 or TPM 1.2 and does not allow fall back to software-based keys.
```

2020-08-29 15:12 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md
> +8. Type the desired **Minimum PIN length** and **Maximum PIN length**.
```suggestion
8. Enter the desired **Minimum PIN length** and **Maximum PIN length**.
```

2020-08-29 15:13 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md
> +9. Select the appropriate configuration for the following settings.
```suggestion
9. Select the appropriate configuration for the following settings:
```

2020-08-29 15:17 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md
> +11. Select **No** to **Allow phone sign-in**.  This feature has been deprecated.
```suggestion
11. Select **No** to **Allow phone sign-in**. This feature has been deprecated.
```

2020-08-29 15:17 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md
> +12. Click **Save**
```suggestion
12. Choose **Save**
```

2020-08-29 15:18 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md
> +13. Sign-out of the Microsoft Endpoint Manager admin center.
```suggestion
13. Sign out of the Microsoft Endpoint Manager admin center.
```

2020-08-29 15:20 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md
> +1. Sign-in to the [Microsoft Endpoint Manager admin center](https://endpoint.microsoft.com/).
```suggestion
1. Sign in to the [Microsoft Endpoint Manager admin center](https://endpoint.microsoft.com/).
```

2020-08-29 15:22 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md
> +3. Click **Enroll devices**.
```suggestion
3. Choose **Enroll devices**.
```

2020-08-29 15:22 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md
>  4. Click **Windows enrollment**
```suggestion
4. Select **Windows enrollment**
```

2020-08-29 15:23 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md
>  5. Under **Windows enrollment**, click **Windows Hello for Business**.
```suggestion
5. Under **Windows enrollment**, select **Windows Hello for Business**.
```

2020-08-29 15:27 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md
>      > The default minimum PIN length for Windows Hello for Business on Windows 10 is 6.  Microsoft Intune defaults the minimum PIN length to 4, which reduces the security of the user's PIN.  If you d
```suggestion
    > The default minimum PIN length for Windows Hello for Business on Windows 10 is six.  Microsoft Intune defaults the minimum PIN length to four, which reduces the security of the user's PIN.  If you do not have a desired PIN length, set the minimum PIN length to six.
```

2020-08-29 15:29 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md
> +10. Select **Yes** next to **Allow biometric authentication** if you want to allow users to use biometrics (fingerprint and/or facial recognition) to unlock the device.  To further secure the use of
```suggestion
10. Select **Yes** next to **Allow biometric authentication** if you want to allow users to use biometrics (fingerprint and/or facial recognition) to unlock the device. To further secure the use of biometrics, select **Yes** to **Use enhanced anti-spoofing, when available**.
```

2020-08-29 15:33 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md
>      > [!NOTE]
```suggestion
    
    > [!NOTE]
```

2020-08-29 15:34 UTC, JohanFreelancer9 requested changes
Copy review.

2020-08-30 14:05 UTC, JohanFreelancer9 approved these changes

2020-09-09 17:40 UTC, merged