removed requirements for enterprise edition
MicrosoftDocs/windows-itpro-docs pull request #8181
Opened 2020-08-30 06:34 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8046
Source: 
1. https://www.microsoft.com/en-gb/windowsforbusiness/compare
2. https://github.com/MicrosoftDocs/windows-itpro-docs/commit/644513525d12ea24a9a71ffee1a54b7ecfed1228

2020-08-30 06:35 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

2020-08-30 14:35 UTC, JohanFreelancer9 commented on windows/security/identity-protection/credential-guard/credential-guard-requirements.md
> +| Software: Qualified **Windows operating system**  | **Requirement**: Windows 10 or Windows Server 2016<br><blockquote><p><b>Important:</b><br> Windows Server 2016 running as a domain controller doe
```suggestion
| Software: Qualified **Windows operating system**  | **Requirement**: Windows 10 or Windows Server 2016.<br><blockquote><p><b>Important:</b><br> Windows Server 2016 running as a domain controller does not support Windows Defender Credential Guard. </p></blockquote> |Support for VBS and for management features that simplify configuration of Windows Defender Credential Guard. |
```

2020-08-30 14:35 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-08-31 14:41 UTC, JohanFreelancer9 approved these changes

2020-09-16 16:28 UTC, DulceMontemayor approved these changes

2020-09-16 16:28 UTC, merged