Update connect-to-remote-aadj-pc.md
MicrosoftDocs/windows-itpro-docs pull request #8253
Opened 2020-09-09 17:02 UTC by RavennMSFT

added note about RDP from AAD registered device that was enabled in 2004 version

2020-09-21 22:27 UTC, RavennMSFT commented
@Dansimp Need this approved, been pending for a while now

2020-09-21 22:27 UTC, RavennMSFT commented
#sign-off

2020-09-23 13:37 UTC, e0i commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-23 13:48 UTC, JohanFreelancer9 commented on windows/client-management/connect-to-remote-aadj-pc.md
> +- Your local PC (where you are connecting from) must be either Azure AD joine or Hybrid Azure AD joined, if using WIndows 10 versio 1607 and above or Azure AD registered, if using Windows 10 version
```suggestion
- Your local PC (where you are connecting from) must be either Azure AD joined or Hybrid Azure AD joined if using Windows 10 version 1607 and above, or Azure AD registered if using Windows 10 version 2004 and above. Remote connections to an Azure AD joined PC from an unjoined device or a non-Windows 10 device are not supported. 
```

2020-09-23 13:48 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-23 16:09 UTC, RavennMSFT commented
@JohanFreelancer9 done

2020-09-24 03:37 UTC, JohanFreelancer9 approved these changes

2020-09-24 15:27 UTC, merged