removed Intune
MicrosoftDocs/windows-itpro-docs pull request #8313
Opened 2020-09-19 14:57 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8107

2020-09-19 14:58 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

2020-09-20 05:22 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-antivirus/review-scan-results-microsoft-defender-antivirus.md
>  After an Microsoft Defender Antivirus scan completes, whether it is an [on-demand](run-scan-microsoft-defender-antivirus.md) or [scheduled scan](scheduled-catch-up-scans-microsoft-defender-antivirus.
```suggestion
After a Microsoft Defender Antivirus scan completes, whether it is an [on-demand](run-scan-microsoft-defender-antivirus.md) or [scheduled scan](scheduled-catch-up-scans-microsoft-defender-antivirus.md), the results are recorded and you can view the results. 
```

2020-09-20 05:23 UTC, JohanFreelancer9 requested changes
Copy review - one minor additional edit, please.

2020-09-28 17:40 UTC, denisebmsft approved these changes
Thank you @MaratMussabekov and @JohanFreelancer9

2020-09-28 17:40 UTC, merged