Minor Changes
MicrosoftDocs/windows-itpro-docs pull request #8314
Opened 2020-09-19 17:03 UTC by joinimran

As suggested by the user, I made a few changes to reflect the document more clear and easy to understand. 

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/7965

2020-09-19 17:03 UTC, joinimran commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-09-20 05:21 UTC, JohanFreelancer9 commented on windows/client-management/connect-to-remote-aadj-pc.md
> +From its release, Windows 10 has supported remote connections to PCs joined to Active Directory. Starting in Windows 10, version 1607, you can also connect to a remote PC that is [joined to Azure Act
```suggestion
From its release, Windows 10 has supported remote connections to PCs joined to Active Directory. Starting in Windows 10, version 1607, you can also connect to a remote PC that is [joined to Azure Active Directory (Azure AD)](https://docs.microsoft.com/azure/active-directory/user-help/device-management-azuread-joined-devices-setup). Starting in Windows 10, version 1809, you can [use biometrics to authenticate to a remote desktop session](https://docs.microsoft.com/windows/whats-new/whats-new-windows-10-version-1809#remote-desktop-with-biometrics).
```

2020-09-20 05:21 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-09-20 09:06 UTC, joinimran commented
Thanks @JohanFreelancer9 - Ready to go live @e0i

2020-09-20 12:35 UTC, Yoshio123 approved these changes

2020-09-20 13:21 UTC, JohanFreelancer9 approved these changes

2020-10-14 19:38 UTC, merged