Update activate-using-key-management-service-vamt.md
MicrosoftDocs/windows-itpro-docs pull request #8335
Opened 2020-09-23 18:04 UTC by baardhermansen

Added retail link for activating Windows 10.
Added markdown for Notes.
Corrected a nested list error, which incorrectly indented a numbered list item. 
Modified spacing inside numbered list so that text is rendered as author seemed to intend.

2020-09-29 18:22 UTC, e0i commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-30 01:25 UTC, JohanFreelancer9 commented on windows/deployment/volume-activation/activate-using-key-management-service-vamt.md
>  - To activate by telephone , follow these steps:
```suggestion
- To activate by telephone, follow these steps:
```

2020-09-30 01:39 UTC, JohanFreelancer9 commented on windows/deployment/volume-activation/activate-using-key-management-service-vamt.md
> +To enable KMS functionality, a KMS key is installed on a KMS host; then, the host is activated over the Internet or by phone using Microsoft's activation services.
```suggestion
To enable KMS functionality, a KMS key is installed on a KMS host; then, the host is activated over the Internet or by phone using Microsoft activation services.
```

2020-09-30 01:39 UTC, JohanFreelancer9 requested changes
Copy review - two more minor edits.

2020-09-30 18:16 UTC, baardhermansen commented on windows/deployment/volume-activation/activate-using-key-management-service-vamt.md
> +To enable KMS functionality, a KMS key is installed on a KMS host; then, the host is activated over the Internet or by phone using Microsoft's activation services.
Hm, not sure i agree with the suggestion: To me, "Microsoft activation services" seems to indicate a product name, whereas "Microsoft's activation services" indicates the activation services that Microsoft has to offer. 
Not sure i managed to explain the difference properly though...

2020-10-01 03:44 UTC, JohanFreelancer9 commented on windows/deployment/volume-activation/activate-using-key-management-service-vamt.md
> +To enable KMS functionality, a KMS key is installed on a KMS host; then, the host is activated over the Internet or by phone using Microsoft's activation services.
@baardhermansen - I take your point, and in fact on the face of it, I tend to agree with you. However, the Microsoft Style Guide prohibits the use of the term "Microsoft's". And if it was a product name, it would have been capitalized as "Microsoft Activation Services". I hope that explains it, but thank you so much for your comment.

2020-10-01 11:17 UTC, baardhermansen commented on windows/deployment/volume-activation/activate-using-key-management-service-vamt.md
> +To enable KMS functionality, a KMS key is installed on a KMS host; then, the host is activated over the Internet or by phone using Microsoft's activation services.
Note to self: Found the reference at https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/m/microsoft.

2020-10-01 13:46 UTC, JohanFreelancer9 approved these changes

2020-10-01 23:34 UTC, merged