Update Feature Updates release time
MicrosoftDocs/windows-itpro-docs pull request #8350
Opened 2020-09-25 04:44 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8320

2020-09-25 04:44 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

2020-09-25 05:19 UTC, JohanFreelancer9 commented on windows/deployment/update/get-started-updates-channels-tools.md
> +- **Feature updates:** Released twice per year, first half and second half of each calendar year. Feature updates add new features and functionality to Windows 10. Because they are delivered frequent
```suggestion
- **Feature updates:** Released twice per year, during the first half and second half of each calendar year. Feature updates add new features and functionality to Windows 10. Because they are delivered frequently (rather than every 3-5 years), they are easier to manage.
```

2020-09-25 05:26 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-27 02:36 UTC, JohanFreelancer9 approved these changes

2020-09-29 17:33 UTC, jaimeo commented
@arcarley are you OK with this edit?

2020-09-29 17:34 UTC, arcarley commented
@jaimeo yep, looks good!

2020-09-29 17:44 UTC, merged