update apps for 2004
MicrosoftDocs/windows-itpro-docs pull request #8352
Opened 2020-09-25 07:27 UTC by VLG17

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8017

2020-09-29 17:20 UTC, e0i commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-30 02:55 UTC, JohanFreelancer9 commented on windows/application-management/apps-in-windows-10.md
> +Here are the provisioned Windows apps in Windows 10 versions 1803, 1809, 1903, 1909 and 2004.
```suggestion
Here are the provisioned Windows apps in Windows 10 versions 1803, 1809, 1903, 1909, and 2004.
```

2020-09-30 03:00 UTC, JohanFreelancer9 requested changes
Copy review - Please note: The table does not render correctly. Also, there is one minor edit.

2020-09-30 07:12 UTC, VLG17 commented
> Copy review - Please note: The table does not render correctly. Also, there is one minor edit.

@JohanFreelancer9 Could you please let me know what i need to change to have it render correctly?

2020-10-01 04:07 UTC, JohanFreelancer9 commented on windows/application-management/apps-in-windows-10.md
>  |----------------------------------------------|--------------------------------------------------------------------------------------------------------------------|:----:|:----:|:----:|:----:|:-----
```suggestion
|----------------------------------------------|--------------------------------------------------------------------------------------------------------------------|:----:|:----:|:----:|:----:|:----:|:---------------------:|
```

2020-10-01 04:10 UTC, JohanFreelancer9 commented on windows/application-management/apps-in-windows-10.md
>  |----------------------------------------------|--------------------------------------------------------------------------------------------------------------------|:----:|:----:|:----:|:----:|:-----
@VLG17  - Unfortunately I cannot check if it works, but I think this should do it.

2020-10-01 04:12 UTC, JohanFreelancer9 commented on windows/application-management/apps-in-windows-10.md
>  |----------------------------------------------|--------------------------------------------------------------------------------------------------------------------|:----:|:----:|:----:|:----:|:-----
```suggestion
|----------------------------------------------|--------------------------------------------------------------------------------------------------------------------|:----:|:----:|:----:|:----:|:----:|:---------------------:|
```

2020-10-01 04:16 UTC, JohanFreelancer9 requested changes
@VLG17 - Unfortunately I cannot check if it works, but I think this should do it.

2020-10-01 08:41 UTC, JohanFreelancer9 approved these changes

2020-10-14 16:45 UTC, merged