clarified the possibility to change the configuration
MicrosoftDocs/windows-itpro-docs pull request #8360
Opened 2020-09-26 18:41 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6962

2020-09-26 18:42 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

2020-09-27 02:30 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/mac-preferences.md
> +In enterprise organizations, Microsoft Defender ATP for Mac can be managed through a configuration profile that is deployed by using one of several management tools. Preferences that are managed by y
```suggestion
In enterprise organizations, Microsoft Defender ATP for Mac can be managed through a configuration profile that is deployed by using one of several management tools. Preferences that are managed by your security operations team take precedence over preferences that are set locally on the device. Changing the preferences that are set through the configuration profile requires escalated privileges and is not available for users without administrative permissions.
```

2020-09-27 02:32 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-28 14:13 UTC, JohanFreelancer9 approved these changes

2020-09-29 12:00 UTC, nam31 commented
Hi @Dansimp PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-29 23:04 UTC, merged