Link Update
MicrosoftDocs/windows-itpro-docs pull request #8386
Opened 2020-09-30 17:16 UTC by joinimran

Updated a link to the correct source.

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/7972

2020-09-30 17:16 UTC, joinimran commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

@e0i - FYI Please.

2020-10-01 03:59 UTC, JohanFreelancer9 commented on windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure.md
> +- [Create and deploy Windows Information Protection (WIP) app protection policy with Intune and MAM](https://docs.microsoft.com/windows/security/information-protection/windows-information-protection/
```suggestion
- [Create a Windows Information Protection (WIP) protection policy using Microsoft Intune](https://docs.microsoft.com/windows/security/information-protection/windows-information-protection/overview-create-wip-policy)
```

2020-10-01 04:00 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-01 14:23 UTC, JohanFreelancer9 approved these changes

2020-10-07 15:47 UTC, merged