Clarity on TimeGenerated, snapshot ingestion
MicrosoftDocs/windows-itpro-docs pull request #8392
Opened 2020-10-01 16:05 UTC by cinglis-msft

@jaimeo

2020-10-03 15:30 UTC, e0i commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-04 04:45 UTC, JohanFreelancer9 commented on windows/deployment/update/update-compliance-using.md
> +The data powering Update Compliance is refreshed every 24 hours, and refreshes with the latest data from all devices part of your organization that have been seen in the past 28 days. The entire set
```suggestion
The data powering Update Compliance is refreshed every 24 hours, and refreshes with the latest data from all devices in your organization that have been seen in the past 28 days. The entire set of data is refreshed in each daily snapshot, which means that the same data can be re-ingested even if no new data actually arrived from the device since the last snapshot. Snapshot time can be determined by the TimeGenerated field for each record, while LastScan can be used to roughly determine the freshness of each record's data.  
```

2020-10-04 04:45 UTC, JohanFreelancer9 commented on windows/deployment/update/update-compliance-using.md
> +The data powering Update Compliance is refreshed every 24 hours, and refreshes with the latest data from all devices part of your organization that have been seen in the past 28 days. The entire set
Suggestion only.

2020-10-04 04:48 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-05 15:58 UTC, jaimeo commented
I'm not a huge fan of "ingestion," which feels a little disgustingly biological to me, but TermStudio says it's copacetic.

2020-10-05 15:59 UTC, merged