Update prevent-end-user-interaction-microsoft-defender-antivirus.md
MicrosoftDocs/windows-itpro-docs pull request #8401
Opened 2020-10-02 17:41 UTC by kurtsarens

Pausing a scan is not supported on Win10

2020-10-03 15:30 UTC, e0i commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-04 04:39 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-antivirus/prevent-end-user-interaction-microsoft-defender-antivirus.md
> +>[!NOTE]
```suggestion
> [!NOTE]
```

2020-10-04 04:39 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-antivirus/prevent-end-user-interaction-microsoft-defender-antivirus.md
> +>This setting is not supported on Windows 10
```suggestion
> This setting is not supported on Windows 10.
```

2020-10-04 04:40 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-05 17:28 UTC, denisebmsft approved these changes
Thank you @kurtsarens and @JohanFreelancer9

2020-10-05 17:28 UTC, merged