troubleshooting option to check GPO
MicrosoftDocs/windows-itpro-docs pull request #8442
Opened 2020-10-11 03:33 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5726

2020-10-11 03:34 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

2020-10-11 07:51 UTC, JohanFreelancer9 commented on windows/deployment/update/waas-delivery-optimization.md
> +If you suspect this is the problem, check Delivery Optimization settings that could limit participation in Peer Caching. Check following settings in assigned group policies, local group policies and
```suggestion
If you suspect this is the problem, check Delivery Optimization settings that could limit participation in Peer Caching. Check whether the following settings in assigned group policies, local group policies, and MDM policies are too restrictive:
```

2020-10-11 07:52 UTC, JohanFreelancer9 commented on windows/deployment/update/waas-delivery-optimization.md
> +- Minimum RAM (inclusive) allowed to use Peer Caching
```suggestion
- Minimum RAM (inclusive) allowed to use Peer Caching.
```

2020-10-11 07:52 UTC, JohanFreelancer9 commented on windows/deployment/update/waas-delivery-optimization.md
> +- Minimum disk size allowed to use Peer Caching
```suggestion
- Minimum disk size allowed to use Peer Caching.
```

2020-10-11 07:54 UTC, JohanFreelancer9 commented on windows/deployment/update/waas-delivery-optimization.md
> +- Enable Peer Caching while the device connects via VPN
```suggestion
- Enable Peer Caching while the device connects via VPN.
```

2020-10-11 07:55 UTC, JohanFreelancer9 commented on windows/deployment/update/waas-delivery-optimization.md
> +- Allow uploads while the device is on battery while under set Battery level
```suggestion
- Allow uploads while the device is on battery while under set battery level.
```

2020-10-11 07:58 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-12 10:37 UTC, JohanFreelancer9 approved these changes

2020-10-12 17:20 UTC, merged