edited warning
MicrosoftDocs/windows-itpro-docs pull request #8443
Opened 2020-10-11 03:39 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5621

2020-10-11 03:40 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

2020-10-11 07:46 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-11 07:46 UTC, JohanFreelancer9 commented on windows/security/identity-protection/user-account-control/how-user-account-control-works.md
> +> **Warning:**  Some Universal Windows apps may not work when UAC is disabled.
```suggestion
> **Warning:**  Some Universal Windows Platform apps may not work when UAC is disabled.
```

2020-10-12 10:39 UTC, JohanFreelancer9 approved these changes

2020-10-19 18:22 UTC, nam31 commented
@Dansimp PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-10-19 18:25 UTC, nam31 commented
@DulceMontemayor PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-10-20 19:02 UTC, illfated approved these changes

2020-10-22 21:31 UTC, DulceMontemayor approved these changes

2020-10-22 21:31 UTC, merged