Addition of information in Note
MicrosoftDocs/windows-itpro-docs pull request #8450
Opened 2020-10-12 16:06 UTC by joinimran

Add additional information in the Note section to enable policy to work.

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8241

2020-10-12 16:07 UTC, joinimran commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-10-12 16:39 UTC, JohanFreelancer9 commented on windows/security/identity-protection/remote-credential-guard.md
> +> GPO [Remote host allows delegation of non-exportable credentials](https://docs.microsoft.com/windows/client-management/mdm/policy-csp-credentialsdelegation) should be enabled for Delegation of non-
```suggestion
> GPO [Remote host allows delegation of non-exportable credentials](https://docs.microsoft.com/windows/client-management/mdm/policy-csp-credentialsdelegation) should be enabled for delegation of non-exportable credentials.
```

2020-10-12 16:39 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-10-12 18:09 UTC, joinimran commented
Thanks @JohanFreelancer9 - @e0i Ready to go live.

2020-10-22 21:38 UTC, DulceMontemayor approved these changes

2020-10-22 21:38 UTC, merged