Removed a content
MicrosoftDocs/windows-itpro-docs pull request #8457
Opened 2020-10-13 16:40 UTC by joinimran

There is no need to create a custom device policy to enable PIN reset recovery. So removing this portion.

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8284#issuecomment-707356130

2020-10-13 16:42 UTC, joinimran commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-10-14 03:05 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md
```suggestion
```

2020-10-14 03:06 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-14 05:00 UTC, joinimran commented
@e0i - Ready to go live.

2020-10-14 13:56 UTC, JohanFreelancer9 approved these changes

2020-10-15 18:46 UTC, illfated commented
@joinimran : Thank you for the work you provide in pull requests and ticket comments & replies. Just a minor detail here in this PR ("English grammar tip of the day", if you like): the word "content" is usually considered to describe some undefined amount of mass or uncountable number of items. The most common usage is to skip "a", going straight to the word itself, so in this case the PR title would in most cases be "Removed content" (or "Removed outdated content").

Anyway, this is mostly an advice for future use. No need to change the PR title, because the commit name will stay unchanged.

2020-10-15 18:47 UTC, illfated approved these changes
Looks good & correct to me.

2020-10-15 18:47 UTC, illfated commented
#sign-off

2020-10-19 16:44 UTC, mapalko commented
Instead of removing this section, it should be replaced with steps for configuring the policy via the UI linked by CHDAFNI-MSFT

2020-10-21 17:08 UTC, e0i commented
> Instead of removing this section, it should be replaced with steps for configuring the policy via the UI linked by CHDAFNI-MSFT

cc @joinimran

2020-10-22 05:26 UTC, joinimran commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-10-22 05:54 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md
> +3. Select Enable PIN recovery to **Yes**.
I think "Set" is better than "Select" in this context, but maybe it needs further rephrasing.
```suggestion
3. Set **Enable PIN recovery** to **Yes**.
```
@JohanFreelancer9 , can you confirm or suggest an improvement?

2020-10-22 07:45 UTC, joinimran commented
Thanks, @illfated. This makes more sense.

2020-10-22 07:48 UTC, JohanFreelancer9 approved these changes

2020-10-22 12:42 UTC, illfated approved these changes
Looks good to me.

2020-10-26 23:34 UTC, mapalko requested changes

2020-10-26 23:34 UTC, mapalko commented on windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md
> +2. Click **Endpoint Security**-> **Account Portection**-> **Properties**.
Typo: "Account Portection" should be "Account Protection"

2020-10-26 23:34 UTC, mapalko commented on windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md
> +3. Set **Enable PIN recovery** to **Yes**.
Endpoint Security/Account Protection is an optional configuration and this step assumes someone has already set it up.

Can we also add an alternative set of steps using configuration profiles?
1. Sign-in to Endpoint Manager
2. Click **Devices** -> **Configuration Profiles** -> Create new profile or edit existing an existing profile using the Identity Protection profile type 
Set **Enable PIN recovery** to **Yes**

2020-10-27 04:33 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md
> +1. Sign-in to [Enpoint Manager Admin Center](https://endpoint.microsoft.com/) using a Global administrator account.
```suggestion
1. Sign-in to [Enpoint Manager admin center](https://endpoint.microsoft.com/) using a Global administrator account.
```

2020-10-27 04:33 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md
> +2. Click **Endpoint Security**-> **Account Portection**-> **Properties**.
```suggestion
2. Click **Endpoint Security**-> **Account Protection**-> **Properties**.
```

2020-10-27 16:42 UTC, joinimran commented
@JohanFreelancer9 please copy review.

2020-10-27 16:56 UTC, mapalko approved these changes

2020-10-28 01:30 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md
> +> [!Note]
```suggestion
> [!NOTE]
```

2020-10-28 01:30 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md
> +> 1. Sign-in to Endpoint Manager
```suggestion
> 1. Sign in to Endpoint Manager.
```

2020-10-28 01:32 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md
> +> 2. Click **Devices** -> **Configuration Profiles** -> Create new profile or edit existing an existing profile using the Identity Protection profile type
```suggestion
> 2. Click **Devices** -> **Configuration Profiles** -> Create new profile or edit an existing profile using the Identity Protection profile type.
```

2020-10-28 01:32 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md
> +> 3. Set **Enable PIN recovery** to **Yes**
```suggestion
> 3. Set **Enable PIN recovery** to **Yes**.
```

2020-10-28 01:33 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-28 04:49 UTC, joinimran commented
Thanks, @JohanFreelancer9.

2020-10-29 03:17 UTC, JohanFreelancer9 approved these changes

2020-10-29 12:15 UTC, illfated approved these changes

2020-11-06 21:55 UTC, illfated commented
Link to rich diff view of the image:
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8457/files?short_path=d82adde#diff-d82addeadf260315de8dde6cd3b4d68258bc3ab9865e09ca461d779301e141dc 

(pick Swipe or Onion Skin to get a big enough image and a small tug handle at the lower left corner to view the text change in the box (in the middle of the image) when moving the handle)

2020-11-06 21:57 UTC, illfated approved these changes
Looks quite good to me.

2020-11-06 22:00 UTC, illfated commented
(also ref. #8509 )

2020-11-06 22:01 UTC, illfated commented
#sign-off

2020-11-13 06:05 UTC, joinimran commented
> Oh. Is the issue that this MacOS image does not belong in this PR, [MicrosoftDocs#8457](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8457) , which is about the Hello for Business _Pin Reset_ feature?

2020-11-13 06:05 UTC, closed without merging

2020-11-13 06:09 UTC, joinimran commented
> Oh. Is the issue that this MacOS image does not belong in this PR, [MicrosoftDocs#8457](https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8457) , which is about the Hello for Business _Pin Reset_ feature?

@illfated - That looks like for a different page and different content.