BitLocker recovery guide: format & spacing edits
MicrosoftDocs/windows-itpro-docs pull request #8462
Opened 2020-10-14 20:34 UTC by illfated

**Description:**

As reported in issue ticket #8460 (Wrong section), there are a couple of sections where the last line of a bullet list has merged with a following paragraph due to missing whitespace or insufficient line breaks.

This pull request should mitigate those issues.

Thanks to @Eddddeee for reporting the document issue(s).

**Additional changes:**

- doubled the number of blank lines before each new heading (H2, H3, H4)
- squashed double or triple spacing in bullet point list and numbered lists
- added an inferred colon at the end of a handful of paragraph/section headings

**Ticket reference or closure:**

Closes #8460

2020-10-14 20:38 UTC, illfated reviewed
- [X] **Regular source file view:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8462/files
- [X] **Hide whitespace changes:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8462/files?diff=unified&w=1 (simplifies the review process)
- [X] **Rich diff view:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8462/files?short_path=3381e07#diff-3381e07ddeb5e31132e071f246b64a9acf6166959d55d86ea75b51744faa4fbf (readability & layout review)

2020-10-14 20:39 UTC, illfated commented
#sign-off

2020-10-19 17:16 UTC, e0i commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-20 06:32 UTC, JohanFreelancer9 commented on windows/security/information-protection/bitlocker/bitlocker-recovery-guide-plan.md
>  If you notice that a computer is having repeated recovery password unlocks, you might want to have an administrator can perform post-recovery analysis to determine the root cause of the recovery and
```suggestion
If you notice that a computer is having repeated recovery password unlocks, you might want to have an administrator perform post-recovery analysis to determine the root cause of the recovery and refresh BitLocker platform validation so that the user no longer needs to enter a recovery password each time that the computer starts up. See:
```

2020-10-20 06:33 UTC, JohanFreelancer9 commented on windows/security/information-protection/bitlocker/bitlocker-recovery-guide-plan.md
> +    1. Right-click the drive and then click **Change PIN**
```suggestion
    1. Right-click the drive and then click **Change PIN**.
```

2020-10-20 06:35 UTC, JohanFreelancer9 commented on windows/security/information-protection/bitlocker/bitlocker-recovery-guide-plan.md
>  This error might occur if you updated the firmware. As a best practice you should suspend BitLocker before making changes the firmware and then resume protection after the update has completed. This
```suggestion
This error might occur if you updated the firmware. As a best practice you should suspend BitLocker before making changes to the firmware and then resume protection after the update has completed. This prevents the computer from going into recovery mode. However if changes were made when BitLocker protection was on you can simply log on to the computer using the recovery password and the platform validation profile will be updated so that recovery will not occur the next time.
```

2020-10-20 06:43 UTC, JohanFreelancer9 commented on windows/security/information-protection/bitlocker/bitlocker-recovery-guide-plan.md
>  BitLocker metadata has been enhanced in Windows 10, version 1903 to include information about when and where the BitLocker recovery key was backed up. This information is not exposed through the UI o
```suggestion
BitLocker metadata has been enhanced in Windows 10, version 1903 to include information about when and where the BitLocker recovery key was backed up. This information is not exposed through the UI or any public API. It is used solely by the BitLocker recovery screen in the form of hints to help a user locate a volume's recovery key. Hints are displayed on the recovery screen and refer to the location where the key has been saved. Hints are displayed in both the modern (blue) and legacy (black) recovery screen. This applies to both the boot manager recovery screen and the WinRE unlock screen.
```

2020-10-20 06:58 UTC, JohanFreelancer9 requested changes
Looks good, just a few additional edits, please.

2020-10-20 11:06 UTC, illfated commented
Thank you very much for going through the text in detail. I must have been skimming the text way too superficially on my own.

2020-10-20 13:12 UTC, JohanFreelancer9 approved these changes

2020-10-20 16:28 UTC, illfated commented
#sign-off

2020-10-21 18:12 UTC, merged