Published recommended driver block rules from HVCI/10S blocklist
MicrosoftDocs/windows-itpro-docs pull request #8483
Opened 2020-10-16 18:12 UTC by jgeurten

Added the driver block list to the recommended block list section. We can now recommend to WDAC customers to add these vulnerable driver blocks to their policy to broaden the coverage of the kernel block policy.

2020-10-16 18:17 UTC, jgeurten commented
Can I please get @jsuther1974 and @degranit added to the PR as **required**  reviewers?

2020-10-17 02:22 UTC, illfated commented
Fair request. One of the MS Docs team members will assign/request the reviewers for you.

2020-10-19 19:27 UTC, degranit approved these changes
Looks great!

2020-10-19 22:32 UTC, illfated commented on windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules.md
> +
Redundant blank line, I believe 2 blank lines should be sufficient spacing:
```suggestion
```

2020-10-19 22:43 UTC, illfated approved these changes
Looks good to me, although I am not an expert on this topic.

2020-10-19 23:28 UTC, jsuther1974 requested changes
I'm not a *huge* fan of embedding the XML in a help topic rather than manifesting the XML to the Windows\Schemas folder. I'll live with it, though, if we have to...

2020-10-19 23:28 UTC, jsuther1974 commented on windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules.md
> +- Windows 10S mode devices
The correct term is "Windows 10 in S mode (S mode)", not Windows 10S mode devices. Referening "(S mode)" on first use allows you to simply refer to S mode through the rest of the doc.

2020-10-19 23:28 UTC, jsuther1974 commented on windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules.md
> +  <Rules>
Are these really the only rule options we should include by default?

2020-10-19 23:34 UTC, jgeurten commented on windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules.md
> +  <Rules>
I was surprised too - instructions in the readme.txt (minkernel/ci/data/MaliciousDriverPolicy/readme.txt)

2020-10-19 23:40 UTC, jgeurten commented on windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules.md
> +- Windows 10S mode devices
Done!

2020-10-20 00:06 UTC, jsuther1974 commented on windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules.md
> +Microsoft has strict requirements for code running in kernel. Consequently, malicious actors are turning to exploit vulnerabilities in legitimate and signed kernel drivers to run malware in kernel. O
You have a typo. “Mirosoft”

2020-10-20 00:07 UTC, jsuther1974 approved these changes

2020-10-21 22:17 UTC, merged