Specify Expected Behavior for Username/Password Setting
MicrosoftDocs/windows-itpro-docs pull request #8498
Opened 2020-10-20 13:47 UTC by angela-em

As an Intune SE, we receive a lot of cases for this OMA-URI setting. Customers use it to create a local admin account for Intune enrolled devices but it always reports as failed.
By including this information, we can set the expectation and prevent future cases.

2020-10-22 16:33 UTC, e0i commented
CC @JohanFreelancer9 for copy editing.

2020-10-23 06:04 UTC, JohanFreelancer9 commented on windows/client-management/mdm/accounts-csp.md
> +GET operation is not supported.  This setting will report as failed when deployed from the Endpoint Manager.
```suggestion
The Get operation is not supported. This setting will report as failed when deployed from the Endpoint Manager.
```

2020-10-23 06:04 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-23 23:01 UTC, merged

2020-10-23 23:48 UTC, illfated commented
🤔 Oh well. I guess the readers will get (pun intended) the added message clearly enough. 😉

2020-10-25 19:37 UTC, angela-em commented on windows/client-management/mdm/accounts-csp.md
> +GET operation is not supported.  This setting will report as failed when deployed from the Endpoint Manager.
How long does it take before the merged changes show in the public doc?