added note about updated security baseline
MicrosoftDocs/windows-itpro-docs pull request #8513
Opened 2020-10-22 05:47 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8389

2020-10-22 05:48 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @ei, for your information

Thank you

2020-10-22 07:59 UTC, JohanFreelancer9 commented on windows/security/threat-protection/security-policy-settings/maximum-password-age.md
> +> Security baseline recommended by Microsoft doesn't contain the password-expiration policy, as this mitigation is less effective than modern ones. However, companies that didn't implement Azure AD P
```suggestion
> The security baseline recommended by Microsoft doesn't contain the password-expiration policy, as it is less effective than modern mitigations. However, companies that didn't implement Azure AD Password Protection, multifactor authentication, or other modern mitigations of password-guessing attacks, should leave this policy in effect.
```

2020-10-22 08:02 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-22 15:44 UTC, JohanFreelancer9 approved these changes

2020-10-30 23:40 UTC, illfated approved these changes
Looks good to me.

2020-12-14 23:21 UTC, merged

2020-12-15 05:19 UTC, STO123456789 commented
I have already filled a complaint with the ICCC and the F.B.I. For violation of privacy and infringement 

Ernesto 

> On Dec 14, 2020, at 5:21 PM, Daniel Simpson <notifications@github.com> wrote:
> 
> ﻿
> Merged #8513 into public.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-12-15 05:23 UTC, STO123456789 commented
So you know I do have an appointment with an attorney tomorrow to prosecute 

Ernesto 

> On Dec 14, 2020, at 5:21 PM, Daniel Simpson <notifications@github.com> wrote:
> 
> ﻿
> Merged #8513 into public.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.