update note section
MicrosoftDocs/windows-itpro-docs pull request #8522
Opened 2020-10-22 16:34 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8359

2020-10-22 16:34 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

2020-10-23 06:33 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md
>  > 4. Launch Powershell as Administrator.
```suggestion
> 4. Launch PowerShell as administrator.
```

2020-10-23 06:34 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md
> +> 5. Get the ObjectIdentifier of application permission with ClientRoleIdentifier parameter equal to "38aa3b87-a06d-4817-b275-7a316988d93b":
```suggestion
> 5. Get the ObjectIdentifier of the application permission with the ClientRoleIdentifier parameter equal to "38aa3b87-a06d-4817-b275-7a316988d93b":
```

2020-10-23 06:36 UTC, JohanFreelancer9 requested changes
Copy review - two additional minor edits as well, please.

2020-10-25 03:03 UTC, JohanFreelancer9 approved these changes

2020-10-25 21:09 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md
> +```(Get-AdfsApplicationPermission -ServerRoleIdentifiers 'http://schemas.microsoft.com/ws/2009/12/identityserver/selfscope' | ?{ $_.ClientRoleIdentifier -eq '38aa3b87-a06d-4817-b275-7a316988d93b' }).
Since you are already using 3 backticks for the cmdlet, maybe it would be just as useful to format it as a code block with syntax highlighting:
```suggestion
> ```PowerShell
> (Get-AdfsApplicationPermission -ServerRoleIdentifiers 'http://schemas.microsoft.com/ws/2009/12/identityserver/selfscope' | ?{ $_.ClientRoleIdentifier -eq '38aa3b87-a06d-4817-b275-7a316988d93b' }).ObjectIdentifier
> ```
```

2020-10-25 21:11 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-cert-trust-adfs.md
>  > 6. Execute the command "Set-AdfsApplicationPermission -TargetIdentifier <ObjectIdentifier from step 5> -AddScope 'ugs'.
This line could use some MD code block fencing to avoid misreading or filtering:
```suggestion
> 6. Execute the command `Set-AdfsApplicationPermission -TargetIdentifier <ObjectIdentifier from step 5> -AddScope 'ugs'`.
```

2020-10-26 02:33 UTC, illfated approved these changes
Looks good to me.

2020-10-26 02:33 UTC, illfated commented
#sign-off

2020-11-13 01:01 UTC, mapalko approved these changes

2020-11-19 00:12 UTC, merged