remodified the sentence
MicrosoftDocs/windows-itpro-docs pull request #8594
Opened 2020-11-05 17:45 UTC by RAJU2529

as per the user report #8587 , so I added grammatical word.

2020-11-05 18:14 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-key-trust-policy-settings.md
> +Alternatively, you can create a copy of the .ADMX and .ADML files from a Windows 10, version 1703 to their respective language folder on a Windows Server or you can create a Group Policy Central Stor
We need to add more missing text here, because the sentence is not complete yet. We need a description to follow
"from a Windows 10, version 1703 (something, something) ". I will make an attempt, but I can't promise it is 100% correct.
```suggestion
Alternatively, you can create a copy of the .ADMX and .ADML files from a Windows 10, version 1703 installation setup template folder to their respective language folder on a Windows Server or you can create a Group Policy Central Store and copy them their respective language folder. See [How to create and manage the Central Store for Group Policy Administrative Templates in Windows](https://support.microsoft.com/help/3087759/how-to-create-and-manage-the-central-store-for-group-policy-administrative-templates-in-windows) for more information.
```
(We may very well need help from @JohanFreelancer9 here, because this sentence has not been changed since this document was created.)

2020-11-06 03:57 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-key-trust-policy-settings.md
> +Alternatively, you can create a copy of the .ADMX and .ADML files from a Windows 10, version 1703 installation setup template folder to their respective language folder on a Windows Server or you can
```suggestion
Alternatively, you can create a copy of the .ADMX and .ADML files from a Windows 10, version 1703 installation setup template folder to their respective language folder on a Windows Server, or you can create a Group Policy Central Store and copy them their respective language folder. See [How to create and manage the Central Store for Group Policy Administrative Templates in Windows](https://support.microsoft.com/help/3087759/how-to-create-and-manage-the-central-store-for-group-policy-administrative-templates-in-windows) for more information.
```

2020-11-06 03:58 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-key-trust-policy-settings.md
> +Alternatively, you can create a copy of the .ADMX and .ADML files from a Windows 10, version 1703 installation setup template folder to their respective language folder on a Windows Server or you can
Looks good to me, please just add the comma as indicated.

2020-11-06 03:59 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-11-06 04:47 UTC, JohanFreelancer9 approved these changes

2020-11-06 11:49 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-key-trust-policy-settings.md
>  You need a Windows 10, version 1703 workstation to run the Group Policy Management Console, which provides the latest Windows Hello for Business and PIN Complexity Group Policy settings.  To run the
Cosmetic correction / minor detail from the original author:
```suggestion
You need a Windows 10, version 1703 workstation to run the Group Policy Management Console, which provides the latest Windows Hello for Business and PIN Complexity Group Policy settings.  To run the Group Policy Management Console, you need to install the Remote Server Administration Tools for Windows 10. You can download these tools from [Microsoft Download Center](https://www.microsoft.com/download/details.aspx?id=45520).
```

2020-11-07 02:54 UTC, JohanFreelancer9 approved these changes

2020-11-07 14:40 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-key-trust-policy-settings.md
> +You need a Windows 10, version 1703 workstation to run the Group Policy Management Console, which provides the latest Windows Hello for Business and PIN Complexity Group Policy settings.  To run the
I don't agree. Reading the sentence, which is correct:
You can download these tools from Microsoft Download Center, or
You can download these tools from the Microsoft Download Center?

2020-11-07 21:24 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-key-trust-policy-settings.md
> +You need a Windows 10, version 1703 workstation to run the Group Policy Management Console, which provides the latest Windows Hello for Business and PIN Complexity Group Policy settings.  To run the
From my point of view, it is more common to see either "the Download Center" or "Microsoft Download Center", but I also see your view as a likely correct phrasing.

2020-11-07 21:25 UTC, illfated approved these changes

2020-11-07 21:25 UTC, illfated commented
#sign-off

2020-11-13 18:03 UTC, nam31 commented
@mapalko PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-11-13 19:13 UTC, mapalko requested changes

2020-11-13 19:13 UTC, mapalko commented on windows/security/identity-protection/hello-for-business/hello-key-trust-policy-settings.md
> +Alternatively, you can create a copy of the .ADMX and .ADML files from a Windows 10, version 1703 installation setup template folder to their respective language folder on a Windows Server, or you ca
Can you change the reference from 1703 to 1703 or later?
I also think there is a 'to' missing from this clause: "or you can create a Group Policy Central Store and copy them their respective language folder.

I think it should be, "or you can create a Group Policy Central Store and copy them **to** their respective language folder"

2020-11-13 19:50 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-key-trust-policy-settings.md
> +Alternatively, you can create a copy of the .ADMX and .ADML files from a Windows 10, version 1703 installation setup template folder to their respective language folder on a Windows Server, or you ca
Thank you, those are good suggestions. I will add the changes as mergeable suggestions.
```suggestion
Alternatively, you can create a copy of the .ADMX and .ADML files from a Windows 10, version 1703 installation setup template folder to their respective language folder on a Windows Server, or you can create a Group Policy Central Store and copy them to their respective language folder. See [How to create and manage the Central Store for Group Policy Administrative Templates in Windows](https://support.microsoft.com/help/3087759/how-to-create-and-manage-the-central-store-for-group-policy-administrative-templates-in-windows) for more information.
```

2020-11-24 16:29 UTC, merged