Update info about device credentials
MicrosoftDocs/windows-itpro-docs pull request #8605
Opened 2020-11-08 08:25 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8532

2020-11-08 08:25 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

2020-11-08 12:40 UTC, illfated approved these changes

2020-11-08 14:56 UTC, JohanFreelancer9 approved these changes

2020-11-11 02:37 UTC, MaratMussabekov commented
Hello @JohanFreelancer9,
"it is not yet supported for MDM solutions (including Intune) yet"
I used "yet" two times...
which one would you recommend to remove?

Thank you!

2020-11-11 08:17 UTC, illfated commented
Just in case this helps you start editing before JohanFreelancer9 replies.
The last "yet" is the one you should remove. As I view it, this makes sense:

> **Device Credential** Credential Type will also work, however, it is not yet supported for MDM solutions (including Intune). It is not recommended to use this option until support is announced.

Reasoning: "not yet" is a very common phrase in English, there is also the case of keeping focus on the importance of "(including Intune)" by removing any less important details after the Intune part.

2020-11-11 09:08 UTC, JohanFreelancer9 commented on windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md
> +> **Device Credential** Credential Type will also work, however, it is not yet supported for MDM solutions (including Intune) yet. It is not recommended to use this option until support is announced.
```suggestion
> **Device Credential** Credential Type will also work, however, it is not yet supported for MDM solutions (including Intune). We don't recommend using this option until support is announced.
```

2020-11-11 09:12 UTC, JohanFreelancer9 requested changes
Dear @MaratMussabekov - I agree with @illfated, and have also made a further suggestion.

2020-11-11 09:15 UTC, illfated commented
Fair point, good suggestion. I agree with the further suggestion.

2020-11-13 18:21 UTC, nam31 commented
@Dansimp PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-11-13 19:47 UTC, illfated commented
Looks good. Just give @MaratMussabekov time to merge the last suggestion from @JohanFreelancer9 and it will be good to go.

2020-11-16 15:06 UTC, JohanFreelancer9 approved these changes

2020-11-16 16:23 UTC, illfated approved these changes

2020-11-16 16:23 UTC, illfated commented
#sign-off

2020-11-17 22:09 UTC, ManikaDhiman commented
Reached out to SME to review the changes.

2020-11-20 20:13 UTC, merged

2020-11-21 06:10 UTC, illfated commented
Thank you for this PR, @MaratMussabekov .