Update vpn-conditional-access.md
MicrosoftDocs/windows-itpro-docs pull request #8610
Opened 2020-11-10 08:26 UTC by msarcletti

Updating the note describing prerequisites for using SSO with information relevant for AAD only joined devices.

2020-11-10 22:50 UTC, illfated commented on windows/security/identity-protection/vpn/vpn-conditional-access.md
> +> In the case of AzureAD-only joined devices (not hybrid joined devices), if the user certificate issued by the on-premises CA has in Subject and SAN (Subject Alternative Name) the user UPN from Azur
The first sentence of the added paragraph appears to have a difficult or unclear sentence structure in the following part:
> if the user certificate issued by the on-premises CA has in Subject and SAN (Subject Alternative Name) the user UPN from AzureAD,

Would it be useful to form a more readable structure by writing, for example, the following?
> if the user certificate issued by the on-premises CA has the user UPN from AzureAD in Subject and SAN (Subject Alternative Name),

2020-11-11 10:42 UTC, msarcletti commented on windows/security/identity-protection/vpn/vpn-conditional-access.md
> +> In the case of AzureAD-only joined devices (not hybrid joined devices), if the user certificate issued by the on-premises CA has in Subject and SAN (Subject Alternative Name) the user UPN from Azur
Thanks for the hint. I've changed the sentence according to your suggestion.

2020-11-11 17:48 UTC, illfated commented on windows/security/identity-protection/vpn/vpn-conditional-access.md
> +> In the case of AzureAD-only joined devices (not hybrid joined devices), if the user certificate issued by the on-premises CA has the user UPN from AzureAD in Subject and SAN (Subject Alternative Na
Cosmetic/codestyle: comma spacing + adding definite articles (the, that)
```suggestion
> In the case of AzureAD-only joined devices (not hybrid joined devices), if the user certificate issued by the on-premises CA has the user UPN from AzureAD in Subject and SAN (Subject Alternative Name), the VPN profile must be modified to ensure that the client does not cache the credentials used for VPN authentication. To do this, after deploying the VPN profile to the client, modify the *Rasphone.pbk* on the client by changing the entry **UseRasCredentials** from 1 (default) to 0 (zero).
```

2020-11-11 17:51 UTC, illfated commented
Just in case my English is not fine-tuned enough to American English writing, I believe we should ask @JohanFreelancer9 to check this content too, to be on the safe side.

2020-11-11 17:59 UTC, illfated commented
(also ref. #8612 - similar grammar)

2020-11-12 02:58 UTC, JohanFreelancer9 commented on windows/security/identity-protection/vpn/vpn-conditional-access.md
>     - Upon request, forwards the Health Attestation Certificate (received from HAS) and related runtime information to the MDM server for verification
```suggestion
   - Upon request, forward the Health Attestation Certificate (received from HAS) and related runtime information to the MDM server for verification
```

2020-11-12 03:02 UTC, JohanFreelancer9 requested changes
Copy review - only @illfated's suggestions and one additional correction to line 72, please.

2020-11-13 13:50 UTC, JohanFreelancer9 approved these changes

2020-11-13 14:43 UTC, illfated approved these changes

2020-11-13 14:43 UTC, illfated commented
#sign-off

2020-11-17 16:52 UTC, merged