removed invalid link and added correct link
MicrosoftDocs/windows-itpro-docs pull request #8640
Opened 2020-11-15 08:47 UTC by RAJU2529

as per user report #8634 , so i removed invalid link and added the correct link.

2020-11-15 22:49 UTC, illfated commented on windows/client-management/troubleshoot-windows-freeze.md
> +Learn [How to use Memory Pool Monitor to troubleshoot kernel mode memory leaks](https://support.microsoft.com/office/how-to-use-memory-pool-monitor-poolmon-exe-to-troubleshoot-kernel-mode-memory-leak
To me, it looks like there should either be a lowercase "how to" in the URL text, but the other option is to extend the "Learn " text to become a more descriptive phrase and point to the URL text with a colon. I would like to ask @JohanFreelancer9 for suggestions here, because I am not quite sure which solution is preferred here, to follow the MS Codestyle correctly.

2020-11-15 22:51 UTC, illfated commented on windows/client-management/troubleshoot-windows-freeze.md
> +Learn [How to use Memory Pool Monitor to troubleshoot kernel mode memory leaks](https://support.microsoft.com/office/how-to-use-memory-pool-monitor-poolmon-exe-to-troubleshoot-kernel-mode-memory-leak
Other than that, it looks like a good solution to provide a single link to one page covering more or less the same as both the previous links, especially given that the previous material is either outdated or gone.

2020-11-16 15:26 UTC, JohanFreelancer9 commented on windows/client-management/troubleshoot-windows-freeze.md
> +Learn [How to use Memory Pool Monitor to troubleshoot kernel mode memory leaks](https://support.microsoft.com/office/how-to-use-memory-pool-monitor-poolmon-exe-to-troubleshoot-kernel-mode-memory-leak
```suggestion
Learn [how to use Memory Pool Monitor to troubleshoot kernel mode memory leaks](https://support.microsoft.com/office/how-to-use-memory-pool-monitor-poolmon-exe-to-troubleshoot-kernel-mode-memory-leaks-4f4a05c2-ef8a-fca4-3ae0-670b940af398). 
```

2020-11-16 15:26 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-16 16:49 UTC, illfated approved these changes
Looks like a useful and good solution to me.

2020-11-17 08:48 UTC, JohanFreelancer9 approved these changes

2020-11-19 17:24 UTC, merged