Typos, MarkDown, whitespace and formatting issues
MicrosoftDocs/windows-itpro-docs pull request #8686
Opened 2020-11-21 23:28 UTC by illfated

**Description:**

As mentioned in PR #8595, I noticed quite a few formatting issues in this document, both for MarkDown code block formatting and whitespace usage (or lack thereof).

Since the PR was focused on a quite specific topic update, the PR author did not want additional changes added. I therefore submit a list of my own improvements.

**Changes proposed:**

- add proper MarkDown code blocks around separate command lines and important lists
- add PowerShell syntax highlighting to PS MD code blocks
- remove PowerShell command prompt for easier command copying (recommended codestyle)
- add missing blank lines between section headings (H2/H3/H4) and their text paragraphs
- typo correction: replace "and" with "a" in "open and command prompt"
- remove any blank space at the end of lines (whitespace cleanup)
- standardize number list spacing to a single blank (MarkDown standard)
- add missing colon at the end of introductory sentences

**Ticket / PR closure or reference:**

Ref. #8595

2020-11-21 23:35 UTC, illfated reviewed
Due to the high amount of whitespace changes in this PR, I recommend using the feature **Hide whitespace changes:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8686/files?diff=unified&w=1 (added blank lines are not skipped, but most of my removal of simple blanks is hidden in this view).

2020-11-21 23:36 UTC, illfated commented
#sign-off

2020-11-27 02:24 UTC, illfated commented
#sign-off

2020-11-27 02:26 UTC, illfated commented
@e0i : For Your Information & please assign Matthew (mapalko) for code review. Request copy review if you find it practical.

2020-11-27 09:55 UTC, e0i commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-11-27 15:38 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
> +To do this, follow the **Configure device settings** steps under [Setting up Azure AD Join in your organization](https://azure.microsoft.com/documentation/articles/active-directory-azureadjoin-setup/
```suggestion
To do this, follow the **Configure device settings** steps under [Setting up Azure AD Join in your organization](https://azure.microsoft.com/documentation/articles/active-directory-azureadjoin-setup/).
```

2020-11-28 07:17 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
> +To do this, follow the **Configure device settings** steps under [Setting up Azure AD Join in your organization](https://azure.microsoft.com/documentation/articles/active-directory-azureadjoin-setup/
```suggestion
To do this, follow the **Configure device settings** steps under [Setting up Azure AD Join in your organization](https://azure.microsoft.com/documentation/articles/active-directory-azureadjoin-setup/).
```

2020-11-28 07:23 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
>  Sign-in to the domain controller hosting the schema master operational role using enterprise administrator equivalent credentials.
```suggestion
Sign in to the domain controller hosting the schema master operational role using enterprise administrator equivalent credentials.
```

2020-11-28 07:24 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
>  ### Setup Active Directory Federation Services
```suggestion
### Set up Active Directory Federation Services
```

2020-11-28 07:24 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
>  If you are new to AD FS and federation services, you should review [Understanding Key AD FS Concepts](https://docs.microsoft.com/windows-server/identity/ad-fs/technical-reference/understanding-key-ad
```suggestion
If you are new to AD FS and federation services, you should review [Understanding Key AD FS Concepts](https://docs.microsoft.com/windows-server/identity/ad-fs/technical-reference/understanding-key-ad-fs-concepts) prior to designing and deploying your federation service.
```

2020-11-28 07:35 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
> +2. Provide your Azure AD global administrator credentials
```suggestion
2. Provide your Azure AD global administrator credentials.
```

2020-11-28 07:38 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
> +Where the [AD connector account name] is the name of the account you configured in Azure AD Connect when adding your on-premises AD DS directory in domain\accountname format
```suggestion
Where the [AD connector account name] is the name of the account you configured in Azure AD Connect when adding your on-premises AD DS directory in domain\accountname format.
```

2020-11-28 07:50 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
> +For your reference, below is a comprehensive list of the AD DS devices, containers and permissions required for device write-back and authentication to work:
```suggestion
For your reference, below is a comprehensive list of the AD DS devices, containers, and permissions required for device write-back and authentication to work:
```

2020-11-28 07:56 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
> +Using an elevated PowerShell command window, configure AD FS policy by executing the following command
```suggestion
Using an elevated PowerShell command window, configure AD FS policy by executing the following command:
```

2020-11-28 07:59 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
> +The AD FS farm used with Windows Hello for Business must be Windows Server 2016 with minimum update of [KB4088889 (14393.2155)](https://support.microsoft.com/help/4088889). If your AD FS farm is not
```suggestion
The AD FS farm used with Windows Hello for Business must be Windows Server 2016 with minimum update of [KB4088889 (14393.2155)](https://support.microsoft.com/help/4088889). If your AD FS farm is not running the AD FS role with updates from Windows Server 2016, then read [Upgrading to AD FS in Windows Server 2016](https://docs.microsoft.com/windows-server/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server-2016).
```

2020-11-28 08:00 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
>  > If your AD FS service is configured to use a GMSA account, enter the account name in the format "domain\accountname$"
```suggestion
> If your AD FS service is configured to use a GMSA account, enter the account name in the format "domain\accountname$".
```

2020-11-28 08:00 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
> +2. Provide your Azure AD global administrator credentials
```suggestion
2. Provide your Azure AD global administrator credentials.
```

2020-11-28 08:01 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
> +3. Run the following PowerShell command
```suggestion
3. Run the following PowerShell command:
```

2020-11-28 08:01 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
> +Where the [AD connector account name] is the name of the account you configured in Azure AD Connect when adding your on-premises AD DS directory in domain\accountname format
```suggestion
Where the [AD connector account name] is the name of the account you configured in Azure AD Connect when adding your on-premises AD DS directory in domain\accountname format.
```

2020-11-28 08:02 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
> +The above command creates the following objects for device write back to AD DS, if they do not exist already, and allows access to the specified AD connector account name
```suggestion
The above command creates the following objects for device write back to AD DS, if they do not exist already, and allows access to the specified AD connector account name:
```

2020-11-28 08:03 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
> +If you have not done so before, enable device write back in Azure AD Connect by running the wizard a second time and selecting **"Customize Synchronization Options"**, then checking the box for devic
```suggestion
If you have not done so before, enable device write back in Azure AD Connect by running the wizard a second time and selecting **"Customize Synchronization Options"**, then checking the box for device write back and selecting the forest in which you have run the above cmdlets.
```

2020-11-28 08:12 UTC, JohanFreelancer9 requested changes
Copy review - a few minor additional edits, please.

2020-11-28 09:21 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
> +To do this, follow the **Configure device settings** steps under [Setting up Azure AD Join in your organization](https://azure.microsoft.com/documentation/articles/active-directory-azureadjoin-setup/
Good point. Thank you.

2020-11-28 09:23 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
>  Sign-in to the domain controller hosting the schema master operational role using enterprise administrator equivalent credentials.
Well spotted. Thank you.

2020-11-28 09:26 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
>  ### Setup Active Directory Federation Services
Good job. Well spotted.

2020-11-28 09:27 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
>  If you are new to AD FS and federation services, you should review [Understanding Key AD FS Concepts](https://docs.microsoft.com/windows-server/identity/ad-fs/technical-reference/understanding-key-ad
Nice. Well spotted. Thank you.

2020-11-28 09:29 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
> +For your reference, below is a comprehensive list of the AD DS devices, containers and permissions required for device write-back and authentication to work:
Thank you. Fair point.

2020-11-28 09:36 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
> +Using an elevated PowerShell command window, configure AD FS policy by executing the following command
Well spotted. Thank you.

2020-11-28 09:37 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
> +The AD FS farm used with Windows Hello for Business must be Windows Server 2016 with minimum update of [KB4088889 (14393.2155)](https://support.microsoft.com/help/4088889). If your AD FS farm is not
Good point. Well spotted.

2020-11-28 09:40 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
>  > If your AD FS service is configured to use a GMSA account, enter the account name in the format "domain\accountname$"
Good point. Well spotted.

2020-11-28 09:42 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
> +2. Provide your Azure AD global administrator credentials
Fair point. Good decision.

2020-11-28 09:43 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
> +3. Run the following PowerShell command
Nice. Well spotted.

2020-11-28 09:46 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
> +Where the [AD connector account name] is the name of the account you configured in Azure AD Connect when adding your on-premises AD DS directory in domain\accountname format
Good point. Very well spotted. It feels like that sentence should have been enclosed in parentheses and be a finalizing item in an already existing sentence before the code example.

2020-11-28 09:50 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-devreg.md
> +If you have not done so before, enable device write back in Azure AD Connect by running the wizard a second time and selecting **"Customize Synchronization Options"**, then checking the box for devic
Well spotted. Thank you.

2020-11-28 09:53 UTC, illfated commented
@JohanFreelancer9 : Very good job. Well spotted. Thank you for pointing out all those missing punctuation items in this document. Feels almost like I did not make much of an effort to check the document for proper punctuation.

2020-11-28 09:53 UTC, illfated commented
#sign-off

2020-11-29 03:35 UTC, JohanFreelancer9 approved these changes
Thank you @illfated - looks good.

2020-11-29 09:33 UTC, illfated commented
Thank **you**. Your confirmation is very welcome.

2020-12-10 03:28 UTC, illfated commented
I recommend using **Hide whitespace changes** to reduce the amount of lines for review, but more importantly, to align the actual changes better:
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8686/files?diff=unified&w=1 

(Some of the whitespace changes are causing disorder in the appearance of factual changes, making it look like I have altered some text content instead of only typo corrections.)

2020-12-19 11:40 UTC, illfated commented
Sorry for the disruption. I made some mistakes during branch clean-up in my repo.

2021-01-11 23:48 UTC, illfated commented
@e0i : May I ask you to please check if this PR has been dislodged from any automatic listing for PRs to be followed up, in case my unwanted closure and re-opening caused a technical problem?

2021-06-06 20:58 UTC, closed without merging