Corrected reference to Azure Active Directory DC
MicrosoftDocs/windows-itpro-docs pull request #8699
Opened 2020-11-23 20:27 UTC by SteveBurkettNZ

Corrected incorrect reference to Azure Active Directory DC, slight rephrase of sentence, formatting fixes.

2020-11-30 21:10 UTC, illfated approved these changes
Looks good to me.

2020-12-01 08:33 UTC, schmurky requested changes

2020-12-01 08:33 UTC, schmurky commented on windows/security/threat-protection/windows-firewall/best-practices-configuring.md
> +1.  **Domain profile**: Used for networks where there is a system of account authentication against an Active Directory Directory Services domain controller, such as a corporate network.
an Active Directory **Domain** Services controller

2020-12-01 08:56 UTC, illfated commented on windows/security/threat-protection/windows-firewall/best-practices-configuring.md
> +1.  **Domain profile**: Used for networks where there is a system of account authentication against an Active Directory Directory Services domain controller, such as a corporate network.
Fair point, it does not exactly sit well on the tongue to read it out loud using "Directory Directory", but on the other hand, "Domain Services domain controller" does not seem correct either.

2020-12-14 15:03 UTC, e0i commented
Please feel free to re-open this PR to confirm and apply the requested changes. Thank you. @SteveBurkettNZ

2020-12-14 15:03 UTC, closed without merging