updated steps for Intune
MicrosoftDocs/windows-itpro-docs pull request #8732
Opened 2020-12-01 12:44 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8706

2020-12-01 12:45 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

2020-12-01 18:18 UTC, illfated commented
(Note to self: this page really needs a MarkDown code block fence format _cleanup_. #MD-cleanup)

2020-12-02 06:17 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md
> +13. Refer to the "Configure Certificate Templates on NDES" task for how you configured the **AADJ WHFB Authentication** certificate template in the registry. Select the appropriate combination of key
```suggestion
13. Refer to the "Configure Certificate Templates on NDES" task for how you configured the **AADJ WHFB Authentication** certificate template in the registry. Select the appropriate combination of key usages from the **Key Usages** list that map to the configured NDES template in the registry. In this example, the **AADJ WHFB Authentication** certificate template was added to the **SignatureTemplate** registry value name. The **Key usage** that maps to that registry value name is **Digital Signature**.
```

2020-12-02 06:21 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md
> +4. Select **Properties**, click **Edit** next to the **Assignments** section.
```suggestion
4. Select **Properties** and click **Edit** next to the **Assignments** section.
```

2020-12-02 06:31 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md
> +19. Click **Next** several times to skip the **Scope tags**, **Assignments** and **Applicability Rules** steps of the wizard and click **Create**.
```suggestion
19. Click **Next** several times to skip the **Scope tags**, **Assignments**, and **Applicability Rules** steps of the wizard and click **Create**.
```

2020-12-02 06:31 UTC, JohanFreelancer9 requested changes
Copy review - three minor changes.

2020-12-02 17:23 UTC, mapalko approved these changes

2020-12-02 17:51 UTC, illfated approved these changes

2020-12-14 20:13 UTC, merged

2020-12-27 23:21 UTC, illfated commented
(ref. issue ticket #8548 **Error 500 if no Value for UPN is given**)