Changes in Deployment steps for GA
MicrosoftDocs/windows-itpro-docs pull request #8733
Opened 2020-12-01 16:09 UTC by sunasing

2020-12-01 17:58 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/ios-install.md
> +This topic describes deploying Defender for Endpoint for iOS on Intune Company Portal enrolled devices. For more information about Intune device enrollment, see [Enroll your device](https://docs.micr
Nitpick: sentence ending period dot.
```suggestion
This topic describes deploying Defender for Endpoint for iOS on Intune Company Portal enrolled devices. For more information about Intune device enrollment, see [Enroll your device](https://docs.microsoft.com/mem/intune/enrollment/ios-enroll).
```

2020-12-01 18:00 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/ios-install.md
> +    >The selected user group should consist of Intune enrolled users.
May I suggest formatting consistency/MarkDown indent marker compatibility spacing?
```suggestion
    > [!NOTE]
    > The selected user group should consist of Intune enrolled users.
```

2020-12-01 18:01 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/ios-install.md
> +    >This app configuration policy for supervised devices is applicable only to managed devices and should be targeted for all managed iOS devices as a best practice.
(as above)
```suggestion
    > [!NOTE]
    > This app configuration policy for supervised devices is applicable only to managed devices and should be targeted for all managed iOS devices as a best practice.
```

2020-12-01 18:02 UTC, illfated approved these changes
Fresh new images, nice. Only cosmetic details to be edited from my perspective.

2020-12-02 09:06 UTC, illfated commented
Oh. I noticed a couple of grammatical details too. May I add those as well?

2020-12-02 09:07 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/ios-install.md
> +1. On the Add app page, click on **Search the App Store** and type **Microsoft Defender ATP** in the search bar. On the search results section, click on *Microsoft Defender ATP* and click **Select**.
minor detail, "on" vs. "in"
```suggestion
1. On the Add app page, click on **Search the App Store** and type **Microsoft Defender ATP** in the search bar. In the search results section, click on *Microsoft Defender ATP* and click **Select**.
```

2020-12-02 09:09 UTC, sunasing commented
> Oh. I noticed a couple of grammatical details too. May I add those as well?

Yes please

2020-12-02 09:10 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/ios-install.md
> +1. In the *Review + Create* section, verify that all the information entered is correct and then select **Create**. In a few moments, the Defender for Endpoint app would be created successfully, and
```suggestion
1. In the *Review + Create* section, verify that all the information entered is correct and then select **Create**. In a few moments, the Defender for Endpoint app should be created successfully, and a notification should show up at the top-right corner of the page.
```

2020-12-02 09:18 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/ios-configure-features.md
> +Phishing websites impersonate trustworthy websites for the purpose of obtaining your personal or financial information. Visit [report unsafe site](https://www.microsoft.com/wdsi/filesubmission/exploi
```suggestion
Phishing websites impersonate trustworthy websites for the purpose of obtaining your personal or financial information. Visit the [report unsafe site](https://www.microsoft.com/wdsi/filesubmission/exploitguard/networkprotection) page if you want to report a website that could be a phishing site.
```

2020-12-02 09:20 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/ios-install.md
> +The Microsoft Defender for Endpoint for iOS app has specialized ability on supervised iOS/iPadOS devices given the increased management capabilities provided by the platform on these types of devices
```suggestion
The Microsoft Defender for Endpoint for iOS app has specialized ability on supervised iOS/iPadOS devices, given the increased management capabilities provided by the platform on these types of devices. To take advantage of these capabilities, the Defender for Endpoint app needs to know if a device is in Supervised mode.
```

2020-12-02 09:21 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/ios-install.md
> +Intune allows you to configure the Defender for iOS app through a App Configuration policy.
```suggestion
Intune allows you to configure the Defender for iOS app through an App Configuration policy.
```

2020-12-02 09:22 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/ios-install.md
> +    - Value type: Sting
```suggestion
    - Value type: String
```

2020-12-02 09:24 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/ios-install.md
> +   When deploying to user groups, a user must sign-in on a device before the policy applies.
```suggestion
   When deploying to user groups, a user must sign in to a device before the policy applies.
```

2020-12-02 09:28 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-ios.md
> +**Microsoft Defender for Endpoint for iOS** will offer protection against phishing and unsafe network connections from websites, emails, and apps. All alerts will be available through a single pane o
Is this phrasing correct - "pane of glass" - describing pages or app sections in Microsoft Defender Security Center?

2020-12-02 09:30 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-ios.md
> +    center](https://go.microsoft.com/fwlink/?linkid=2109431), to deploy the app to enrolled user groups in your organization
Line break/NewLine removal:
```suggestion
- Access to [Microsoft Endpoint Manager admin center](https://go.microsoft.com/fwlink/?linkid=2109431), to deploy the app to enrolled user groups in your organization
```

2020-12-02 16:58 UTC, sunasing commented on windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-ios.md
> +**Microsoft Defender for Endpoint for iOS** will offer protection against phishing and unsafe network connections from websites, emails, and apps. All alerts will be available through a single pane o
Yes thats how they refer it.

Thanks for other suggestions. Some of them were so silly on my part.

2020-12-02 17:55 UTC, illfated commented
Just to be on the safe side, I suggest having a copy review by @JohanFreelancer9 (in case I missed some sentence details not obvious enough to me).

2020-12-03 06:59 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/ios-configure-features.md
>  To protect corporate data from being accessed on jailbroken iOS devices, we recommend that you setup the following compliance policy on Intune.
```suggestion
To protect corporate data from being accessed on jailbroken iOS devices, we recommend that you set up the following compliance policy on Intune.
```

2020-12-03 07:00 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/ios-configure-features.md
> +Phishing websites impersonate trustworthy websites for the purpose of obtaining your personal or financial information. Visit the [report unsafe site](https://www.microsoft.com/wdsi/filesubmission/ex
```suggestion
Phishing websites impersonate trustworthy websites for the purpose of obtaining your personal or financial information. Visit the [Provide feedback about network protection](https://www.microsoft.com/wdsi/filesubmission/exploitguard/networkprotection) page if you want to report a website that could be a phishing site.
```

2020-12-03 07:03 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/ios-install.md
> +This topic describes deploying Defender for Endpoint for iOS on Intune Company Portal enrolled devices. For more information about Intune device enrollment, see [Enroll your device](https://docs.micr
```suggestion
This topic describes deploying Defender for Endpoint for iOS on Intune Company Portal enrolled devices. For more information about Intune device enrollment, see [Enroll iOS/iPadOS devices in Intune](https://docs.microsoft.com/mem/intune/enrollment/ios-enroll).
```

2020-12-03 07:06 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/ios-install.md
> +- Ensure iOS enrollment is done for your users. Users need to have Defender for Endpoint license assigned in order to use Defender for Endpoint for iOS. Refer [Assign licenses to users](https://docs.
```suggestion
- Ensure iOS enrollment is done for your users. Users need to have a Defender for Endpoint license assigned in order to use Defender for Endpoint for iOS. Refer to [Assign licenses to users](https://docs.microsoft.com/azure/active-directory/users-groups-roles/licensing-groups-assign) for instructions on how to assign licenses.
```

2020-12-03 07:07 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/ios-install.md
> +> **Microsoft Defender ATP (Microsoft Defender for Endpoint) for iOS is now available on [Apple App Store](https://aka.ms/mdatpiosappstore).**
```suggestion
> Microsoft Defender ATP (Microsoft Defender for Endpoint) for iOS is now available on the [Apple App Store](https://aka.ms/mdatpiosappstore).
```

2020-12-03 07:08 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/ios-install.md
> +1. In [Microsoft Endpoint manager admin center](https://go.microsoft.com/fwlink/?linkid=2109431), go to **Apps** -> **iOS/iPadOS** -> **Add** -> **iOS store app** and click Select.
```suggestion
1. In [Microsoft Endpoint manager admin center](https://go.microsoft.com/fwlink/?linkid=2109431), go to **Apps** -> **iOS/iPadOS** -> **Add** -> **iOS store app** and click **Select**.
```

2020-12-03 07:24 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/ios-install.md
> +    - In the **Assignment** section, select the device group you want to apply this profile to. As a best practice, this should be applied for all managed iOS devices. Click **Next**
```suggestion
    - In the **Assignment** section, select the device group to which you want to apply this profile. As a best practice, this should be applied to all managed iOS devices. Click **Next**.
```

2020-12-03 07:33 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-ios.md
> +- Microsoft Defender for Endpoint license assigned to the end user(s) of the app. See [Microsoft Defender for Endpoint licensing requirements](https://docs.microsoft.com/windows/security/threat-prote
```suggestion
- Microsoft Defender for Endpoint license assigned to the end user(s) of the app. See [Microsoft Defender for Endpoint licensing requirements](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements#licensing-requirements).
```

2020-12-03 07:39 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-ios.md
> +- Access to [Microsoft Endpoint Manager admin center](https://go.microsoft.com/fwlink/?linkid=2109431), to deploy the app to enrolled user groups in your organization
```suggestion
- Access to [Microsoft Endpoint Manager admin center](https://go.microsoft.com/fwlink/?linkid=2109431), to deploy the app to enrolled user groups in your organization.
```

2020-12-03 07:40 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-ios.md
> +- Device is enrolled with Intune Company Portal [app](https://apps.apple.com/us/app/intune-company-portal/id719171358)
```suggestion
- Device is enrolled with the [Intune Company Portalapp](https://apps.apple.com/us/app/intune-company-portal/id719171358).
```

2020-12-03 07:41 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-ios.md
> +- Stay informed about upcoming releases by visiting our [blog](https://techcommunity.microsoft.com/t5/microsoft-defender-atp/bg-p/MicrosoftDefenderATPBlog/label-name/iOS)
```suggestion
- Stay informed about upcoming releases by visiting our [blog](https://techcommunity.microsoft.com/t5/microsoft-defender-atp/bg-p/MicrosoftDefenderATPBlog/label-name/iOS).
```

2020-12-03 07:44 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/ios-install.md
> +The Microsoft Defender for Endpoint for iOS app has specialized ability on supervised iOS/iPadOS devices, given the increased management capabilities provided by the platform on these types of device
```suggestion
The Microsoft Defender for Endpoint for iOS app has specialized ability on supervised iOS/iPadOS devices, given the increased management capabilities provided by the platform on these types of devices. To take advantage of these capabilities, the Defender for Endpoint app needs to know if a device is in Supervised Mode.
```

2020-12-03 07:51 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-ios.md
> +    - Intune Company Portal app can be downloaded from [Apple App Store](https://apps.apple.com/us/app/intune-company-portal/id719171358).
```suggestion
    - Intune Company Portal app can be downloaded from the [Apple App Store](https://apps.apple.com/us/app/intune-company-portal/id719171358).
```

2020-12-03 07:55 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-03 20:31 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-ios.md
> +- Device is enrolled with Intune Company Portal [app](https://apps.apple.com/us/app/intune-company-portal/id719171358)
@JohanFreelancer9 : Are you sure about this? The word "Portalapp" looks unusual to me, but maybe I am too familiar with British English and the norm of not combining words.

2020-12-03 20:33 UTC, illfated commented
Thank you for the effort. Good job. I notice I missed a lot of details.

2020-12-04 09:28 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-ios.md
> +- Device is enrolled with Intune Company Portal [app](https://apps.apple.com/us/app/intune-company-portal/id719171358)
@illfated - my bad. Thank you for noticing.

2020-12-04 09:28 UTC, JohanFreelancer9 approved these changes

2020-12-04 20:21 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-ios.md
> +**Microsoft Defender for Endpoint for iOS** will offer protection against phishing and unsafe network connections from websites, emails, and apps. All alerts will be available through a single pane o
That is very OK. Don't worry. I just wanted to make sure I hadn't missed something and needed to confirm this phrase. 🙂

2020-12-04 20:23 UTC, illfated approved these changes

2020-12-04 20:24 UTC, illfated commented
#sign-off

2020-12-07 15:05 UTC, sunasing commented
#sign-off

2020-12-07 15:27 UTC, shadows911 commented
> #sign-off

not so good

2020-12-07 16:06 UTC, merged