Update android-intune.md
MicrosoftDocs/windows-itpro-docs pull request #8766
Opened 2020-12-06 13:19 UTC by shthota77

2020-12-06 22:31 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/android-intune.md
> +2. On the device, you can validate the onboarding status by going to the **work profile**. Confirm that Defender for Endpoint is available and that you are enrolled to **Personally-owned devices with
Readability details, although I would like to see a better phrasing.
```suggestion
2. On the device, you can validate the onboarding status by going to the **work profile**. Confirm that Defender for Endpoint is available and that you are enrolled to the **Personally-owned devices with work profile**.  If you are enrolled to a **Corporate-owned, fully managed user device**, you will have a single profile on the device where you can confirm that Defender for Endpoint is available.
```
@JohanFreelancer9 : Do you have an improvement suggestion for the beginning of this paragraph?

2020-12-07 03:56 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/android-intune.md
> +2. On the device, you can validate the onboarding status by going to the **work profile**. Confirm that Defender for Endpoint is available and that you are enrolled to **Personally-owned devices with
I would leave it as is to keep the context.

2020-12-07 03:57 UTC, JohanFreelancer9 requested changes
Copy review - only @illfated's suggestions.

2020-12-07 06:28 UTC, JohanFreelancer9 approved these changes

2020-12-07 16:08 UTC, merged