add link about AD config for BitLocker
MicrosoftDocs/windows-itpro-docs pull request #8772
Opened 2020-12-07 12:49 UTC by VLG17

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8621

2020-12-09 14:34 UTC, nam31 commented
@JohanFreelancer9, can you please do the copy editor review for this PR. Thank you

2020-12-09 14:39 UTC, illfated commented on windows/security/information-protection/bitlocker/bitlocker-group-policy-settings.md
> +> For more details about Active Directory configuration related to BitLocker enablement, please check [this article](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/set-up-mdt-
The target page is language agnostic, handles other languages quite OK, so we don't need to specify /en-us/ here:
```suggestion
> For more details about Active Directory configuration related to BitLocker enablement, please check [this article](https://docs.microsoft.com/windows/deployment/deploy-windows-mdt/set-up-mdt-for-bitlocker).
```

2020-12-10 03:58 UTC, JohanFreelancer9 commented on windows/security/information-protection/bitlocker/bitlocker-group-policy-settings.md
> +> For more details about Active Directory configuration related to BitLocker enablement, please check [this article](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/set-up-mdt-
```suggestion
> For more details about Active Directory configuration related to BitLocker enablement, please see [Set up MDT for BitLocker](https://docs.microsoft.com/windows/deployment/deploy-windows-mdt/set-up-mdt-for-bitlocker).
```

2020-12-10 03:59 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-10 04:11 UTC, illfated commented on windows/security/information-protection/bitlocker/bitlocker-group-policy-settings.md
> +> For more details about Active Directory configuration related to BitLocker enablement, please check [this article](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/set-up-mdt-
Ah, right I notice a better suggestion has been made below. I defer to the more experienced suggestion.

2020-12-10 08:40 UTC, illfated approved these changes

2020-12-11 05:42 UTC, JohanFreelancer9 approved these changes

2020-12-14 23:20 UTC, merged