Update respond-file-alerts.md
MicrosoftDocs/windows-itpro-docs pull request #8787
Opened 2020-12-10 00:23 UTC by illfated

**Changes proposed:**

- Whitespace standardization and normalization
- MarkDown table extended to simplify future editing
- Use MD H4 instead of **bold** style paragraph headings

**Whitespace changes:**

- remove redundant end-of-line whitespace
- whitespace indents: use 3 instead of 4 blank spaces
- add MD indent marker (`> `) compatibility spacing

**Ticket / PR reference or closure:**

Ref. my own comment in PR #8726

2020-12-10 00:25 UTC, illfated reviewed
To skip the trivial whitespace changes (shorten the source page review length) and view the more effective changes in this PR, use the **Hide whitespace changes** feature:
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8787/files?diff=unified&w=1

2020-12-10 00:27 UTC, illfated commented
#sign-off

2020-12-10 18:14 UTC, illfated commented
Thanks. I guess I missed that one.

2020-12-10 18:18 UTC, illfated commented
I did not think much of it at first, but now, using the **Rich Diff view** (https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8787/files?short_path=d0d04ac#diff-d0d04acb98d10029b8ed98c7bffe4302a644fe5f84343094c5b549cd7064b595), I notice that the H4 headings seem to be more contrasted against the white background compared to the previous \*\***bold**\*\* style headings.

2020-12-14 15:46 UTC, e0i commented
cc @JohanFreelancer9 for copy editing review. Thanks.

2020-12-14 21:40 UTC, illfated commented
Feel free to review the expanded view of the file, if you like. I can always add changes, even though you may not be able to post a comment on lines outside of the current changes +/- 3 lines.

2020-12-15 06:54 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/respond-file-alerts.md
>  > [!Important]
```suggestion
> [!IMPORTANT]
```

2020-12-15 07:04 UTC, JohanFreelancer9 requested changes
Copy review - one minor additional edit for the sake of consistency.

2020-12-15 12:58 UTC, illfated commented
I agree. I will merge the suggestion.

2020-12-16 07:14 UTC, JohanFreelancer9 approved these changes

2020-12-16 07:29 UTC, illfated commented
#sign-off

2020-12-19 11:37 UTC, illfated commented
I made some mistakes while trying to clean up my branches. Yesterday was particularly difficult for me, I did not pay attention closely enough.

2021-01-04 20:28 UTC, merged