Addition to information
MicrosoftDocs/windows-itpro-docs pull request #8800
Opened 2020-12-11 18:11 UTC by joinimran

As we can also configure credential guard using account protection profile in endpoint security. Added link to that article as well. 

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8711

2020-12-11 18:12 UTC, joinimran commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-12-11 19:11 UTC, illfated commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> +> You can also configure Credential Guard using account protection profile in Endpoint Security. See [https://docs.microsoft.com/mem/intune/protect/endpoint-security-account-protection-profile-settin
You seem to have reversed the order of URL and its link text description. Let me reorder:
```suggestion
> You can also configure Credential Guard using account protection profile in Endpoint Security. See [Account protection policy settings for endpoint security in Intune](https://docs.microsoft.com/mem/intune/protect/endpoint-security-account-protection-profile-settings).
```
Also note: I copied the verbatim page title text, including the capitalized first word "Account" .

2020-12-11 19:11 UTC, illfated commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> +> You can also configure Credential Guard using account protection profile in Endpoint Security. See [https://docs.microsoft.com/mem/intune/protect/endpoint-security-account-protection-profile-settin
(Maybe JohanFreelancer9 would like to offer an improvement to the sentence, I don't know yet.)

2020-12-12 05:02 UTC, JohanFreelancer9 commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> +> You can also configure Credential Guard using account protection profile in Endpoint Security. See [https://docs.microsoft.com/mem/intune/protect/endpoint-security-account-protection-profile-settin
```suggestion
> You can also configure Credential Guard using an account protection profile in endpoint security. See [Account protection policy settings for endpoint security in Intune](https://docs.microsoft.com/mem/intune/protect/endpoint-security-account-protection-profile-settings).
```

2020-12-12 05:02 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-14 15:05 UTC, JohanFreelancer9 approved these changes

2020-12-14 21:41 UTC, illfated approved these changes

2021-02-18 10:58 UTC, nam31 commented
@DulceMontemayor, PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-07 22:10 UTC, merged