Joknierm patch 1
MicrosoftDocs/windows-itpro-docs pull request #8837
Opened 2020-12-17 21:21 UTC by josephknierman

2020-12-17 21:59 UTC, illfated commented on windows/client-management/mdm/assignedaccess-csp.md
> +Example XML configuration for a multi app kiosk.
2 cosmetic/codestyle details here: hyphen between multi and app, colon to indicate that the described item follows:
```suggestion
Example XML configuration for a multi-app kiosk:
```

2020-12-17 22:03 UTC, illfated commented on windows/client-management/mdm/assignedaccess-csp.md
> +Example XML configuration for setting a breakout sequence to be Shift+Windows on a Microsoft Edge kiosk. Note BreakoutSequence can be applied to any kiosk type not just an Edge kiosk.
Depending on how important the note is, it could be implemented as a colored Note blob. Otherwise, a colon should be used:
```suggestion
Example XML configuration for setting a breakout sequence to be Shift+Windows on a Microsoft Edge kiosk. Note: **BreakoutSequence** can be applied to any kiosk type, not just an Edge kiosk.
```
Also: it is preferable to use some form of highlighting (**bold** or _italics_), or just code marking ( ` ` ) for a keyword.
Added a natural readability comma.

2020-12-17 22:04 UTC, illfated commented on windows/client-management/mdm/assignedaccess-ddf.md
> + ---
Unwanted space, the metadata is always separated by 3 un-indented hyphens:
```suggestion
---
```

2020-12-17 22:06 UTC, illfated commented on windows/client-management/mdm/assignedaccess-ddf.md
> +
Cosmetic/codestyle: not sure if this extra blank line is needed. Please consider its necessity.

2020-12-17 22:11 UTC, illfated commented
I don't know XML well enough to offer any advice on the correctness of it, but I can (and will) offer suggestions for regular text writing and codestyle.

Feel free to ask questions, if you think I am overstepping any boundaries.

2020-12-18 19:40 UTC, josephknierman commented on windows/client-management/mdm/assignedaccess-ddf.md
> +
extra blank line was not needed. it has been removed.

2020-12-18 19:40 UTC, josephknierman commented on windows/client-management/mdm/assignedaccess-ddf.md
> + ---
removed space

2020-12-18 19:42 UTC, josephknierman commented on windows/client-management/mdm/assignedaccess-csp.md
> +Example XML configuration for setting a breakout sequence to be Shift+Windows on a Microsoft Edge kiosk. Note BreakoutSequence can be applied to any kiosk type not just an Edge kiosk.
Added note blob, bolded the xml keyword

2020-12-18 19:43 UTC, josephknierman commented on windows/client-management/mdm/assignedaccess-csp.md
> +Example XML configuration for a multi app kiosk.
added hyphen and colon

2020-12-19 10:51 UTC, illfated commented on windows/client-management/mdm/assignedaccess-csp.md
> +**BreakoutSequence** can be applied to any kiosk type, not just an Edge kiosk.
To make sure this Note blob is kept safe from formatting on previous lines and also kept from interfering with succeeding lines, the recommended format looks like this:
```suggestion

> [!NOTE]
> **BreakoutSequence** can be applied to any kiosk type, not just an Edge kiosk.

```
Notice that I have put the Note blob keyword "NOTE" in all caps, which is the prevalent format of MarkDown Note blob keywords here in the MicrosoftDocs repositories.

2020-12-19 10:57 UTC, illfated commented
Just so you know: One of my pet peeves is the lack of MarkDown indent marker compatibility spacing, 1 space between the indent marker (`> `) and its following text. Don't feel bothered if I pick on those, it is more like my only practical alternative to the inconvenience of me making a a Pull Request to have all of them updated at once, which would involve too many topic sections and too many document authors.

2020-12-19 11:01 UTC, illfated commented
Otherwise, unless you know it needs to have more content added, I think this PR is ready to be changed from its "Draft" state to "Ready for review".

2021-01-14 18:15 UTC, lilyhou commented on windows/client-management/mdm/assignedaccess-csp.md
> +Updated in Windows 10, version 1909. Added Microsoft Edge kiosk mode. This allows Microsoft Edge to be the specified kiosk application. For details about configuring Microsoft Edge kiosk mode, see [C
- When the OS update is released with the DCR change in, we should add a note here and link it to the update KB article, so customers know which update they need to apply.
- Shall we say "Added Microsoft Edge kiosk mode support"?
- Can we add some more descriptions here for the breakout key sequence customization, e.g. the format it accepts, a few samples?

2021-01-14 18:29 UTC, lilyhou commented on windows/client-management/mdm/assignedaccess-csp.md
> +Below schema is for AssignedAccess Configuration up to Windows 10 1909 release.
Shall we say "up to Windows 10 20H2 release" as it is the latest Windows 10 release in the market? https://docs.microsoft.com/en-us/windows/release-information/

2021-01-14 18:35 UTC, lilyhou commented on windows/client-management/mdm/assignedaccess-csp.md
> +Schema for features introduced in Windows 10, version 1909.
Can we describe the features? Something like "Here is the schema for features introduced in Windows 10, version 1909 to support Microsoft Edge kiosk mode and breakout key sequence customization.

2021-01-14 19:22 UTC, lilyhou commented on windows/client-management/mdm/assignedaccess-csp.md
> +Example XML configuration for a Microsoft Edge kiosk. This Edge kiosk s configure to launch www.bing.com on startup.
The 2nd sentence seems incomplete. Shall we say "This Microsoft Edge kiosk is configured to launch www.bing.com on startup in a public browsing mode", and also update the below two XML samples to include the kiosk mode type command line.

2021-01-14 19:51 UTC, illfated commented on windows/client-management/mdm/assignedaccess-csp.md
> +Example XML configuration for a Microsoft Edge kiosk. This Edge kiosk s configure to launch www.bing.com on startup.
Sounds good to me. Here is a suggestion, in case you prefer to use the "commit suggestion" feature to add more material:
```suggestion
Example XML configuration for a Microsoft Edge kiosk. This Microsoft Edge kiosk is configured to launch www.bing.com on startup in a public browsing mode.
```

2021-01-14 19:55 UTC, illfated commented on windows/client-management/mdm/assignedaccess-csp.md
> +Below schema is for AssignedAccess Configuration up to Windows 10 1909 release.
Maybe that is correct, I haven't checked yet. Here is a suggestion you can use to commit the change (unless you want to edit the file manually to add more material):
```suggestion
The schema below is for AssignedAccess Configuration up to Windows 10 20H2 release.
```
I also find it more natural to say "The schema below" than "Below schema", but that could be caused by being used to European/British English usage.

2021-01-25 23:32 UTC, lilyhou commented on windows/configuration/guidelines-for-assigned-access-app.md
> +There is currently no GUI for customizing the breakout sequence, so it would need to be specified in a provision method where an XML format is used like MDM.
We might want to call out Windows Settings here "There is currently no UI for customizing the breakout sequence in Windows Settings"

2021-01-25 23:32 UTC, lilyhou commented on windows/configuration/kiosk-xml.md
>  ## [Preview] Global Profile Sample XML
We should remove [Preview] from this as it has been released in version 2004.

2021-01-25 23:32 UTC, lilyhou commented on windows/configuration/kiosk-xml.md
>  Global Profile is currently supported in Windows 10 Insider Preview (20H1 builds). Global Profile is designed for scenarios where a user does not have a designated profile, yet IT Admin still wants t
Same here, we might want to say "Global profile is currently supported in Windows 10, version 2004 and later".

2021-01-25 23:40 UTC, illfated commented
@josephknierman : Do you have a preferred method of applying the suggested changes? Would you like to apply the changes manually, or do you find it more convenient to have them added inline in the comments above, like I did at the start of your PR?

2021-01-27 08:29 UTC, josephknierman commented on windows/client-management/mdm/assignedaccess-csp.md
> +**BreakoutSequence** can be applied to any kiosk type, not just an Edge kiosk.
Changed note keyword to all caps

2021-01-27 08:39 UTC, josephknierman commented on windows/client-management/mdm/assignedaccess-csp.md
> +Schema for features introduced in Windows 10, version 1909.
Update comment to specify the specific changes present in the schema.

2021-01-27 08:44 UTC, josephknierman commented on windows/configuration/guidelines-for-assigned-access-app.md
> +In Windows 10, Version 1909, Assigned access adds support for the new Microsoft Edge kiosk mode support. [Learn how to deploy Microsoft Edge kiosk mode](https://docs.microsoft.com/en-us/DeployEdge/mi
changed to be consistent with other sections

2021-01-27 08:46 UTC, josephknierman commented on windows/configuration/guidelines-for-assigned-access-app.md
> +In Windows 10, version 1809, Microsoft Edge includes support for legacy kiosk mode. [Learn how to deploy Microsoft Edge kiosk mode.](https://docs.microsoft.com/microsoft-edge/deploy/microsoft-edge-ki
changed to use Microsoft Edge Legacy

2021-01-27 08:49 UTC, josephknierman commented on windows/configuration/guidelines-for-assigned-access-app.md
> +There is currently no GUI for customizing the breakout sequence, so it would need to be specified in a provision method where an XML format is used like MDM.
Added call out to windows settings in this section

2021-01-27 08:52 UTC, josephknierman commented on windows/configuration/kiosk-xml.md
>  ## [Preview] Global Profile Sample XML
removed [Preview]

2021-01-27 08:53 UTC, josephknierman commented on windows/configuration/kiosk-xml.md
>  Global Profile is currently supported in Windows 10 Insider Preview (20H1 builds). Global Profile is designed for scenarios where a user does not have a designated profile, yet IT Admin still wants t
changed to remove preview and have proper version numbers.

2021-01-27 08:54 UTC, josephknierman commented on windows/client-management/mdm/assignedaccess-csp.md
> +Below schema is for AssignedAccess Configuration up to Windows 10 1909 release.
Added recommended changes.

2021-01-27 09:14 UTC, josephknierman commented on windows/client-management/mdm/assignedaccess-csp.md
> +Updated in Windows 10, version 1909. Added Microsoft Edge kiosk mode. This allows Microsoft Edge to be the specified kiosk application. For details about configuring Microsoft Edge kiosk mode, see [C
Changed to "Added Microsoft Edge kiosk mode support". Added in format for breakout sequence with an example if you think more examples in this section would be beneficial let me know.

2021-02-06 10:49 UTC, illfated commented on windows/configuration/guidelines-for-assigned-access-app.md
> +In Windows 10, version 1909, assigned access adds support for the new Microsoft Edge kiosk mode. [Learn how to deploy Microsoft Edge kiosk mode](https://docs.microsoft.com/en-us/DeployEdge/microsoft-
As long as the link target page supports language agnosticism (being language agnostic), MS prefers to use language agnostic links:
```suggestion
In Windows 10, version 1909, assigned access adds support for the new Microsoft Edge kiosk mode. [Learn how to deploy Microsoft Edge kiosk mode](https://docs.microsoft.com/DeployEdge/microsoft-edge-configure-kiosk-mode).
```
(Tested and confirmed that the target page is language agnostic.)

2021-02-06 11:00 UTC, illfated commented on windows/configuration/kiosk-single-app.md
> + The Breakout Sequence of **Ctrl + Alt + Del** is the default, but this can be configured to be a different sequence of keys. The breakout sequence uses the format **modifiers + keys**. An example br
Same here, language agnostic target page, hence the following suggestion:
```suggestion
 The Breakout Sequence of **Ctrl + Alt + Del** is the default, but this can be configured to be a different sequence of keys. The breakout sequence uses the format **modifiers + keys**. An example breakout sequence would look something like **Shift + Alt + a**, where **Shift** and **Alt** are the modifiers and **A** is the key value. [See how this is configured using in xml](https://docs.microsoft.com/windows/configuration/kiosk-xml#microsoft-edge-kiosk-xml-sample).
```
Also, the link description should be either "See how this is configured using XML" or "See how this is configured in XML", removing either "in" or "using" (as well as writing XML in uppercase for the name of the language).

By the way, the current link anchor does not seem to go anywhere, there are no anchors named `#microsoft-edge-kiosk-xml-sample` (as far as I can see in the page source). Did you mean https://docs.microsoft.com/windows/configuration/kiosk-xml#kiosk-only-sample-xml ?

2021-02-10 06:28 UTC, JohanFreelancer9 commented on windows/client-management/mdm/assignedaccess-csp.md
> +The schema below is for AssignedAccess Configuration up to Windows 10 20H2 release.
```suggestion
The following schema is for AssignedAccess Configuration up to Windows 10 20H2 release.
```

2021-02-10 06:37 UTC, JohanFreelancer9 commented on windows/configuration/guidelines-for-assigned-access-app.md
> +Assigned access allows for the specification of a new breakout sequence. A breakout sequence is a keyboard shortcut that stops the kiosk experience and brings the user back to the lock screen. By def
```suggestion
Assigned access allows for the specification of a new breakout sequence. A breakout sequence is a keyboard shortcut that stops the kiosk experience and brings the user back to the lock screen. By default, the breakout sequence is configured to be ctrl+alt+delete, a common Windows keyboard shortcut. It is recommended that this is set to a non-standard Windows shortcut to prevent disruptions in the kiosk experience.
```

2021-02-10 06:39 UTC, JohanFreelancer9 commented on windows/configuration/guidelines-for-assigned-access-app.md
> +There is currently no UI for customizing the breakout sequence in Windows Settings, so it would need to be specified in a provision method where an XML format is used like MDM.
```suggestion
There is currently no user interface for customizing the breakout sequence in Windows settings, so it would need to be specified in a provisioning method where an XML format is used, like MDM.
```

2021-02-10 06:44 UTC, JohanFreelancer9 commented on windows/configuration/kiosk-single-app.md
> + The Breakout Sequence of **Ctrl + Alt + Del** is the default, but this can be configured to be a different sequence of keys. The breakout sequence uses the format **modifiers + keys**. An example br
```suggestion
 The Breakout Sequence of **Ctrl + Alt + Del** is the default, but this can be configured to be a different sequence of keys. The breakout sequence uses the format **modifiers + keys**. An example breakout sequence would look something like **Shift + Alt + a**, where **Shift** and **Alt** are the modifiers and **a** is the key value. [See how this is configured in xml](https://docs.microsoft.com/windows/configuration/kiosk-xml#microsoft-edge-kiosk-xml-sample).
```

2021-02-10 06:45 UTC, JohanFreelancer9 commented on windows/configuration/kiosk-single-app.md
> + The Breakout Sequence of **Ctrl + Alt + Del** is the default, but this can be configured to be a different sequence of keys. The breakout sequence uses the format **modifiers + keys**. An example br
Included @illfated's suggestions and changed "A" to "a" as per the example.

2021-02-10 06:49 UTC, JohanFreelancer9 commented on windows/configuration/kiosk-xml.md
> +Global profile is currently supported in Windows 10, version 2004 and later. Global Profile is designed for scenarios where a user does not have a designated profile, yet IT Admin still wants the use
```suggestion
Global Profile is currently supported in Windows 10, version 2004 and later. Global Profile is designed for scenarios where a user does not have a designated profile, yet IT Admin still wants the user to run in lockdown mode, or is used as mitigation when a profile cannot be determined for a user.
```

2021-02-10 06:52 UTC, JohanFreelancer9 commented on windows/configuration/kiosk-xml.md
>  This sample demonstrates that only a global profile is used, no active user configured. Global profile will be applied when every non-admin account logs in
```suggestion
This sample demonstrates that only a global profile is used, with no active user configured. Global Profile will be applied when every non-admin account logs in 
```

2021-02-10 06:54 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-05 20:27 UTC, josephknierman commented on windows/configuration/guidelines-for-assigned-access-app.md
> +In Windows 10, version 1909, assigned access adds support for the new Microsoft Edge kiosk mode. [Learn how to deploy Microsoft Edge kiosk mode](https://docs.microsoft.com/en-us/DeployEdge/microsoft-
Fixed link. will be seen in the next iteration

2021-03-05 20:30 UTC, josephknierman commented on windows/configuration/kiosk-single-app.md
> + The Breakout Sequence of **Ctrl + Alt + Del** is the default, but this can be configured to be a different sequence of keys. The breakout sequence uses the format **modifiers + keys**. An example br
fixed phrasing to be "See how this is configured in XML". The link to microsoft-edge-kiosk-xml-sample should exist in this PR. check the changes to kiosk-xml.md

2021-03-05 20:32 UTC, josephknierman commented on windows/configuration/guidelines-for-assigned-access-app.md
> +Assigned access allows for the specification of a new breakout sequence. A breakout sequence is a keyboard shortcut that stops the kiosk experience and brings the user back to the lock screen. By def
fixed to be "Windows"

2021-03-05 20:33 UTC, josephknierman commented on windows/configuration/guidelines-for-assigned-access-app.md
> +There is currently no UI for customizing the breakout sequence in Windows Settings, so it would need to be specified in a provision method where an XML format is used like MDM.
fixed

2021-03-05 20:35 UTC, josephknierman commented on windows/configuration/kiosk-single-app.md
> + The Breakout Sequence of **Ctrl + Alt + Del** is the default, but this can be configured to be a different sequence of keys. The breakout sequence uses the format **modifiers + keys**. An example br
fixed link, changed to be "a", and removed using from phrase

2021-03-05 20:37 UTC, josephknierman commented on windows/configuration/kiosk-xml.md
> +Global profile is currently supported in Windows 10, version 2004 and later. Global Profile is designed for scenarios where a user does not have a designated profile, yet IT Admin still wants the use
Changed to "Profiles" and added in "it is"

2021-03-05 20:38 UTC, josephknierman commented on windows/configuration/kiosk-xml.md
>  This sample demonstrates that only a global profile is used, no active user configured. Global profile will be applied when every non-admin account logs in
added in changes

2021-03-06 04:21 UTC, JohanFreelancer9 approved these changes

2021-03-06 04:22 UTC, JohanFreelancer9 commented
Thank you @josephknierman.

2021-03-06 08:04 UTC, illfated commented on windows/client-management/mdm/assignedaccess-ddf.md
> +Example: {"User":"domain\\user", "AUMID":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"}.
Redundant end-of-line whitespace (blank):
```suggestion
Example: {"User":"domain\\user", "AUMID":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"}.
```

2021-03-06 08:10 UTC, illfated approved these changes
Looks good to me.

2021-04-16 21:13 UTC, illfated commented
> **This branch has conflicts that must be resolved**
>
> **Conflicting files**
> windows/configuration/guidelines-for-assigned-access-app.md
> windows/configuration/kiosk-single-app.md

I hope you will be able to resolve the file conflict. Feel free to ask for help if it gets too difficult.

2021-06-18 05:00 UTC, JohanFreelancer9 commented on windows/client-management/mdm/assignedaccess-csp.md
> +Updated in Windows 10, version 1909. Added Microsoft Edge kiosk mode support. This allows Microsoft Edge to be the specified kiosk application. For details about configuring Microsoft Edge kiosk mode
```suggestion
Updated in Windows 10, version 1909. Added Microsoft Edge kiosk mode support. This allows Microsoft Edge to be the specified kiosk application. For details about configuring Microsoft Edge kiosk mode, see [Configure a Windows 10 kiosk that runs Microsoft Edge](/DeployEdge/microsoft-edge-configure-kiosk-mode). Windows 10, version 1909 also allows for configuration of the breakout sequence. The breakout sequence specifies the keyboard shortcut that returns a kiosk session to the lock screen. The breakout sequence is defined with the format modifiers + keys. An example breakout sequence would look something like "shift+alt+a", where "shift" and "alt" are the modifiers and "a" is the key.
```

2021-06-18 05:02 UTC, JohanFreelancer9 commented on windows/configuration/guidelines-for-assigned-access-app.md
> +In Windows 10, version 1909, assigned access adds support for the new Microsoft Edge kiosk mode. [Learn how to deploy Microsoft Edge kiosk mode](https://docs.microsoft.com/DeployEdge/microsoft-edge-c
```suggestion
In Windows 10, version 1909, assigned access adds support for the new Microsoft Edge kiosk mode. [Learn how to deploy Microsoft Edge kiosk mode](/DeployEdge/microsoft-edge-configure-kiosk-mode).
```

2021-06-18 05:03 UTC, JohanFreelancer9 commented on windows/configuration/guidelines-for-assigned-access-app.md
> +In Windows 10, version 1809, Microsoft Edge Legacy includes support for kiosk mode. [Learn how to deploy Microsoft Edge kiosk mode.](https://docs.microsoft.com/microsoft-edge/deploy/microsoft-edge-ki
```suggestion
In Windows 10, version 1809, Microsoft Edge Legacy includes support for kiosk mode. [Learn how to deploy Microsoft Edge kiosk mode.](/microsoft-edge/deploy/microsoft-edge-kiosk-mode-deploy)
```

2021-06-18 05:04 UTC, JohanFreelancer9 commented on windows/configuration/kiosk-single-app.md
> + The Breakout Sequence of **Ctrl + Alt + Del** is the default, but this can be configured to be a different sequence of keys. The breakout sequence uses the format **modifiers + keys**. An example br
```suggestion
 The Breakout Sequence of **Ctrl + Alt + Del** is the default, but this can be configured to be a different sequence of keys. The breakout sequence uses the format **modifiers + keys**. An example breakout sequence would look something like **Shift + Alt + a**, where **Shift** and **Alt** are the modifiers and **a** is the key value. [See how this is configured in XML](/windows/configuration/kiosk-xml#microsoft-edge-kiosk-xml-sample).
```

2021-06-18 05:11 UTC, JohanFreelancer9 requested changes
@josephknierman, kindly change all the absolute links to relevant links as indicated as per the latest convention. Many thanks.

2021-09-02 12:11 UTC, e0i commented
> @josephknierman, kindly change all the absolute links to relative links as indicated as per the latest convention. Many thanks.

Can you apply the copy editing suggestions quoted above?

Thank you for your patience with the process.

2021-09-14 22:39 UTC, josephknierman commented on windows/client-management/mdm/assignedaccess-csp.md
> +Updated in Windows 10, version 1909. Added Microsoft Edge kiosk mode support. This allows Microsoft Edge to be the specified kiosk application. For details about configuring Microsoft Edge kiosk mode
made recommended change

2021-09-14 22:39 UTC, josephknierman commented on windows/configuration/guidelines-for-assigned-access-app.md
> +In Windows 10, version 1809, Microsoft Edge Legacy includes support for kiosk mode. [Learn how to deploy Microsoft Edge kiosk mode.](https://docs.microsoft.com/microsoft-edge/deploy/microsoft-edge-ki
made recommended change

2021-09-14 22:39 UTC, josephknierman commented on windows/configuration/guidelines-for-assigned-access-app.md
> +In Windows 10, version 1909, assigned access adds support for the new Microsoft Edge kiosk mode. [Learn how to deploy Microsoft Edge kiosk mode](https://docs.microsoft.com/DeployEdge/microsoft-edge-c
made recommended change

2021-09-14 22:39 UTC, josephknierman commented on windows/configuration/kiosk-single-app.md
> + The Breakout Sequence of **Ctrl + Alt + Del** is the default, but this can be configured to be a different sequence of keys. The breakout sequence uses the format **modifiers + keys**. An example br
made recommended change

2021-09-14 22:51 UTC, josephknierman commented
I think Everything here has been resolved. Could someone with write permissions please merge it.

2021-09-15 05:43 UTC, JohanFreelancer9 approved these changes

2022-05-04 04:13 UTC, aczechowski commented
I fixed some final merge conflicts, and am now merging this PR! Thanks @josephknierman for the contribution, and my apologies for the severe delay. I hope you'll contribute more in the future, when we can get it finalized more quickly.

2022-05-04 04:14 UTC, merged