replaced outdated cmdlet
MicrosoftDocs/windows-itpro-docs pull request #8868
Opened 2020-12-26 17:55 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8821
source: https://devblogs.microsoft.com/scripting/should-i-use-cim-or-wmi-with-windows-powershell/

2020-12-26 17:56 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

2020-12-26 23:07 UTC, illfated approved these changes
Looks good to me. Follows the PowerShell example criteria in https://docs.microsoft.com/powershell/module/cimcmdlets/get-ciminstance#example-3--get-instances-of-a-class-filtered-by-using-a-query .

2020-12-26 23:08 UTC, illfated commented on windows/deployment/deploy-enterprise-licenses.md
>  ```
Cosmetic detail: We could add "PowerShell" syntax highlighting here to make it even more obvious:
```suggestion
```PowerShell
```

2020-12-27 02:50 UTC, JohanFreelancer9 commented on windows/deployment/deploy-enterprise-licenses.md
>  To determine if the computer has a firmware-embedded activation key, type the following command at an elevated Windows PowerShell prompt
```suggestion
To determine if the computer has a firmware-embedded activation key, type the following command at an elevated Windows PowerShell prompt:
```

2020-12-27 02:52 UTC, JohanFreelancer9 requested changes
Copy review -One minor additional edit, please.

2020-12-28 14:35 UTC, illfated approved these changes
Looks very good to me.

2020-12-28 14:36 UTC, illfated commented
#sign-off

2020-12-29 06:57 UTC, JohanFreelancer9 approved these changes

2020-12-30 22:43 UTC, merged