Procedural Changes
MicrosoftDocs/windows-itpro-docs pull request #8901
Opened 2021-01-04 08:03 UTC by joinimran

An unnecessary step was added in the procedure and has been removed. 

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8408

2021-01-04 08:04 UTC, joinimran commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2021-01-04 13:40 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/mac-jamfpro-policies.md
> +4. Select your computer and click the gear icon on the top, select **Computer Management**
```suggestion
4. Select your computer and click the gear icon at the top, then select **Computer Management**.
```

2021-01-04 13:50 UTC, JohanFreelancer9 requested changes
Copy review - it seems that a number of images also needs to be removed now. @joinimran could you please check and confirm?

2021-01-04 14:16 UTC, illfated commented
Rich diff view: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8901/files?short_path=168119a (in case it helps)

2021-01-04 16:12 UTC, joinimran commented
There was one image that needs to be removed and was removed. So we are good with this.

2021-01-04 16:14 UTC, illfated approved these changes
Rich Diff view: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8901/files?short_path=168119a#diff-168119a330b6d49028183467ea1cb90824f5a3c3e27b6243b6ad522447db338d

Looks good to me.

2021-01-05 10:01 UTC, JohanFreelancer9 approved these changes

2021-01-05 10:03 UTC, illfated commented
#sign-off

2021-01-25 21:43 UTC, merged