Addition of Value type supported
MicrosoftDocs/windows-itpro-docs pull request #8903
Opened 2021-01-04 08:49 UTC by joinimran

Added information on value type supported and example.

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8402

2021-01-04 08:49 UTC, joinimran commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2021-01-04 13:29 UTC, JohanFreelancer9 commented on windows/client-management/mdm/policy-csp-timelanguagesettings.md
> +- Name of Standard Time Zone - e.g. Pacific Standard Time, Mountain Standard Time
```suggestion
- Name of Standard Time Zone - for example, Pacific Standard Time, Mountain Standard Time. 
```

2021-01-04 13:30 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-04 16:16 UTC, illfated approved these changes

2021-01-05 09:56 UTC, JohanFreelancer9 approved these changes

2021-01-05 09:56 UTC, illfated commented
#sign-off

2021-02-19 22:15 UTC, merged