Update filesystem-csp.md
MicrosoftDocs/windows-itpro-docs pull request #8908
Opened 2021-01-05 00:24 UTC by illfated

**Description:**

Based on the implied confusion in issue ticket #8387 (**FileSystem CSP examples**), I noticed that the 2 **Note** lines in this document do not adhere to the MS standard of using colored Note blobs. This PR aims to rectify that issue, hoping that this may clarify the following:

> FileSystem CSP is only supported in Windows 10 Mobile.

Thanks to @joinimran for mentioning this fact and for indirectly making me aware of this issue.

**Changes proposed:**

- update/upgrade 2 **Note** lines to use standard Microsoft Note blob formatting
- encapsulate filename `winnt.h` in MD back ticks to display as monospaced font

**Whitespace changes:**

- Remove 10 empty lines at the end of the document
- reduce double blank lines to single (3 occurrences)
- remove all redundant end-of-line blank spaces
- bullet point lists: reduce triple consecutive blank space to single

**Ticket closure or reference:**
Closes #8387

2021-01-05 00:35 UTC, illfated reviewed
- [ ] **Normal source view:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8908/files
- [ ] **Hide whitespace changes:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8908/files?diff=unified&w=1 (shortens the page length to focus on the effective changes, albeit including the reduction of blank lines)
- [ ] **Rich Diff view:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8908/files?diff=unified&w=1&short_path=1f0b8cc (visual preview)

2021-01-05 04:34 UTC, joinimran commented
Great @illfated.

2021-01-06 15:38 UTC, e0i commented
@JohanFreelancer9 Copy editing needed for copy editing suggestions. Thanks :)

2021-01-07 02:14 UTC, JohanFreelancer9 commented on windows/client-management/mdm/filesystem-csp.md
> +- `Type`: The MIME type of the file, which an empty string for directories that are not the root node. The Get command is the only supported command.
```suggestion
- `Type`: The MIME type of the file, which is an empty string for directories that are not the root node. The Get command is the only supported command.
```

2021-01-07 02:22 UTC, JohanFreelancer9 commented on windows/client-management/mdm/filesystem-csp.md
> +- `Format`: The format, which is b64 encoded for binary data is sent over XML, and bin format for binary data sent over wbxml. The Get command is the only supported command.
```suggestion
- `Format`: The format, which is b64 encoded for binary data is sent over XML, and bin format for binary data sent over WBXML. The Get command is the only supported command.
```

2021-01-07 02:29 UTC, JohanFreelancer9 requested changes
Copy review - two additional minor edits, please.

2021-01-07 19:56 UTC, illfated commented
Thank you, good job spotting those details. Both suggestions added to commits.

2021-01-07 19:56 UTC, illfated commented
#sign-off

2021-01-08 02:27 UTC, JohanFreelancer9 approved these changes

2021-01-29 21:43 UTC, merged