Update in the note section
MicrosoftDocs/windows-itpro-docs pull request #8936
Opened 2021-01-09 14:28 UTC by joinimran

As pointed by the user, the note section of the document has been updated to reflect the correct information regarding NTAuth.

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8709

2021-01-09 14:30 UTC, joinimran commented
@JohanFreelancer9 - Please copy review.

2021-01-09 14:32 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki.md
> +To check the NTAuth certificate, you can use the below powershell command
```suggestion
The following PowerShell command can be used to check the NTAuth certificate:
```

2021-01-09 14:33 UTC, joinimran commented
Thanks, @illfated.

2021-01-09 14:35 UTC, illfated approved these changes
The Note blob text content is identical to the paragraph suggested by the issue ticket author, and looks quite good to me. I have simply provided a rephrased sentence pointing to the PowerShell command.

2021-01-09 14:38 UTC, illfated commented
By the way, did you have time to look into whether the last section provided by the issue ticket author is useful or not in this document?

Quote/ref.:
***

### Single-tier PKI
```
└─ Root / Issuing Certificate Authority         <-- This certificate is required in the NTAuth store
  └─ Domain Controller Certificate
```

### Multi-tier PKI
```
└─ Root Certificate Authority
  └─ Intermediate Certificate Authority
    └─ Issuing Certificate Authority            <-- This certificate is required in the NTAuth store
      └─ Domain Controller Certificate
```

2021-01-09 14:46 UTC, joinimran commented
I don't feel that this is the necessary information to be added to the document. If required by the doc author, we will go with this as well.

2021-01-09 14:53 UTC, illfated commented
Very well, that is fair enough for me. Good answer.

2021-01-10 14:20 UTC, JohanFreelancer9 approved these changes

2021-01-10 17:36 UTC, illfated commented
#sign-off

2021-02-18 10:57 UTC, nam31 commented
@mapalko, PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-02-18 20:19 UTC, illfated commented
@nam31 : Just to keep you informed, @mapalko usually does not have merging rights for most documents in this repository, but you are 100% correct in asking for a final review (especially since mapalko is the current document author). The merge will likely have to be performed by the document manager or one of the other MS Docs team members with merging rights. To see who may be available for the merge, besides the doc manager, browse the commit list for this repository, https://github.com/MicrosoftDocs/windows-itpro-docs/commits/public .

2021-02-18 21:34 UTC, mapalko requested changes

2021-02-18 21:34 UTC, mapalko commented on windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki.md
> +> The CA issuing the domain controller certificate must be included in the NTAuth store. By default, the Active Directory Certificate Authority's root certificate is added to the NTAuth store. If you
```suggestion
> The certificate for the CA issuing the domain controller certificate must be included in the NTAuth store. By default, the Active Directory Certificate Authority's root certificate is added to the NTAuth store. If you are using a multi-tier CA hierarchy or a third-party CA, this may not be done by default. If the Domain Controller certificate does not directly chain to a CA certificate in the NTAuth store, user authentication will fail.
```

2021-02-18 21:34 UTC, mapalko commented on windows/security/identity-protection/hello-for-business/hello-hybrid-key-whfb-settings-pki.md
> +The following PowerShell command can be used to check the NTAuth certificate:
```suggestion
The following PowerShell command can be used to check all certificates in the NTAuth store:
```

2021-02-19 05:42 UTC, joinimran commented
Thanks for your feedback and suggestion @mapalko .

2021-02-19 06:01 UTC, JohanFreelancer9 approved these changes

2021-02-19 20:59 UTC, illfated approved these changes
Rich Diff view: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8936/files?short_path=028833d#diff-028833d95785da5f189fe5291e31d7ea4e768cfffb98d975320556441e990b0e

2021-02-19 21:00 UTC, illfated commented
#sign-off

2021-03-22 17:53 UTC, merged