Update distribute-offline-apps.md
MicrosoftDocs/windows-itpro-docs pull request #8950
Opened 2021-01-11 23:29 UTC by illfated

**Description:**

From issue ticket #8942 (**Broken link - Distribute offline apps**):

> Hi all.
> 
> In Distribute offline apps (https://docs.microsoft.com/en-us/microsoft-store/distribute-offline-apps) the link Manage apps from Microsoft Store for Business with Microsoft Intune that points to [docs.microsoft.com/en-us/intune/deploy-use/manage-apps-you-purchased-from-the-windows-store-for-business-with-microsoft-intune](https://docs.microsoft.com/en-us/intune/deploy-use/manage-apps-you-purchased-from-the-windows-store-for-business-with-microsoft-intune) rports error 404. Probably the destination has changed URL. I believe that it should point to the doc How to manage volume purchased apps from the Microsoft Store for Business with Microsoft Intune - [docs.microsoft.com/en-us/mem/intune/apps/windows-store-for-business](https://docs.microsoft.com/en-us/mem/intune/apps/windows-store-for-business).
> 
> Can you double check this and fix it please?

Thanks to @joaonltome for noticing and reporting this broken link and also suggesting a likely solution.

**Changes proposed:**

- Replace the broken link /microsoft-store/distribute-offline-apps with the working page link /mem/intune/apps/windows-store-for-business .
- Change the paragraph title "To download an offline-licensed app" from **bold** formatting to a H3 heading, as well as including the HTML anchor in that heading.
  (This heading level might possibly need to be a H4 heading size to remain the same size as its current **bold**-only format.)

**Whitespace changes:**

- Remove 13 redundant blank lines at the end of the document page.
- By removing these 13 blank lines, we also remove that redundant empty command copy box (created by indents).
- Reduce 12 occurrences of 3 blank spaces after bullet point list indicators to 1 space.
- Reduce 6 occurrences of double blank space after numbered list indicators to 1 space.
- Add missing colon in **Applies to:**
 
**Ticket closure or reference:**

Closes #8942

2021-01-11 23:32 UTC, illfated reviewed
- **Regular source view:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8950/files
- **Hide whitespace changes:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8950/files?diff=unified&w=1 (focuses on visible or effective changes)
- **Rich Diff view:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8950/files?diff=unified&w=1&short_path=5b7d86f (mostly useful to evaluate if H3 or H4 should be used in the last section)

2021-01-11 23:33 UTC, illfated commented
@JohanFreelancer9 : copy review, please (if & when able).

2021-01-11 23:35 UTC, illfated commented
Also, to all reviewers: Please check if we should include any additional changes in the link description text, to match the page titles exactly, or if it is preferred to keep the current text as is.

2021-01-11 23:35 UTC, illfated commented
#sign-off

2021-01-12 00:05 UTC, illfated commented
Hmm, I can't seem to enable the anchor link functionality to make it appear in the Rich Diff view, neither in this PR nor in the file preview in my branch. Oh well, if it doesn't work on the currently existing page, it should not make much difference. The new change adheres to the most common anchor link usage in other documents.

2021-01-12 05:07 UTC, JohanFreelancer9 commented on store-for-business/distribute-offline-apps.md
> +- **You don't have access to Microsoft Store services** - If your employees don't have access to the internet and Microsoft Store services, downloading offline-licensed apps and deploying them with i
```suggestion
- **You don't have access to Microsoft Store services** - If your employees don't have access to the Internet and Microsoft Store services, downloading offline-licensed apps and deploying them with imaging is an alternative to online-licensed apps.
```

2021-01-12 05:08 UTC, JohanFreelancer9 requested changes
Copy review - just one more additional minor edit, please.

2021-01-13 15:08 UTC, JohanFreelancer9 approved these changes

2021-01-29 21:48 UTC, merged