Update connect-to-remote-aadj-pc.md
MicrosoftDocs/windows-itpro-docs pull request #8954
Opened 2021-01-12 08:16 UTC by RavennMSFT

Updated supported configs to be more readable, added details on adding AAD users and groups to Remote Desktop Users group via policy, removed the Windows account picker text which is not supported for AAD users

2021-01-12 14:41 UTC, e0i commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-01-12 16:24 UTC, JohanFreelancer9 commented on windows/client-management/connect-to-remote-aadj-pc.md
> +From its release, Windows 10 has supported remote connections to PCs joined to Active Directory. Starting in Windows 10, version 1607, you can also connect to a remote PC that is [joined to Azure Act
```suggestion
From its release, Windows 10 has supported remote connections to PCs joined to Active Directory. Starting in Windows 10, version 1607, you can also connect to a remote PC that is [joined to Azure Active Directory (Azure AD)](https://docs.microsoft.com/azure/active-directory/devices/concept-azure-ad-join). Starting in Windows 10, version 1809, you can [use biometrics to authenticate to a remote desktop session](https://docs.microsoft.com/windows/whats-new/whats-new-windows-10-version-1809#remote-desktop-with-biometrics).
```

2021-01-12 16:28 UTC, JohanFreelancer9 commented on windows/client-management/connect-to-remote-aadj-pc.md
> +- Your local PC (where you are connecting from) must be either Azure AD joined or Hybrid Azure AD joined if using Windows 10 version 1607 and above, or [Azure AD registered](https://docs.microsoft.co
```suggestion
- Your local PC (where you are connecting from) must be either Azure AD-joined or Hybrid Azure AD-joined if using Windows 10, version 1607 and above, or [Azure AD registered](https://docs.microsoft.com/azure/active-directory/devices/concept-azure-ad-register) if using Windows 10, version 2004 and above. Remote connections to an Azure AD-joined PC from an unjoined device or a non-Windows 10 device are not supported. 
```

2021-01-12 16:32 UTC, JohanFreelancer9 commented on windows/client-management/connect-to-remote-aadj-pc.md
> +         > For devices running Windows 10, version 1703 or earlier, the user must to sign in to the remote device first before attempting remote connections.
```suggestion
         > For devices running Windows 10, version 1703 or earlier, the user must sign in to the remote device first before attempting remote connections.
```

2021-01-12 16:38 UTC, JohanFreelancer9 commented on windows/client-management/connect-to-remote-aadj-pc.md
> +         > Starting Windows 10, version 1709, you can add other Azure AD users to the **Administrators** group on a device in **Settings** and restrict remote credentials to **Administrators**. If th
```suggestion
         > Starting in Windows 10, version 1709, you can add other Azure AD users to the **Administrators** group on a device in **Settings** and restrict remote credentials to **Administrators**. If there is a problem connecting remotely, make sure that both devices are joined to Azure AD and that TPM is functioning properly on both devices.
```

2021-01-12 16:38 UTC, JohanFreelancer9 commented on windows/client-management/connect-to-remote-aadj-pc.md
> +         Starting Windows 10 version 2004, you can add users or Azure AD groups to the Remote Desktop Users using MDM policies as described [in this article](https://docs.microsoft.com/azure/active-d
```suggestion
         Starting in Windows 10, version 2004, you can add users or Azure AD groups to the Remote Desktop Users using MDM policies as described in [How to manage the local administrators group on Azure AD joined devices](https://docs.microsoft.com/azure/active-directory/devices/assign-local-admin#manage-administrator-privileges-using-azure-ad-groups-preview).
```

2021-01-12 16:39 UTC, JohanFreelancer9 commented on windows/client-management/connect-to-remote-aadj-pc.md
> +         > [!Note]
```suggestion
         > [!NOTE]
```

2021-01-12 16:40 UTC, JohanFreelancer9 commented on windows/client-management/connect-to-remote-aadj-pc.md
> +         > If you cannot connect using Remote Desktop Connection 6.0, you must turn off the new features of RDP 6.0 and revert back to RDP 5.0 by making a few changes in the RDP file. See the details
```suggestion
         > If you cannot connect using Remote Desktop Connection 6.0, you must turn off the new features of RDP 6.0 and revert back to RDP 5.0 by making a few changes in the RDP file. See the details in this [support article](https://support.microsoft.com/help/941641/remote-desktop-connection-6-0-prompts-you-for-credentials-before-you-e).
```

2021-01-12 16:41 UTC, JohanFreelancer9 commented on windows/client-management/connect-to-remote-aadj-pc.md
> +The table below lists out the supported configurations for remotely connecting to an Azure AD-joined PC:
```suggestion
The table below lists the supported configurations for remotely connecting to an Azure AD-joined PC:
```

2021-01-12 16:44 UTC, JohanFreelancer9 commented on windows/client-management/connect-to-remote-aadj-pc.md
> +| Criteria | RDP from Azure AD registered device| RDP from Azure AD joined device| RDP from Hybrid Azure AD joined device |
```suggestion
| Criteria | RDP from Azure AD registered device| RDP from Azure AD-joined device| RDP from hybrid Azure AD-joined device |
```

2021-01-12 16:45 UTC, JohanFreelancer9 commented on windows/client-management/connect-to-remote-aadj-pc.md
> +| **Client operating systems**| Windows 10 2004 and above| Windows 10 1607 and above | Windows 10 1607 and above |
```suggestion
| **Client operating systems**| Windows 10, version 2004 and above| Windows 10, version 1607 and above | Windows 10, version 1607 and above |
```

2021-01-12 16:54 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-12 18:22 UTC, illfated commented on windows/client-management/connect-to-remote-aadj-pc.md
> +         > If you cannot connect using Remote Desktop Connection 6.0, you must turn off the new features of RDP 6.0 and revert back to RDP 5.0 by making a few changes in the RDP file. See the details
If this had not been a Microsoft Docs document, something more like a personal document, I might have suggested to include the word "this" in the link description. But it is what it is. 🙂

2021-01-12 18:25 UTC, illfated commented
I concur. Good job.

2021-01-12 20:20 UTC, RavennMSFT commented on windows/client-management/connect-to-remote-aadj-pc.md
> +- Your local PC (where you are connecting from) must be either Azure AD joined or Hybrid Azure AD joined if using Windows 10 version 1607 and above, or [Azure AD registered](https://docs.microsoft.co
There are no "-" for Azure AD joined and hybrid Azure AD joined. They are not hyphenated terms

2021-01-12 20:22 UTC, RavennMSFT commented on windows/client-management/connect-to-remote-aadj-pc.md
> +| Criteria | RDP from Azure AD registered device| RDP from Azure AD joined device| RDP from Hybrid Azure AD joined device |
Not hyphenated terms

2021-01-12 23:11 UTC, RavennMSFT commented
#sign-off

2021-01-12 23:15 UTC, illfated commented on windows/client-management/connect-to-remote-aadj-pc.md
> +- Your local PC (where you are connecting from) must be either Azure AD joined or Hybrid Azure AD joined if using Windows 10 version 1607 and above, or [Azure AD registered](https://docs.microsoft.co
OK, so maybe a moderate suggestion, containing only the comma suggestions, will be OK instead:
```suggestion
- Your local PC (where you are connecting from) must be either Azure AD joined or Hybrid Azure AD joined if using Windows 10, version 1607 and above, or [Azure AD registered](https://docs.microsoft.com/azure/active-directory/devices/concept-azure-ad-register) if using Windows 10, version 2004 and above. Remote connections to an Azure AD joined PC from an unjoined device or a non-Windows 10 device are not supported. 
```

2021-01-12 23:16 UTC, illfated commented on windows/client-management/connect-to-remote-aadj-pc.md
> +| Criteria | RDP from Azure AD registered device| RDP from Azure AD joined device| RDP from Hybrid Azure AD joined device |
Suggesting only the casing correction instead:
```suggestion
| Criteria | RDP from Azure AD registered device| RDP from Azure AD joined device| RDP from hybrid Azure AD joined device |
```

2021-01-12 23:42 UTC, RavennMSFT commented
@JohanFreelancer9 , @illfated done with the suggestions

2021-01-12 23:47 UTC, illfated approved these changes
Looks good to me.

2021-01-13 09:14 UTC, JohanFreelancer9 approved these changes

2021-01-13 23:10 UTC, merged