Removal of Note
MicrosoftDocs/windows-itpro-docs pull request #8967
Opened 2021-01-14 17:32 UTC by joinimran

As Gen 2 VMs are now available in Azure, the Credential guard feature is made available. So removing this note.

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8938

2021-01-14 17:32 UTC, joinimran commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2021-01-14 18:05 UTC, illfated commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
>      >```
```suggestion
    >```

```
For some unexplained reason, I am unable to suggest a reduction in removed blank lines below, but I am able to suggest adding a blank line here.

2021-01-15 00:40 UTC, truekonrads commented
Can I suggest that this note should remain, but say: “Gen1 does not support cred guard, use Gen2?” Else those who are on Gen1 will be lost.

2021-01-15 03:42 UTC, JohanFreelancer9 commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> -> Credential Guard and Device Guard are not currently supported when using Azure IaaS VMs. These options will be made available with future Gen 2 VMs.
```suggestion
Credential Guard Generation 1 is not supported when using Azure IaaS VMs. Use Generation 2 instead.
```

2021-01-15 03:44 UTC, JohanFreelancer9 commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> -> Credential Guard and Device Guard are not currently supported when using Azure IaaS VMs. These options will be made available with future Gen 2 VMs.
In line with the recommendation, my suggestion. But it is only a suggestion.

2021-01-15 03:44 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-15 06:00 UTC, joinimran commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> -> Credential Guard and Device Guard are not currently supported when using Azure IaaS VMs. These options will be made available with future Gen 2 VMs.
I have  updated the note section.

2021-01-15 06:00 UTC, joinimran commented
@JohanFreelancer9 - Please copy review.

2021-01-15 07:04 UTC, JohanFreelancer9 approved these changes
Thank you @joinimran - looks good. Please just change the word "NOTE" to all caps.

2021-01-15 07:09 UTC, JohanFreelancer9 commented on windows/security/identity-protection/credential-guard/credential-guard-manage.md
> +> [!Note]
```suggestion
> [!NOTE]
```

2021-01-15 14:55 UTC, JohanFreelancer9 approved these changes

2021-01-15 21:29 UTC, illfated approved these changes

2021-02-18 11:13 UTC, nam31 commented
@Dansimp, PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-02-18 21:08 UTC, illfated commented
#sign-off

2021-03-23 22:38 UTC, merged