added note about changing algorithm
MicrosoftDocs/windows-itpro-docs pull request #8977
Opened 2021-01-18 07:49 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8918

2021-01-18 07:49 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

2021-01-18 08:31 UTC, beerisgood commented
I would change

> device must be decrypted first

To something like

> device must be configured and decrypted (if already encrypted) first.

As some want configuring Bitlocker before encryption so in that case decryption isn't needed.

2021-01-18 09:58 UTC, JohanFreelancer9 commented on windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10.md
> +> BitLocker Device Encryption feature uses XTS-AES 128-bit encryption method. In case you need to use different encryption method and/or cipher strength, device must be decrypted first. After that, d
```suggestion
> BitLocker Device Encryption uses the XTS-AES 128-bit encryption method. In case you need to use a different encryption method and/or cipher strength, the device must be configured and decrypted (if already encrypted) first. After that, different BitLocker settings can be applied.
```

2021-01-18 10:00 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-20 16:28 UTC, JohanFreelancer9 approved these changes

2021-01-20 17:53 UTC, illfated approved these changes

2021-01-22 14:23 UTC, nam31 commented
@Dansimp PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-02-18 05:37 UTC, merged