Added a Store Content Related URL
MicrosoftDocs/windows-itpro-docs pull request #9007
Opened 2021-01-23 17:17 UTC by joinimran

As the user has mentioned that to access the content of the store required URL was missing. I have updated the URL.

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8874

Reset of the URL's mentioned in the comment doesn't have any reference in MS docs and previous version document. So as of now, I have dropped them. 

Thanks.
Imran.

2021-01-23 17:17 UTC, joinimran commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2021-01-24 06:39 UTC, JohanFreelancer9 commented on windows/privacy/manage-windows-20H2-endpoints.md
> +||The following endpoint is needed to load the content in Microsoft Store App.|HTTPS|livetileedge.dsx.mp.microsoft.com|
```suggestion
||The following endpoint is needed to load the content in the Microsoft Store app.|HTTPS|livetileedge.dsx.mp.microsoft.com|
```

2021-01-24 06:43 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-24 11:57 UTC, illfated approved these changes
Looks good to me.

2021-01-25 08:51 UTC, JohanFreelancer9 approved these changes

2021-01-26 23:13 UTC, illfated commented
#sign-off

2021-01-29 06:02 UTC, Gental-Giant commented
#sign-off

2021-02-18 15:56 UTC, merged