pointing to the Application proxy page
MicrosoftDocs/windows-itpro-docs pull request #9008
Opened 2021-01-23 17:30 UTC by joinimran

Added a link so that users can directly get more information about the application proxy and how the application proxy works.

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8988

2021-01-23 17:30 UTC, joinimran commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2021-01-24 06:30 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md
> +Azure AD Application proxies are serviced by lightweight Application Proxy Connector agents. See, [What is Application Proxy](https://docs.microsoft.com/azure/active-directory/manage-apps/application
```suggestion
Azure AD Application proxies are serviced by lightweight Application Proxy Connector agents. See [What is Application Proxy](https://docs.microsoft.com/azure/active-directory/manage-apps/application-proxy#what-is-application-proxy) for more details. These agents are installed on your on-premises, domain joined devices and make authenticated secure outbound connection to Azure, waiting to process requests from Azure AD Application Proxies. You can create connector groups in Azure Active Directory to assign specific connectors to service specific applications.
```

2021-01-24 06:30 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2021-01-24 12:04 UTC, illfated approved these changes
Looks good to me.

2021-01-25 08:55 UTC, JohanFreelancer9 approved these changes

2021-01-26 21:24 UTC, mapalko approved these changes

2021-01-26 21:37 UTC, illfated commented
#sign-off

2021-02-17 21:14 UTC, merged