update hybrid scenario naming and add link to description
MicrosoftDocs/windows-itpro-docs pull request #9012
Opened 2021-01-25 13:26 UTC by VLG17

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8703

2021-01-26 22:04 UTC, illfated approved these changes
Looks good to me.

2021-02-10 04:36 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/create-wdac-policy-for-fully-managed-devices.md
> +- All clients are managed by Microsoft Endpoint Manager (MEM) either with Configuration Manager (MEMCM) standalone or [Co-Managed](https://docs.microsoft.com/mem/configmgr/comanage/overview) with Int
```suggestion
- All clients are managed by Microsoft Endpoint Manager (MEM) either with Configuration Manager (MEMCM) standalone or [co-managed](https://docs.microsoft.com/mem/configmgr/comanage/overview) with Intune;
```

2021-02-10 04:40 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-10 09:31 UTC, JohanFreelancer9 approved these changes

2021-02-13 14:51 UTC, illfated approved these changes

2021-02-18 21:28 UTC, merged