Removing bad security practice
MicrosoftDocs/windows-itpro-docs pull request #9060
Opened 2021-02-01 15:27 UTC by FriedrichWeinmann

Secrets should not be stored in clear text files.
Also added syntax highlighting for PowerShell

2021-02-01 23:47 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/exposed-apis-create-app-webapp.md
>  # Paste below your Tenant ID, App ID and App Secret (App key).
Since you are already adding a change here, I would like to suggest some improvement to the English grammar and the specific referencing in these comments.
```suggestion
# This script acquires the App Context Token and stores it in the variable $token for later use in the script.
# Paste your Tenant ID, App ID and App Secret (App key) into the indicated quotes below.
```

2021-02-04 23:42 UTC, illfated approved these changes
Looks quite OK to me. I have not tested the script, but the change seems appropriate.

2021-02-10 03:34 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/exposed-apis-create-app-webapp.md
> +# Paste your Tenant ID, App ID and App Secret (App key) into the indicated quotes below.
```suggestion
# Paste your Tenant ID, App ID, and App Secret (App key) into the indicated quotes below.
```

2021-02-10 03:39 UTC, JohanFreelancer9 requested changes
Copy review - minor additional edit, please.

2021-02-18 05:36 UTC, merged