minor changes regarding the checkpoints
MicrosoftDocs/windows-itpro-docs pull request #9080
Opened 2021-02-05 11:06 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8924

2021-02-05 11:06 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

2021-02-05 12:22 UTC, JohanFreelancer9 approved these changes

2021-02-06 10:30 UTC, illfated commented on windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md
>  > If you recieve a message that "Something went wrong" and it "Looks like we can't connect to the URL for your organization's MDM terms of use" then verify you have correctly [assigned licenses](http
I could be mistaken, but I think this part of the sentence can be adjusted for readability:
```suggestion
> If you recieve a message that "Something went wrong" and it "Looks like we can't connect to the URL for your organization's MDM terms of use", verify that you have correctly [assigned licenses](https://docs.microsoft.com/mem/intune/fundamentals/licenses-assign) to the current user.
```

2021-02-06 10:32 UTC, illfated commented on windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md
>  > If you recieve a message that "Something went wrong" and it "Looks like we can't connect to the URL for your organization's MDM terms of use" then verify you have correctly [assigned licenses](http
BTW, this is outside the scope of your changes, I am only taking the opportunity to improve additional content.

2021-02-09 08:39 UTC, JohanFreelancer9 commented on windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md
> +> If you recieve a message that "Something went wrong" and it "Looks like we can't connect to the URL for your organization's MDM terms of use", verify that you have correctly [assigned licenses](htt
```suggestion
> If you receive a message that "Something went wrong" and it "Looks like we can't connect to the URL for your organization's MDM terms of use", verify that you have correctly [assigned licenses](https://docs.microsoft.com/mem/intune/fundamentals/licenses-assign) to the current user.
```

2021-02-09 08:40 UTC, JohanFreelancer9 requested changes
Apologies, one more, please.

2021-02-11 17:49 UTC, JohanFreelancer9 approved these changes

2021-02-13 09:36 UTC, illfated approved these changes
Looks good to me.

2021-03-11 22:31 UTC, merged