Update use-windows-event-forwarding-to-assist-in-intrusion-detection.md
MicrosoftDocs/windows-itpro-docs pull request #9089
Opened 2021-02-05 23:07 UTC by warren-msft

Updated the "What are the WEC server's limitations section per Gianni Bragante's recommendation.

2021-02-06 09:53 UTC, illfated approved these changes
Looks good to me.

2021-02-10 03:01 UTC, JohanFreelancer9 commented on windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection.md
> +There are three factors that limit the scalability of WEC servers. The general rule for a stable WEC server on commodity hardware is planning for a total of 3000 events per second for all configured
```suggestion
There are three factors that limit the scalability of WEC servers. The general rule for a stable WEC server on commodity hardware is planning for a total of 3,000 events per second on average for all configured subscriptions.
```

2021-02-10 03:09 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-10 20:24 UTC, merged

2021-05-08 23:55 UTC, ianni1998g reviewed
Bien