add note about premium connectors licensing
MicrosoftDocs/windows-itpro-docs pull request #9108
Opened 2021-02-09 13:18 UTC by VLG17

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8616

2021-02-09 18:08 UTC, adirdidi requested changes

2021-02-10 02:42 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/api-microsoft-flow.md
> +> More details about premium connectors licensing prerequisites [here](https://docs.microsoft.com/en-us/power-automate/triggers-introduction#licensing-for-premium-connectors)
```suggestion
> For more details about premium connectors licensing prerequisites, see [Licensing for premium connectors](https://docs.microsoft.com/power-automate/triggers-introduction#licensing-for-premium-connectors).
```

2021-02-10 02:43 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-10 09:32 UTC, JohanFreelancer9 approved these changes

2021-02-17 21:15 UTC, merged