Update euiccs-ddf-file.md
MicrosoftDocs/windows-itpro-docs pull request #9137
Opened 2021-02-12 18:32 UTC by apdutta

Updating the DDF to reflect the current DDF from the codebase

2021-02-12 22:42 UTC, jdbruner approved these changes
I believe this is the same content as the DDF file itself, which we've already reviewed and approved.

2021-02-13 07:34 UTC, JohanFreelancer9 commented on windows/client-management/mdm/euiccs-ddf-file.md
> +                    <Description>Indicates whether the download of a profile with PPR1 is allowed. If the eUICC has already a profile (regardless of its origin and policy rules associated with it), t
```suggestion
                    <Description>Indicates whether the download of a profile with PPR1 is allowed. If the eUICC already has a profile (regardless of its origin and policy rules associated with it), the download of a profile with PPR1 is not allowed.</Description>
```

2021-02-13 07:34 UTC, JohanFreelancer9 commented on windows/client-management/mdm/euiccs-ddf-file.md
> +                    <Description>Indicates whether the eUICC has already a profile with PPR1.</Description>
```suggestion
                    <Description>Indicates whether the eUICC already has a profile with PPR1.</Description>
```

2021-02-13 07:40 UTC, JohanFreelancer9 commented on windows/client-management/mdm/euiccs-ddf-file.md
> +                        <Description>Node representing the discovery operation for a server name. The node name is the fully qualified domain name of the SM-DP+ server that will be used for profile d
```suggestion
                        <Description>Node specifying the server name for a discovery operation. The node name is the fully qualified domain name of the SM-DP+ server that will be used for profile discovery. Creation of this subtree triggers a discovery request.</Description>
```

2021-02-13 07:42 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-19 21:27 UTC, illfated approved these changes
Regular source file view: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9137/files

Rich Diff view: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9137/files?short_path=ba9dc2e#diff-ba9dc2e81715b572193445278a2b7ceb5963e41538b155edc51ecb818379e088

Looks good to me.

2021-02-20 04:01 UTC, JohanFreelancer9 approved these changes

2021-02-22 18:58 UTC, merged