Update mandatory-user-profile.md
MicrosoftDocs/windows-itpro-docs pull request #9139
Opened 2021-02-12 22:26 UTC by warren-msft

2021-02-13 07:16 UTC, JohanFreelancer9 commented on windows/client-management/mandatory-user-profile.md
>  6. Right-click Start, go to **Control Panel** (view by large or small icons) > **System** > **Advanced system settings**, and click **Settings** in the **User Profiles** section.
```suggestion
6. Right-click **Start**, go to **Control Panel** (view by large or small icons) > **System** > **Advanced system settings**, and click **Settings** in the **User Profiles** section. Alternatively, starting in Windows 10, version 2004, open the **Settings** app and select **Advanced system settings**.
```

2021-02-13 07:16 UTC, JohanFreelancer9 commented on windows/client-management/mandatory-user-profile.md
> +Starting in Windows 10 version (2004) Open the Settings app and click on Advanced system settings
```suggestion
```

2021-02-13 07:20 UTC, illfated commented
This PR targets the file `windows/client-management/mandatory-user-profile.md` which is the same file used in PR #9141 — likely reason for the file conflict.

2021-02-13 07:22 UTC, JohanFreelancer9 commented on windows/client-management/mandatory-user-profile.md
> +   - Optionally you can check the box “Mandatory profile”. This step is not required but will set permissions that are more restrictive and it is recommend to do so
```suggestion
   - Optionally, you can check the **Mandatory profile** checkbox. This step is not required but will set permissions that are more restrictive and we recommend doing so.
```

2021-02-13 07:23 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-13 08:11 UTC, illfated commented on windows/client-management/mandatory-user-profile.md
> +   - Optionally you can check the box “Mandatory profile”. This step is not required but will set permissions that are more restrictive and it is recommend to do so
Maybe add a comma after "required", to have the sentence correctly divided into main sentence + clause, like this:
```suggestion
   - Optionally, you can check the **Mandatory profile** checkbox. This step is not required, but will set permissions that are more restrictive and we recommend doing so.
```

2021-02-17 20:31 UTC, e0i commented
@warren-msft Please follow-up with the copy editing suggestions and if you can, resolve the merge conflicts to proceed. Thank you again for the contributions.

2021-02-18 05:24 UTC, JohanFreelancer9 approved these changes

2021-02-19 21:30 UTC, illfated commented on windows/client-management/mandatory-user-profile.md
> +
This looks like a remnant from resolving the file conflict. I am fairly certain we don't need those 2 lines.
```suggestion
```

2021-02-19 21:31 UTC, illfated commented on windows/client-management/mandatory-user-profile.md
> +=======
Same here, a remnant from resolving the file conflict.
```suggestion

```

2021-02-19 21:38 UTC, illfated commented on windows/client-management/mandatory-user-profile.md
>     - If the device is not joined to the domain, you can save the profile locally and then copy it to the shared folder location.
Thank you for merging my suggestions. Just an image spacing issue remains, from what I can see:
```suggestion

   ![Example of UI](images/copy-to-path.png)

   - If the device is not joined to the domain, you can save the profile locally and then copy it to the shared folder location.
```

2021-02-19 21:53 UTC, illfated approved these changes
Looks good to me.

2021-02-19 21:53 UTC, illfated commented
#sign-off

2021-02-20 03:41 UTC, JohanFreelancer9 approved these changes

2021-02-22 18:56 UTC, merged

2021-04-20 14:06 UTC, warren-msft commented
I just checked the Docs content and the changes never got published.

From: Kateyanne ***@***.***>
Sent: Monday, February 22, 2021 12:57 PM
To: MicrosoftDocs/windows-itpro-docs ***@***.***>
Cc: Warren Williams ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/windows-itpro-docs] Update mandatory-user-profile.md (#9139)


Merged #9139<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fwindows-itpro-docs%2Fpull%2F9139&data=04%7C01%7CWarren.Williams%40microsoft.com%7Cbb4fcb8252864d385b0b08d8d763a20a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637496170286535627%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=G5YM1amz4bDlkQXwMr559SzqbF68SWfGO%2FXAuqhVB18%3D&reserved=0> into public.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fwindows-itpro-docs%2Fpull%2F9139%23event-4361387906&data=04%7C01%7CWarren.Williams%40microsoft.com%7Cbb4fcb8252864d385b0b08d8d763a20a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637496170286535627%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nTkbMTMEuHul51p3BXr8ZdE7ztr1X7RrMwKsaH9jU74%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEVBGZWNAQZU7IGY5CYZP4DTAKSHXANCNFSM4XRNXFMA&data=04%7C01%7CWarren.Williams%40microsoft.com%7Cbb4fcb8252864d385b0b08d8d763a20a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637496170286545619%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FvZh2XUIs89ExJaJbFJTXfa8QpPWbBhqclGjGlh%2Fn3g%3D&reserved=0>.

2021-04-20 14:29 UTC, illfated commented
Yes, unfortunately, it sometimes happens that the migration subroutine fails silently. Please advise on how to proceed to have this PR commit change migrated to docs.microsoft.com .