Azure ATP: Microsoft Defender for Identity
MicrosoftDocs/windows-itpro-docs pull request #9143
Opened 2021-02-14 02:36 UTC by illfated

**Description:**

From issue ticket #9142 (**old product name - Azure ATP**):
> **Azure ATP is now called Defender for Identity, please update the text on this page.**

Thanks to @DeanGross (Dean Gross) for noticing and reporting the issue.

**Changes proposed:**

- Replace "Azure ATP" with 'Microsoft Defender for Identity'
- Replace "Microsoft Defender ATP" with 'Microsoft Defender for Endpoint'
- Replace "Microsoft Defender Advanced Threat Protection" with 'Microsoft Defender for Endpoint'

**Codestyle & whitespace:**

- Add missing MarkDown indent marker compatibility spacing (20 occurrences)

**Additional notes:**

Please note that some of the changes might be premature or not yet approvable. Please notify me of incorrect changes or missing link changes so I can correct them.

**Ticket closure or reference:**

Closes #9142

2021-02-14 02:39 UTC, illfated reviewed
**Regular source file view:**
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9143/files

**Hide whitespace changes:** (for easier review of the effective changes)
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9143/files?diff=unified&w=1

**Rich Diff view:**
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9143/files?diff=unified&w=1&short_path=b072cc0#diff-b072cc0705a4b71ff80c170180a4079330cf359dd8d563eb94439dbc7d3ecb57

2021-02-14 02:40 UTC, illfated commented
@JohanFreelancer9 : copy review, please.

2021-02-15 07:21 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/advanced-features.md
>  For tenants created on or after Windows 10, version 1809 the automated investigation and remediation capability is configured by default to resolve alerts where the automated analysis result status i
```suggestion
For tenants created on or after Windows 10, version 1809, the automated investigation and remediation capability is configured by default to resolve alerts where the automated analysis result status is "No threats found" or "Remediated".  If you don't want to have alerts auto-resolved, you'll need to manually turn off the feature.
```

2021-02-15 07:22 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/advanced-features.md
> +> For tenants created prior that version, you'll need to manually turn this feature on from the [Advanced features](https://securitycenter.windows.com/preferences2/integration) page.
```suggestion
> For tenants created prior to that version, you'll need to manually turn this feature on from the [Advanced features](https://securitycenter.windows.com/preferences2/integration) page.
```

2021-02-15 07:28 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/advanced-features.md
>  To receive contextual device integration in Office 365 Threat Intelligence, you'll need to enable the Defender for Endpoint settings in the Security & Compliance dashboard. For more information, see
```suggestion
To receive contextual device integration in Office 365 Threat Intelligence, you'll need to enable the Defender for Endpoint settings in the Security & Compliance dashboard. For more information, see [Office 365 Threat Intelligence overview](https://support.office.com/article/Office-365-Threat-Intelligence-overview-32405DA5-BEE1-4A4B-82E5-8399DF94C512).
```

2021-02-15 07:30 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/advanced-features.md
> +> This feature will be available with an E5 license for [Enterprise Mobility + Security](https://www.microsoft.com/cloud-platform/enterprise-mobility-security) on devices running Windows 10, version
```suggestion
> This feature will be available with an E5 license for [Enterprise Mobility + Security](https://www.microsoft.com/cloud-platform/enterprise-mobility-security) on devices running Windows 10, version 1709 (OS Build 16299.1085 with [KB4493441](https://support.microsoft.com/help/4493441)), Windows 10, version 1803 (OS Build 17134.704 with [KB4493464](https://support.microsoft.com/help/4493464)), Windows 10, version 1809 (OS Build 17763.379 with [KB4489899](https://support.microsoft.com/help/4489899)), or later Windows 10 versions.
```

2021-02-15 07:32 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/advanced-features.md
> +Forwards Microsoft Defender for Endpoint signals to Microsoft Secure Score in the Microsoft 365 security center. Turning on this feature gives Microsoft Secure Score visibility into the devices secur
```suggestion
Forwards Microsoft Defender for Endpoint signals to Microsoft Secure Score in the Microsoft 365 security center. Turning on this feature gives Microsoft Secure Score visibility into the device's security posture. Forwarded data is stored and processed in the same location as your Microsoft Secure Score data.
```

2021-02-15 07:37 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-15 20:44 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/advanced-features.md
>  To receive contextual device integration in Office 365 Threat Intelligence, you'll need to enable the Defender for Endpoint settings in the Security & Compliance dashboard. For more information, see
Hmm, that link redirects to docs.microsoft.com (https://docs.microsoft.com/microsoft-365/security/office-365-security/office-365-ti?view=o365-worldwide).
I wonder if it would be better to link the ending page directly.

2021-02-15 20:44 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/advanced-features.md
>  To receive contextual device integration in Office 365 Threat Intelligence, you'll need to enable the Defender for Endpoint settings in the Security & Compliance dashboard. For more information, see
```suggestion
To receive contextual device integration in Office 365 Threat Intelligence, you'll need to enable the Defender for Endpoint settings in the Security & Compliance dashboard. For more information, see [Office 365 Threat Intelligence overview](https://docs.microsoft.com/microsoft-365/security/office-365-security/office-365-ti?view=o365-worldwide).
```

2021-02-15 20:53 UTC, illfated commented
Thank you for the copy review, those corrections are good. Would you mind checking if my suggestion of using the direct link looks OK too?

2021-02-16 02:11 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-atp/advanced-features.md
>  To receive contextual device integration in Office 365 Threat Intelligence, you'll need to enable the Defender for Endpoint settings in the Security & Compliance dashboard. For more information, see
It looks good to me, and please if you could also rather use the title of the topic, i.e. [Threat investigation and response].

2021-02-16 19:06 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/advanced-features.md
>  To receive contextual device integration in Office 365 Threat Intelligence, you'll need to enable the Defender for Endpoint settings in the Security & Compliance dashboard. For more information, see
> It looks good to me, and please if you could also rather use the title of the topic, i.e. [Threat investigation and response].

Sure thing, will do. Thank you for the useful feedback. 👍🏻 I will get right to it.

2021-02-16 19:08 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/advanced-features.md
>  To receive contextual device integration in Office 365 Threat Intelligence, you'll need to enable the Defender for Endpoint settings in the Security & Compliance dashboard. For more information, see
```suggestion
To receive contextual device integration in Office 365 Threat Intelligence, you'll need to enable the Defender for Endpoint settings in the Security & Compliance dashboard. For more information, see [Threat investigation and response](https://docs.microsoft.com/microsoft-365/security/office-365-security/office-365-ti).
```

2021-02-16 19:12 UTC, illfated commented
**Regular source file view:**
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9143/files

**Hide whitespace changes:** (for easier review of the effective changes)
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9143/files?diff=unified&w=1

**Rich Diff view:**
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9143/files?diff=unified&w=1&short_path=b072cc0#diff-b072cc0705a4b71ff80c170180a4079330cf359dd8d563eb94439dbc7d3ecb57

2021-02-16 19:12 UTC, illfated commented
#sign-off

2021-02-16 19:13 UTC, illfated commented
@JohanFreelancer9 : if you are happy with the changes, may I ask you to apply your approval to this PR?

2021-02-17 03:10 UTC, JohanFreelancer9 approved these changes

2021-02-18 05:34 UTC, merged