corrected layout issue
MicrosoftDocs/windows-itpro-docs pull request #9175
Opened 2021-02-18 12:56 UTC by RAJU2529

as per user report #9174 , so i added one line gap .

2021-02-18 16:18 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md
> +> The Microsoft PIN Reset service only works with **Enterprise Edition** for Windows 10, version 1709 to 1809.  The feature works with **Enterprise Edition** and **Pro edition** with Windows 10, vers
```suggestion
> The Microsoft PIN Reset service only works with **Enterprise Edition** for Windows 10, version 1709 to 1809.  The feature works with **Enterprise Edition** and **Pro Edition** with Windows 10, version 1903 and later.
```

2021-02-18 16:22 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-18 18:38 UTC, mapalko approved these changes

2021-02-18 20:47 UTC, illfated approved these changes

2021-02-19 11:59 UTC, JohanFreelancer9 approved these changes

2021-02-19 21:48 UTC, illfated commented
#sign-off

2021-02-22 18:33 UTC, merged