Update install-vamt.md
MicrosoftDocs/windows-itpro-docs pull request #9179
Opened 2021-02-19 16:13 UTC by Karl-WE

missed to align the information in requirements section with merged PR #9009

2021-02-19 20:54 UTC, illfated commented on windows/deployment/volume-activation/install-vamt.md
> +- the latest version of [Windows 10 ADK](https://docs.microsoft.com/windows-hardware/get-started/adk-install
This sentence needs some form of rephrasing, it feels incomplete to me.
```suggestion
- Latest version of the [Windows 10 ADK](https://docs.microsoft.com/windows-hardware/get-started/adk-install)
```
@JohanFreelancer9 : May I ask you to suggest a correction or rephrasing to make it seem more natural? To me, it feels like "Windows 10 ADK" refers specifically to the Development Kit, hence my suggestion of the definite article "the" in front of "Windows 10 ADK".

2021-02-20 04:51 UTC, JohanFreelancer9 commented on windows/deployment/volume-activation/install-vamt.md
> +- the latest version of [Windows 10 ADK](https://docs.microsoft.com/windows-hardware/get-started/adk-install
```suggestion
- Latest version of the [Windows 10 ADK](https://docs.microsoft.com/windows-hardware/get-started/adk-install)
```

2021-02-20 04:52 UTC, JohanFreelancer9 commented on windows/deployment/volume-activation/install-vamt.md
> +- the latest version of [Windows 10 ADK](https://docs.microsoft.com/windows-hardware/get-started/adk-install
@illfated - I am good with your changes.

2021-02-20 04:53 UTC, JohanFreelancer9 requested changes
Copy review - only @illfated's changes.

2021-02-20 06:21 UTC, illfated commented
@JohanFreelancer9 : Thank you for your valuable feedback.

@Karl-WE : Merging my suggestion should be enough.

2021-02-21 12:36 UTC, Karl-WE commented
Aye. Thanks again. I wonder if I will ever achieve this level of written english :)

2021-02-21 18:58 UTC, illfated commented
😄 Don't worry too much about it. There will always be someone available to proof read anything you write, if correct grammar, syntax, and semantics becomes important in your work.

2021-02-21 19:01 UTC, illfated approved these changes
Looks good to me.

2021-02-21 19:02 UTC, illfated commented
- **Regular source view:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9179/files
- **Rich Diff view:** https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9179/files?short_path=510612e

2021-02-21 19:03 UTC, illfated commented
#sign-off

2021-03-05 22:43 UTC, Karl-WE commented
Hi @greg-lindsay do you agree on the small change here? It would save time in the future, even if there will be only one ADK per year and I don't suspect a successor of ADK 2004 before 21H2. Thanks for your thoughts and merge.

2021-03-15 20:08 UTC, merged

2021-03-15 20:15 UTC, illfated commented
Nice. Thank you both for the PR and for the merge. 👍🏻

2021-03-16 20:20 UTC, Karl-WE commented
Thanks @greg-lindsay