ESU callout for Win 7
MicrosoftDocs/windows-itpro-docs pull request #9205
Opened 2021-02-25 17:15 UTC by computeronix

Windows 7 requires SCEP or relies upon SCEP, in order for SCEP to be in a supported state, it would require a customer to purchase and use ESU on a support Windows 7 device

Called that out, technically Windows 7 is not listed as a supported OS in SCCM/SCEP any longer - https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/configs/supported-operating-systems-for-clients-and-devices

2021-02-25 19:04 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md
> +- Windows 7 SP1 Pro [requires ESU for support](https://docs.microsoft.com/troubleshoot/windows-client/windows-7-eos-faq/windows-7-extended-security-updates-faq)
Hmm, maybe we could add parentheses around the added text, like this, for readability & slight separation?
```suggestion
- Windows 7 SP1 Enterprise ([Requires ESU for support](https://docs.microsoft.com/troubleshoot/windows-client/windows-7-eos-faq/windows-7-extended-security-updates-faq).)
- Windows 7 SP1 Pro ([Requires ESU for support](https://docs.microsoft.com/troubleshoot/windows-client/windows-7-eos-faq/windows-7-extended-security-updates-faq).)
```
(My suggestion changes the added text to a short sentence, with an ending period dot, in parenthesis.)

2021-02-25 19:05 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md
> +- Windows 7 SP1 Pro [requires ESU for support](https://docs.microsoft.com/troubleshoot/windows-client/windows-7-eos-faq/windows-7-extended-security-updates-faq)
See also the Rich Diff view to view the already existing text in the PR:
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9205/files?short_path=7487559#diff-7487559bce588875d56ab4bf72d3c0d9d2674d9067999fab4e7334b5dab822e7

2021-02-26 02:34 UTC, JohanFreelancer9 requested changes
Copy review - agree with @illfated's suggestion.

2021-02-27 21:09 UTC, e0i commented
@computeronix Good to go with the above suggestions applied, thank you.

2021-03-03 16:47 UTC, JohanFreelancer9 approved these changes

2021-03-03 19:21 UTC, illfated approved these changes
Looks good to me.

2021-03-03 19:22 UTC, illfated commented
**Rich diff view** for easier review: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9205/files?short_path=7487559#diff-7487559bce588875d56ab4bf72d3c0d9d2674d9067999fab4e7334b5dab822e7

2021-03-05 18:51 UTC, merged