Update onboard-configure with server versions
MicrosoftDocs/windows-itpro-docs pull request #9206
Opened 2021-02-25 17:44 UTC by wahidsaleemi

Added the Windows Server versions that are now supported. The list was taken from the linked article.

2021-02-25 18:58 UTC, illfated commented
I agree with the addition of Server 2018, 2019, and SAC 1803, but I thought 2008 R2 reached End Of Support about a year ago. Are there any exclusions to the EOS date?

2021-02-25 19:45 UTC, adirdidi approved these changes

2021-02-25 19:46 UTC, adirdidi commented
It's supported by MDE.

2021-02-25 19:47 UTC, illfated approved these changes
Very well, thank you for the explanation. Looks good and valid to me.

2021-02-25 19:48 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/onboard-configure.md
> +[Onboard servers](configure-server-endpoints.md) |  Onboard Windows Server 2008 R2 SP1, Windows Server 2012 R2, Windows Server 2016, Windows Server (SAC) version 1803 and later, Windows Server 2019 a
Cosmetic/minor: may we have a period dot at the end of the sentence?
```suggestion
[Onboard servers](configure-server-endpoints.md) |  Onboard Windows Server 2008 R2 SP1, Windows Server 2012 R2, Windows Server 2016, Windows Server (SAC) version 1803 and later, Windows Server 2019 and later, and Windows Server 2019 core edition to Defender for Endpoint.
```

2021-02-26 02:25 UTC, JohanFreelancer9 requested changes
Copy review - only @illfated's suggestion.

2021-02-27 21:06 UTC, e0i commented
Hello @wahidsaleemi Would you be able to merge the copy editing suggestions mentioned above? The PR is good to go once those changes have been applied. Thank you for your contributions.

2021-03-01 17:59 UTC, illfated approved these changes
Looks good to me.

2021-03-01 17:59 UTC, illfated commented
#sign-off

2021-03-02 04:44 UTC, JohanFreelancer9 approved these changes

2021-03-05 18:50 UTC, merged