add note about enabling Sandbox using Powershell
MicrosoftDocs/windows-itpro-docs pull request #9210
Opened 2021-02-26 11:12 UTC by VLG17

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9098

2021-02-26 18:21 UTC, illfated commented on windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md
> +> To enable Sandbox using Powershell, open Powershell as Administrator and run **Enable-WindowsOptionalFeature -FeatureName "Containers-DisposableClientVM" -All -Online**
For consistency, please add a MarkDown indent marker compatibility spacing here too:
```suggestion
> [!NOTE]
> To enable Sandbox using PowerShell, open PowerShell as Administrator and run **Enable-WindowsOptionalFeature -FeatureName "Containers-DisposableClientVM" -All -Online**
```
Also: The name "PowerShell" is usually written in CamelCase.

BTW, would it be interesting to encapsulate the command line in MarkDown back ticks, both to display it in monospaced typeface (font) and also shield it from being translated by Machine Translation used for this page when it is auto-translated to other languages?

2021-02-27 03:52 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md
> +> To enable Sandbox using Powershell, open Powershell as Administrator and run **Enable-WindowsOptionalFeature -FeatureName "Containers-DisposableClientVM" -All -Online**
Agree with these suggestions. Also please insert a period (.) at the end of the note.

2021-02-27 03:52 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-27 06:39 UTC, illfated commented on windows/security/threat-protection/windows-sandbox/windows-sandbox-overview.md
> +> To enable Sandbox using Powershell, open Powershell as Administrator and run **Enable-WindowsOptionalFeature -FeatureName "Containers-DisposableClientVM" -All -Online**
Done. Thank you for pointing that out. 👍🏻

2021-03-01 16:20 UTC, JohanFreelancer9 approved these changes

2021-03-01 21:54 UTC, illfated approved these changes
Looks good to me. The only thing I would have considered adding to the existing PR content (knowing that I tend to be an OCD perfectionist) is a separate code block for the PS code, but that should not be necessary when the goal is just to inform the reader what the simple command content looks like (and it would seem like a bit of "overkill" to do so).

2021-03-11 19:39 UTC, nam31 commented
@Dansimp PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-23 22:49 UTC, merged