Update bitlocker-upgrading-faq.md
MicrosoftDocs/windows-itpro-docs pull request #9214
Opened 2021-02-26 22:57 UTC by rafals2

clarification when BitLocker suspension is required

2021-02-27 03:27 UTC, JohanFreelancer9 commented on windows/security/information-protection/bitlocker/bitlocker-upgrading-faq.md
> +-	Some TPM firmware updates if these update clears TPM outside of Windows API. Not every TPM firmware update will clear the TPM and this happens if known vulnerability has been discovered in the TPM
```suggestion
-	Some TPM firmware updates if these updates clear TPM outside of Windows API. Not every TPM firmware update will clear the TPM and this happens if a known vulnerability has been discovered in the TPM firmware. Users don’t have to suspend BitLocker if the TPM firmware update uses Windows API to clear TPM because in this case BitLocker will be automatically suspended. We recommend users testing their TPM firmware updates if they don’t want to suspend BitLocker protection.
```

2021-02-27 03:28 UTC, JohanFreelancer9 commented on windows/security/information-protection/bitlocker/bitlocker-upgrading-faq.md
> +-	Non-Microsoft application updates that modify UEFI\BIOS configuration
```suggestion
-	Non-Microsoft application updates that modify the UEFI\BIOS configuration.
```

2021-02-27 03:29 UTC, JohanFreelancer9 commented on windows/security/information-protection/bitlocker/bitlocker-upgrading-faq.md
> +-	Manual or 3rd party updates to secure boot databases (only If BitLocker uses Secure Boot for Integrity validation)
```suggestion
-	Manual or third-party updates to secure boot databases (only if BitLocker uses Secure Boot for integrity validation).
```

2021-02-27 03:31 UTC, JohanFreelancer9 commented on windows/security/information-protection/bitlocker/bitlocker-upgrading-faq.md
> +-	Updates to UEFI\BIOS firmware, installation of additional UEFI drivers or UEFI applications without using Windows Update mechanism (only If BitLocker does not use Secure Boot for Integrity validati
```suggestion
-	Updates to UEFI\BIOS firmware, installation of additional UEFI drivers, or UEFI applications without using the Windows update mechanism (only if you update and BitLocker does not use Secure Boot for integrity validation).
```

2021-02-27 03:32 UTC, JohanFreelancer9 commented on windows/security/information-protection/bitlocker/bitlocker-upgrading-faq.md
> + -	You can check if BitLocker uses Secure Boot for integrity validation with manage-bde -protectors -get C: (and see if "Uses Secure Boot for integrity validation" is reported)
```suggestion
 -	You can check if BitLocker uses Secure Boot for integrity validation with manage-bde -protectors -get C: (and see if "Uses Secure Boot for integrity validation" is reported).
```

2021-02-27 03:34 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-27 06:50 UTC, illfated commented on windows/security/information-protection/bitlocker/bitlocker-upgrading-faq.md
> +-	Some TPM firmware updates if these update clears TPM outside of Windows API. Not every TPM firmware update will clear the TPM and this happens if known vulnerability has been discovered in the TPM
To my mind, it looks as if there should be a definite article "the" between "clear" and "TPM" as well as in front of "Windows API"; something like this:
```suggestion
-	Some TPM firmware updates if these updates clear the TPM outside of the Windows API. Not every TPM firmware update will clear the TPM and this happens if a known vulnerability has been discovered in the TPM firmware.  Users don’t have to suspend BitLocker if the TPM firmware update uses Windows API to clear TPM, because in this case, BitLocker will automatically be suspended. We recommend that users test their TPM firmware updates if they don’t want to suspend BitLocker protection.
```
Also: added some more suggestions for the rest of the paragraph. Does my suggestion look usable?

2021-02-27 15:24 UTC, JohanFreelancer9 commented on windows/security/information-protection/bitlocker/bitlocker-upgrading-faq.md
> +-	Some TPM firmware updates if these update clears TPM outside of Windows API. Not every TPM firmware update will clear the TPM and this happens if known vulnerability has been discovered in the TPM
Final suggestion.

2021-03-11 14:07 UTC, e0i commented
@rafals2 The PR is good to go once the copy editing suggestions have been applied. Thank you.

2021-03-11 19:40 UTC, illfated approved these changes
Looks good to me as soon as the suggestions have been added (committed).

2021-03-11 19:54 UTC, merged