<Update with how to do> allow-com-object-registration-in-windows-defender-application-…
MicrosoftDocs/windows-itpro-docs pull request #9217
Opened 2021-02-28 10:07 UTC by TJ2215

…control-policy.md

2021-02-28 18:04 UTC, illfated commented on windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy.md
> +For example, you get an error in the Event Viewer (Application and Service Logs > Microsoft > Windows > AppLocker > MSI and Script) like below:
I don't know enough about this document to say if this addition will become accepted (I am not a Microsoft employee), but in the meanwhile, here are some improvement suggestions:
```suggestion
### How to configure settings for the CLSIDs

Given the following example of an error in the Event Viewer (Application and Service Logs > Microsoft > Windows > AppLocker > MSI and Script):
```

2021-02-28 18:07 UTC, illfated commented on windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy.md
> +Event Xml:
Spacing is important. Removed redundant blanks, adjusted indentation, capitalization for XML (eXtensible Markup Language).
```suggestion
Keywords:
User:          S-1-5-21-3340858017-3068726007-3466559902-3647
Computer:      contoso.com
Description:
{f8d253d9-89a4-4daa-87b6-1168369f0b21} was prevented from running due to Config CI policy.

Event XML:

```

2021-02-28 18:09 UTC, illfated commented on windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy.md
> +</Event>
```suggestion
```XML
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-AppLocker" Guid="{cbda4dbf-8d5d-4f69-9578-be14aa540d22}" />
    <EventID>8036</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2020-11-11T19:18:11.4029179Z" />
    <EventRecordID>819347</EventRecordID>
    <Correlation ActivityID="{61e3e871-adb0-0047-c9cc-e761b0add601}" />
    <Execution ProcessID="21060" ThreadID="23324" />
    <Channel>Microsoft-Windows-AppLocker/MSI and Script</Channel>
    <Computer>contoso.com</Computer>
    <Security UserID="S-1-5-21-3340858017-3068726007-3466559902-3647" />
  </System>
  <EventData>
    <Data Name="IsApproved">false</Data>
    <Data Name="CLSID">{f8d253d9-89a4-4daa-87b6-1168369f0b21}</Data>
  </EventData>
</Event>
```
I have tried adding a MarkDown fenced code block with syntax highlighting for XML, but I am not sure if I have been successful in adding the ending fence (3 back ticks, **```**)

2021-02-28 18:11 UTC, illfated commented on windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy.md
> +Once the command is run, you will find that the following section is added to the policy xml.
~~~suggestion
To add this CLSID to the existing policy, use the following steps:

1. Open PowerShell ISE with Administrative privileges.
2. From the admin PowerShell ISE, copy and edit this command, then run it. Consider the policy name to be `WDAC_policy.xml`.

```PowerShell
PS C:\WINDOWS\system32> Set-CIPolicySetting -FilePath <path to policy xml>\WDAC_policy.xml -Key 8856f961-340a-11d0-a96b-00c04fd705a2 -Provider WSH -Value True -ValueName EnterpriseDefinedClsId -ValueType Boolean
```

Once the command has been run, you will find that the following section is added to the policy XML.
~~~

2021-02-28 18:12 UTC, illfated commented on windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy.md
> +    </Setting>
~~~suggestion
```XML
  <Settings>
    <Setting Provider="WSH" Key="8856f961-340a-11d0-a96b-00c04fd705a2" ValueName="EnterpriseDefinedClsId">
      <Value>
        <Boolean>true</Boolean>
      </Value>
    </Setting>
```
~~~

2021-02-28 18:17 UTC, illfated commented
I can only apologize for the fact that GitHub is unable to highlight the individual changes for slightly big sections in suggestions. The other option would be to add the suggestions line by line, or max 2 lines at a time (which would result in quite a lot of commits). Feel free to tell me if you would prefer many commits to for easier review of the individual edits.

2021-03-01 03:32 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy.md
> +To add this CLSID to the existing policy, follow the steps below,
```suggestion
You can add this CLSID to the existing policy by following these steps:
```

2021-03-01 03:36 UTC, JohanFreelancer9 requested changes
Copy review - @illfated, your suggestions look good, I have just added a few more. I'll do a final edit after the technical review.

2021-03-01 03:39 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy.md
> +For example, you get an error in the Event Viewer (Application and Service Logs > Microsoft > Windows > AppLocker > MSI and Script) like below:
```suggestion
For example, should you get an error in the Event Viewer (**Application and Service Logs** > **Microsoft** > **Windows** > **AppLocker** > **MSI and Script**) such as the following:
```

2021-03-01 08:07 UTC, andreiztm commented
Thanks everyone for the help so far with this!

2021-03-01 20:02 UTC, illfated commented
@TJ2215 : Would you be able to commit the suggested changes, or apply your own changes as close as possible to our suggestions, so we can move this PR forward to being merge ready?

2021-03-01 20:03 UTC, TJ2215 commented
@illfated  sure.. let me make those changes

2021-03-01 22:54 UTC, illfated commented on windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy.md
> +
Cosmetic/codestyle: we can remove one blank line here to keep the spacing consistent (although not terribly important).
```suggestion
```

2021-03-01 22:57 UTC, illfated commented on windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy.md
> +Given the following example of an error in the Event Viewer (Application and Service Logs > Microsoft > Windows > AppLocker > MSI and Script):
I also suggest applying the following part of @JohanFreelancer9's earlier suggestion:
```suggestion
Given the following example of an error in the Event Viewer (**Application and Service Logs** > **Microsoft** > **Windows** > **AppLocker** > **MSI and Script**):
```

2021-03-03 02:24 UTC, JohanFreelancer9 approved these changes

2021-03-03 19:31 UTC, illfated approved these changes
Seems ready for final review & merge (unless anyone in the MS Docs management should have any arguments against it).

2021-03-03 19:33 UTC, TJ2215 commented
thanks everyone for their contribution. I believe this is ready for the final review by @isbrahm and team.

2021-03-22 18:22 UTC, merged