Minor Modification in Note Section
MicrosoftDocs/windows-itpro-docs pull request #9219
Opened 2021-02-28 17:33 UTC by joinimran

I have made a minor modifications in the note section so that it can reflect the correct information.

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9070

2021-02-28 17:33 UTC, joinimran commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2021-02-28 17:45 UTC, illfated commented on windows/client-management/mdm/policy-csp-controlpolicyconflict.md
> +> MDMWinsOverGP only applies to policies in Policy CSP. MDM  policies win over Group Policies where applicable, not all Group Policies are available via MDM or CSP. It does not apply to other MDM set
I mostly only found a redundant blank space in the added sentence, but maybe @JohanFreelancer9 could find something else worth adjusting. Anyway:
```suggestion
> MDMWinsOverGP only applies to policies in Policy CSP. MDM policies win over Group Policies where applicable, not all Group Policies are available via MDM or CSP. It does not apply to other MDM settings with equivalent GP settings that are defined in other CSPs.
```
(Also changed "on other CSPs" to "in other CSPs", because the contents of said CSPs is the topic.)

2021-02-28 18:19 UTC, illfated commented
Thank you. Well done so far. 🙂 👍🏻

2021-02-28 18:19 UTC, illfated approved these changes

2021-03-01 02:14 UTC, JohanFreelancer9 commented on windows/client-management/mdm/policy-csp-controlpolicyconflict.md
> +> MDMWinsOverGP only applies to policies in Policy CSP. MDM policies win over Group Policies where applicable, not all Group Policies are available via MDM or CSP. It does not apply to other MDM sett
```suggestion
> MDMWinsOverGP only applies to policies in Policy CSP. MDM policies win over Group Policies where applicable; not all Group Policies are available via MDM or CSP. It does not apply to other MDM settings with equivalent GP settings that are defined in other CSPs.
```

2021-03-01 02:18 UTC, JohanFreelancer9 commented on windows/client-management/mdm/policy-csp-controlpolicyconflict.md
>  This policy is used to ensure that MDM policy wins over GP when policy is configured on MDM channel. The default value is 0. The MDM policies in Policy CSP will behave as described if this policy val
```suggestion
This policy is used to ensure that MDM policy wins over GP when the policy is configured on the MDM channel. The default value is 0. The MDM policies in Policy CSP will behave as described if this policy value is set to 1.
```

2021-03-01 02:19 UTC, JohanFreelancer9 requested changes
Copy review - one more small change and a few minor additional edits in the existing text, please.

2021-03-01 16:04 UTC, JohanFreelancer9 approved these changes

2021-03-01 20:06 UTC, illfated approved these changes

2021-03-11 19:40 UTC, nam31 commented
@Dansimp PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-23 22:40 UTC, merged