Resolve broken links to Insider Preview builds
MicrosoftDocs/windows-itpro-docs pull request #9244
Opened 2021-03-03 20:37 UTC by illfated

**Resolve broken links in whats-new-windows-10-version-2004.md**

From issue ticket #9241:

> The link is broken:
>
> **Reset this PC**
> The 'reset this PC' recovery function now includes a cloud download option.

Thanks to @CoMMyCZ for noticing & reporting this issue.

**Changes proposed:**

- Replace 8 occurrences of the outdated `/at-work-pro/wip-4-biz-whats-new` directory & page links

**Codestyle & whitespace:**

- Remove redundant leading space before dash in the "See Also" bullet point list
- Remove redundant HTML `<br>` tags from "See Also" sentence endings (handled by MarkDown)
- Remove any redundant end-of-line (EOL) whitespace (blanks)

Closes #9241

2021-03-03 20:40 UTC, illfated commented
@JohanFreelancer9 : Kindly perform a copy review for this PR. Please note that a couple of the link updates also contain preliminary suggestions for updated text by copying the section heading from the Archive page, making sentence structure changes. I will need suggestions for better phrasing to make sure that MS Docs codestyle is preserved.

2021-03-03 20:42 UTC, illfated reviewed
**Hide whitespace changes** (removes a couple lines where the change is only a cleanup of end-of-line blanks):
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9244/files?diff=unified&w=1

**Rich Diff view** for readability review: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9244/files?diff=unified&w=1&short_path=4d09d59#diff-4d09d5969635a11bf502b5c5cb469f854d493679cc35b0b0b08b9f31d3ffb365

2021-03-03 20:42 UTC, illfated commented
#sign-off

2021-03-04 05:24 UTC, nam31 commented
@JohanFreelancer9 please do the copy editor review for this PR.
Thank you

2021-03-04 08:38 UTC, JohanFreelancer9 commented on windows/whats-new/whats-new-windows-10-version-2004.md
>    - Reason: Replaced with separate policies for foreground and background
```suggestion
  - Reason: Replaced with separate policies for foreground and background.
```

2021-03-04 08:38 UTC, JohanFreelancer9 commented on windows/whats-new/whats-new-windows-10-version-2004.md
> +  - Reason: impacts uploads to internet peers only, which isn't used in Enterprises.
```suggestion
  - Reason: Impacts uploads to internet peers only, which isn't used in enterprises.
```

2021-03-04 08:39 UTC, JohanFreelancer9 commented on windows/whats-new/whats-new-windows-10-version-2004.md
>    - Reason: separated to foreground and background
```suggestion
  - Reason: Separated to foreground and background.
```

2021-03-04 08:51 UTC, JohanFreelancer9 commented on windows/whats-new/whats-new-windows-10-version-2004.md
> +[Introducing a new tablet experience for 2-in-1 convertible PCs! (Build 18970)](https://docs.microsoft.com/windows-insider/archive/new-in-20H1#introducing-a-new-tablet-experience-for-2-in-1-convertib
```suggestion
See [Introducing a new tablet experience for 2-in-1 convertible PCs! (Build 18970)](https://docs.microsoft.com/windows-insider/archive/new-in-20H1#introducing-a-new-tablet-experience-for-2-in-1-convertible-pcs-build-18970) for details on a new tablet experience for two-in-one convertible PCs that is now available. The screen will be optimized for touch when you detach your two-in-one's keyboard, but you'll still keep the familiar look of your desktop without interruption.
```

2021-03-04 08:56 UTC, JohanFreelancer9 requested changes
Copy review - looks good, just a few minor suggestions.

2021-03-04 23:46 UTC, illfated commented
Very good, thank you for the added corrections. Appreciated.

2021-03-04 23:47 UTC, illfated commented
#sign-off

2021-03-05 03:28 UTC, JohanFreelancer9 approved these changes

2021-03-05 21:01 UTC, illfated commented
Copy edit review done. PR ready for final review & merge.

2021-03-07 07:56 UTC, nam31 commented
@greg-lindsay PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-22 17:54 UTC, merged