More clarification
MicrosoftDocs/windows-itpro-docs pull request #9251
Opened 2021-03-05 11:22 UTC by joinimran

There was confusion if the license is not assigned to the user.  Updated the information.

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9161

2021-03-05 11:22 UTC, joinimran commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2021-03-05 21:05 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-atp/mac-support-license.md
> +You deployed and/or installed the Microsoft Defender for Endpoint for macOS package ("Download installation package") but you might have run the configuration script ("Download onboarding package").
Looks like there should be some form of continuation of the existing sentence, if the added text should start with "or". I will add an improvement suggestion, but I suspect that @JohanFreelancer9 may have a better suggestion.
```suggestion
You deployed and/or installed the Microsoft Defender for Endpoint for macOS package ("Download installation package"), but you might have run the configuration script ("Download onboarding package"), or you have not assigned a license to the user.
```

2021-03-06 03:32 UTC, JohanFreelancer9 requested changes
Only @illfated's suggestion.

2021-03-06 15:32 UTC, illfated approved these changes
Looks good to me.

2021-03-08 05:54 UTC, JohanFreelancer9 approved these changes

2021-03-18 10:48 UTC, nam31 commented
Hi @Dansimp, PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-05-02 08:31 UTC, closed without merging

2021-05-02 09:50 UTC, illfated commented
(The target pages have moved to the MicrosoftDocs/microsoft-365-docs repository and are updated from there.)

2021-05-02 09:52 UTC, illfated commented
New PR targeting the new page: https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4866