added potential impact
MicrosoftDocs/windows-itpro-docs pull request #9261
Opened 2021-03-07 14:27 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9128

2021-03-07 14:27 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

2021-03-07 17:25 UTC, illfated commented on windows/security/threat-protection/security-policy-settings/modify-firmware-environment-values.md
> +Removing local Administrators group from the **Modify firmware environment values** could cause the inoperability of BitLocker Drive Encryption feature.
The sentence feels incomplete, grammatically, both in the beginning and in the last part of the sentence. I suggest the following:
```suggestion
Removing the local Administrators group from the **Modify firmware environment values** user right could cause inoperability of the BitLocker Drive Encryption feature.
```

2021-03-08 02:47 UTC, JohanFreelancer9 requested changes
Copy review - only @illfated's suggestions.

2021-03-08 06:21 UTC, JohanFreelancer9 approved these changes

2021-03-11 22:33 UTC, merged