added trust type
MicrosoftDocs/windows-itpro-docs pull request #9277
Opened 2021-03-09 16:02 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9242
According to "Configure Active Directory" section of the article, it applies to Certificate trust deployments

2021-03-09 16:02 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

2021-03-09 17:12 UTC, illfated approved these changes
Looks good to me.

2021-03-10 04:23 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-feature-dual-enrollment.md
>  * Enterprise Joined or Hybrid Azure joined devices
```suggestion
* Enterprise joined or Hybrid Azure joined devices
```

2021-03-10 04:24 UTC, JohanFreelancer9 requested changes
Copy review - minor additional edit, please.

2021-03-10 06:01 UTC, JohanFreelancer9 approved these changes

2021-03-10 18:57 UTC, illfated commented
#sign-off

2021-03-11 04:34 UTC, JohanFreelancer9 approved these changes

2021-03-24 23:59 UTC, mapalko commented
I don't see a mention in the article that this requires cert trust. I am checking with some engineers on this one. Please do not merge.

2021-03-25 04:47 UTC, MaratMussabekov commented
Dear @mapalko ,
The "Configure Active Directory to support Domain Administrator enrollment" section of the article describes the actions that required for certificate trust only.
Thank you

2021-04-12 21:43 UTC, merged