Update info about licenses
MicrosoftDocs/windows-itpro-docs pull request #9290
Opened 2021-03-10 11:44 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9133

2021-03-10 18:25 UTC, illfated commented on windows/deployment/windows-10-subscription-activation.md
> +- Up to five devices can be upgraded for each user license. If user license is used for the sixth device, the operating system on the computer to which user has not logged in the longest will revert
```suggestion
- Up to five devices can be upgraded for each user license. If the user license is used for a sixth device, the operating system on the computer to which a user has not logged in the longest will revert to Windows 10 Pro or Windows 10 Pro Education.
```
Somewhat long and difficult sentence, not quite sure how to make it easier to read and also understand, although it is fairly understandable as is (with adjustments like the one I have suggested).

2021-03-11 05:08 UTC, JohanFreelancer9 requested changes
Copy review - only @illfated's suggestions.

2021-03-11 19:28 UTC, nam31 commented
@greg-lindsay PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-11 19:31 UTC, illfated commented
Please note that we are still waiting for the suggested sentence adjustment is still waiting to be committed.

2021-03-14 09:03 UTC, illfated approved these changes
Looks good to me.

2021-03-15 04:06 UTC, JohanFreelancer9 approved these changes

2021-03-23 22:51 UTC, merged