Update windowsdefenderapplicationguard-csp.md
MicrosoftDocs/windows-itpro-docs pull request #9301
Opened 2021-03-12 21:12 UTC by sazankha

2021-03-13 04:56 UTC, JohanFreelancer9 commented on windows/client-management/mdm/windowsdefenderapplicationguard-csp.md
> +> To enforce this policy device restart or user logon/off is required.
```suggestion
> To enforce this policy, device restart or user logon/logoff is required. 
```

2021-03-13 04:56 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-13 05:56 UTC, illfated approved these changes
Looks good to me with the suggested change added.

2021-03-13 07:24 UTC, illfated approved these changes

2021-03-14 03:34 UTC, JohanFreelancer9 approved these changes

2021-03-16 21:11 UTC, merged