add note pointing to older article
MicrosoftDocs/windows-itpro-docs pull request #9303
Opened 2021-03-14 19:01 UTC by VLG17

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9068

2021-03-14 22:36 UTC, illfated commented on windows/security/threat-protection/auditing/audit-file-system.md
> +> For more details about applicability on older operating system versions, check [this article](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn319
```suggestion
> For more details about applicability on older operating system versions, read the article [Audit File System](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn319068(v=ws.11)).
```
Not 100% sure, but it is usually recommended to use the page title, when the link points to the top of a page instead of a subsection.

2021-03-15 04:12 UTC, JohanFreelancer9 commented on windows/security/threat-protection/auditing/audit-file-system.md
> +> For more details about applicability on older operating system versions, check [this article](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn319
@illfated - please also remove the locale in the link from your suggestion.

2021-03-15 04:14 UTC, JohanFreelancer9 requested changes
Copy review - please apply suggestions.

2021-03-15 20:07 UTC, illfated approved these changes
Looks correct now. Thank you for the PR. 👍🏻

2021-03-16 01:03 UTC, JohanFreelancer9 approved these changes

2021-03-22 18:20 UTC, merged