Update event-4670.md
MicrosoftDocs/windows-itpro-docs pull request #9328
Opened 2021-03-18 18:43 UTC by illfated

**Description:**

- https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4670

As reported in issue ticket #9318 (**Broken "Left pane"**), the TOC pane overshoots its boundaries and covers the article document partially, both in the Japanese version as well as in other automatically machine translated pages.

Thanks to @hyoshioka0128 for reporting the issue appearing on the /ja-jp/ page.

It has been determined that leftover HTML tags is the underlying cause of this issue.

Thanks to @TinaMcN for pointing out the outdated HTML tagging issue.

**Changes proposed:**

- Remove redundant HTML tags and use MarDown formatting wherever possible.
- Use MarkDown Note blob format for Note sections and the Important note.
- Replace outdated and redirected MSDN links with links to their current MS Docs pages.

**Whitespace and formatting corrections:**

- Reduce bullet point list whitespace (blanks) from 3x to 1x (MarkDown default).
- Replace curly quote characters with straight ASCII quote characters.
- Use XML beautify formatting tool to arrange the XML code properly.
- Add MD syntax highlighting tag "xml" to the MD code block fence.

**Ticket closure or reference:**

Closes #9318

2021-03-18 19:00 UTC, illfated reviewed
**Rich Diff view** for easier layout-based review:
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9328/files?short_path=4dd4c03#diff-4dd4c038d22cc9c15cabda0cd2ff085a2b7441102713238b0f1f449138f09bcd

**Hide whitespace changes** to slightly reduce the number of default source view lines to review:
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9328/files?diff=unified&w=1

2021-03-18 19:00 UTC, illfated commented
@JohanFreelancer9 : Kindly perform a copy review. Thank you.

2021-03-19 08:08 UTC, JohanFreelancer9 commented on windows/security/threat-protection/auditing/event-4670.md
> +- **Security ID** [Type = SID] : SID of account that requested the "change object’s permissions" operation. Event Viewer automatically tries to resolve SIDs and show the account name. If the SID cann
```suggestion
- **Security ID** [Type = SID]: SID of account that requested the "change object’s permissions" operation. Event Viewer automatically tries to resolve SIDs and shows the account name. If the SID cannot be resolved, you will see the source data in the event.
```

2021-03-19 08:13 UTC, JohanFreelancer9 commented on windows/security/threat-protection/auditing/event-4670.md
> +- **Account Name** [Type = UnicodeString] : the name of the account that requested the "change object’s permissions" operation.
```suggestion
- **Account Name** [Type = UnicodeString]**:** The name of the account that requested the "change object’s permissions" operation.
```

2021-03-19 08:14 UTC, JohanFreelancer9 commented on windows/security/threat-protection/auditing/event-4670.md
> +- **Account Domain** [Type = UnicodeString] : subject’s domain or computer name. Formats vary, and include the following:
```suggestion
- **Account Domain** [Type = UnicodeString]**:** Subject’s domain or computer name. Formats vary, and include the following:
```

2021-03-19 08:15 UTC, JohanFreelancer9 commented on windows/security/threat-protection/auditing/event-4670.md
> +- **Logon ID** [Type = HexInt64]**:** hexadecimal value that can help you correlate this event with recent events that might contain the same Logon ID, for example, "[4624](event-4624.md): An account
```suggestion
- **Logon ID** [Type = HexInt64]**:** Hexadecimal value that can help you correlate this event with recent events that might contain the same Logon ID, for example, "[4624](event-4624.md): An account was successfully logged on."
```

2021-03-19 08:16 UTC, JohanFreelancer9 commented on windows/security/threat-protection/auditing/event-4670.md
> +- **Object Server** [Type = UnicodeString]: has "**Security**" value for this event.
```suggestion
- **Object Server** [Type = UnicodeString]**:** Has "**Security**" value for this event.
```

2021-03-19 08:16 UTC, JohanFreelancer9 commented on windows/security/threat-protection/auditing/event-4670.md
> +- **Object Type** [Type = UnicodeString]: The type of an object that was accessed during the operation.
```suggestion
- **Object Type** [Type = UnicodeString]**:** The type of an object that was accessed during the operation.
```

2021-03-19 08:17 UTC, JohanFreelancer9 commented on windows/security/threat-protection/auditing/event-4670.md
> +- **Object Name** \[Type = UnicodeString\]: name and other identifying information for the object for which permissions were changed. For example, for a file, the path would be included. For Token ob
```suggestion
- **Object Name** \[Type = UnicodeString\]**:** Name and other identifying information for the object for which permissions were changed. For example, for a file, the path would be included. For Token objects, this field typically equals "-".
```

2021-03-19 08:18 UTC, JohanFreelancer9 commented on windows/security/threat-protection/auditing/event-4670.md
> +- **Handle ID** \[Type = Pointer\]: hexadecimal value of a handle to **Object Name**. This field can help you correlate this event with other events that might contain the same Handle ID, for example
```suggestion
- **Handle ID** \[Type = Pointer\]**:** Hexadecimal value of a handle to **Object Name**. This field can help you correlate this event with other events that might contain the same Handle ID, for example, "[4663](event-4663.md)(S): An attempt was made to access an object." This parameter might not be captured in the event, and in that case, appears as "0x0".
```

2021-03-19 08:20 UTC, JohanFreelancer9 commented on windows/security/threat-protection/auditing/event-4670.md
> +- **Process Name** \[Type = UnicodeString\]**:** full path and the name of the executable for the process.
```suggestion
- **Process Name** \[Type = UnicodeString\]**:** Full path and the name of the executable for the process.
```

2021-03-19 08:20 UTC, JohanFreelancer9 commented on windows/security/threat-protection/auditing/event-4670.md
> +- **Original Security Descriptor** [Type = UnicodeString]**:** the old Security Descriptor Definition Language (SDDL) value for the object.
```suggestion
- **Original Security Descriptor** [Type = UnicodeString]**:** The old Security Descriptor Definition Language (SDDL) value for the object.
```

2021-03-19 08:20 UTC, JohanFreelancer9 commented on windows/security/threat-protection/auditing/event-4670.md
> +- **New Security Descriptor** [Type = UnicodeString]**:** the new Security Descriptor Definition Language (SDDL) value for the object.
```suggestion
- **New Security Descriptor** [Type = UnicodeString]**:** The new Security Descriptor Definition Language (SDDL) value for the object.
```

2021-03-19 08:26 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-22 08:49 UTC, Kuermel approved these changes

2021-03-22 20:57 UTC, illfated commented
Corrections applied. Thank you for the copy review.

2021-03-23 01:05 UTC, JohanFreelancer9 approved these changes

2021-04-22 16:15 UTC, nam31 commented
@illfated , can you please look into conflicts with your PR

2021-04-22 17:43 UTC, illfated commented
Sure thing, not a problem. Thank you for notifying me. 🙂 👍🏻

2021-06-06 20:58 UTC, closed without merging