HKEY_LOCAL_MACHINE_MACHINE typo correction
MicrosoftDocs/windows-itpro-docs pull request #9374
Opened 2021-03-28 20:55 UTC by illfated

**Description:**

As reported in issue ticket #9373 (**Typo in item 25. Windows Spotlight last bullet DisableWindowsConsumerFeatures: HKEY_LOCAL_MACHINE_MACHINE**), `/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md#L1769` contains a redundant extra occurrence of the key phrase `_MACHINE` (`HKEY_LOCAL_MACHINE_MACHINE`) (https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public@%7B2021-03-28T19:38:33Z%7D/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md#L1769)

Because this document is rather massive (1917 lines, 119 993 characters), I will mainly be focusing on the typo correction, to avoid losing the overview of my changes.

(Additional whitespace corrections and improvements are added, as a matter of course.)

Content: [Manage connections from Windows 10 operating system components to Microsoft services - Windows Privacy](https://docs.microsoft.com/en-us/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services)
Content Source: https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md
Product: **w10**
Technology: **windows**
GitHub Login: @linque1
Microsoft Alias: **robsize**

**Changes proposed:**
- Remove redundant occurrence of `_MACHINE` in Line 1766 (was 1769)
- Use UPPERCASE for HIVE_KEY (`HKEY_*`) names (business standard)
- Expand "regkey" to 'registry key' (1 occurrence)

**Codestyle and whitespace changes:**
- Reduce all triple blank lines (5x) to double (2 consecutive blank lines should be enough for MarkDown and HTML)
- Normalize number list and bullet point list spacing to 1 blank space in front of the text content
- Standardize MarkDown indent marker compatibility spacing, add missing blank space in Note blobs
- Normalize spacing between sentences, reduce to a single space after sentence period dots.
- Remove all redundant End-Of-Line blank spaces (140 characters)
- Add missing NewLine at End-Of-File (EOF)

**Ticket reference or closure:**

Closes #9373

2021-03-28 20:59 UTC, illfated reviewed
To save yourself from the big job of scrolling through the entire document, use **Hide whitespace changes** to view only the actual effective text changes:
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9374/files?diff=unified&w=1

A similar effect can be achieved when using the **Rich Diff view**, although it is more oriented towards the GitHub document Layout:
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9374/files?diff=unified&w=1&short_path=22e2027

2021-03-28 21:01 UTC, illfated commented
@JohanFreelancer9 : Please provide your copy review services as usual. Thank you.

2021-03-28 21:03 UTC, illfated commented
#sign-off

2021-03-29 03:20 UTC, JohanFreelancer9 commented on windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md
>  To use Microsoft Intune cloud based device management for restricting traffic please refer to the [Manage connections from Windows 10 operating system components to Microsoft services using Microsoft
```suggestion
To use Microsoft Intune cloud-based device management for restricting traffic please refer to the [Manage connections from Windows 10 operating system components to Microsoft services using Microsoft Intune MDM Server](./manage-connections-from-windows-operating-system-components-to-microsoft-services-using-mdm.md).
```

2021-03-29 03:34 UTC, JohanFreelancer9 commented on windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md
>  - Create a REG_DWORD registry setting named **LetAppsAccessAccountInfo** in **HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy** with a value of 2 (two).
```suggestion
- Create a REG_DWORD registry setting named **LetAppsAccessAccountInfo** in **HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy** with a **value of 2 (two)**
```

2021-03-29 03:37 UTC, JohanFreelancer9 commented on windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md
> +- Create a REG_DWORD registry setting named **DisableTailoredExperiencesWithDiagnosticData** in **HKEY_CURRENT_USER\\SOFTWARE\\Policies\\Microsoft\\Windows\\CloudContent** with a value of **1**
```suggestion
- Create a REG_DWORD registry setting named **DisableTailoredExperiencesWithDiagnosticData** in **HKEY_CURRENT_USER\\SOFTWARE\\Policies\\Microsoft\\Windows\\CloudContent** with a **value of 1 (one)**
```

2021-03-29 03:40 UTC, JohanFreelancer9 commented on windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md
>  - Create a REG_DWORD registry setting named **NoAcquireGT** in **HKEY_LOCAL_MACHINE\\Software\\Policies\\Microsoft\\Windows NT\\CurrentVersion\\Software Protection Platform** with a value of 1 (one).
```suggestion
- Create a REG_DWORD registry setting named **NoAcquireGT** in **HKEY_LOCAL_MACHINE\\Software\\Policies\\Microsoft\\Windows NT\\CurrentVersion\\Software Protection Platform** with a **value of 1 (one)**.
```

2021-03-29 03:42 UTC, JohanFreelancer9 commented on windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md
> +> Due to a known issue the **Turn off KMS Client Online AVS Validation** group policy does not work as intended on Windows Server 2016, the **NoAcquireGT** value needs to be set instead.
```suggestion
> Due to a known issue the **Turn off KMS Client Online AVS Validation** group policy does not work as intended on Windows Server 2016; the **NoAcquireGT** value needs to be set instead.
```

2021-03-29 03:44 UTC, JohanFreelancer9 commented on windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md
> +> Beginning with Windows 10, version 1803, Wi-Fi Sense is no longer available. The following section only applies to Windows 10, version 1709 and prior. Please see [Connecting to open Wi-Fi hotspots
```suggestion
> Beginning with Windows 10, version 1803, Wi-Fi Sense is no longer available. The following section only applies to Windows 10, version 1709 and prior. Please see [Connecting to open Wi-Fi hotspots in Windows 10](https://privacy.microsoft.com/windows-10-open-wi-fi-hotspots) for more details.
```

2021-03-29 03:50 UTC, JohanFreelancer9 commented on windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md
>  - Add a REG_DWORD value named **UseWUServer** to **HKEY_LOCAL_MACHINE\\Software\\Policies\\Microsoft\\Windows\WindowsUpdate\\AU** and set the value to 1.
```suggestion
- Add a REG_DWORD value named **UseWUServer** to **HKEY_LOCAL_MACHINE\\Software\\Policies\\Microsoft\\Windows\WindowsUpdate\\AU** and set the **value to 1 (one)**.
```

2021-03-29 03:52 UTC, JohanFreelancer9 commented on windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md
>  - Add a REG_DWORD value named **HapDownloadEnabled** to **HKEY_LOCAL_MACHINE\\Software\\Microsoft\\LexiconUpdate\\loc_0804** and set the value to 0.
```suggestion
- Add a REG_DWORD value named **HapDownloadEnabled** to **HKEY_LOCAL_MACHINE\\Software\\Microsoft\\LexiconUpdate\\loc_0804** and set the **value to 0 (zero)**.
```

2021-03-29 03:57 UTC, JohanFreelancer9 requested changes
A few additional suggestions, mainly for consistency.

2021-03-29 16:23 UTC, illfated commented
Thank you, those looked absolutely fine. Thank you also for reviewing such a long document which I found to be somewhat tiresome and sleep-inducing on my own screen. ;-) 😉

2021-03-29 16:24 UTC, illfated commented
#sign-off

2021-03-30 05:46 UTC, JohanFreelancer9 approved these changes

2021-03-30 17:38 UTC, illfated commented
#sign-off

2021-03-30 17:40 UTC, illfated commented
@denisebmsft : Please assign someone to perform final review & merge.

2021-04-06 12:24 UTC, merged