add info about cache expiration
MicrosoftDocs/windows-itpro-docs pull request #9401
Opened 2021-04-09 06:37 UTC by VLG17

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9182#issuecomment-815945339

2021-04-10 02:42 UTC, illfated commented on windows/security/threat-protection/security-policy-settings/interactive-logon-number-of-previous-logons-to-cache-in-case-domain-controller-is-not-available.md
> +> The cached account information does not expire, but can get overwritten, as described previously.
Minor grammar adjustment
```suggestion
> The cached account information does not expire, but can get overwritten, as previously described.
```

2021-04-10 03:01 UTC, JohanFreelancer9 requested changes
Copy review - only @illfated's suggestion.

2021-04-12 11:52 UTC, nam31 commented
@Dansimp PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-12 17:05 UTC, illfated commented
@VLG17 : Would you be so kind as to commit the suggested change and make this PR ready for final review & merge?

2021-04-12 18:58 UTC, illfated approved these changes

2021-04-12 21:42 UTC, merged