added detail to the note section
MicrosoftDocs/windows-itpro-docs pull request #9404
Opened 2021-04-11 03:49 UTC by MaratMussabekov

source: https://docs.microsoft.com/en-us/windows/client-management/determine-appropriate-page-file-size
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9392

2021-04-11 03:49 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

2021-04-11 15:23 UTC, JohanFreelancer9 commented on windows/client-management/introduction-page-file.md
>  >[!Note]
```suggestion
>[!NOTE]
```

2021-04-11 15:26 UTC, JohanFreelancer9 commented on windows/client-management/introduction-page-file.md
> +>System-managed page files automatically grow up to three times the physical memory or 4 GB (whichever is larger, but no more than 1/8 of the volume size) when the system commit charge reaches 90 per
```suggestion
>System-managed page files automatically grow up to three times the physical memory or 4 GB (whichever is larger, but no more than one-eighth of the volume size) when the system commit charge reaches 90 percent of the system commit limit. This assumes that enough free disk space is available to accommodate the growth.
```

2021-04-11 15:28 UTC, JohanFreelancer9 requested changes
Copy review,

2021-04-11 20:54 UTC, illfated commented on windows/client-management/introduction-page-file.md
>  >[!Note]
If possible, please also add a space after the MD indent marker (`>`).

2021-04-11 20:54 UTC, illfated commented on windows/client-management/introduction-page-file.md
> +>System-managed page files automatically grow up to three times the physical memory or 4 GB (whichever is larger, but no more than 1/8 of the volume size) when the system commit charge reaches 90 per
If possible, please also add a space after the MD indent marker (`>`).

2021-04-12 19:02 UTC, illfated approved these changes

2021-04-13 04:28 UTC, JohanFreelancer9 approved these changes

2021-04-13 17:06 UTC, illfated commented
#sign-off

2021-04-16 18:35 UTC, merged