Update note section
MicrosoftDocs/windows-itpro-docs pull request #9441
Opened 2021-04-22 12:13 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9235

2021-04-22 15:21 UTC, JohanFreelancer9 commented on windows/client-management/mdm/networkqospolicy-csp.md
> +> The NetworkQoSPolicy configuration service provider is officially supported for devices that are Intune managed and Azure AD joined. Currently, this CSP is not supported on following devices:
```suggestion
> The NetworkQoSPolicy configuration service provider is officially supported for devices that are Intune managed and Azure AD joined. Currently, this CSP is not supported on the following devices:
```

2021-04-22 15:22 UTC, JohanFreelancer9 commented on windows/client-management/mdm/networkqospolicy-csp.md
> +> - Azure AD Hybrid joined devices
```suggestion
> - Azure AD Hybrid joined devices.
```

2021-04-22 15:24 UTC, JohanFreelancer9 commented on windows/client-management/mdm/networkqospolicy-csp.md
> +> - Devices, that use both GPO and CSP at the same time
```suggestion
> - Devices that use both GPO and CSP at the same time.
```

2021-04-22 15:25 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-24 19:55 UTC, illfated approved these changes
Looks good to me.

2021-04-25 05:28 UTC, JohanFreelancer9 approved these changes

2021-05-06 18:40 UTC, merged