added notes about OnPrem_Distinguished_Name
MicrosoftDocs/windows-itpro-docs pull request #9455
Opened 2021-04-25 18:14 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9438

2021-04-25 18:15 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

2021-04-25 19:26 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md
> +   > [!Note]
```suggestion
   > [!NOTE]
```

2021-04-25 19:29 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md
> +   > If the distinguished names contain scpecial characters ("+", ",", ";" or "="), put quotation marks: CN=”{{OnPrem_Distinguished_Name}}”.
```suggestion
   > If the distinguished name contains special characters ("+", ",", ";" or "="), the bracketed name must be enclosed in quotation marks: CN=”{{OnPrem_Distinguished_Name}}”.
```

2021-04-25 19:31 UTC, illfated commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md
> +   > If the distinguished names length is more than 64 characters, name length enforcement on the Certification Authority [must be disabled](https://docs.microsoft.com/previous-versions/windows/it-pr
```suggestion
   > If the length of the distinguished name is more than 64 characters, the name length enforcement on the Certification Authority [must be disabled](https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2003/cc784789(v=ws.10)?#disable-dn-length-enforcement).
```

2021-04-25 19:34 UTC, illfated commented
The added note text might be phrased differently from what I have suggested. If you happen to know how exactly how it needs to be written to get the information across correctly, please recommend further improvements to my suggestions above.

2021-04-26 06:47 UTC, JohanFreelancer9 requested changes
Copy review - only @illfated's suggestions.

2021-04-26 18:28 UTC, illfated commented
@MaratMussabekov : Looks like my suggestions are good to use, please commit the suggestions.

2021-04-26 20:58 UTC, mapalko approved these changes

2021-04-27 16:22 UTC, illfated approved these changes
Looks good to me.

2021-04-27 16:53 UTC, JohanFreelancer9 approved these changes

2021-04-27 16:56 UTC, illfated commented
#sign-off

2021-08-07 17:54 UTC, e0i commented
@tiburd This PR has been approved by the author and can be merged. FYI.

2021-08-09 06:24 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md
> +   > If the distinguished name contains special characters like plus sign ("+"), comma (","), semicolon (";"), or equal sign ("="), the bracketed name must be enclosed in quotation marks: CN=”{{OnPre
```suggestion
   > If the distinguished name contains special characters like a plus sign ("+"), comma (","), semicolon (";"), or equal sign ("="), the bracketed name must be enclosed in quotation marks: CN=”{{OnPrem_Distinguished_Name}}”.
```

2021-08-09 06:26 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md
> +   > If the length of the distinguished name is more than 64 characters, the name length enforcement on the Certification Authority [must be disabled](https://docs.microsoft.com/previous-versions/win
```suggestion
   > If the length of the distinguished name is more than 64 characters, the name length enforcement on the Certification Authority [must be disabled](/previous-versions/windows/it-pro/windows-server-2003/cc784789(v=ws.10)?#disable-dn-length-enforcement).
```

2021-08-09 06:28 UTC, JohanFreelancer9 requested changes
@MaratMussabekov, I have approved this PR quite a while back, before the links rule change. Could you kindly also commit these two suggested changes? Many thanks.

2021-08-09 06:46 UTC, JohanFreelancer9 approved these changes
Thank you @MaratMussabekov.

2021-08-09 16:30 UTC, merged