Update deploy-enterprise-licenses.md
MicrosoftDocs/windows-itpro-docs pull request #9462
Opened 2021-04-27 12:46 UTC by GenerAhl

Clarifying Windows 10 version requirements.

2021-04-27 13:10 UTC, GenerAhl commented
Ready for review @greg-lindsay

2021-04-27 16:52 UTC, illfated approved these changes
Looks good and very apt to me.

2021-04-28 05:26 UTC, JohanFreelancer9 commented on windows/deployment/deploy-enterprise-licenses.md
> +If a device is running a version of Windows 10 Pro prior to 1703 (for example, version 1511), it will not be upgraded to Windows 10 Enterprise when a user signs in, even if the user has been assigned
```suggestion
If a device is running a version of Windows 10 Pro prior to version 1703 (for example, version 1511), it will not be upgraded to Windows 10 Enterprise when a user signs in, even if the user has been assigned a subscription in the CSP portal.
```

2021-04-28 05:27 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-28 07:16 UTC, JohanFreelancer9 approved these changes

2021-04-28 20:04 UTC, merged