Update faq-md-app-guard.md
MicrosoftDocs/windows-itpro-docs pull request #9466
Opened 2021-04-27 20:31 UTC by sazankha

Added more information regarding WDAGUtility Account.

2021-04-27 21:52 UTC, illfated commented on windows/security/threat-protection/microsoft-defender-application-guard/faq-md-app-guard.md
> +This account is a part of Application Guard beginning with Windows 10, version 1709 (Fall Creators Update). It remains disabled by default unless Application Guard is enabled on your device. WDAGUtil
minor adjustments needed:
```suggestion
This account is part of Application Guard, beginning with Windows 10, version 1709 (Fall Creators Update). It remains disabled by default, unless Application Guard is enabled on your device. The WDAGUtilityAccount is leveraged to login to the Application Guard container as a standard user with a random password. It is NOT a malicious account. If "Run as a service" permissions are revoked for this account, you may encounter the following error: "Error: 0x80070569, Ext error: 0x00000001; RDP: Error: 0x00000000, Ext error: 0x00000000 Location: 0x00000000". It is recommended not to modify this account.
```
- "part of" used as a phrase does not need the indefinite article unless there is a comparison with other parts.
- readability & grammatical commas added
- "is leveraged to login" seems unusual to me, because "leverage" usually refers to debt vs. financial equity. Did you mean "elevated", or is "leveraged" used with a different meaning in software & programming?
- "may" instead of "might": General usage; when the described result is more likely than other results.

2021-04-27 21:56 UTC, illfated commented
@sazankha : Thank you for merging my suggestions. 👍🏻

@JohanFreelancer9 : Could you take a look at the usage of "leveraged" in this PR content to verify that it is used correctly?

2021-04-28 04:43 UTC, JohanFreelancer9 commented on windows/security/threat-protection/microsoft-defender-application-guard/faq-md-app-guard.md
> +This account is part of Application Guard, beginning with Windows 10, version 1709 (Fall Creators Update). It remains disabled by default, unless Application Guard is enabled on your device. The WDAG
```suggestion
This account is part of Application Guard, beginning with Windows 10, version 1709 (Fall Creators Update). It remains disabled by default, unless Application Guard is enabled on your device. The WDAGUtilityAccount is leveraged to sign in to the Application Guard container as a standard user with a random password. It is NOT a malicious account. If "Run as a service" permissions are revoked for this account, you may encounter the following error: "Error: 0x80070569, Ext error: 0x00000001; RDP: Error: 0x00000000, Ext error: 0x00000000 Location: 0x00000000". We recommend not to modify this account.
```

2021-04-28 04:49 UTC, JohanFreelancer9 requested changes
@sazankha - please commit my additional edits. Many thanks.
@illfated - the use of "leveraged" in this instance is correct - loosely meaning "using something to maximum advantage".

2021-04-28 14:02 UTC, illfated commented
Very good. Thank you.

2021-04-28 19:56 UTC, denisebmsft approved these changes
Thank you @sazankha

2021-04-28 19:56 UTC, merged