Applied to Win Server 2019
MicrosoftDocs/windows-itpro-docs pull request #9470
Opened 2021-04-28 18:43 UTC by joinimran

As this approach is also applicable on Windows Server 2019 so updating this accordingly. 

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9375

2021-04-28 18:43 UTC, joinimran commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2021-04-28 22:33 UTC, illfated commented on windows/security/threat-protection/windows-firewall/isolated-domain.md
> +-   Windows Server 2019
General codestyle improvement suggestion:
```suggestion
**Applies to:**
- Windows 10
- Windows Server 2016
- Windows Server 2019
```

2021-04-29 03:02 UTC, JohanFreelancer9 requested changes
Only @illfated's suggestion.

2021-04-29 13:25 UTC, JohanFreelancer9 approved these changes

2021-04-29 14:13 UTC, illfated approved these changes
Looks good to me.

2021-04-29 14:13 UTC, illfated commented
#sign-off

2021-04-29 16:15 UTC, merged