addition of note
MicrosoftDocs/windows-itpro-docs pull request #9471
Opened 2021-04-28 19:06 UTC by joinimran

The event Ids mentioned in this document don't apply to the windows server core edition.

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9429

2021-04-28 19:06 UTC, joinimran commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2021-04-28 22:31 UTC, illfated commented on windows/security/threat-protection/windows-defender-application-control/event-id-explanations.md
> +> [!Note]
```suggestion
> [!NOTE]
```
(I don't have an improvement suggestion for the sentence below, but maybe JohanFreelancer9 can provide one.)

2021-04-29 03:15 UTC, JohanFreelancer9 requested changes
Copy review - only @illfated's suggestion.

2021-04-29 13:41 UTC, JohanFreelancer9 approved these changes

2021-04-29 14:12 UTC, illfated approved these changes
Looks good to me. In accordance with the issue ticket.

2021-04-29 18:22 UTC, nam31 commented
@Dansimp PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-29 18:57 UTC, illfated commented
#sign-off

2021-06-15 22:01 UTC, merged