update machine inactivity limit policy
MicrosoftDocs/windows-itpro-docs pull request #9486
Opened 2021-05-03 04:31 UTC by MaratMussabekov

https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9448

2021-05-03 04:31 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

2021-05-03 04:46 UTC, JohanFreelancer9 commented on windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md
> +Valid values: from 0 to 599940, where the value is the amount of inactivity time (in seconds), after which the session will be locked. If it is set to zero (0), the  setting is disabled.
```suggestion
Valid values: From 0 to 599940, where the value is the amount of inactivity time (in seconds) after which the session will be locked. If it is set to zero (0), the setting is disabled.
```

2021-05-03 04:47 UTC, JohanFreelancer9 requested changes
Copy review.

2021-05-04 11:49 UTC, illfated approved these changes
Looks good to me. Thank you for updating this page with the correct value type.

2021-05-04 12:57 UTC, JohanFreelancer9 approved these changes

2021-05-04 18:43 UTC, nam31 commented
@Dansimp PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-09 00:06 UTC, merged