Document ProxyServers property
MicrosoftDocs/windows-itpro-docs pull request #9494
Opened 2021-05-05 22:16 UTC by DanPandre

This was initially documented in https://techcommunity.microsoft.com/t5/surface-it-pro-blog/surface-hub-proxy-improvements/ba-p/636156 but the CSP should have this information as well.

2021-05-05 22:40 UTC, illfated approved these changes
Easier review by applying the Rich Diff view:
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9494/files?short_path=c8eb73a

Looks good to me.

2021-05-06 10:32 UTC, JohanFreelancer9 commented on windows/client-management/mdm/surfacehub-csp.md
> +<p style="margin-left: 20px">Added in <a href="https://support.microsoft.com/en-us/topic/may-28-2019-kb4499162-os-build-15063-1839-ed6780ab-38d6-f590-d789-5ba873b1e142" data-raw-source="[KB4499162](h
```suggestion
<p style="margin-left: 20px">Added in <a href="https://support.microsoft.com/topic/may-28-2019-kb4499162-os-build-15063-1839-ed6780ab-38d6-f590-d789-5ba873b1e142" data-raw-source="[KB4499162](https://support.microsoft.com/en-us/topic/may-28-2019-kb4499162-os-build-15063-1839-ed6780ab-38d6-f590-d789-5ba873b1e142)">KB4499162</a> for Windows 10, version 1703. Specifies FQDNs of proxy servers to provide device account credentials to before any user interaction (if AllowAutoProxyAuth is enabled). This is a semi-colon separated list of server names, without any additional prefixes (e.g. https://).
```

2021-05-06 10:33 UTC, JohanFreelancer9 requested changes
Copy review - please remove the locale from the link.

2021-05-08 03:04 UTC, JohanFreelancer9 approved these changes

2021-06-09 00:11 UTC, merged