"Disable WDAC Policies": Cleanup formatting
MicrosoftDocs/windows-itpro-docs pull request #9527
Opened 2021-05-14 01:14 UTC by sewillia-msft

This PR performs a few list/callout-related changes to the article ["Disable Windows Defender Application Control Policies"](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/disable-windows-defender-application-control-policies):  
* Move list of WDAC policy locations into "Note" callout referencing them
* Replace boldface "Note"  with DFM `[!NOTE]` tags

2021-05-14 03:20 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/disable-windows-defender-application-control-policies.md
>  -   &lt;EFI System Partition&gt;\\Microsoft\\Boot\\
```suggestion
> 
> * &lt;EFI System Partition&gt;\\Microsoft\\Boot\\
> * &lt;OS Volume&gt;\\Windows\\System32\\CodeIntegrity\\
```

2021-05-14 03:20 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/disable-windows-defender-application-control-policies.md
>  -   &lt;OS Volume&gt;\\Windows\\System32\\CodeIntegrity\\
```suggestion
```

2021-05-14 03:21 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/disable-windows-defender-application-control-policies.md
>  -   &lt;EFI System Partition&gt;\\Microsoft\\Boot\\
```suggestion
> 
> * &lt;EFI System Partition&gt;\\Microsoft\\Boot\\
> * &lt;OS Volume&gt;\\Windows\\System32\\CodeIntegrity\\
```

2021-05-14 03:21 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/disable-windows-defender-application-control-policies.md
>  -   &lt;OS Volume&gt;\\Windows\\System32\\CodeIntegrity\\
```suggestion
```

2021-05-14 03:23 UTC, JohanFreelancer9 requested changes
Copy review. @sewillia-msft, please commit my suggested changes. Many thanks.

2021-05-14 22:48 UTC, sewillia-msft commented
@JohanFreelancer9, is there any specific requirement in the style guide that lists must be enclosed in quote-blocks like that? The only reason I did that for the list around L45 is because the previous statement contextualizing/referring to said list was already in a `[!NOTE]` quote-block:
![image](https://user-images.githubusercontent.com/72675818/118330263-5d791600-b4bc-11eb-8350-84ea732b6a80.png)

2021-05-15 03:32 UTC, illfated commented
Good question. I was wondering the same, because I have not seen this formatting style yet, unless it is to include it as a part of a [!NOTE] blob.

2021-05-15 07:30 UTC, JohanFreelancer9 commented
@sewillia-msft, you are absolutely correct. Sorry about that, it is totally my mistake, and thank you for pointing it out. There certainly is no such requirement and I have deleted my suggested changes. Thanks again.

2021-05-15 07:34 UTC, JohanFreelancer9 approved these changes

2021-05-15 07:35 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/disable-windows-defender-application-control-policies.md
>  -   &lt;OS Volume&gt;\\Windows\\System32\\CodeIntegrity\\
```suggestion
-   &lt;OS Volume&gt;\\Windows\\System32\\CodeIntegrity\\
```

2021-05-15 11:05 UTC, illfated approved these changes
Looks good to me. I might get back to this document at a later time for some whitespace cleanup.

2021-05-17 16:59 UTC, merged