removed link
MicrosoftDocs/windows-itpro-docs pull request #9528
Opened 2021-05-14 13:47 UTC by RAJU2529

as per user report #9518, so i removed security boundary link

2021-05-14 18:49 UTC, illfated commented on windows/security/threat-protection/windows-defender-application-control/applocker/applocker-overview.md
> +> AppLocker is a defense-in-depth security feature and not a security boundary.[Windows Defender Application Control](https://www.microsoft.com/msrc/windows-security-servicing-criteria) should be use
Looks almost OK, it just needs a normal sentence spacing between those two sentences. (Always keep at least one space between the period ending one sentence and the next sentence.):
```suggestion
> AppLocker is a defense-in-depth security feature and not a security boundary. [Windows Defender Application Control](https://www.microsoft.com/msrc/windows-security-servicing-criteria) should be used when the goal is to provide robust protection against a threat and there are expected to be no by-design limitations that would prevent the security feature from achieving this goal.
```
Also, I am uncertain why not keep the **bold** formatting around **not** in the first sentence, since it appears to be an important part of the information.

2021-05-15 07:44 UTC, JohanFreelancer9 approved these changes

2021-05-15 10:38 UTC, illfated approved these changes

2021-05-15 22:03 UTC, grnathan commented on windows/security/threat-protection/windows-defender-application-control/applocker/applocker-overview.md
> +> AppLocker is a defense-in-depth security feature and not a security boundary.[Windows Defender Application Control](https://www.microsoft.com/msrc/windows-security-servicing-criteria) should be use
I would have thought it makes more sense to delete the second link to /msrc/windows-security-servicing-criteria, not the first.  As per: 

`> AppLocker is a defense-in-depth security feature and not a [security boundary].(https://www.microsoft.com/msrc/windows-security-servicing-criteria) Windows Defender Application Control  should be used when the goal is to provide robust protection against a threat and there are expected to be no by-design limitations that would prevent the security feature from achieving this goal.
`

Better yet, find a suitable reference for Windows Defender Application Control and link there in place of the current link to /msrc/windows-security-servicing-criteria

2021-05-16 00:33 UTC, illfated commented
@JohanFreelancer9 : I don't know if you noticed, I commented about the removal of bold formatting in the following line:
```diff
- > AppLocker is a defense-in-depth security feature and **not** a [security boundary]().
+ > AppLocker is a defense-in-depth security feature and not a security boundary.
```
What is your view, does MS codestyle suggest that this removal is preferable, or would it improve the intended meaning of the sentence to keep it?

2021-05-16 06:48 UTC, JohanFreelancer9 commented
@illfated - Removal of the bold formatting is correct. I am happy to leave it as is. MS codestyle, however, strongly suggests not using bold formatting for emphasis but rather _italics_. Thank you for picking up on that, I hope this answers your question.

2021-05-16 07:52 UTC, illfated commented
It does. Thank you very much for the adequate answer.

2021-05-28 17:04 UTC, illfated commented
Also, note the user feedback after my suggestion comment:

> I would have thought it makes more sense to delete the second link to /msrc/windows-security-servicing-criteria, not the first. As per:
>
> AppLocker is a defense-in-depth security feature and not a [security boundary].(https://www.microsoft.com/msrc/windows-security-servicing-criteria) Windows Defender Application Control should be used when the goal is to provide robust protection against a threat and there are expected to be no by-design limitations that would prevent the security feature from achieving this goal.
>
> Better yet, find a suitable reference for Windows Defender Application Control and link there in place of the current link to /msrc/windows-security-servicing-criteria

2021-05-31 04:27 UTC, JohanFreelancer9 commented
@Kateyanne - the link https://www.microsoft.com/msrc/windows-security-servicing-criteria is correctly formatted as it is a link to a Microsoft article outside the doc set.

2021-05-31 09:34 UTC, RAJU2529 commented
@JohanFreelancer9 , do you require any modifications from my side for this issue #9528 . Please reply to me

2021-05-31 13:15 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/applocker/applocker-overview.md
> +> AppLocker is a defense-in-depth security feature and not a security boundary. [Windows Defender Application Control](https://www.microsoft.com/msrc/windows-security-servicing-criteria) should be us
```suggestion
> AppLocker is a defense-in-depth security feature and not a [security boundary](https://www.microsoft.com/msrc/windows-security-servicing-criteria). [Windows Defender Application Control](/windows/security/threat-protection/windows-defender-application-control/wdac-and-applocker-overview) should be used when the goal is to provide robust protection against a threat and there are expected to be no by-design limitations that would prevent the security feature from achieving this goal.
```

2021-05-31 13:17 UTC, JohanFreelancer9 requested changes
@RAJU2529 - after reading the comments, I have suggested the necessary changes. Could you please commit these changes if you agree with them? Many thanks.

2021-05-31 13:19 UTC, RAJU2529 commented
@JohanFreelancer9  committed changes are finished

2021-05-31 13:19 UTC, JohanFreelancer9 approved these changes

2021-05-31 14:04 UTC, illfated approved these changes
Looks good to me, in accordance with the issue ticket.

2021-06-01 14:43 UTC, merged