Note addition to the Countermeasure section
MicrosoftDocs/windows-itpro-docs pull request #9531
Opened 2021-05-16 08:22 UTC by illfated

**Description:**

As requested in issue ticket #9523 (**Please add a note**), the aim of this PR is to add a note to the Countermeasure section of the document article "Deny access to this computer from the network".

Thanks to Daniele Bona (dbona75) (dabona@microsoft.com) for the request.

**Proposed change:**

- Add a Note blob explaining the required Network Logon rights to the domain controllers.

**Codestyle & whitespace changes:**

- Remove any redundant end-of-line (EOL) blanks.
- Standardize indent whitespace in numbered lists and bullet point lists to one single blank space.

**Additional notes:**

- The added note could possibly benefit from improved phrasing, I am not sure if the current phrasing is clear enough.
- I also updated the article date to 05/19/2021 (from 04/19/2017), but this may be changed to a more accurate date by the person merging this PR.

**Ticket closure or reference:**

Closes #9523

2021-05-16 08:25 UTC, illfated reviewed
Regular source file view:
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9531/files

To skip the lines containing only whitespace reduction, Rich Diff view:
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9531/files?diff=unified&w=1

2021-05-16 08:25 UTC, illfated commented
#sign-off

2021-05-17 16:02 UTC, JohanFreelancer9 commented on windows/security/threat-protection/security-policy-settings/deny-access-to-this-computer-from-the-network.md
> +> it requires Network Logon rights to the domain controllers to start properly.
```suggestion
> If the service account is configured in the logon properties of a Windows service, it requires network logon rights to the domain controllers to start properly.
```

2021-05-17 16:02 UTC, JohanFreelancer9 requested changes
Copy review.

2021-05-17 16:58 UTC, merged