addition of note
MicrosoftDocs/windows-itpro-docs pull request #9544
Opened 2021-05-19 07:55 UTC by joinimran

As KB4564442 is generally required for seamless implementation of the procedure so added a note for the same.

Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9484

2021-05-19 07:56 UTC, joinimran commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

@nam31 FYI Please.

2021-05-19 09:05 UTC, JohanFreelancer9 commented on windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image.md
> +> [KB4564442](https://download.microsoft.com/download/3/0/6/306AC1B2-59BE-43B8-8C65-E141EF287A5E/KB4564442/MDT_KB4564442.exe) needs to be download for Windows 10 deployments using the Microsoft Deplo
```suggestion
> [KB4564442](https://download.microsoft.com/download/3/0/6/306AC1B2-59BE-43B8-8C65-E141EF287A5E/KB4564442/MDT_KB4564442.exe) needs to be downloaded for Windows 10 deployments using the Microsoft Deployment Toolkit (MDT) to prevent failure when used with the Windows Assessment and Deployment Kit (ADK). See [Windows 10 deployments fail with Microsoft Deployment Toolkit on computers with BIOS type firmware](https://support.microsoft.com/topic/windows-10-deployments-fail-with-microsoft-deployment-toolkit-on-computers-with-bios-type-firmware-70557b0b-6be3-81d2-556f-b313e29e2cb7).
```

2021-05-19 09:07 UTC, JohanFreelancer9 requested changes
Copy review.

2021-05-19 09:18 UTC, JohanFreelancer9 approved these changes

2021-05-19 18:06 UTC, illfated approved these changes
Looks good to me.

2021-05-20 15:50 UTC, greg-lindsay reviewed
See https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/prepare-for-windows-deployment-with-mdt#install-the-windows-adk

We do not need this note here because the previous article where we cover installation of the ADK instructs the user to add the optional patch

2021-05-20 15:55 UTC, closed without merging