added  Allow Update Compliance Processing
MicrosoftDocs/windows-itpro-docs pull request #9554
Opened 2021-05-20 15:48 UTC by RAJU2529

as per user feedback issue #9540,  so I added  **Allow Update Compliance Processing**   policy-related settings in this article, after looking at GPO in windows 10  pre release build 21h1 19043.985.

2021-05-20 16:39 UTC, illfated commented on windows/client-management/mdm/policy-csp-system.md
> +    <a href="#system-allowusertoresetphone">System/AllowUpdateComplianceProcessing</a>
To make this link work as advertised, it needs to point to the added section below:
```suggestion
    <a href="#system-allowUpdateComplianceProcessing">System/AllowUpdateComplianceProcessing</a>
```

2021-05-20 16:45 UTC, illfated commented
Rich Diff view of the PR file content, for easier review:
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9554/files?short_path=a9e7961#diff-a9e7961d419e9c9deb75a159668a32d7b33abb3d8992affbd85e6eb802a8e62a

2021-05-20 17:51 UTC, RAJU2529 commented
@illfated . Tomorrow morning I create new PR

2021-05-21 07:25 UTC, JohanFreelancer9 commented on windows/client-management/mdm/policy-csp-system.md
> +If you enable this setting, Enables data flow through Update Compliance's data processing system and indicates a device's explicit enrollment to the service.
```suggestion
If you enable this setting, it enables data flow through Update Compliance's data processing system and indicates a device's explicit enrollment to the service.
```

2021-05-21 07:28 UTC, JohanFreelancer9 requested changes
Copy review.

2021-05-21 08:59 UTC, RAJU2529 commented
@illfated . i created new PR #9559 , so look

2021-05-21 10:16 UTC, illfated commented
Very well. Just remember that if this PR (#9554) gets merged before the other PR (#9559), the merge result will add approximately 70 lines to the line numbers in PR #9559 , making it necessary to resolve a file conflict. Hope it will be easy enough for you to resolve.

2021-05-21 12:36 UTC, JohanFreelancer9 approved these changes

2021-06-09 00:13 UTC, merged