Update manage-connections-from-windows-operating-system-components-to…
MicrosoftDocs/windows-itpro-docs pull request #9561
Opened 2021-05-21 16:28 UTC by TomLayson

…-microsoft-services.md

Minor text change

2021-05-21 17:47 UTC, illfated commented on windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md
> +> Feedback frequency only applies to user-generated feedback, not diagnostic and usage data sent from the device.
This extra space is not required and can be safely omitted.
```suggestion
> Feedback frequency only applies to user-generated feedback, not diagnostic and usage data sent from the device.
```

2021-05-21 19:03 UTC, illfated commented
Looks fairly good, just a couple of questions of minor importance regarding the added table:
- Would it be OK to align the cell dividers between column 1 and column 2, for easier future editing?
- Would it be desirable to keep the text within one and the same row, while still having a Line Break/NewLine between the current "row 1" and "row 2" of the values part of the table?

Example to accompany question 2:

| Policy                        | Group Policy Path  | Registry Path                               |
|-------------------------------|--------------------|---------------------------------------------|
| **SearchSuggestEnabled**      |  Computer Configuration/Administrative Templates/Windows Component/Microsoft Edge - Enable search suggestions<br> **Set to Disabled**  | HKEY_LOCAL_MACHINE \SOFTWARE\Policies\Microsoft\Edge<br>**REG_DWORD name: SearchSuggestEnabled Set to 0** |
| **AutofillAddressEnabled**    |  Computer Configurations/Administrative Templates/Windows Component/Microsoft Edge - Enable AutoFill for addresses<br> **Set to Disabled** | HKEY_LOCAL_MACHINE \SOFTWARE\Policies\Microsoft\Edge<br>  **REG_DWORD name: AutofillAddressEnabled Set to 0** |
| **AutofillCreditCardEnabled** |  Computer Configurations/Administrative Templates/Windows Component/Microsoft Edge - Enable AutoFill for credit cards<br> **Set to Disabled** | HKEY_LOCAL_MACHINE \SOFTWARE\Policies\Microsoft\Edge<br> **REG_DWORD name: AutofillCreditCardEnabled Set to 0** |

2021-05-24 04:07 UTC, JohanFreelancer9 commented on windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md
> +For a complete list of the Microsoft Edge policies, see [Microsoft Edge and privacy: FAQ](https://docs.microsoft.com/en-us/microsoft-edge/deploy/available-policies).
```suggestion
For a complete list of the Microsoft Edge policies, see [Group Policy and Mobile Device Management (MDM) settings for Microsoft Edge](/microsoft-edge/deploy/available-policies). 
```

2021-05-24 04:08 UTC, JohanFreelancer9 commented on windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md
> +> [!Important]
```suggestion
> [!IMPORTANT]
```

2021-05-24 04:09 UTC, JohanFreelancer9 commented on windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md
> +> - The following settings are applicable to Microsoft Edge version 77 or later.
```suggestion
> - The following settings are applicable to Microsoft Edge version 77 or later. 
```
```suggestion
> - The following settings are applicable to Microsoft Edge version 77 or later.
```

2021-05-24 04:10 UTC, JohanFreelancer9 commented on windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md
> +> - For details on supported Operating Systems see Microsoft Edge supported Operating Systems
```suggestion
> - For details on supported Operating Systems, see [Microsoft Edge supported Operating Systems](/deployedge/microsoft-edge-supported-operating-systems).
```

2021-05-24 04:12 UTC, JohanFreelancer9 commented on windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md
> +> - These policies require the Microsoft Edge administrative templates to be applied. For more information on administrative templates for Microsoft Edge see Configure Microsoft Edge policy settings
```suggestion
> - These policies require the Microsoft Edge administrative templates to be applied. For more information on administrative templates for Microsoft Edge, see [Configure Microsoft Edge policy settings on Windows](/deployedge/configure-microsoft-edge).
```

2021-05-24 04:12 UTC, JohanFreelancer9 commented on windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md
> +> - Devices must be domain joined for some of the policies to take effect.
```suggestion
> - Devices must be domain joined for some of the policies to take effect.
```

2021-05-24 04:19 UTC, JohanFreelancer9 requested changes
Copy review.

2021-05-25 09:16 UTC, siosulli commented
Thanks @JohanFreelancer9 I have committed your suggestions and merged the PR.

2021-05-25 09:16 UTC, merged