removed device word
MicrosoftDocs/windows-itpro-docs pull request #9610
Opened 2021-05-31 16:21 UTC by RAJU2529

this is my own PR i removed word **Device**

2021-05-31 21:17 UTC, illfated commented
@RAJU2529 : Could you please take me through the reasoning behind your choice to remove the word?

From my point of view, that text mirrors the page title, so I don't see the reason for making this change. Please help me understand.

2021-06-01 05:45 UTC, JohanFreelancer9 commented on windows/client-management/mdm/healthattestation-csp.md
> +title: HealthAttestation CSP
```suggestion
title: Device HealthAttestation CSP
```

2021-06-01 05:46 UTC, JohanFreelancer9 requested changes
Agree with @illfated

2021-06-01 05:49 UTC, RAJU2529 commented on windows/client-management/mdm/healthattestation-csp.md
> +title: HealthAttestation CSP
@JohanFreelancer9 . This **HealthAttestation CSP** is mentioned in below article

https://docs.microsoft.com/en-us/windows/client-management/mdm/configuration-service-provider-reference

so thats why I removed device

2021-06-01 06:20 UTC, JohanFreelancer9 approved these changes

2021-06-15 22:01 UTC, merged