added CSP link
MicrosoftDocs/windows-itpro-docs pull request #9619
Opened 2021-05-31 16:35 UTC by RAJU2529

this is my own PR, i added CSP link under Related topics

2021-05-31 21:59 UTC, illfated commented on windows/client-management/mdm/policymanager-csp.md
> +## Related topics
```suggestion
## See also
```

2021-06-01 04:04 UTC, RAJU2529 commented on windows/client-management/mdm/policymanager-csp.md
> +## Related topics
@illfated . sorry i cant commit change, because in most articles Related topics are already added by the authors

2021-06-01 05:30 UTC, JohanFreelancer9 commented on windows/client-management/mdm/policymanager-csp.md
>  > **Note**   The PolicyManager CSP is supported in Windows 10 Mobile for backward compatibility. For Windows 10 devices you should use [Policy CSP](policy-configuration-service-provider.md), which re
```suggestion
> [!NOTE]
> The PolicyManager CSP is supported in Windows 10 Mobile for backward compatibility. For Windows 10 devices you should use [Policy CSP](policy-configuration-service-provider.md), which replaces PolicyManager CSP. You can continue to use PolicyManager CSP for Windows Phone 8.1 and Windows Phone 8.1 GDR devices.
```

2021-06-01 05:31 UTC, JohanFreelancer9 requested changes
@RAJU2529 - Not related to your PR but could you please also correct the Note formatting? Many thanks.

2021-06-01 06:20 UTC, JohanFreelancer9 approved these changes

2021-06-01 12:13 UTC, illfated commented on windows/client-management/mdm/policymanager-csp.md
> +## Related topics
Untrue. You added this line. You are therefore free to modify it before it gets merged.

2021-06-08 13:06 UTC, closed without merging