formatted table properly. added cross check marks
MicrosoftDocs/windows-itpro-docs pull request #9632
Opened 2021-05-31 18:19 UTC by RAJU2529

this is my own PR,
01.
 I added   Checkmarks only for Business  edition  if  under Professional and Enterprise are already added Checkmarks.

02.
 I added   Crossmarks only for Business  edition  if   under Professional and Enterprise are already added Crossmarks.

03.
Removed the following words
 **Only for mobile application management (MAM)**
**Provisioning only** 

04.
Added footnotes  
**A- Only for mobile application management (MAM)**
**B- Provisioning only**

2021-05-31 18:42 UTC, illfated commented on windows/client-management/mdm/configuration-service-provider-reference.md
> +- B - Provisioning only
This PR looks very good to me format-wise, we only need to remove some redundant whitespace (blanks) here:
```suggestion
- A - Only for mobile application management (MAM)
- B - Provisioning only
```

2021-05-31 18:47 UTC, illfated reviewed
Seems like a very good idea to implement the footnotes A and B, to follow the codestyle of numbering the Windows versions.

Rich Diff view, to simplify the review process:
- https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9632/files?short_path=b0c1433#diff-b0c143366f62d1fa18dac35243db9180ef9c6dbcf5b896a4f8147d91ce4f3112

Knowing that I don't have any working experience with CSP and provisioning, I select to merit the changes based on the formatting, rather than content. I defer to the document author or manager for content approval.

2021-05-31 18:50 UTC, illfated commented
( Ref. our conversations in issue ticket **non-functioning links** #9584 )

2021-05-31 20:36 UTC, theonlycoder commented
Thank you for taking the time to put this together following on from my original issue. 

Before merging, has anyone been able to confirm for sure whether my assumption that all CSPs that are  supported in Pro edition would also be supported in Business edition is correct?

2021-05-31 20:56 UTC, illfated commented
Thank you for asking, that is appropriate and useful. Count me out, because I am not fluent in this topic, as well as not having used this technology myself. All I can provide is formatting advice, so I defer to the MS Docs team members, the document author or manager, or possibly the tech writers for MS Docs.

2021-05-31 21:32 UTC, illfated commented
( also ref. issue ticket **Confusion regarding AppLocker CSP support with Windows 10 Business edition** #9560 )

2021-06-01 04:55 UTC, JohanFreelancer9 approved these changes

2021-06-01 05:17 UTC, JohanFreelancer9 commented on windows/client-management/mdm/configuration-service-provider-reference.md
> +- A - Only for mobile application management (MAM)
```suggestion
- A - Only for mobile application management (MAM).
```

2021-06-01 05:17 UTC, JohanFreelancer9 commented on windows/client-management/mdm/configuration-service-provider-reference.md
> +- B - Provisioning only
```suggestion
- B - Provisioning only.
```

2021-06-01 05:17 UTC, JohanFreelancer9 commented on windows/client-management/mdm/configuration-service-provider-reference.md
>  - 9 - Added in Windows 10 Team 2020 Update
```suggestion
- 9 - Added in Windows 10 Team 2020 Update
```
```suggestion
- 9 - Added in Windows 10 Team 2020 Update.
```

2021-06-01 05:17 UTC, JohanFreelancer9 commented on windows/client-management/mdm/configuration-service-provider-reference.md
> +- 10 - Added in [Windows Holographic, version 20H2](/hololens/hololens-release-notes#windows-holographic-version-20h2)
```suggestion
- 10 - Added in [Windows Holographic, version 20H2](/hololens/hololens-release-notes#windows-holographic-version-20h2).
```

2021-06-01 05:18 UTC, JohanFreelancer9 requested changes
@RAJU2529 - Could you please just add the periods (.) at the end of the lines? Thanks.

2021-06-01 05:19 UTC, JohanFreelancer9 approved these changes

2021-06-01 06:23 UTC, JohanFreelancer9 approved these changes

2021-06-01 12:07 UTC, illfated approved these changes
Looks good to me, format-wise. (https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9632/files/818a12067925afaadc3bc520df2a63a3c25d6ff1?short_path=b0c1433#diff-b0c143366f62d1fa18dac35243db9180ef9c6dbcf5b896a4f8147d91ce4f3112)

I refer to the document author or manager for content change validation.

2021-06-15 22:02 UTC, merged

2021-06-17 09:33 UTC, RAJU2529 commented
sincere thanks to @JohanFreelancer9 for suggestions to improve this article  and Thanks to @Dansimp and @ghost.