Update in Changing the PIN
MicrosoftDocs/windows-itpro-docs pull request #9641
Opened 2021-06-02 09:30 UTC by joinimran

Made some update in Changing the PIN.
Problem: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9475

2021-06-02 12:55 UTC, illfated commented on windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-use-virtual-smart-cards.md
> +- Log on with the old pin or password.
PIN = personal identification number (not the noun "pin")
```suggestion
- Log on with the old PIN or password.
```

2021-06-02 12:56 UTC, illfated commented on windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-use-virtual-smart-cards.md
> +- Change the pin.
(as above)
```suggestion
- Change the PIN.
```

2021-06-02 13:05 UTC, JohanFreelancer9 commented on windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-use-virtual-smart-cards.md
> +The PIN for virtual smart card can be changed by following steps:
```suggestion
The PIN for a virtual smart card can be changed by following these steps:
```

2021-06-02 13:08 UTC, JohanFreelancer9 commented on windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-use-virtual-smart-cards.md
> +- Click ""Sign-in Options**.
```suggestion
- Select **Sign-in Options**.
```

2021-06-02 13:10 UTC, JohanFreelancer9 commented on windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-use-virtual-smart-cards.md
> +- Click the **Virtual smart card icon**.
```suggestion
- Select the virtual smart card icon.
```

2021-06-02 13:14 UTC, JohanFreelancer9 commented on windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-use-virtual-smart-cards.md
> +- Log on with the old pin or password.
```suggestion
- Sign in with the old PIN or password.
```

2021-06-02 13:16 UTC, JohanFreelancer9 commented on windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-use-virtual-smart-cards.md
> +- Change the pin.
```suggestion
- Enter and confirm the new PIN.
```

2021-06-02 13:17 UTC, JohanFreelancer9 requested changes
Copy review.

2021-06-03 07:58 UTC, JohanFreelancer9 approved these changes

2021-06-03 21:51 UTC, illfated approved these changes
Looks good to me.

2021-06-03 21:51 UTC, illfated commented
#sign-off

2021-06-09 00:15 UTC, merged