Added a note to page
MicrosoftDocs/windows-itpro-docs pull request #9646
Opened 2021-06-02 20:58 UTC by v-kikl

@jgeurten, I added the note about separating allow and deny rules is at the end of the "More information about file path rules" section.

2021-06-02 22:59 UTC, illfated commented on windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md
> +>We recommend maintaining separate ALLOW and DENY policies on version 1903 and higher, if for no other reason than it makes it a bit easier for an average person to reason over the policy.
Please include MarkDown indent marker compatibility spacing:
```suggestion
> [!NOTE]
> We recommend maintaining separate ALLOW and DENY policies on version 1903 and higher, if for no other reason than it makes it a bit easier for an average person to reason over the policy.
```
The last half of the sentence could use some phrasing improvement, but I am uncertain how to phrase it to clarify the intended meaning.

2021-06-02 23:49 UTC, jgeurten requested changes

2021-06-02 23:49 UTC, jgeurten commented on windows/security/threat-protection/windows-defender-application-control/event-id-explanations.md
> +| 8036| COM object was blocked. Learn more about COM object authorization: Allow COM object registration in a WDAC policy (Windows 10) - Windows security - Microsoft Docs |
The Allow COM object registration .. is supposed to be a hyperlink

2021-06-03 00:00 UTC, illfated commented on windows/security/threat-protection/windows-defender-application-control/event-id-explanations.md
> +| 8036| COM object was blocked. Learn more about COM object authorization: Allow COM object registration in a WDAC policy (Windows 10) - Windows security - Microsoft Docs |
Thank you, found it, it is a parallel document in the same directory as this file:
```suggestion
| 8036 | COM object was blocked. Learn more about COM object authorization: [Allow COM object registration in a WDAC policy (Windows 10)](allow-com-object-registration-in-windows-defender-application-control-policy.md) |
```
(also: keep the same spacing as the line before & after)

2021-06-03 00:02 UTC, illfated commented on windows/security/threat-protection/windows-defender-application-control/event-id-explanations.md
> +| 8036| COM object was blocked. Learn more about COM object authorization: Allow COM object registration in a WDAC policy (Windows 10) - Windows security - Microsoft Docs |
Links to the document in question:
- https://docs.microsoft.com/windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy.md

2021-06-03 00:07 UTC, illfated commented on windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md
> +>For others to better understand the WDAC policies that has been deployed, we recommend maintaining separate ALLOW and DENY policies on version 1903 and higher.
Looks like the suggested change got skipped. May we have the standard MarkDown indent marker compatibility spacing?
```suggestion
> [!NOTE]
> For others to better understand the WDAC policies that has been deployed, we recommend maintaining separate ALLOW and DENY policies on version 1903 and higher.
```

2021-06-03 08:26 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/event-id-explanations.md
> +| 8036| COM object was blocked. Learn more about COM object authorization: [Allow COM object registration in a WDAC policy (Windows 10) - Windows security - Microsoft Docs](allow-com-object-registrat
```suggestion
| 8036| COM object was blocked. To learn more about COM object authorization, see [Allow COM object registration in a Windows Defender Application Control policy](/windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy). |
```

2021-06-03 08:30 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/event-id-explanations.md
> +| 3086 | The file under validation does not meet the signing requirements for an IUM (isolated user mode) process. |
```suggestion
| 3086 | The file under validation does not meet the signing requirements for an isolated user mode (IUM) process. |
```

2021-06-03 08:35 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md
> +> For others to better understand the WDAC policies that has been deployed, we recommend maintaining separate ALLOW and DENY policies on version 1903 and higher.
```suggestion
> For others to better understand the WDAC policies that have been deployed, we recommend maintaining separate allow and deny policies on Windows 10, version 1903 and later.
```

2021-06-03 08:36 UTC, JohanFreelancer9 requested changes
Copy review - @v-kikl, please commit my suggested changes if you agree with them. Many thanks.

2021-06-07 15:50 UTC, v-kikl commented
Is this PR ready to be approved? Or, are there other changes that need to be made? @JohanFreelancer9?

2021-06-07 16:18 UTC, JohanFreelancer9 commented
@v-kikl - it does not seem as if my suggested changes have been committed. Could you please commit them?

2021-06-07 17:43 UTC, jgeurten approved these changes

2021-06-08 04:16 UTC, JohanFreelancer9 approved these changes

2021-06-11 18:15 UTC, merged