Rtb update
MicrosoftDocs/windows-itpro-docs pull request #9706
Opened 2021-06-22 17:49 UTC by TomLayson

Cleaned up table display for new Edge section

2021-06-23 10:45 UTC, JohanFreelancer9 approved these changes

2021-06-28 15:01 UTC, e0i commented
Hello @TomLayson. Thank you for this contribution. Can you resolve the merge conflicts to proceed? Have a nice day.

2021-06-29 10:24 UTC, siosulli commented
Just putting do not merge as I want to run a few updates past @TomLayson

2021-06-30 13:24 UTC, JohanFreelancer9 commented on windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md
> +For a complete list of the Microsoft Edge policies, see [Microsoft Edge and privacy: FAQ](https://docs.microsoft.com/en-us/microsoft-edge/deploy/available-policies).
```suggestion
For a complete list of the Microsoft Edge policies, see [Group Policy and Mobile Device Management (MDM) settings for Microsoft Edge](/microsoft-edge/deploy/available-policies). 
```

2021-06-30 13:28 UTC, JohanFreelancer9 commented on windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md
>  > [!Important]
```suggestion
> [!IMPORTANT]
```

2021-06-30 13:28 UTC, JohanFreelancer9 requested changes
Copy review.

2021-06-30 13:51 UTC, JohanFreelancer9 approved these changes

2021-07-01 12:11 UTC, merged