Kk wdac edits event tag link update
MicrosoftDocs/windows-itpro-docs pull request #9708
Opened 2021-06-22 21:43 UTC by v-kikl

@jgeurten, is this what you imaged the section to look like?

2021-06-22 21:57 UTC, jgeurten requested changes

2021-06-22 21:57 UTC, jgeurten commented on windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md
> +<<<<<<< HEAD
Need to remove this line nd the whitespace

2021-06-22 21:57 UTC, jgeurten commented on windows/security/threat-protection/windows-defender-application-control/event-tag-explanations.md
> +## NTSTATUS Values
We can rename this header to "Status Codes" or "Status Values"

2021-06-23 10:57 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/event-tag-explanations.md
> +## Status Values
```suggestion
## Status values
```

2021-06-23 10:59 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/event-tag-explanations.md
> +Represents values that are used to communicate system information. They are of four types: success values, information values, warning values, and error values. Click on the [NTSATUS](https://docs.mi
```suggestion
Represents values that are used to communicate system information. There are four types of values; success values, information values, warning values, and error values. Go to the [NTSATUS](/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55) link for information about common usage details.
```

2021-06-23 11:01 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md
> +<<<<<<< HEAD
```suggestion
```

2021-06-23 11:02 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md
> +WDAC has a built-in file rule conflict logic that translates to precedence order. It will first processes all explicit deny rules it finds. Then, it will process all explicit allow rules. If no deny
```suggestion
WDAC has a built-in file rule conflict logic that translates to precedence order. It will first process all explicit deny rules it finds. Then, it will process all explicit allow rules. If no deny or allow rule exists, WDAC will check for [Managed Installer EA](deployment/deploy-wdac-policies-with-memcm.md). Lastly, if none of these exists, WDAC will fall back on [ISG](use-windows-defender-application-control-with-intelligent-security-graph.md).
```

2021-06-23 11:04 UTC, JohanFreelancer9 reviewed
Copy review.

2021-07-13 20:26 UTC, denisebmsft reviewed
Thank you @v-kikl @jgeurten @JohanFreelancer9

2021-07-13 20:26 UTC, merged