Kk wdac edits task 33881267
MicrosoftDocs/windows-itpro-docs pull request #9744
Opened 2021-06-28 16:48 UTC by v-kikl

@jgeurten, is this what you had in mind?

2021-06-28 17:11 UTC, jgeurten approved these changes
This is perfect. Thank you, Kim

2021-06-29 12:52 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md
> +Some of the [SKUs](feature-availability.md) that support our PowerShell commandlets [(ConfigCI Module | Microsoft Docs)](powershell/module/configci) support but do not have the module installed on th
```suggestion
Some of the [SKUs](feature-availability.md) that support our PowerShell commandlets [(ConfigCI Module)](powershell/module/configci/?view=windowsserver2019-ps) support but do not have the module installed on the box. 
```

2021-06-29 12:53 UTC, JohanFreelancer9 requested changes
Copy review - @v-kikl, please commit my suggested change if you agree with it. Many thanks.

2021-07-06 18:31 UTC, v-kikl commented
Updated the link and fixed merge conflict.

2021-07-07 04:38 UTC, JohanFreelancer9 approved these changes

2021-07-08 13:50 UTC, merged