fixed typo error
MicrosoftDocs/windows-itpro-docs pull request #9793
Opened 2021-07-09 16:09 UTC by RAJU2529

as per  user report #9790 , so I have corrected the word **Havens** to **Hagens**

2021-07-10 05:58 UTC, JohanFreelancer9 commented on windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements.md
> +    The displayName is parsed for delimiters: commas, periods, dashes or hyphens, underscores, spaces, pound signs, and tabs. If any of these delimiters are found, the displayName is split and all pa
```suggestion
    The displayName is parsed for delimiters: commas, periods, dashes or hyphens, underscores, spaces, pound signs, and tabs. If any of these delimiters are found, the displayName is split and all parsed sections (tokens) are confirmed not to be included in the password. Tokens that are shorter than three characters are ignored, and substrings of the tokens are not checked. For example, the name "Erin M. Hagens" is split into three tokens: "Erin", "M", and "Hagens". Because the second token is only one character long, it is ignored. Therefore, this user could not have a password that included either "erin" or "hagens" as a substring anywhere in the password.
```

2021-07-10 05:59 UTC, JohanFreelancer9 requested changes
Copy review.

2021-07-12 04:49 UTC, JohanFreelancer9 approved these changes

2021-07-12 19:25 UTC, denisebmsft approved these changes
Thank you @RAJU2529

2021-07-12 19:25 UTC, merged