added windows 11 , added tpm link and added one column
MicrosoftDocs/windows-itpro-docs pull request #9855
Opened 2021-07-28 10:52 UTC by RAJU2529

as per user feedback #9853, so i added windows 11 , added tpm link and added one column

2021-07-29 06:26 UTC, JohanFreelancer9 commented on windows/security/information-protection/tpm/trusted-platform-module-overview.md
> +[Trusted Platform Module (TPM)](https://docs.microsoft.com/windows/security/information-protection/tpm/trusted-platform-module-top-node) technology is designed to provide hardware-based, security-rel
```suggestion
[Trusted Platform Module (TPM)](/windows/security/information-protection/tpm/trusted-platform-module-top-node) technology is designed to provide hardware-based, security-related functions. A TPM chip is a secure crypto-processor that is designed to carry out cryptographic operations. The chip includes multiple physical security mechanisms to make it tamper-resistant, and malicious software is unable to tamper with the security functions of the TPM. Some of the key advantages of using TPM technology are that you can:
```

2021-07-29 06:28 UTC, JohanFreelancer9 commented on windows/security/information-protection/tpm/trusted-platform-module-overview.md
> +>  Windows 11, Windows 10, Windows Server 2016 and Windows Server 2019 support Device Health Attestation with TPM 2.0. Support for TPM 1.2 was added beginning with Windows version 1607 (RS1). TPM 2.0
```suggestion
>  Windows 11, Windows 10, Windows Server 2016, and Windows Server 2019 support Device Health Attestation with TPM 2.0. Support for TPM 1.2 was added beginning with Windows version 1607 (RS1). TPM 2.0 requires UEFI firmware. A computer with legacy BIOS and TPM 2.0 won't work as expected.
```

2021-07-29 06:28 UTC, JohanFreelancer9 requested changes
Copy review.

2021-07-29 06:31 UTC, RAJU2529 commented
This PR is final, not draft.

2021-07-29 06:36 UTC, JohanFreelancer9 approved these changes

2021-08-14 14:59 UTC, e0i commented
@tiburd

2021-08-16 19:31 UTC, tiburd approved these changes

2021-08-16 19:31 UTC, merged