Created a new section Deploy Managed Installer.
MicrosoftDocs/windows-itpro-docs pull request #9886
Opened 2021-08-09 17:46 UTC by v-kikl

@jgeurten, let me know if this is how you imagined the Deploy Managed Installer section look like.
@jsuther1974.

2021-08-09 18:11 UTC, jgeurten requested changes

2021-08-09 18:11 UTC, jgeurten commented on windows/security/threat-protection/windows-defender-application-control/configure-authorized-apps-deployed-with-a-managed-installer.md
> +## Deploying the Managed Installer
Let's call this "Deploying the Managed Installer rule collection"

2021-08-09 18:11 UTC, jgeurten commented on windows/security/threat-protection/windows-defender-application-control/configure-authorized-apps-deployed-with-a-managed-installer.md
> +   Set-AppLockerPolicy -XmlPolicy $policyFile -Merge -ErrorAction SilentlyContinue
$policyFile= 
@"
      Raw_AppLocker_Policy_XML
"@

Set-AppLockerPolicy -XmlPolicy $policyFile -Merge -ErrorAction SilentlyContinue

2021-08-09 18:15 UTC, jgeurten requested changes

2021-08-09 18:15 UTC, jgeurten commented on windows/security/threat-protection/windows-defender-application-control/configure-authorized-apps-deployed-with-a-managed-installer.md
> +2. Verify policy deployment
```suggestion
2. Verify Deployment of the Rule set was successful
```

2021-08-09 18:15 UTC, jgeurten commented on windows/security/threat-protection/windows-defender-application-control/configure-authorized-apps-deployed-with-a-managed-installer.md
> +    Notice the output shows the ManagedInstaller rule is there.
```suggestion
    Verify the output shows the ManagedInstaller rule set.
```

2021-08-09 18:15 UTC, jgeurten commented on windows/security/threat-protection/windows-defender-application-control/configure-authorized-apps-deployed-with-a-managed-installer.md
> +   ```
At the end, mention that this command will show the raw XML to verify the individual rules (re-word this section)

2021-08-11 07:07 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/configure-authorized-apps-deployed-with-a-managed-installer.md
> +An example of a valid Managed Installer rule collection, using Microsoft Endpoint Config Manager (MEMCM), MEM (Intune), Powershell, and Powershell ISE, is shown below. Remove any rules that you do no
```suggestion
An example of a valid Managed Installer rule collection, using Microsoft Endpoint Config Manager (MEMCM), MEM (Intune), PowerShell, and PowerShell ISE, is shown below. Remove any rules that you do not wish to designate as a Managed Installer.
```

2021-08-11 07:12 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/configure-authorized-apps-deployed-with-a-managed-installer.md
> +## Deploying the Managed Installer
```suggestion
## Deploying the Managed Installer rule collection
```

2021-08-11 07:18 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/configure-authorized-apps-deployed-with-a-managed-installer.md
> +Once you've completed configuring your chosen Managed Installer, by specifying which to use in the AppLocker policy, enabling the service enforcement of it, and by enabling the Managed Installer opti
```suggestion
Once you've completed configuring your chosen Managed Installer by specifying which option to use in the AppLocker policy, enabling the service enforcement of it, and enabling the Managed Installer option in a WDAC policy, you'll need to deploy it.
```

2021-08-11 07:18 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/configure-authorized-apps-deployed-with-a-managed-installer.md
> +1. Using the following command to deploy the policy.
```suggestion
1. Use the following command to deploy the policy.
```

2021-08-11 07:20 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/configure-authorized-apps-deployed-with-a-managed-installer.md
> +2. Verify Deployment of the Rule set was successful
```suggestion
2. Verify deployment of the ruleset was successful.
```

2021-08-11 07:21 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/configure-authorized-apps-deployed-with-a-managed-installer.md
> +3. Get the policy XML (optional) using PS:
```suggestion
3. Get the policy XML (optional) using PowerShell:
```

2021-08-11 07:27 UTC, JohanFreelancer9 requested changes
Copy review - @v-kikl, kindly commit the suggested changes if you agree with them. Many thanks.

2021-08-12 05:36 UTC, JohanFreelancer9 commented on windows/security/threat-protection/windows-defender-application-control/configure-authorized-apps-deployed-with-a-managed-installer.md
> +An example of a valid Managed Installer rule collection, using Microsoft Endpoint Config Manager (MEMCM), MEM (Intune), Powershell, and PowerShell ISE, is shown below. Remove any rules that you do no
```suggestion
An example of a valid Managed Installer rule collection, using Microsoft Endpoint Config Manager (MEMCM), MEM (Intune), PowerShell, and PowerShell ISE, is shown below. Remove any rules that you do not wish to designate as a Managed Installer.
```

2021-08-12 05:39 UTC, JohanFreelancer9 requested changes
Copy review.

2021-08-16 17:18 UTC, merged