added missed step
MicrosoftDocs/windows-itpro-docs pull request #9911
Opened 2021-08-18 06:39 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9786

2021-08-18 06:39 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

2021-08-18 09:18 UTC, JohanFreelancer9 commented on windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md
> +8. Select **Object Types**, then, in the appeared window, choose **Computers** and click **OK**
```suggestion
8. Select **Object Types**, then, in the window that appears, choose **Computers** and click **OK**.
```

2021-08-18 09:20 UTC, JohanFreelancer9 requested changes
Copy review.

2021-08-18 14:39 UTC, JohanFreelancer9 approved these changes

2021-09-02 16:25 UTC, mapalko commented
Checking this with some people.

2021-09-17 19:26 UTC, e0i commented
@mapalko Please let me know when your evaluations are complete. Thanks.

2022-05-04 03:56 UTC, aczechowski commented
I'm following up
Apologies for the delay

2022-07-29 20:02 UTC, vinaypamnani-msft commented
I've resolved the conflict. Proposed changes look good to me.

2022-07-29 20:48 UTC, merged