Update virus-initiative-criteria.md
MicrosoftDocs/windows-itpro-docs pull request #9944
Opened 2021-09-08 19:57 UTC by nbassett-MSFT

Update to membership requirements, follow-up link for application, and high-level program summary.

2021-09-09 09:09 UTC, JohanFreelancer9 commented on windows/security/threat-protection/intelligence/virus-initiative-criteria.md
> +The Microsoft Virus Initiative (MVI) helps organizations develop better-together security solutions that are performant, reliable, and aligned with Microsoft technology & strategy.
```suggestion
The Microsoft Virus Initiative (MVI) helps organizations develop better-together security solutions that are performant, reliable, and aligned with Microsoft technology and strategy.
```

2021-09-09 09:11 UTC, JohanFreelancer9 commented on windows/security/threat-protection/intelligence/virus-initiative-criteria.md
> +To qualify for the MVI program, your organization must meet all the following requirements.
```suggestion
To qualify for the MVI program, your organization must meet all the following requirements:
```

2021-09-09 09:18 UTC, JohanFreelancer9 commented on windows/security/threat-protection/intelligence/virus-initiative-criteria.md
> +3)	Your organization must be active in the antimalware industry and have a positive reputation, as evidenced by participation in industry conferences or being reviewed in an industry standard report
```suggestion
3)	Your organization must be active in the antimalware industry and have a positive reputation, as evidenced by participation in industry conferences or being reviewed in an industry-standard report such as AV-Comparatives, OPSWAT, or Gartner.
```

2021-09-09 09:20 UTC, JohanFreelancer9 commented on windows/security/threat-protection/intelligence/virus-initiative-criteria.md
> +7)	Your solution must be certified through independent testing by at least one industry standard organization, and yearly certification must be maintained.
```suggestion
7)	Your solution must be certified through independent testing by at least one industry-standard organization, and yearly certification must be maintained.
```

2021-09-09 09:22 UTC, JohanFreelancer9 requested changes
Copy review - @nbassett-MSFT, kindly commit the minor suggested changes if you agree with them. Many thanks.

2021-09-18 05:26 UTC, JohanFreelancer9 approved these changes

2021-09-23 23:21 UTC, nbassett-MSFT commented
Sorry for the additional mail on this, but the site still shows the old content... is there anything I need to do?  I want to make sure I'm not blocking.

Thanks,
Nick
________________________________
From: JohanFreelancer9 ***@***.***>
Sent: Friday, September 17, 2021 10:27 PM
To: MicrosoftDocs/windows-itpro-docs ***@***.***>
Cc: Nick Bassett (HE/HIM) ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/windows-itpro-docs] Update virus-initiative-criteria.md (#9944)


@JohanFreelancer9 approved this pull request.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fwindows-itpro-docs%2Fpull%2F9944%23pullrequestreview-758028210&data=04%7C01%7CNick.Bassett%40microsoft.com%7Cd05a14d1cfe84e224a5208d97a64f210%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637675396578878183%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VguHS69jbKqiEDY20gcXrESRI1UrzH9NHAEL2VQ3XdU%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGVNOYBIE233FZ75GLIA3Y3UCQPKNANCNFSM5DVSOFWA&data=04%7C01%7CNick.Bassett%40microsoft.com%7Cd05a14d1cfe84e224a5208d97a64f210%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637675396578888139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qXJ5S2QKR3b08nI2frUiSDs49xPbFiXy9nLpvaXd0jc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CNick.Bassett%40microsoft.com%7Cd05a14d1cfe84e224a5208d97a64f210%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637675396578888139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=c3aEhWmHz6s3au03GS9tppQYFCFCqpRgb%2BXu%2FvPc1ws%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CNick.Bassett%40microsoft.com%7Cd05a14d1cfe84e224a5208d97a64f210%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637675396578898096%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mLkFd1ENin1CUzT2t6TRQ0cI8713QvUJQFj%2Br9ZywHk%3D&reserved=0>.

2021-09-24 02:53 UTC, JohanFreelancer9 commented
@e0i, can you please help to move this PR forward? Many thanks.

2021-09-28 16:31 UTC, merged