Rtb update
MicrosoftDocs/windows-itpro-docs pull request #9963
Opened 2021-09-18 19:56 UTC by TomLayson

2021-09-23 04:26 UTC, JohanFreelancer9 commented on windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md
> +> - [CSP - Troubleshooting](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-troubleshooting)
```suggestion
 > [!IMPORTANT]
> **If you need assistance with troubleshooting issues, please refer to:**</br> 
>  - [Keep your device running smoothly](https://support.microsoft.com/topic/keep-your-device-running-smoothly-with-recommended-troubleshooting-ec76fe10-4ac8-ce9d-49c6-757770fe68f1)</br>
> - [CSP - Troubleshooting](/windows/client-management/mdm/policy-csp-troubleshooting)
```

2021-09-23 04:29 UTC, JohanFreelancer9 commented on windows/privacy/manage-windows-1709-endpoints.md
> +Certificates are digital files, stored on client devices, used to both encrypt data and verify the identity of an individual or organization. Trusted root certificates issued by a certification autho
```suggestion
Certificates are digital files, stored on client devices, used to both encrypt data and verify the identity of an individual or organization. Trusted root certificates issued by a certification authority (CA) are stored in a certificate trust list (CTL). The Automatic Root Certificates Update mechanism contacts Windows Updates to update the CTL. If a new version of the CTL is identified, the list of trusted root certificates cached on the local device will be updated. Untrusted certificates are certificates where the server certificate issuer is unknown or is not trusted by the service. Untrusted certificates are also stored in a list on the local device and updated by the Automatic Root Certificates Update mechanism.
```

2021-09-23 04:38 UTC, JohanFreelancer9 commented on windows/privacy/manage-windows-1803-endpoints.md
> +Certificates are digital files, stored on client devices, used to both encrypt data and verify the identity of an individual or organization. Trusted root certificates issued by a certification autho
```suggestion
Certificates are digital files, stored on client devices, used to both encrypt data and verify the identity of an individual or organization. Trusted root certificates issued by a certification authority (CA) are stored in a certificate trust list (CTL). The Automatic Root Certificates Update mechanism contacts Windows Updates to update the CTL. If a new version of the CTL is identified, the list of trusted root certificates cached on the local device will be updated. Untrusted certificates are certificates where the server certificate issuer is unknown or is not trusted by the service. Untrusted certificates are also stored in a list on the local device and updated by the Automatic Root Certificates Update mechanism.
```

2021-09-23 04:40 UTC, JohanFreelancer9 commented on windows/privacy/manage-windows-1809-endpoints.md
> +Certificates are digital files, stored on client devices, used to both encrypt data and verify the identity of an individual or organization. Trusted root certificates issued by a certification autho
```suggestion
Certificates are digital files, stored on client devices, used to both encrypt data and verify the identity of an individual or organization. Trusted root certificates issued by a certification authority (CA) are stored in a certificate trust list (CTL). The Automatic Root Certificates Update mechanism contacts Windows Updates to update the CTL. If a new version of the CTL is identified, the list of trusted root certificates cached on the local device will be updated. Untrusted certificates are certificates where the server certificate issuer is unknown or is not trusted by the service. Untrusted certificates are also stored in a list on the local device and updated by the Automatic Root Certificates Update mechanism.
```

2021-09-23 04:42 UTC, JohanFreelancer9 commented on windows/privacy/manage-windows-1903-endpoints.md
> +|Certificates|Certificates are digital files, stored on client devices, used to both encrypt data and verify the identity of an individual or organization. Trusted root certificates issued by a certi
```suggestion
|Certificates|Certificates are digital files, stored on client devices, used to both encrypt data and verify the identity of an individual or organization. Trusted root certificates issued by a certification authority (CA) are stored in a certificate trust list (CTL). The Automatic Root Certificates Update mechanism contacts Windows Updates to update the CTL. If a new version of the CTL is identified, the list of trusted root certificates cached on the local device will be updated. Untrusted certificates are certificates where the server certificate issuer is unknown or is not trusted by the service. Untrusted certificates are also stored in a list on the local device and updated by the Automatic Root Certificates Update mechanism.
```

2021-09-23 04:46 UTC, JohanFreelancer9 commented on windows/privacy/manage-windows-1909-endpoints.md
> +|Certificates|Certificates are digital files, stored on client devices, used to both encrypt data and verify the identity of an individual or organization. Trusted root certificates issued by a certi
```suggestion
|Certificates|Certificates are digital files, stored on client devices, used to both encrypt data and verify the identity of an individual or organization. Trusted root certificates issued by a certification authority (CA) are stored in a certificate trust list (CTL). The Automatic Root Certificates Update mechanism contacts Windows Updates to update the CTL. If a new version of the CTL is identified, the list of trusted root certificates cached on the local device will be updated. Untrusted certificates are certificates where the server certificate issuer is unknown or is not trusted by the service. Untrusted certificates are also stored in a list on the local device and updated by the Automatic Root Certificates Update mechanism.
```

2021-09-23 04:47 UTC, JohanFreelancer9 commented on windows/privacy/manage-windows-2004-endpoints.md
> +|Certificates|Certificates are digital files, stored on client devices, used to both encrypt data and verify the identity of an individual or organization. Trusted root certificates issued by a certi
```suggestion
|Certificates|Certificates are digital files, stored on client devices, used to both encrypt data and verify the identity of an individual or organization. Trusted root certificates issued by a certification authority (CA) are stored in a certificate trust list (CTL). The Automatic Root Certificates Update mechanism contacts Windows Updates to update the CTL. If a new version of the CTL is identified, the list of trusted root certificates cached on the local device will be updated. Untrusted certificates are certificates where the server certificate issuer is unknown or is not trusted by the service. Untrusted certificates are also stored in a list on the local device and updated by the Automatic Root Certificates Update mechanism.
```

2021-09-23 04:48 UTC, JohanFreelancer9 commented on windows/privacy/manage-windows-20H2-endpoints.md
> +|Certificates|Certificates are digital files, stored on client devices, used to both encrypt data and verify the identity of an individual or organization. Trusted root certificates issued by a certi
```suggestion
|Certificates|Certificates are digital files, stored on client devices, used to both encrypt data and verify the identity of an individual or organization. Trusted root certificates issued by a certification authority (CA) are stored in a certificate trust list (CTL). The Automatic Root Certificates Update mechanism contacts Windows Updates to update the CTL. If a new version of the CTL is identified, the list of trusted root certificates cached on the local device will be updated. Untrusted certificates are certificates where the server certificate issuer is unknown or is not trusted by the service. Untrusted certificates are also stored in a list on the local device and updated by the Automatic Root Certificates Update mechanism.
```

2021-09-23 04:54 UTC, TomLayson commented on windows/privacy/manage-windows-1903-endpoints.md
> +|Certificates|Certificates are digital files, stored on client devices, used to both encrypt data and verify the identity of an individual or organization. Trusted root certificates issued by a certi
The text for this item was supplied by CELA and contains specific language needed.

2021-09-23 04:55 UTC, TomLayson commented on windows/privacy/manage-windows-1909-endpoints.md
> +|Certificates|Certificates are digital files, stored on client devices, used to both encrypt data and verify the identity of an individual or organization. Trusted root certificates issued by a certi
Same as above.  The text for this item was supplied by CELA and contains specific language needed.

2021-09-23 04:56 UTC, JohanFreelancer9 commented on windows/privacy/manage-windows-21H1-endpoints.md
> +The following methodology was used to derive these network endpoints:
```suggestion
The following methodology was used to derive at these network endpoints:
```

2021-09-23 04:56 UTC, TomLayson commented on windows/privacy/manage-windows-1909-endpoints.md
> +|Certificates|Certificates are digital files, stored on client devices, used to both encrypt data and verify the identity of an individual or organization. Trusted root certificates issued by a certi
misread.  please disregard

2021-09-23 04:57 UTC, JohanFreelancer9 commented on windows/privacy/manage-windows-21H1-endpoints.md
> +||The following endpoint is used for the Weather app. To turn off traffic for this endpoint, either uninstall the Weather app or disable the Microsoft Store. If you disable the Microsoft store, other
```suggestion
||The following endpoint is used for the Weather app. To turn off traffic for this endpoint, either uninstall the Weather app or disable the Microsoft Store. If you disable the Microsoft Store, other Store apps cannot be installed or updated. Additionally, the Microsoft Store won't be able to revoke malicious Store apps and users will still be able to open them.|HTTP|tile-service.weather.microsoft.com|
```

2021-09-23 04:57 UTC, JohanFreelancer9 commented on windows/privacy/manage-windows-21H1-endpoints.md
> +||The following endpoint is used by the Photos app to download configuration files, and to connect to the Office 365 portal's shared infrastructure, including Office in a browser. To turn off traffic
```suggestion
||The following endpoint is used for OneNote Live Tile. To turn off traffic for this endpoint, either uninstall OneNote or disable the Microsoft Store. If you disable the Microsoft Store, other Store apps cannot be installed or updated. Additionally, the Microsoft Store won't be able to revoke malicious Store apps and users will still be able to open them.|TLSv1.2/HTTPS/HTTP|cdn.onenote.net|
||The following endpoint is used by the Photos app to download configuration files, and to connect to the Office 365 portal's shared infrastructure, including Office in a browser. To turn off traffic for this endpoint, either uninstall the Photos app or disable the Microsoft Store. If you disable the Microsoft Store, other Store apps cannot be installed or updated. Additionally, the Microsoft Store won't be able to revoke malicious Store apps and users will still be able to open them.|TLSv1.2/HTTPS|evoke-windowsservices-tas.msedge.net
```

2021-09-23 04:58 UTC, JohanFreelancer9 commented on windows/privacy/manage-windows-21H1-endpoints.md
> +|Certificates|Certificates are digital files, stored on client devices, used to both encrypt data and verify the identity of an individual or organization. Trusted root certificates issued by a certi
```suggestion
|Certificates|Certificates are digital files, stored on client devices, used to both encrypt data and verify the identity of an individual or organization. Trusted root certificates issued by a certification authority (CA) are stored in a certificate trust list (CTL). The Automatic Root Certificates Update mechanism contacts Windows Updates to update the CTL. If a new version of the CTL is identified, the list of trusted root certificates cached on the local device will be updated. Untrusted certificates are certificates where the server certificate issuer is unknown or is not trusted by the service. Untrusted certificates are also stored in a list on the local device and updated by the Automatic Root Certificates Update mechanism.
```

2021-09-23 05:01 UTC, JohanFreelancer9 commented on windows/privacy/manage-windows-21H1-endpoints.md
> +||The following endpoints are used by Windows Error Reporting. To turn off traffic for these endpoints, enable the following Group Policy: Administrative Templates > Windows Components > Windows Erro
```suggestion
||The following endpoints are used by Windows Error Reporting. To turn off traffic for these endpoints, enable the following Group Policy: **Administrative Templates** > **Windows Components** > **Windows Error Reporting** > **Disable Windows Error Reporting**. This means error reporting information will not be sent back to Microsoft.|TLSv1.2|telecommand.telemetry.microsoft.com|
```

2021-09-23 05:01 UTC, TomLayson commented on windows/privacy/manage-windows-21H1-endpoints.md
> +The following methodology was used to derive these network endpoints:
This doesn't seem right to me.  Per https://www.merriam-webster.com/dictionary/derive we should use derive as is or change it to "arrive at".  Thoughts?

2021-09-23 05:04 UTC, JohanFreelancer9 commented on windows/privacy/manage-windows-21H1-endpoints.md
> +|Microsoft forward link redirection service (FWLink)|The following endpoint is used by the Microsoft forward link redirection service (FWLink) to redirect permanent web links to their actual, sometim
```suggestion
|Microsoft forward link redirection service (FWLink)|The following endpoint is used by the Microsoft forward link redirection service (FWLink) to redirect permanent web links to their actual, sometimes transitory, URL. FWlinks are similar to URL shorteners, just longer. If you disable this endpoint, Windows Defender won't be able to update its malware definitions; links from Windows and other Microsoft products to the web won't work; and PowerShell updateable Help won't update. To disable the traffic, instead, disable the traffic that's getting forwarded.|HTTP|go.microsoft.com|
```

2021-09-23 05:10 UTC, JohanFreelancer9 commented on windows/privacy/manage-windows-21H1-endpoints.md
> +|Teams|The following endpoint is used for Microsoft Teams application.||[Learn how to turn off traffic to all of the following endpoint(s).]( manage-connections-from-windows-operating-system-componen
```suggestion
|Teams|The following endpoint is used for Microsoft Teams application.||[Learn how to turn off traffic to all of the following endpoint(s).](manage-connections-from-windows-operating-system-components-to-microsoft-services.md#26-microsoft-store)|
```

2021-09-23 05:13 UTC, JohanFreelancer9 commented on windows/privacy/manage-windows-21H1-endpoints.md
> +|Windows Update|The following endpoint is used for Windows Update downloads of apps and OS updates, including HTTP downloads or HTTP downloads blended with peers. If you turn off traffic for this end
```suggestion
|Windows Update|The following endpoint is used for Windows Update downloads of apps and operating system updates, including HTTP downloads or HTTP downloads blended with peers. If you turn off traffic for this endpoint, Windows Update downloads will not be managed, as critical metadata that is used to make downloads more resilient is blocked. Downloads may be impacted by corruption (resulting in re-downloads of full files). Additionally, downloads of the same update by multiple devices on the same local network will not use peer devices for bandwidth reduction.||[Learn how to turn off traffic to all of the following endpoint(s).](manage-connections-from-windows-operating-system-components-to-microsoft-services.md#bkmk-updates)|
```

2021-09-23 05:14 UTC, JohanFreelancer9 commented on windows/privacy/manage-windows-21H1-endpoints.md
> +|Skype|The following endpoint is used to retrieve Skype configuration values. To turn off traffic for this endpoint, either uninstall the app or disable the Microsoft Store. If you disable the Micros
```suggestion
|Skype|The following endpoint is used to retrieve Skype configuration values. To turn off traffic for this endpoint, either uninstall the app or disable the Microsoft Store. If you disable the Microsoft Store, other Microsoft Store apps cannot be installed or updated. Additionally, the Microsoft Store won't be able to revoke malicious apps and users will still be able to open them.||[Learn how to turn off traffic to all of the following endpoint(s).](manage-connections-from-windows-operating-system-components-to-microsoft-services.md#bkmk-windowsstore)|
```

2021-09-23 05:16 UTC, JohanFreelancer9 commented on windows/privacy/manage-windows-21H1-endpoints.md
> +||The following endpoints enable connections to Windows Update, Microsoft Update, and the online services of the Store. If you turn off traffic for these endpoints, the device will not be able to con
```suggestion
||The following endpoints enable connections to Windows Update, Microsoft Update, and the online services of the Store. If you turn off traffic for these endpoints, the device will not be able to connect to Windows Update and Microsoft Update to help keep the device secure. Also, the device will not be able to acquire and update apps from the Microsoft Store. These are dependent on also enabling "Device authentication" and "Microsoft Account" endpoints.|TLSv1.2/HTTPS/HTTP|*.delivery.mp.microsoft.com|
```

2021-09-23 05:18 UTC, JohanFreelancer9 commented on windows/privacy/manage-windows-21H1-endpoints.md
> +- [Office 365 URLs and IP address ranges](https://support.office.com/en-us/article/Office-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2?ui=en-US&rs=en-US&ad=US)
```suggestion
- [Office 365 URLs and IP address ranges](https://support.office.com/article/Office-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2?ui=en-US&rs=en-US&ad=US)
```

2021-09-23 05:28 UTC, JohanFreelancer9 commented on windows/privacy/manage-windows-21H1-endpoints.md
> +The following methodology was used to derive these network endpoints:
Thanks, @TomLayson, I stand corrected. Of course, you are right. Please ignore my suggestion.

2021-09-23 05:29 UTC, JohanFreelancer9 requested changes
Copy review.

2021-09-23 07:57 UTC, JohanFreelancer9 commented
@TomLayson - thank you for committing my suggested changes, but you seem to have missed my final three suggestions. Could you kindly commit them as well if you agree with them? Many thanks.

2021-09-23 17:13 UTC, TomLayson commented
Hi Johan,

I had 1 question about wording.  I have accepted the rest of the changes.  I'm new to GitHub, so if I need to do something, please let me know.

Thanks
Tom Layson
Privacy Program Manager 2
Windows, Browsers & Devices Privacy
https://aka.ms/wdgprivacy

General Privacy Questions? Check out our Stack Overflow page: https://aka.ms/wbdprivacyquestions
Request a privacy consult or review: https://aka.ms/wbdprivacyengage

From: JohanFreelancer9 ***@***.***>
Sent: Thursday, September 23, 2021 12:57 AM
To: MicrosoftDocs/windows-itpro-docs ***@***.***>
Cc: Tom Layson ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/windows-itpro-docs] Rtb update (#9963)


@TomLayson<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTomLayson&data=04%7C01%7Ctomlayson%40microsoft.com%7C86c269e0f41c4838aa6508d97e67ca05%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637679806622309384%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f1N3BsccAYfcaqFGvDR%2BgyNSWHCGSw5FNX6cT23pSA4%3D&reserved=0> - thank you for committing my suggested changes, but you seem to have missed my final three suggestions. Could you kindly commit them as well if you agree with them? Many thanks.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fwindows-itpro-docs%2Fpull%2F9963%23issuecomment-925584686&data=04%7C01%7Ctomlayson%40microsoft.com%7C86c269e0f41c4838aa6508d97e67ca05%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637679806622309384%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xEVqbrjmq3nm9ytDswm5yhpf3vsyYpxPJpb2%2BTMY9Go%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAT3S7MCFALPHTNB5ATZ7U7LUDLMWPANCNFSM5EJQTBAQ&data=04%7C01%7Ctomlayson%40microsoft.com%7C86c269e0f41c4838aa6508d97e67ca05%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637679806622319376%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=V7Yhht5AwgXZUgJuJPkijaaBXWbkdT4sRFmzQ9XZ2kw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctomlayson%40microsoft.com%7C86c269e0f41c4838aa6508d97e67ca05%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637679806622329374%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8408YpmcyaedzpJAVbW2H8ijRQdRNPyMzHTr5o4xGqM%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ctomlayson%40microsoft.com%7C86c269e0f41c4838aa6508d97e67ca05%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637679806622329374%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BncCcEaTxXX9RW4YA%2FY00898ooinqTY15j%2BIupse5iU%3D&reserved=0>.

2021-09-24 04:13 UTC, JohanFreelancer9 commented
> Hi Johan, I had 1 question about wording. I have accepted the rest of the changes. I'm new to GitHub, so if I need to do something, please let me know. Thanks Tom Layson Privacy Program Manager 2 Windows, Browsers & Devices Privacy https://aka.ms/wdgprivacy General Privacy Questions? Check out our Stack Overflow page: https://aka.ms/wbdprivacyquestions Request a privacy consult or review: https://aka.ms/wbdprivacyengage From: JohanFreelancer9 ***@***.***> Sent: Thursday, September 23, 2021 12:57 AM To: MicrosoftDocs/windows-itpro-docs ***@***.***> Cc: Tom Layson ***@***.***>; Mention ***@***.***> Subject: Re: [MicrosoftDocs/windows-itpro-docs] Rtb update (#9963) @TomLayson<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTomLayson&data=04%7C01%7Ctomlayson%40microsoft.com%7C86c269e0f41c4838aa6508d97e67ca05%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637679806622309384%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f1N3BsccAYfcaqFGvDR%2BgyNSWHCGSw5FNX6cT23pSA4%3D&reserved=0> - thank you for committing my suggested changes, but you seem to have missed my final three suggestions. Could you kindly commit them as well if you agree with them? Many thanks. - You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fwindows-itpro-docs%2Fpull%2F9963%23issuecomment-925584686&data=04%7C01%7Ctomlayson%40microsoft.com%7C86c269e0f41c4838aa6508d97e67ca05%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637679806622309384%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xEVqbrjmq3nm9ytDswm5yhpf3vsyYpxPJpb2%2BTMY9Go%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAT3S7MCFALPHTNB5ATZ7U7LUDLMWPANCNFSM5EJQTBAQ&data=04%7C01%7Ctomlayson%40microsoft.com%7C86c269e0f41c4838aa6508d97e67ca05%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637679806622319376%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=V7Yhht5AwgXZUgJuJPkijaaBXWbkdT4sRFmzQ9XZ2kw%3D&reserved=0>. Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctomlayson%40microsoft.com%7C86c269e0f41c4838aa6508d97e67ca05%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637679806622329374%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8408YpmcyaedzpJAVbW2H8ijRQdRNPyMzHTr5o4xGqM%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ctomlayson%40microsoft.com%7C86c269e0f41c4838aa6508d97e67ca05%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637679806622329374%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BncCcEaTxXX9RW4YA%2FY00898ooinqTY15j%2BIupse5iU%3D&reserved=0>.

Hi Tom,

Thank you for committing all the changes. It is all good. You can please just mark your question as "Resolved". Thanks again.

Johan

2021-09-24 04:20 UTC, JohanFreelancer9 approved these changes

2021-09-24 04:27 UTC, TomLayson commented
@JohanFreelancer9  I don't see an option to do anything with the final comment.  The active option on the page is "Close with comment".

2021-09-24 04:35 UTC, JohanFreelancer9 commented
@TomLayson - If you select "**...** at the top of your comment, you should get the option to resolve or delete. Could you please have a look?

2022-05-04 03:32 UTC, aczechowski commented
Apologies for the delay in finalizing this PR, but thank you @TomLayson for the contribution. I fixed some conflicts due to the time lapse, and will merge this now. The changes will publish live around 11 AM Pacific on 4 May.

2022-05-04 03:33 UTC, merged